In [100]:
# Import dependences
import pandas as pd
pd.set_option('display.max_rows', None)

In [101]:
# Read the Dataset
dataset = pd.read_csv("train.csv")
dataset

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
5        6          50       RL         85.0    14115   Pave   NaN      IR1
6        7          20       RL         75.0    10084   Pave   NaN      Reg
7        8          60       RL          NaN    10382   Pave   NaN      IR1
8        9          50       RM         51.0     6120   Pave   NaN      Reg
9       10         190       RL         50.0     7420   Pave   NaN      Reg
10      11          20       RL         70.0    11200   Pave   NaN      Reg
11      12          60       RL         85.0    11924   Pave   NaN      IR1
12      13          20       RL          NaN    12968   Pave   NaN      IR2
13      14          20       RL         91.0    10652   Pave   NaN      IR1
14      15          20       RL          NaN    10920   Pave   NaN      IR1
15      16          45       RM         51.0     6120   Pave   NaN      Reg
16      17          20       RL          NaN    11241   Pave   NaN      IR1
17      18          90       RL         72.0    10791   Pave   NaN      Reg
18      19          20       RL         66.0    13695   Pave   NaN      Reg
19      20          20       RL         70.0     7560   Pave   NaN      Reg
20      21          60       RL        101.0    14215   Pave   NaN      IR1
21      22          45       RM         57.0     7449   Pave  Grvl      Reg
22      23          20       RL         75.0     9742   Pave   NaN      Reg
23      24         120       RM         44.0     4224   Pave   NaN      Reg
24      25          20       RL          NaN     8246   Pave   NaN      IR1
25      26          20       RL        110.0    14230   Pave   NaN      Reg
26      27          20       RL         60.0     7200   Pave   NaN      Reg
27      28          20       RL         98.0    11478   Pave   NaN      Reg
28      29          20       RL         47.0    16321   Pave   NaN      IR1
29      30          30       RM         60.0     6324   Pave   NaN      IR1
30      31          70  C (all)         50.0     8500   Pave  Pave      Reg
31      32          20       RL          NaN     8544   Pave   NaN      IR1
32      33          20       RL         85.0    11049   Pave   NaN      Reg
33      34          20       RL         70.0    10552   Pave   NaN      IR1
34      35         120       RL         60.0     7313   Pave   NaN      Reg
35      36          60       RL        108.0    13418   Pave   NaN      Reg
36      37          20       RL        112.0    10859   Pave   NaN      Reg
37      38          20       RL         74.0     8532   Pave   NaN      Reg
38      39          20       RL         68.0     7922   Pave   NaN      Reg
39      40          90       RL         65.0     6040   Pave   NaN      Reg
40      41          20       RL         84.0     8658   Pave   NaN      Reg
41      42          20       RL        115.0    16905   Pave   NaN      Reg
42      43          85       RL          NaN     9180   Pave   NaN      IR1
43      44          20       RL          NaN     9200   Pave   NaN      IR1
44      45          20       RL         70.0     7945   Pave   NaN      Reg
45      46         120       RL         61.0     7658   Pave   NaN      Reg
46      47          50       RL         48.0    12822   Pave   NaN      IR1
47      48          20       FV         84.0    11096   Pave   NaN      Reg
48      49         190       RM         33.0     4456   Pave   NaN      Reg
49      50          20       RL         66.0     7742   Pave   NaN      Reg
50      51          60       RL          NaN    13869   Pave   NaN      IR2
51      52          50       RM         52.0     6240   Pave   NaN      Reg
52      53          90       RM        110.0     8472   Grvl   NaN      IR2
53      54          20       RL         68.0    50271   Pave   NaN      IR1
54      55          80       RL         60.0     7134   Pave   NaN      Reg
55      56          20       RL        100.0    10175   Pave   NaN      IR1
56      57         160       FV         24.0     2645   Pave  Pave      Reg
57      58          60       RL         89.0    11645   Pave   NaN      IR1
58      59          60       RL         66.0    13682   Pave   NaN      IR2
59      60          20       RL         60.0     7200   Pave   NaN      Reg
60      61          20       RL         63.0    13072   Pave   NaN      Reg
61      62          75       RM         60.0     7200   Pave   NaN      Reg
62      63         120       RL         44.0     6442   Pave   NaN      IR1
63      64          70       RM         50.0    10300   Pave   NaN      IR1
64      65          60       RL          NaN     9375   Pave   NaN      Reg
65      66          60       RL         76.0     9591   Pave   NaN      Reg
66      67          20       RL          NaN    19900   Pave   NaN      Reg
67      68          20       RL         72.0    10665   Pave   NaN      IR1
68      69          30       RM         47.0     4608   Pave   NaN      Reg
69      70          50       RL         81.0    15593   Pave   NaN      Reg
70      71          20       RL         95.0    13651   Pave   NaN      IR1
71      72          20       RL         69.0     7599   Pave   NaN      Reg
72      73          60       RL         74.0    10141   Pave   NaN      IR1
73      74          20       RL         85.0    10200   Pave   NaN      Reg
74      75          50       RM         60.0     5790   Pave   NaN      Reg
75      76         180       RM         21.0     1596   Pave   NaN      Reg
76      77          20       RL          NaN     8475   Pave   NaN      IR1
77      78          50       RM         50.0     8635   Pave   NaN      Reg
78      79          90       RL         72.0    10778   Pave   NaN      Reg
79      80          50       RM         60.0    10440   Pave  Grvl      Reg
80      81          60       RL        100.0    13000   Pave   NaN      Reg
81      82         120       RM         32.0     4500   Pave   NaN      Reg
82      83          20       RL         78.0    10206   Pave   NaN      Reg
83      84          20       RL         80.0     8892   Pave   NaN      IR1
84      85          80       RL          NaN     8530   Pave   NaN      IR1
85      86          60       RL        121.0    16059   Pave   NaN      Reg
86      87          60       RL        122.0    11911   Pave   NaN      IR2
87      88         160       FV         40.0     3951   Pave  Pave      Reg
88      89          50  C (all)        105.0     8470   Pave   NaN      IR1
89      90          20       RL         60.0     8070   Pave   NaN      Reg
90      91          20       RL         60.0     7200   Pave   NaN      Reg
91      92          20       RL         85.0     8500   Pave   NaN      Reg
92      93          30       RL         80.0    13360   Pave  Grvl      IR1
93      94         190  C (all)         60.0     7200   Pave   NaN      Reg
94      95          60       RL         69.0     9337   Pave   NaN      IR1
95      96          60       RL          NaN     9765   Pave   NaN      IR2
96      97          20       RL         78.0    10264   Pave   NaN      IR1
97      98          20       RL         73.0    10921   Pave   NaN      Reg
98      99          30       RL         85.0    10625   Pave   NaN      Reg
99     100          20       RL         77.0     9320   Pave   NaN      IR1
100    101          20       RL          NaN    10603   Pave   NaN      IR1
101    102          60       RL         77.0     9206   Pave   NaN      Reg
102    103          90       RL         64.0     7018   Pave   NaN      Reg
103    104          20       RL         94.0    10402   Pave   NaN      IR1
104    105          50       RM          NaN     7758   Pave   NaN      Reg
105    106          60       FV         75.0     9375   Pave   NaN      Reg
106    107          30       RM         60.0    10800   Pave  Grvl      Reg
107    108          20       RM         50.0     6000   Pave   NaN      Reg
108    109          50       RM         85.0     8500   Pave   NaN      Reg
109    110          20       RL        105.0    11751   Pave   NaN      IR1
110    111          50       RL         75.0     9525   Pave   NaN      Reg
111    112          80       RL          NaN     7750   Pave   NaN      IR1
112    113          60       RL         77.0     9965   Pave   NaN      Reg
113    114          20       RL          NaN    21000   Pave   NaN      Reg
114    115          70       RL         61.0     7259   Pave   NaN      IR1
115    116         160       FV         34.0     3230   Pave  Pave      Reg
116    117          20       RL          NaN    11616   Pave   NaN      Reg
117    118          20       RL         74.0     8536   Pave   NaN      Reg
118    119          60       RL         90.0    12376   Pave   NaN      Reg
119    120          60       RL         65.0     8461   Pave   NaN      Reg
120    121          80       RL          NaN    21453   Pave   NaN      IR1
121    122          50       RM         50.0     6060   Pave   NaN      Reg
122    123          20       RL         75.0     9464   Pave   NaN      Reg
123    124         120       RL         55.0     7892   Pave   NaN      Reg
124    125          20       RL         48.0    17043   Pave   NaN      IR1
125    126         190       RM         60.0     6780   Pave   NaN      Reg
126    127         120       RL          NaN     4928   Pave   NaN      IR1
127    128          45       RM         55.0     4388   Pave   NaN      IR1
128    129          60       RL         69.0     7590   Pave   NaN      Reg
129    130          20       RL         69.0     8973   Pave   NaN      Reg
130    131          60       RL         88.0    14200   Pave   NaN      Reg
131    132          60       RL          NaN    12224   Pave   NaN      IR1
132    133          20       RL         75.0     7388   Pave   NaN      Reg
133    134          20       RL          NaN     6853   Pave   NaN      IR1
134    135          20       RL         78.0    10335   Pave   NaN      IR1
135    136          20       RL         80.0    10400   Pave   NaN      Reg
136    137          20       RL          NaN    10355   Pave   NaN      IR1
137    138          90       RL         82.0    11070   Pave   NaN      Reg
138    139          60       RL         73.0     9066   Pave   NaN      IR1
139    140          60       RL         65.0    15426   Pave   NaN      IR1
140    141          20       RL         70.0    10500   Pave   NaN      Reg
141    142          20       RL         78.0    11645   Pave   NaN      Reg
142    143          50       RL         71.0     8520   Pave   NaN      Reg
143    144          20       RL         78.0    10335   Pave   NaN      IR1
144    145          90       RM         70.0     9100   Pave   NaN      Reg
145    146         160       RM         24.0     2522   Pave   NaN      Reg
146    147          30       RM         51.0     6120   Pave   NaN      Reg
147    148          60       RL          NaN     9505   Pave   NaN      IR1
148    149          20       RL         63.0     7500   Pave   NaN      Reg
149    150          50       RM          NaN     6240   Pave   NaN      Reg
150    151          20       RL        120.0    10356   Pave   NaN      Reg
151    152          20       RL        107.0    13891   Pave   NaN      Reg
152    153          60       RL          NaN    14803   Pave   NaN      IR1
153    154          20       RL          NaN    13500   Pave   NaN      Reg
154    155          30       RM         84.0    11340   Pave   NaN      Reg
155    156          50       RL         60.0     9600   Pave   NaN      Reg
156    157          20       RL         60.0     7200   Pave   NaN      Reg
157    158          60       RL         92.0    12003   Pave   NaN      Reg
158    159          60       FV        100.0    12552   Pave   NaN      Reg
159    160          60       RL        134.0    19378   Pave   NaN      IR1
160    161          20       RL          NaN    11120   Pave   NaN      IR1
161    162          60       RL        110.0    13688   Pave   NaN      IR1
162    163          20       RL         95.0    12182   Pave   NaN      Reg
163    164          45       RL         55.0     5500   Pave   NaN      Reg
164    165          40       RM         40.0     5400   Pave  Pave      Reg
165    166         190       RL         62.0    10106   Pave   NaN      Reg
166    167          20       RL          NaN    10708   Pave   NaN      IR1
167    168          60       RL         86.0    10562   Pave   NaN      Reg
168    169          60       RL         62.0     8244   Pave   NaN      IR1
169    170          20       RL          NaN    16669   Pave   NaN      IR1
170    171          50       RM          NaN    12358   Pave   NaN      IR1
171    172          20       RL        141.0    31770   Pave   NaN      IR1
172    173         160       RL         44.0     5306   Pave   NaN      IR1
173    174          20       RL         80.0    10197   Pave   NaN      IR1
174    175          20       RL         47.0    12416   Pave   NaN      IR1
175    176          20       RL         84.0    12615   Pave   NaN      Reg
176    177          60       RL         97.0    10029   Pave   NaN      IR1
177    178          50       RL          NaN    13650   Pave   NaN      Reg
178    179          20       RL         63.0    17423   Pave   NaN      IR1
179    180          30       RM         60.0     8520   Pave   NaN      Reg
180    181         160       FV          NaN     2117   Pave   NaN      Reg
181    182          70       RL         54.0     7588   Pave   NaN      Reg
182    183          20       RL         60.0     9060   Pave   NaN      Reg
183    184          50       RM         63.0    11426   Pave   NaN      Reg
184    185          50       RL         92.0     7438   Pave   NaN      IR1
185    186          75       RM         90.0    22950   Pave   NaN      IR2
186    187          80       RL          NaN     9947   Pave   NaN      IR1
187    188          50       RL         60.0    10410   Pave   NaN      Reg
188    189          90       RL         64.0     7018   Pave   NaN      Reg
189    190         120       RL         41.0     4923   Pave   NaN      Reg
190    191          70       RL         70.0    10570   Pave   NaN      Reg
191    192          60       RL          NaN     7472   Pave   NaN      IR1
192    193          20       RL         68.0     9017   Pave   NaN      IR1
193    194         160       RM         24.0     2522   Pave   NaN      Reg
194    195          20       RL         60.0     7180   Pave   NaN      IR1
195    196         160       RL         24.0     2280   Pave   NaN      Reg
196    197          20       RL         79.0     9416   Pave   NaN      Reg
197    198          75       RL        174.0    25419   Pave   NaN      Reg
198    199          75       RM         92.0     5520   Pave   NaN      Reg
199    200          20       RL         76.0     9591   Pave   NaN      Reg
200    201          20       RM         80.0     8546   Pave   NaN      Reg
201    202          20       RL         75.0    10125   Pave   NaN      Reg
202    203          50       RL         50.0     7000   Pave   NaN      Reg
203    204         120       RM          NaN     4438   Pave   NaN      Reg
204    205          50       RM         50.0     3500   Pave  Grvl      Reg
205    206          20       RL         99.0    11851   Pave   NaN      Reg
206    207          20       RL         40.0    13673   Pave   NaN      IR1
207    208          20       RL          NaN    12493   Pave   NaN      IR1
208    209          60       RL          NaN    14364   Pave   NaN      IR1
209    210          20       RL         75.0     8250   Pave   NaN      Reg
210    211          30       RL         67.0     5604   Pave   NaN      Reg
211    212          20       RL         83.0    10420   Pave   NaN      Reg
212    213          60       FV         72.0     8640   Pave   NaN      Reg
213    214          20       RL         43.0    13568   Pave   NaN      IR2
214    215          60       RL          NaN    10900   Pave   NaN      IR1
215    216          20       RL         72.0    10011   Pave   NaN      IR1
216    217          20       RL         65.0     8450   Pave   NaN      Reg
217    218          70       RM         57.0     9906   Pave  Grvl      Reg
218    219          50       RL          NaN    15660   Pave   NaN      IR1
219    220         120       RL         43.0     3010   Pave   NaN      Reg
220    221          20       RL         73.0     8990   Pave   NaN      IR1
221    222          60       RL          NaN     8068   Pave   NaN      IR1
222    223          60       RL         85.0    11475   Pave   NaN      Reg
223    224          20       RL         70.0    10500   Pave   NaN      Reg
224    225          20       RL        103.0    13472   Pave   NaN      Reg
225    226         160       RM         21.0     1680   Pave   NaN      Reg
226    227          60       RL         82.0     9950   Pave   NaN      IR1
227    228         160       RM         21.0     1869   Pave   NaN      Reg
228    229          20       RL         70.0     8521   Pave   NaN      Reg
229    230         120       RL         43.0     3182   Pave   NaN      Reg
230    231          20       RL         73.0     8760   Pave   NaN      Reg
231    232          60       RL        174.0    15138   Pave   NaN      IR1
232    233         160       RM         21.0     1680   Pave   NaN      Reg
233    234          20       RL         75.0    10650   Pave   NaN      Reg
234    235          60       RL          NaN     7851   Pave   NaN      Reg
235    236         160       RM         21.0     1680   Pave   NaN      Reg
236    237          20       RL         65.0     8773   Pave   NaN      Reg
237    238          60       RL          NaN     9453   Pave   NaN      IR1
238    239          20       RL         93.0    12030   Pave   NaN      Reg
239    240          50       RL         52.0     8741   Pave   NaN      Reg
240    241          20       FV         75.0     9000   Pave   NaN      Reg
241    242          30       RM         40.0     3880   Pave   NaN      Reg
242    243          50       RM         63.0     5000   Pave   NaN      Reg
243    244         160       RL         75.0    10762   Pave   NaN      Reg
244    245          60       RL          NaN     8880   Pave   NaN      IR1
245    246          20       RL         80.0    10400   Pave   NaN      Reg
246    247         190       RM         69.0     9142   Pave  Grvl      Reg
247    248          20       RL         75.0    11310   Pave   NaN      Reg
248    249          60       RL         72.0    11317   Pave   NaN      Reg
249    250          50       RL          NaN   159000   Pave   NaN      IR2
250    251          30       RL         55.0     5350   Pave   NaN      IR1
251    252         120       RM         44.0     4750   Pave   NaN      IR1
252    253          60       RL         65.0     8366   Pave   NaN      IR1
253    254          80       RL         85.0     9350   Pave   NaN      Reg
254    255          20       RL         70.0     8400   Pave   NaN      Reg
255    256          60       RL         66.0     8738   Pave   NaN      IR1
256    257          60       FV         64.0     8791   Pave   NaN      IR1
257    258          20       RL         68.0     8814   Pave   NaN      Reg
258    259          60       RL         80.0    12435   Pave   NaN      Reg
259    260          20       RM         70.0    12702   Pave   NaN      Reg
260    261          80       RL        120.0    19296   Pave   NaN      Reg
261    262          60       RL         69.0     9588   Pave   NaN      IR1

In [102]:
# View dataset statistics
dataset.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,...,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,...,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,...,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,...,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,...,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,...,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [103]:
# Checking missing values
missing_values = dataset.isnull().sum().sum()
print(f"Are any features missing data? Answer:", "No" if missing_values == 0 else "Yes")

Are any features missing data? Answer: Yes

In [104]:
# How to get column names, data types and column counts
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [105]:
# SalePrice statistics
sale_price_count = dataset['SalePrice'].count()
print(f"How many SalePrice values do I have? Answer: {sale_price_count}")

sale_price_mean = dataset['SalePrice'].mean()
print(f"What is the average house price? Answer: {sale_price_mean:.3f}")

sale_price_median = dataset['SalePrice'].median()
print(f"What's the median house price? Answer: {sale_price_median}")

sale_price_std = dataset['SalePrice'].std()
print(f"How spread out are the prices? Answer: {sale_price_std:.3f}")

sale_price_min = dataset['SalePrice'].min()
print(f"What is the cheapest house? Answer: {sale_price_min}")

sale_price_max= dataset['SalePrice'].max()
print(f"What is the most expensive house? Answer: {sale_price_max}")

sale_price_null = dataset['SalePrice'].isnull().sum()
print(f"Is there a null value in the SalePrice column? Answer: ", "No" if sale_price_null == 0 else "Yes")

How many SalePrice values do I have? Answer: 1460
What is the average house price? Answer: 180921.196
What's the median house price? Answer: 163000.0
How spread out are the prices? Answer: 79442.503
What is the cheapest house? Answer: 34900
What is the most expensive house? Answer: 755000
Is there a null value in the SalePrice column? Answer:  No

In [106]:
# View Correlation of SalePrice to other features in descending order
dataset.corr(numeric_only=True)['SalePrice'].sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [107]:
# Categorical Features
neighborhood_uniqe_values = dataset["Neighborhood"].nunique()
print(f"How many unique value are in Neighborhood? Answer: {neighborhood_uniqe_values}")

How many unique value are in Neighborhood? Answer: 25

In [108]:
# Grouping neighborhood and there average prices
dataset.groupby(["Neighborhood"])['SalePrice'].mean().sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [109]:
# Getting categorical feature unique values
dataset.select_dtypes('str').nunique().sort_values()

Street            2
Alley             2
CentralAir        2
Utilities         2
MasVnrType        3
LandSlope         3
PoolQC            3
PavedDrive        3
GarageFinish      3
BsmtQual          4
ExterQual         4
KitchenQual       4
BsmtCond          4
BsmtExposure      4
Fence             4
MiscFeature       4
LandContour       4
LotShape          4
FireplaceQu       5
Electrical        5
HeatingQC         5
GarageQual        5
GarageCond        5
MSZoning          5
LotConfig         5
BldgType          5
ExterCond         5
BsmtFinType1      6
RoofStyle         6
GarageType        6
Foundation        6
Heating           6
BsmtFinType2      6
SaleCondition     6
Functional        7
RoofMatl          8
HouseStyle        8
Condition2        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [110]:
dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
FireplaceQu       690
GarageType         81
GarageCond         81
GarageQual         81
GarageFinish       81
BsmtFinType2       38
BsmtExposure       38
BsmtFinType1       37
BsmtQual           37
BsmtCond           37
Electrical          1
KitchenQual         0
CentralAir          0
Functional          0
HeatingQC           0
Heating             0
PavedDrive          0
SaleType            0
MSZoning            0
Street              0
Condition2          0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
BldgType            0
Foundation          0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
SaleCondition       0
dtype: int64

In [111]:
dataset['PoolQC'].value_counts()

PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

In [112]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [113]:
dataset['Alley'].value_counts()

Alley
Grvl    50
Pave    41
Name: count, dtype: int64

In [114]:
dataset[['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageCond', 'GarageQual', 'GarageFinish', 'BsmtFinType2', 'BsmtExposure', 'BsmtFinType1', 'BsmtQual', 'BsmtCond']]

     PoolQC MiscFeature Alley  Fence FireplaceQu GarageType GarageCond  \
0       NaN         NaN   NaN    NaN         NaN     Attchd         TA
1       NaN         NaN   NaN    NaN          TA     Attchd         TA
2       NaN         NaN   NaN    NaN          TA     Attchd         TA
3       NaN         NaN   NaN    NaN          Gd     Detchd         TA
4       NaN         NaN   NaN    NaN          TA     Attchd         TA
5       NaN        Shed   NaN  MnPrv         NaN     Attchd         TA
6       NaN         NaN   NaN    NaN          Gd     Attchd         TA
7       NaN        Shed   NaN    NaN          TA     Attchd         TA
8       NaN         NaN   NaN    NaN          TA     Detchd         TA
9       NaN         NaN   NaN    NaN          TA     Attchd         TA
10      NaN         NaN   NaN    NaN         NaN     Detchd         TA
11      NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
12      NaN         NaN   NaN    NaN         NaN     Detchd         TA
13      NaN         NaN   NaN    NaN          Gd     Attchd         TA
14      NaN         NaN   NaN   GdWo          Fa     Attchd         TA
15      NaN         NaN   NaN  GdPrv         NaN     Detchd         TA
16      NaN        Shed   NaN    NaN          TA     Attchd         TA
17      NaN        Shed   NaN    NaN         NaN    CarPort         TA
18      NaN         NaN   NaN    NaN         NaN     Detchd         TA
19      NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
20      NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
21      NaN         NaN  Grvl  GdPrv          Gd     Attchd         TA
22      NaN         NaN   NaN    NaN          Gd     Attchd         TA
23      NaN         NaN   NaN    NaN          TA     Attchd         TA
24      NaN         NaN   NaN  MnPrv          TA     Attchd         TA
25      NaN         NaN   NaN    NaN          Gd     Attchd         TA
26      NaN         NaN   NaN    NaN         NaN     Detchd         TA
27      NaN         NaN   NaN    NaN          Gd     Attchd         TA
28      NaN         NaN   NaN    NaN          Gd     Attchd         TA
29      NaN         NaN   NaN    NaN         NaN     Detchd         TA
30      NaN         NaN  Pave  MnPrv         NaN     Detchd         Fa
31      NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
32      NaN         NaN   NaN    NaN         NaN     Attchd         TA
33      NaN         NaN   NaN    NaN          Gd     Attchd         TA
34      NaN         NaN   NaN    NaN          Gd     Attchd         TA
35      NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
36      NaN         NaN   NaN    NaN         NaN     Attchd         TA
37      NaN         NaN   NaN    NaN          TA     Attchd         TA
38      NaN         NaN   NaN    NaN         NaN     Detchd         TA
39      NaN         NaN   NaN    NaN         NaN        NaN        NaN
40      NaN         NaN   NaN   GdWo          TA     Attchd         TA
41      NaN         NaN   NaN    NaN          Gd     Attchd         TA
42      NaN         NaN   NaN  MnPrv         NaN     Attchd         Gd
43      NaN         NaN   NaN  MnPrv         NaN     Detchd         TA
44      NaN         NaN   NaN    NaN         NaN     Attchd         TA
45      NaN         NaN   NaN    NaN          Gd     Attchd         TA
46      NaN         NaN   NaN    NaN          Ex     Attchd         TA
47      NaN         NaN   NaN    NaN         NaN     Attchd         TA
48      NaN         NaN   NaN    NaN         NaN        NaN        NaN
49      NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
50      NaN         NaN   NaN    NaN         NaN     Attchd         TA
51      NaN        Shed   NaN  MnPrv          Gd     Detchd         TA
52      NaN         NaN   NaN    NaN         NaN    CarPort         TA
53      NaN         NaN   NaN    NaN          Gd     Attchd         TA
54      NaN         NaN   NaN  MnPrv          TA     Detchd         TA
55      NaN         NaN   NaN    NaN          Gd     Attchd         TA
56      NaN         NaN  Pave    NaN         NaN     Attchd         TA
57      NaN         NaN   NaN    NaN         NaN     Attchd         TA
58      NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
59      NaN         NaN   NaN  MnPrv         NaN     Detchd         TA
60      NaN         NaN   NaN    NaN         NaN     Detchd         TA
61      NaN         NaN   NaN    NaN         NaN     Detchd         TA
62      NaN         NaN   NaN    NaN          Gd     Attchd         TA
63      NaN         NaN   NaN  GdPrv         NaN     Detchd         TA
64      NaN         NaN   NaN  GdPrv         NaN     Attchd         TA
65      NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
66      NaN         NaN   NaN    NaN          Gd     Attchd         TA
67      NaN         NaN   NaN    NaN         NaN     Attchd         TA
68      NaN         NaN   NaN    NaN         NaN     Attchd         TA
69      NaN         NaN   NaN    NaN          TA     Attchd         TA
70      NaN         NaN   NaN    NaN          Gd     Attchd         TA
71      NaN         NaN   NaN    NaN         NaN     Detchd         TA
72      NaN         NaN   NaN    NaN          TA     Attchd         TA
73      NaN         NaN   NaN   GdWo         NaN     Attchd         TA
74      NaN         NaN   NaN    NaN         NaN     Detchd         TA
75      NaN         NaN   NaN   GdWo         NaN    BuiltIn         TA
76      NaN         NaN   NaN    NaN         NaN     Detchd         TA
77      NaN         NaN   NaN  MnPrv         NaN     Detchd         TA
78      NaN         NaN   NaN    NaN         NaN        NaN        NaN
79      NaN         NaN  Grvl  MnPrv         NaN     Detchd         TA
80      NaN         NaN   NaN    NaN          Gd     Attchd         TA
81      NaN         NaN   NaN    NaN         NaN     Attchd         TA
82      NaN         NaN   NaN    NaN          Gd     Attchd         TA
83      NaN         NaN   NaN    NaN         NaN     Detchd         TA
84      NaN        Shed   NaN    NaN          TA    BuiltIn         TA
85      NaN         NaN   NaN    NaN          TA     Attchd         TA
86      NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
87      NaN         NaN  Pave    NaN         NaN     Detchd         TA
88      NaN         NaN   NaN  MnPrv         NaN        NaN        NaN
89      NaN         NaN   NaN    NaN         NaN        NaN        NaN
90      NaN         NaN   NaN    NaN         NaN     Detchd         TA
91      NaN         NaN   NaN   GdWo         NaN     Attchd         TA
92      NaN         NaN  Grvl    NaN         NaN     Detchd         TA
93      NaN         NaN   NaN    NaN          Gd     Detchd         TA
94      NaN         NaN   NaN    NaN         NaN     Attchd         TA
95      NaN        Shed   NaN    NaN          TA    BuiltIn         TA
96      NaN         NaN   NaN    NaN         NaN     Attchd         TA
97      NaN         NaN   NaN    NaN         NaN     Attchd         TA
98      NaN        Shed   NaN    NaN         NaN    Basment         TA
99      NaN        Shed   NaN    NaN         NaN        NaN        NaN
100     NaN         NaN   NaN    NaN          TA     Attchd         TA
101     NaN         NaN   NaN    NaN          TA     Attchd         TA
102     NaN         NaN   NaN    NaN         NaN     Attchd         TA
103     NaN         NaN   NaN    NaN         NaN     Attchd         TA
104     NaN         NaN   NaN    NaN          TA     Detchd         TA
105     NaN         NaN   NaN    NaN          Gd     Attchd         TA
106     NaN        Shed  Grvl    NaN         NaN     Detchd         Fa
107     NaN         NaN   NaN    NaN         NaN     Detchd         TA
108     NaN         NaN   NaN    NaN         NaN        NaN        NaN
109     NaN         NaN   NaN  MnPrv          TA     Attchd         TA
110     NaN         NaN   NaN    NaN         NaN     Attchd         TA
111     NaN         NaN   NaN    NaN          TA    BuiltIn         TA
112     NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
113     NaN         NaN   NaN  MnPrv          Gd    Basment         TA
114     NaN         NaN   NaN  MnPrv          TA     Detchd         TA
115     NaN         NaN  Pave    NaN          Fa     Detchd         TA
116     NaN         NaN   NaN    NaN          Po     Attchd         TA
117     NaN         NaN   NaN    NaN         NaN     Attchd         TA
118     NaN         NaN   NaN    NaN          TA     Attchd         TA
119     NaN         NaN   NaN    NaN          Gd     Attchd         TA
120     NaN         NaN   NaN    NaN          TA     Attchd         TA
121     NaN         NaN   NaN  MnPrv         NaN     Detchd         TA
122     NaN         NaN   NaN    NaN         NaN     Attchd         TA
123     NaN         NaN   NaN    NaN         NaN     Attchd         TA
124     NaN         NaN   NaN    NaN          TA     Attchd         TA
125     NaN         NaN   NaN    NaN         NaN        NaN        NaN
126     NaN         NaN   NaN    NaN          TA     Attchd         TA
127     NaN         NaN   NaN    NaN          TA        NaN        NaN
128     NaN         NaN   NaN    NaN          Fa     Attchd         TA
129     NaN         NaN   NaN   MnWw         NaN     2Types         TA
130     NaN         NaN   NaN  GdPrv          Gd     Attchd         TA
131     NaN         NaN   NaN    NaN          TA    BuiltIn         TA
132     NaN         NaN   NaN    NaN         NaN     Detchd         TA
133     NaN         NaN   NaN    NaN         NaN     Attchd         TA
134     NaN         NaN   NaN  MnPrv          TA     Attchd         TA
135     NaN         NaN   NaN  MnPrv          Gd     Attchd         TA
136     NaN         NaN   NaN    NaN          Fa     Attchd         TA
137     NaN         NaN   NaN    NaN         NaN     2Types         TA
138     NaN         NaN   NaN  GdPrv          TA     Attchd         TA
139     NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
140     NaN         NaN   NaN    NaN          Po        NaN        NaN
141     NaN         NaN   NaN    NaN         NaN     Attchd         TA
142     NaN         NaN   NaN  MnPrv         NaN     Detchd         TA
143     NaN         NaN   NaN    NaN         NaN     Attchd         TA
144     NaN         NaN   NaN    NaN         NaN     Detchd         TA
145     NaN         NaN   NaN    NaN         NaN     Detchd         TA
146     NaN         NaN   NaN    NaN         NaN     Detchd         TA
147     NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
148     NaN         NaN   NaN    NaN         NaN        NaN        NaN
149     NaN         NaN   NaN    NaN         NaN     Detchd         TA
150     NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
151     NaN         NaN   NaN    NaN          Gd     Attchd         TA
152     NaN         NaN   NaN   GdWo          Gd     Attchd         TA
153     NaN         NaN   NaN    NaN          Gd     Attchd         TA
154     NaN         NaN   NaN    NaN         NaN     Detchd         Fa
155     NaN         NaN   NaN    NaN         NaN        NaN        NaN
156     NaN         NaN   NaN    NaN         NaN     Detchd         TA
157     NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
158     NaN         NaN   NaN   GdWo          Gd     Attchd         TA
159     NaN         NaN   NaN    NaN          Gd     Attchd         TA
160     NaN         NaN   NaN    NaN         NaN     Attchd         TA
161     NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
162     NaN         NaN   NaN    NaN          Gd     Attchd         TA
163     NaN         NaN   NaN  MnPrv         NaN        NaN        NaN
164     NaN         NaN  Pave    NaN         NaN     Detchd         TA
165     NaN         NaN   NaN    NaN         NaN        NaN        NaN
166     NaN         NaN   NaN   GdWo          Gd     Attchd         TA
167     NaN         NaN   NaN    NaN          Gd     Attchd         TA
168     NaN         NaN   NaN    NaN          Gd     Attchd         TA
169     NaN         NaN   NaN    NaN          TA     Attchd         TA
170     NaN         NaN   NaN    NaN         NaN     Detchd         TA
171     NaN         NaN   NaN    NaN          Gd     Attchd         TA
172     NaN         NaN   NaN    NaN          TA     Attchd         TA
173     NaN         NaN   NaN    NaN          TA     Attchd         TA
174     NaN         NaN   NaN    NaN          TA     Attchd         TA
175     NaN         NaN   NaN  MnPrv          Gd     Attchd         TA
176     NaN         NaN   NaN    NaN          TA     Attchd         TA
177     NaN         NaN   NaN    NaN          Gd     Attchd         TA
178     NaN         NaN   NaN    NaN          Gd     Attchd         TA
179     NaN         NaN   NaN    NaN         NaN     Detchd         TA
180     NaN         NaN   NaN    NaN          TA     Detchd         TA
181     NaN         NaN   NaN    NaN          Gd     Detchd         TA
182     NaN         NaN   NaN  MnPrv          Gd     Attchd         TA
183     NaN         NaN   NaN    NaN         NaN     Detchd         TA
184     NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
185     NaN         NaN   NaN  GdPrv          TA     Detchd         TA
186     NaN         NaN   NaN  GdPrv         NaN     Attchd         TA
187     NaN         NaN   NaN  MnPrv         NaN     Detchd         Fa
188     NaN         NaN   NaN    NaN          TA     Detchd         TA
189     NaN         NaN   NaN    NaN          Gd     Attchd         TA
190     NaN         NaN   NaN    NaN          TA     Detchd         TA
191     NaN         NaN   NaN    NaN         NaN     Attchd         TA
192     NaN         NaN   NaN    NaN         NaN     Attchd         TA
193     NaN         NaN   NaN    NaN         NaN     Detchd         TA
194     NaN         NaN   NaN    NaN         NaN     Detchd         TA
195     NaN         NaN   NaN    NaN          TA     Attchd         TA
196     NaN         NaN   NaN    NaN          Gd     Attchd         TA
197      Ex         NaN   NaN  GdPrv          Ex     Detchd         TA
198     NaN         NaN   NaN  MnPrv         NaN        NaN        NaN
199     NaN         NaN   NaN    NaN          Gd     Attchd         TA
200     NaN         NaN   NaN    NaN         NaN     Attchd         TA
201     NaN         NaN   NaN  MnPrv          Fa     Detchd         TA
202     NaN         NaN   NaN    NaN         NaN     Attchd         TA
203     NaN         NaN   NaN    NaN          Gd     Attchd         TA
204     NaN         NaN  Grvl   MnWw         NaN     Detchd         TA
205     NaN         NaN   NaN    NaN         NaN     Attchd         TA
206     NaN         NaN   NaN    NaN          TA     Attchd         TA
207     NaN         NaN   NaN   GdWo          Po     Attchd         TA
208     NaN         NaN   NaN    NaN          Gd     Attchd         TA
209     NaN         NaN   NaN  MnPrv         NaN     Attchd         Gd
210     NaN         NaN   NaN    NaN         NaN        NaN        NaN
211     NaN         NaN   NaN    NaN         NaN     Attchd         TA
212     NaN         NaN   NaN    NaN          TA     Attchd         TA
213     NaN         NaN   NaN    NaN         NaN     Attchd         TA
214     NaN        Shed   NaN  MnPrv         NaN     Attchd         TA
215     NaN         NaN   NaN  MnPrv          Fa     Attchd         TA
216     NaN         NaN   NaN    NaN         NaN     Attchd         TA
217     NaN         NaN  Grvl    NaN         NaN     Detchd         TA
218     NaN         NaN   NaN    NaN          TA     Attchd         TA
219     NaN         NaN   NaN    NaN         NaN     Attchd         TA
220     NaN         NaN   NaN    NaN         NaN     Attchd         TA
221     NaN         NaN   NaN    NaN          TA    BuiltIn         TA
222     NaN         NaN   NaN  MnPrv          TA     Attchd         TA
223     NaN         NaN   NaN    NaN         NaN     Detchd         TA
224     NaN         NaN   NaN    NaN          Ex     Attchd         TA
225     NaN         NaN   NaN    NaN         NaN     Detchd         TA
226     NaN         NaN   NaN    NaN          TA     Attchd         TA
227     NaN         NaN   NaN    NaN         NaN     Detchd         TA
228     NaN         NaN   NaN  MnPrv          Fa     Detchd         TA
229     NaN         NaN   NaN    NaN          TA     Attchd         TA
230     NaN         NaN   NaN    NaN         NaN     Attchd         TA
231     NaN         NaN   NaN    NaN          TA     Attchd         TA
232     NaN         NaN   NaN    NaN          Po     Attchd         TA
233     NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
234     NaN         NaN   NaN    NaN          TA    BuiltIn         TA
235     NaN         NaN   NaN    NaN         NaN     Detchd         TA
236     NaN         NaN   NaN    NaN         NaN     Attchd         TA
237     NaN         NaN   NaN    NaN         NaN     Attchd         TA
238     NaN         NaN   NaN    NaN         NaN     Attchd         TA
239     NaN         NaN   NaN  MnPrv          Gd     Detchd         TA
240     NaN         NaN   NaN    NaN         NaN     Attchd         TA
241     NaN         NaN   NaN    NaN         NaN        NaN        NaN
242     NaN         NaN   NaN    NaN         NaN     Attchd         TA
243     NaN         NaN   NaN    NaN          TA     Attchd         TA
244     NaN         NaN   NaN    NaN          Fa     Attchd         TA
245     NaN         NaN   NaN    NaN          TA     Attchd         TA
246     NaN         NaN  Grvl    NaN         NaN     Detchd         Po
247     NaN         NaN   NaN    NaN          TA     Attchd         TA
248     NaN         NaN   NaN    NaN         NaN     Attchd         TA
249     NaN        Shed   NaN    NaN          TA     Attchd         TA
250     NaN        Shed   NaN   GdWo         NaN        NaN        NaN
251     NaN         NaN   NaN    NaN          Gd     Attchd         TA
252     NaN         NaN   NaN    NaN         NaN     Attchd         TA
253     NaN         NaN   NaN  MnPrv         NaN     Attchd         TA
254     NaN         NaN   NaN    NaN         NaN     Attchd         TA
255     NaN         NaN   NaN    NaN          TA    BuiltIn         TA
256     NaN         NaN   NaN    NaN         NaN     Attchd         TA
257     NaN         NaN   NaN    NaN          Gd     Attchd         TA
258     NaN         NaN   NaN    NaN          TA     Attchd         TA
259     NaN         NaN   NaN    NaN         NaN     Detchd         TA
260     NaN         NaN   NaN   GdWo          TA     Attchd         TA
261     NaN         NaN   NaN    NaN          Gd    BuiltIn         TA
262     NaN         NaN   NaN   GdWo          TA     Attchd         TA
263     NaN         NaN   NaN    NaN         NaN     Detchd         TA
264     NaN         NaN  Grvl    NaN         NaN     Detchd         TA
265     NaN         NaN   NaN  GdPrv          TA     Attchd         TA
266     NaN         NaN   NaN    NaN          TA     Attchd         TA
267     NaN         NaN   NaN    NaN          Gd     Detchd         TA
268     NaN         NaN   NaN    NaN          Gd     Detchd         Ex
269     NaN         NaN   NaN  GdPrv          Fa     Attchd         Gd
270     NaN         NaN   NaN    NaN          Gd     Attchd         TA
271     NaN         NaN   NaN    NaN          TA     Attchd         TA
272     NaN         NaN   NaN    NaN          Gd     Attchd         TA
273     NaN         NaN   NaN  MnPrv          Gd     Attchd         TA
274     NaN         NaN   NaN    NaN         NaN     Attchd         TA
275     NaN         NaN   NaN    NaN         NaN     Detchd         TA
276     NaN         NaN   NaN    NaN         NaN     Attchd         TA
277     NaN         NaN   NaN    NaN         NaN     Detchd         TA
278     NaN         NaN   NaN    NaN          Ex     Attchd         TA
279     NaN         NaN   NaN    NaN          TA     Attchd         TA

In [115]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [116]:
dataset[dataset['MasVnrType'].isnull()]['MasVnrArea'].value_counts(dropna=False)

MasVnrArea
0.0      859
NaN        8
1.0        2
288.0      1
344.0      1
312.0      1
Name: count, dtype: int64

In [117]:
dataset[dataset['MasVnrType'].isnull() & (dataset['MasVnrArea'] != 0)][['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
624         NaN       288.0
650         NaN         NaN
773         NaN         1.0
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1230        NaN         1.0
1243        NaN         NaN
1278        NaN         NaN
1300        NaN       344.0
1334        NaN       312.0

In [118]:
dataset.loc[
    [624, 773, 1230, 1300, 1334],
    ['MasVnrType', 'MasVnrArea', 'OverallQual',
     'YearBuilt', 'YearRemodAdd', 'Neighborhood', 
     'HouseStyle']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,Neighborhood,HouseStyle
624,NaN,288.0,6,1972,1972,NWAmes,2Story
773,NaN,1.0,5,1958,1958,NAmes,1Story
1230,NaN,1.0,5,1977,1977,Sawyer,1.5Fin
1300,NaN,344.0,7,1999,1999,Gilbert,2Story
1334,NaN,312.0,5,1970,1970,BrDale,2Story

In [119]:
# Investigating cell 624
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['HouseStyle'] == '2Story')
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
7         Stone       240.0            7       1973          1973
152     BrkFace       252.0            6       1971          1971
222         NaN         0.0            6       1975          1975
293     BrkFace        34.0            7       1977          1994
298     BrkFace       365.0            6       1968          1968
316     BrkFace       278.0            7       1980          1980
364     BrkFace       120.0            6       1976          1976
471         NaN         0.0            7       1977          1977
621         NaN         0.0            6       1974          1997
624         NaN       288.0            6       1972          1972
643     BrkFace       263.0            5       1969          1969
660     BrkFace       233.0            7       1976          1976
745     BrkFace       289.0            8       1976          1996
766     BrkFace        42.0            7       1988          1988
859     BrkFace       220.0            6       1968          1984
927     BrkFace       342.0            7       1968          1968
961     BrkFace       424.0            6       1977          1995
988     BrkFace       298.0            6       1976          1976
1015        NaN         0.0            8       2001          2001
1041    BrkFace       252.0            6       1966          2000
1071        NaN         0.0            6       1968          1968
1111    BrkFace       660.0            7       1976          1976
1141    BrkFace        44.0            5       1976          1976
1159    BrkFace       270.0            6       1974          1974
1276        NaN         0.0            6       1972          1972
1293        NaN         0.0            7       1976          1976
1386    BrkFace       184.0            7       1978          1978
1409    BrkFace       123.0            7       1986          1991
1420    BrkFace       420.0            6       1968          1968

In [120]:
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['MasVnrArea'].between(250, 350))
][['MasVnrType', 'MasVnrArea', 'Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea Neighborhood  OverallQual  YearBuilt  YearRemodAdd
135     BrkFace       288.0       NWAmes            7       1970          1970
152     BrkFace       252.0       NWAmes            6       1971          1971
316     BrkFace       278.0       NWAmes            7       1980          1980
455     BrkFace       320.0       NWAmes            7       1973          1973
516     BrkFace       333.0       NWAmes            6       1972          1972
624         NaN       288.0       NWAmes            6       1972          1972
643     BrkFace       263.0       NWAmes            5       1969          1969
745     BrkFace       289.0       NWAmes            8       1976          1996
927     BrkFace       342.0       NWAmes            7       1968          1968
988     BrkFace       298.0       NWAmes            6       1976          1976
1041    BrkFace       252.0       NWAmes            6       1966          2000
1159    BrkFace       270.0       NWAmes            6       1974          1974
1429    BrkFace       310.0       NWAmes            6       1981          1981

In [121]:
dataset.loc[624, ['MasVnrType']] = 'BrkFace'

In [122]:
dataset.loc[624, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      288.0
Name: 624, dtype: object

In [123]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
14      BrkFace       212.0            6       1960          1960
16      BrkFace       180.0            6       1970          1970
37      BrkFace       650.0            5       1954          1990
40      BrkFace       101.0            6       1965          1965
55      BrkFace       272.0            6       1964          1964
66      BrkFace       287.0            7       1970          1989
70      BrkFace      1115.0            7       1973          1973
73      BrkFace       104.0            5       1954          2003
83       BrkCmn        66.0            5       1960          1960
91       BrkCmn       203.0            5       1961          1961
122     BrkFace       135.0            6       1958          1958
129     BrkFace        85.0            5       1958          1991
136     BrkFace       196.0            5       1967          1967
171       Stone       112.0            6       1960          1960
173      BrkCmn       491.0            6       1961          1961
209       Stone       260.0            6       1964          1964
215     BrkFace        64.0            5       1957          1996
230     BrkFace       220.0            6       1959          1959
273      BrkCmn       183.0            6       1958          1988
294       Stone       238.0            6       1953          1953
327     BrkFace       175.0            6       1960          1960
330     BrkFace        84.0            5       1964          1964
339     BrkFace       176.0            6       1958          1998
342     BrkFace       340.0            3       1949          1950
347     BrkFace        30.0            6       1960          1960
366     BrkFace       247.0            6       1963          1963
368     BrkFace       200.0            5       1954          1954
424     BrkFace        74.0            6       1956          1956
486     BrkFace       168.0            5       1965          1965
509     BrkFace       132.0            5       1959          1959
510      BrkCmn        70.0            5       1951          2000
570     BrkFace       108.0            5       1965          1965
571     BrkFace       207.0            6       1959          1959
580     BrkFace        85.0            6       1960          1987
625     BrkFace       261.0            6       1962          1962
656     BrkFace        54.0            5       1959          2006
662     BrkFace       216.0            6       1968          1968
728     BrkFace        95.0            5       1958          1958
773         NaN         1.0            5       1958          1958
813     BrkFace       243.0            6       1958          1958
830     BrkFace       387.0            6       1957          1957
833     BrkFace       180.0            6       1964          1964
834     BrkFace       136.0            5       1961          1961
865     BrkFace        76.0            5       1970          1970
884     BrkFace        60.0            5       1967          1967
886     BrkFace       122.0            5       1959          2005
889     BrkFace        90.0            6       1953          1953
905       Stone       110.0            5       1954          1954
967     BrkFace       151.0            5       1955          1955
1014    BrkFace       206.0            6       1948          1950
1026    BrkFace       324.0            5       1960          1960
1064    BrkFace       200.0            5       1966          1966
1070    BrkFace       120.0            5       1956          1956
1083    BrkFace       425.0            6       1964          1964
1093    BrkFace       166.0            5       1965          1998
1102    BrkFace        45.0            5       1960          2002
1223    BrkFace        44.0            5       1951          1951
1227    BrkFace       300.0            5       1965          2008
1233    BrkFace       180.0            5       1959          1959
1295    BrkFace       168.0            5       1968          1968
1296    BrkFace       148.0            5       1963          1963
1356    BrkFace        65.0            5       1966          1966
1425      Stone       243.0            6       1959          1959
1435    BrkFace       237.0            6       1962          2005

In [124]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['YearBuilt'].between(1955, 1961)) &
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
14      BrkFace       212.0            6       1960          1960     1Story
83       BrkCmn        66.0            5       1960          1960     1Story
91       BrkCmn       203.0            5       1961          1961     1Story
122     BrkFace       135.0            6       1958          1958     1Story
129     BrkFace        85.0            5       1958          1991     1Story
171       Stone       112.0            6       1960          1960     1Story
173      BrkCmn       491.0            6       1961          1961     1Story
215     BrkFace        64.0            5       1957          1996     1Story
230     BrkFace       220.0            6       1959          1959     1Story
273      BrkCmn       183.0            6       1958          1988     1Story
327     BrkFace       175.0            6       1960          1960     1Story
339     BrkFace       176.0            6       1958          1998     1Story
347     BrkFace        30.0            6       1960          1960     1Story
424     BrkFace        74.0            6       1956          1956     1Story
509     BrkFace       132.0            5       1959          1959     1Story
571     BrkFace       207.0            6       1959          1959     1Story
580     BrkFace        85.0            6       1960          1987     1Story
627     BrkFace       164.0            6       1955          1972       SLvl
656     BrkFace        54.0            5       1959          2006     1Story
728     BrkFace        95.0            5       1958          1958     1Story
773         NaN         1.0            5       1958          1958     1Story
813     BrkFace       243.0            6       1958          1958     1Story
830     BrkFace       387.0            6       1957          1957     1Story
834     BrkFace       136.0            5       1961          1961     1Story
886     BrkFace       122.0            5       1959          2005     1Story
910     BrkFace       361.0            5       1960          1960     2Story
946     BrkFace       128.0            5       1959          1959       SLvl
967     BrkFace       151.0            5       1955          1955     1Story
969     BrkFace       105.0            6       1958          1958       SLvl
980       Stone       210.0            7       1961          2007     SFoyer
1026    BrkFace       324.0            5       1960          1960     1Story
1070    BrkFace       120.0            5       1956          1956     1Story
1102    BrkFace        45.0            5       1960          2002     1Story
1225    BrkFace        63.0            6       1958          1958       SLvl
1233    BrkFace       180.0            5       1959          1959     1Story
1269    BrkFace       180.0            5       1958          1958     1.5Fin
1425      Stone       243.0            6       1959          1959     1Story

In [125]:
dataset[(dataset['MasVnrArea'] <= 10) &
(dataset['MasVnrArea'] > 0)][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
773         NaN         1.0            5       1958          1958     1Story
1230        NaN         1.0            5       1977          1977     1.5Fin

In [126]:
# Investigating cell 1230
dataset.loc[1230, ['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

Neighborhood     Sawyer
MasVnrType          NaN
MasVnrArea          1.0
OverallQual           5
YearBuilt          1977
YearRemodAdd       1977
HouseStyle       1.5Fin
Exterior1st     Plywood
Exterior2nd     Plywood
Name: 1230, dtype: object

In [127]:
dataset[
    (dataset['MasVnrType'].isnull()) &
    (dataset['MasVnrArea'] > 0)
    ][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,Exterior1st,Exterior2nd
773,NAmes,NaN,1.0,5,1958,1958,1Story,Wd Sdng,Wd Sdng
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,Plywood,Plywood
1300,Gilbert,NaN,344.0,7,1999,1999,2Story,VinylSd,VinylSd
1334,BrDale,NaN,312.0,5,1970,1970,2Story,HdBoard,HdBoard

In [128]:
# Investigating row 1300
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['YearBuilt'].between(1997, 2001))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
72,BrkFace,40.0,7,1998,1998,2Story,60,RL,Pave,VinylSd,VinylSd
131,BrkFace,40.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
147,BrkFace,180.0,7,2001,2001,2Story,60,RL,Pave,VinylSd,VinylSd
255,BrkFace,302.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
379,BrkFace,16.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
665,BrkFace,40.0,8,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
929,BrkFace,285.0,7,1997,1997,2Story,60,RL,Pave,HdBoard,HdBoard
941,BrkFace,298.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1300,NaN,344.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1433,BrkFace,318.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd

In [129]:
dataset.loc[1300, ['MasVnrType']] = 'BrkFace'

In [130]:
dataset.loc[1300, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      344.0
Name: 1300, dtype: object

In [131]:
# Investigating row 1334
dataset[(dataset['Neighborhood'] == 'BrDale') &
(dataset['YearBuilt'].between(1965, 1975))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
225,BrkFace,142.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
227,BrkFace,127.0,6,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
232,BrkFace,297.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
235,BrkFace,604.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
363,BrkFace,510.0,6,1972,2007,2Story,160,RM,Pave,HdBoard,HdBoard
430,BrkFace,232.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
432,BrkFace,376.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
500,BrkFace,285.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
655,BrkFace,381.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,ImStucc
837,BrkFace,158.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
1029,BrkFace,281.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
1104,BrkFace,304.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1219,BrkFace,236.0,6,1971,1971,2Story,160,RM,Pave,CemntBd,CmentBd
1291,BrkFace,268.0,5,1972,1972,2Story,160,RM,Pave,CemntBd,CmentBd
1334,NaN,312.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1378,BrkFace,408.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard

In [132]:
dataset.loc[1334, ['MasVnrType']] = 'BrkFace'

In [133]:
dataset.loc[1334, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1334, dtype: str

In [134]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['YearBuilt'].between(1956, 1960))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
83,NAmes,BrkCmn,66.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,MetalSd
129,NAmes,BrkFace,85.0,5,1958,1991,1Story,20,RL,Pave,Plywood,Plywood
215,NAmes,BrkFace,64.0,5,1957,1996,1Story,20,RL,Pave,HdBoard,HdBoard
509,NAmes,BrkFace,132.0,5,1959,1959,1Story,20,RL,Pave,MetalSd,MetalSd
656,NAmes,BrkFace,54.0,5,1959,2006,1Story,20,RL,Pave,HdBoard,HdBoard
728,NAmes,BrkFace,95.0,5,1958,1958,1Story,90,RL,Pave,VinylSd,VinylSd
773,NAmes,NaN,1.0,5,1958,1958,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
886,NAmes,BrkFace,122.0,5,1959,2005,1Story,90,RL,Pave,MetalSd,MetalSd
1026,NAmes,BrkFace,324.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,HdBoard
1070,NAmes,BrkFace,120.0,5,1956,1956,1Story,20,RL,Pave,MetalSd,MetalSd
1102,NAmes,BrkFace,45.0,5,1960,2002,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
1233,NAmes,BrkFace,180.0,5,1959,1959,1Story,20,RL,Pave,Plywood,Plywood

In [135]:
dataset.loc[773, ['MasVnrType']] = 'BrkFace'

In [136]:
dataset.loc[773, ['MasVnrType']]

MasVnrType    BrkFace
Name: 773, dtype: str

In [137]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['YearBuilt'].between(1970, 1985))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave,Plywood,Plywood
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave,Plywood,Plywood

In [138]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['Exterior1st'] == 'Plywood') &
(dataset['Exterior2nd'] == 'Plywood') &
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street
538,Sawyer,BrkFace,188.0,5,1968,1968,1Story,20,RL,Pave
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave
796,Sawyer,BrkFace,148.0,6,1977,1977,1Story,20,RL,Pave
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave

In [139]:
dataset.loc[1230, ['MasVnrType']] = 'BrkFace'

In [140]:
dataset.loc[1230, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1230, dtype: str

In [141]:
dataset.loc[[624, 773, 1230, 1300, 1334], ['Neighborhood','MasVnrType']]

     Neighborhood MasVnrType
624        NWAmes    BrkFace
773         NAmes    BrkFace
1230       Sawyer    BrkFace
1300      Gilbert    BrkFace
1334       BrDale    BrkFace

In [142]:
dataset[dataset['MasVnrType'].isnull() &
dataset['MasVnrArea'].isnull()][['Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
234,Gilbert,6,2002,2002,2Story,60,RL,Pave,VinylSd,VinylSd
529,Crawfor,6,1957,1975,1Story,20,RL,Pave,Wd Sdng,Stone
650,Somerst,7,2007,2007,2Story,60,FV,Pave,CemntBd,CmentBd
936,SawyerW,7,2003,2003,1Story,20,RL,Pave,VinylSd,VinylSd
973,Somerst,7,2007,2008,1Story,20,FV,Pave,CemntBd,CmentBd
977,Somerst,7,2006,2007,1Story,120,FV,Pave,VinylSd,VinylSd
1243,NridgHt,10,2006,2006,1Story,20,RL,Pave,VinylSd,VinylSd
1278,CollgCr,8,2002,2002,2Story,60,RL,Pave,VinylSd,VinylSd

In [143]:
dataset.groupby('MasVnrType', dropna=False)['MasVnrArea'].agg(
    ['count', 'min', 'mean', 'max']
)

            count   min        mean     max
MasVnrType
BrkCmn         15  41.0  247.666667   621.0
BrkFace       450   0.0  258.233333  1600.0
Stone         128   0.0  239.304688   860.0
NaN           859   0.0    0.000000     0.0

In [144]:
dataset['MasVnrArea'].isnull().sum()

np.int64(8)

In [145]:
dataset[dataset['MasVnrArea'].isnull()]['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN    8
Name: count, dtype: int64

In [146]:
dataset[['MasVnrType', 'MasVnrArea']].isnull().sum()

MasVnrType    867
MasVnrArea      8
dtype: int64

In [147]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        867
BrkFace    450
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [148]:
dataset[dataset['MasVnrArea'] == 0]['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        859
BrkFace      1
Stone        1
Name: count, dtype: int64

In [149]:
dataset[(dataset['MasVnrArea'] == 0) &
(dataset['MasVnrType'].notnull())][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
688,StoneBr,BrkFace,0.0,8,2007,2007,1Story,20,RL,Pave,MetalSd,MetalSd
1241,Somerst,Stone,0.0,7,2007,2007,1Story,20,RL,Pave,VinylSd,VinylSd

In [150]:
dataset[(dataset['Neighborhood'] == 'StoneBr') &
(dataset['YearBuilt'].between(2000, 2010))][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,Exterior1st,Exterior2nd
58,StoneBr,BrkFace,1031.0,2006,10,2Story,VinylSd,VinylSd
178,StoneBr,Stone,748.0,2008,9,1Story,VinylSd,VinylSd
189,StoneBr,NaN,0.0,2001,8,1Story,CemntBd,CmentBd
336,StoneBr,Stone,200.0,2005,9,1Story,VinylSd,VinylSd
378,StoneBr,Stone,350.0,2010,9,1Story,VinylSd,VinylSd
474,StoneBr,NaN,0.0,2000,8,1Story,CemntBd,CmentBd
566,StoneBr,BrkFace,245.0,2005,9,2Story,VinylSd,VinylSd
595,StoneBr,BrkFace,238.0,2005,8,1Story,VinylSd,Other
678,StoneBr,Stone,464.0,2008,8,1Story,VinylSd,VinylSd
688,StoneBr,BrkFace,0.0,2007,8,1Story,MetalSd,MetalSd
702,StoneBr,BrkFace,466.0,2006,8,2Story,VinylSd,VinylSd
769,StoneBr,BrkFace,603.0,2003,8,2Story,CemntBd,Wd Shng
1046,StoneBr,Stone,208.0,2005,9,2Story,CemntBd,CmentBd
1060,StoneBr,NaN,0.0,2001,8,1Story,CemntBd,CmentBd
1288,StoneBr,NaN,0.0,2000,8,1Story,CemntBd,CmentBd
1361,StoneBr,Stone,16.0,2005,7,1Story,VinylSd,VinylSd

In [151]:
dataset.groupby(['MasVnrType',	'MasVnrArea'], dropna=False).size().sort_values(ascending=False)

MasVnrType  MasVnrArea
NaN         0.0           859
            NaN             8
BrkFace     120.0           7
            180.0           7
            16.0            6
            108.0           6
            80.0            6
            360.0           5
            320.0           5
            170.0           5
            72.0            5
            40.0            4
            196.0           4
            456.0           4
            340.0           4
            168.0           4
            252.0           4
            132.0           3
            130.0           3
Stone       186.0           3
BrkFace     116.0           3
Stone       72.0            3
            200.0           3
BrkFace     106.0           3
            136.0           3
            99.0            3
            90.0            3
            85.0            3
            84.0            3
            104.0           3
            176.0           3
            148.0           3
            169.0           3
Stone       50.0            3
BrkFace     178.0           3
Stone       106.0           3
BrkFace     200.0           3
Stone       100.0           3
BrkFace     210.0           3
            220.0           3
            246.0           3
            288.0           3
            336.0           3
            183.0           3
            312.0           3
            44.0            3
Stone       160.0           2
BrkFace     171.0           2
Stone       208.0           2
BrkFace     18.0            2
Stone       216.0           2
BrkFace     189.0           2
            184.0           2
            335.0           2
            30.0            2
Stone       240.0           2
BrkFace     174.0           2
            172.0           2
            344.0           2
            145.0           2
Stone       256.0           2
            84.0            2
BrkFace     164.0           2
Stone       268.0           2
BrkFace     160.0           2
            158.0           2
            157.0           2
Stone       270.0           2
BrkFace     153.0           2
            42.0            2
            318.0           2
            206.0           2
            212.0           2
            1.0             2
            268.0           2
            266.0           2
Stone       94.0            2
            76.0            2
BrkFace     281.0           2
Stone       108.0           2
            110.0           2
BrkFace     285.0           2
            289.0           2
Stone       132.0           2
BrkFace     245.0           2
            305.0           2
            236.0           2
            298.0           2
            233.0           2
            232.0           2
            226.0           2
            480.0           2
            300.0           2
Stone       166.0           2
BrkFace     304.0           2
            216.0           2
            147.0           2
            350.0           2
            144.0           2
            650.0           2
Stone       420.0           2
BrkFace     54.0            2
            105.0           2
            423.0           2
            101.0           2
            425.0           2
            98.0            2
            95.0            2
            442.0           2
            60.0            2
            82.0            2
            513.0           2
            76.0            2
            75.0            2
            74.0            2
Stone       340.0           2
BrkFace     270.0           2
            45.0            2
Stone       300.0           2
BrkFace     128.0           2
            660.0           2
            362.0           2
            125.0           2
            554.0           1
Stone       16.0            1
BrkFace     564.0           1
            664.0           1
Stone       24.0            1
            36.0            1
            42.0            1
BrkCmn      203.0           1
Stone       68.0            1
BrkFace     562.0           1
            632.0           1
            571.0           1
            530.0           1
Stone       70.0            1
BrkCmn      192.0           1
BrkFace     528.0           1
Stone       74.0            1
BrkFace     673.0           1
            510.0           1
            768.0           1
            766.0           1
Stone       82.0            1
BrkFace     731.0           1
            506.0           1
            541.0           1
            653.0           1
            630.0           1
            816.0           1
            870.0           1
            894.0           1
            616.0           1
            921.0           1
            922.0           1
            604.0           1
            603.0           1
            975.0           1
            600.0           1
            594.0           1
            1031.0          1
            1047.0          1
Stone       0.0             1
BrkFace     584.0           1
            579.0           1
            1115.0          1
            1129.0          1
            705.0           1
            1378.0          1
            1600.0          1
            772.0           1
            576.0           1
            651.0           1
            573.0           1
            1170.0          1
            68.0            1
Stone       92.0            1
            272.0           1
            370.0           1
            366.0           1
            351.0           1
            350.0           1
            338.0           1
            336.0           1
            328.0           1
            306.0           1
            302.0           1
            295.0           1
            294.0           1
            288.0           1
            286.0           1
            284.0           1
            275.0           1
            410.0           1
            424.0           1
            426.0           1
            748.0           1
BrkCmn      67.0            1
Stone       860.0           1
            796.0           1
            788.0           1
            762.0           1
            760.0           1
            640.0           1
            432.0           1
            567.0           1
            481.0           1
            468.0           1
            464.0           1
            450.0           1
            436.0           1
            274.0           1
            260.0           1
BrkCmn      183.0           1
Stone       250.0           1
            163.0           1
            162.0           1
            154.0           1
            149.0           1
            146.0           1
            145.0           1
            143.0           1
            140.0           1
            135.0           1
            128.0           1
            126.0           1
            119.0           1
            117.0           1
            112.0           1
BrkCmn      161.0           1
Stone       174.0           1
            178.0           1
            180.0           1
            224.0           1
            248.0           1
            246.0           1
            243.0           1
            238.0           1
            230.0           1
            226.0           1
            220.0           1
            182.0           1
            215.0           1
            210.0           1
            205.0           1
BrkCmn      70.0            1
Stone       194.0           1
BrkCmn      113.0           1
BrkFace     500.0           1
            376.0           1
            479.0           1
            22.0            1
            188.0           1
            27.0            1
            182.0           1
            28.0            1
            31.0            1
            175.0           1
            32.0            1
            34.0            1
            38.0            1
            167.0           1
            166.0           1
            165.0           1
            162.0           1
            156.0           1
            151.0           1
            192.0           1
            202.0           1
            473.0           1
            203.0           1
            237.0           1
            234.0           1
            228.0           1
            225.0           1
            223.0           1
            11.0            1
            219.0           1
            218.0           1
            215.0           1
            14.0            1
            209.0           1
            208.0           1
            207.0           1
            205.0           1
            204.0           1
            150.0           1
            149.0           1
            143.0           1
            142.0           1
            56.0            1
            102.0           1
            100.0           1
            57.0            1
            97.0            1
            96.0            1
            92.0            1
            89.0            1
            88.0            1
            86.0            1
            63.0            1
            64.0            1
            81.0            1
            65.0            1
            66.0            1
            53.0            1
            109.0           1
            110.0           1
            123.0           1
            140.0           1
            138.0           1
            137.0           1
            135.0           1
            46.0            1
            127.0           1
            122.0           1
            112.0           1
            48.0            1
            117.0           1
            51.0            1
            115.0           1
            114.0           1
            113.0           1
            238.0           1
            240.0           1
            243.0           1
            338.0           1
            388.0           1
            387.0           1
            381.0           1
            380.0           1
            378.0           1
            70.0            1
            375.0           1
            368.0           1
            365.0           1
            361.0           1
BrkCmn      328.0           1
BrkFace     359.0           1
            351.0           1
            348.0           1
            342.0           1
            391.0           1
            396.0           1
            399.0           1
            448.0           1
            472.0           1
            466.0           1
            459.0           1
BrkCmn      272.0           1
BrkFace     452.0           1
            451.0           1
            443.0           1
            408.0           1
            438.0           1
            428.0           1
            424.0           1
            420.0           1
            415.0           1
            412.0           1
BrkCmn      435.0           1
BrkFace     337.0           1
            244.0           1
BrkCmn      472.0           1
BrkFace     280.0           1
            278.0           1
            272.0           1
            263.0           1
            262.0           1
            261.0           1
            260.0           1
            259.0           1
            258.0           1
            256.0           1
            255.0           1
            254.0           1
            0.0             1
            250.0           1
            247.0           1
            284.0           1
            287.0           1
BrkCmn      621.0           1
BrkFace     309.0           1
            333.0           1
            324.0           1
BrkCmn      491.0           1
BrkFace     315.0           1
BrkCmn      66.0            1
BrkFace     310.0           1
            306.0           1
            290.0           1
            302.0           1
            299.0           1
            297.0           1
            296.0           1
            293.0           1
            292.0           1
BrkCmn      41.0            1
dtype: int64

In [152]:
dataset[
    (dataset['MasVnrArea'] == 0) &
    (dataset['MasVnrType'].isnull())].shape[0]

859

In [153]:
dataset.loc[
    (dataset['MasVnrArea'] == 0) &
    (dataset['MasVnrType'].isnull()),
    'MasVnrType'
    ] = 'None'

In [154]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
None       859
BrkFace    450
Stone      128
BrkCmn      15
NaN          8
Name: count, dtype: int64

In [155]:
dataset[dataset['MasVnrArea'].isnull()][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
234,Gilbert,NaN,NaN,2002,6,2Story,60,VinylSd,VinylSd
529,Crawfor,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone
650,Somerst,NaN,NaN,2007,7,2Story,60,CemntBd,CmentBd
936,SawyerW,NaN,NaN,2003,7,1Story,20,VinylSd,VinylSd
973,Somerst,NaN,NaN,2007,7,1Story,20,CemntBd,CmentBd
977,Somerst,NaN,NaN,2006,7,1Story,120,VinylSd,VinylSd
1243,NridgHt,NaN,NaN,2006,10,1Story,20,VinylSd,VinylSd
1278,CollgCr,NaN,NaN,2002,8,2Story,60,VinylSd,VinylSd

In [156]:
# Investigating row 234
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 6) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
221,None,0.0,2002,6,2Story,60,VinylSd,VinylSd
234,NaN,NaN,2002,6,2Story,60,VinylSd,VinylSd
616,None,0.0,2002,6,2Story,60,VinylSd,VinylSd

In [157]:
dataset.loc[234, ['MasVnrType',	'MasVnrArea']] = ['BrkFace', 0]

In [158]:
dataset.loc[234, ['MasVnrType',	'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea        0.0
Name: 234, dtype: object

In [159]:
# Investigating row 529
dataset[(dataset['Neighborhood'] == 'Crawfor') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'Wd Sdng') &
(dataset['Exterior2nd'] == 'Stone')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
529,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone

In [160]:
# Investigating row 529
dataset[(dataset['Neighborhood'] == 'Crawfor') &
(dataset['Exterior2nd'] == 'Stone')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
529,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone
1152,None,0.0,1956,6,1Story,20,Stone,Stone
1343,None,0.0,1928,6,1.5Fin,50,BrkFace,Stone

In [161]:
dataset.loc[529, ['MasVnrType', 'MasVnrArea']] = ['None', 0]

In [162]:
dataset.loc[529, ['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

MasVnrType        None
MasVnrArea         0.0
YearBuilt         1957
OverallQual          6
HouseStyle      1Story
MSSubClass          20
Exterior1st    Wd Sdng
Exterior2nd      Stone
Name: 529, dtype: object

In [163]:
# Investigating row 650
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['Exterior2nd'] == 'CmentBd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
377,None,0.0,2004,8,2Story,60,CemntBd,CmentBd
399,Stone,100.0,2006,7,2Story,60,CemntBd,CmentBd
650,NaN,NaN,2007,7,2Story,60,CemntBd,CmentBd
875,None,0.0,2007,8,2Story,60,CemntBd,CmentBd
1374,None,0.0,2005,7,2Story,60,CemntBd,CmentBd

In [164]:
dataset.loc[650, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [165]:
dataset.loc[650, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 650, dtype: object

In [166]:
# Investigating row 936
dataset[(dataset['Neighborhood'] == 'SawyerW') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
18,None,0.0,2004,5,1Story,20,VinylSd,VinylSd
60,None,0.0,2004,6,1Story,20,VinylSd,VinylSd
148,BrkFace,120.0,2004,7,1Story,20,VinylSd,VinylSd
742,BrkFace,108.0,2000,7,1Story,20,VinylSd,VinylSd
827,None,0.0,2001,7,1Story,20,VinylSd,VinylSd
936,NaN,NaN,2003,7,1Story,20,VinylSd,VinylSd
951,None,0.0,1965,5,1Story,20,VinylSd,VinylSd
1238,None,0.0,2005,6,1Story,20,VinylSd,VinylSd
1341,None,0.0,2003,6,1Story,20,VinylSd,VinylSd
1348,None,0.0,1998,7,1Story,20,VinylSd,VinylSd
1413,Stone,366.0,2005,8,1Story,20,VinylSd,VinylSd

In [167]:
dataset.loc[936, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [168]:
dataset.loc[936, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 936, dtype: object

In [169]:

# Investigating row 973
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['Exterior2nd'] == 'CmentBd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
196,Stone,205.0,2007,7,1Story,20,CemntBd,CmentBd
644,Stone,162.0,2009,9,1Story,20,CemntBd,CmentBd
793,Stone,140.0,2007,8,1Story,20,CemntBd,CmentBd
973,NaN,NaN,2007,7,1Story,20,CemntBd,CmentBd
1217,Stone,72.0,2009,8,1Story,20,CemntBd,CmentBd
1451,Stone,194.0,2008,8,1Story,20,CemntBd,CmentBd

In [170]:

# Investigating row 973
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['MasVnrType'] == 'Stone') &
(dataset['Exterior2nd'] == 'CmentBd')]['MasVnrArea'].agg(['count', 'mean', 'median', 'min', 'max'])

count       5.0
mean      154.6
median    162.0
min        72.0
max       205.0
Name: MasVnrArea, dtype: float64

In [171]:
dataset.loc[973, ['MasVnrArea']] = 162

In [172]:
dataset.loc[973, ['MasVnrType']] = 'Stone'

In [173]:
dataset.loc[973, ['MasVnrType', 'MasVnrArea']]

MasVnrType    Stone
MasVnrArea    162.0
Name: 973, dtype: object

In [174]:
# Investigating row 977
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 120) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
977,NaN,NaN,2006,7,1Story,120,VinylSd,VinylSd
1317,None,0.0,2006,7,1Story,120,VinylSd,VinylSd

In [175]:
dataset.loc[977, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [176]:
dataset.loc[977, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 977, dtype: object

In [177]:
# Investigating row 1243
dataset[(dataset['Neighborhood'] == 'NridgHt') &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2006) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'OverallQual']]

     MasVnrType  MasVnrArea  OverallQual
62        Stone       178.0            8
320       Stone       370.0            9
408     BrkFace       350.0            7
468       Stone       248.0            8
473     BrkFace       304.0            8
477     BrkFace       772.0            9
552       Stone       250.0            8
631       Stone       108.0            8
774     BrkFace       375.0            8
1243        NaN         NaN           10
1289      Stone       788.0            8
1305      Stone       300.0            9

In [178]:
# Investigating row 1243
dataset[(dataset['Neighborhood'] == 'NridgHt') &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2006) &
(dataset['MasVnrType'] == 'Stone') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrArea']].agg(['count', 'mean', 'median', 'min', 'max'])

        MasVnrArea
count     7.000000
mean    320.285714
median  250.000000
min     108.000000
max     788.000000

In [179]:
dataset.loc[1243, ['MasVnrType', 'MasVnrArea']] = ['Stone', 320.29]

In [180]:
dataset.loc[1243, ['MasVnrType', 'MasVnrArea']]

MasVnrType     Stone
MasVnrArea    320.29
Name: 1243, dtype: object

In [181]:
# Investigating row 1278
dataset[(dataset['Neighborhood'] == 'CollgCr') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 8) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
1054,BrkFace,210.0,2002,8,2Story,60,VinylSd,VinylSd
1278,NaN,NaN,2002,8,2Story,60,VinylSd,VinylSd
1342,BrkFace,149.0,2002,8,2Story,60,VinylSd,VinylSd

In [182]:
# Investigating row 1278
dataset[(dataset['Neighborhood'] == 'CollgCr') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 8) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrArea']].agg(['count', 'mean', 'median', 'min', 'max'])

        MasVnrArea
count          2.0
mean         179.5
median       179.5
min          149.0
max          210.0

In [183]:
dataset.loc[1278, ['MasVnrType', 'MasVnrArea']] = ['BrkFace', 179.5]

In [184]:
dataset.loc[1278, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      179.5
Name: 1278, dtype: object

In [185]:
dataset.loc[1278, ['OverallQual', 'GarageArea', 'GrLivArea', 'TotalBsmtSF','1stFlrSF', 'SalePrice']]

OverallQual         8
GarageArea        577
GrLivArea        2031
TotalBsmtSF      1128
1stFlrSF         1128
SalePrice      237000
Name: 1278, dtype: int64

In [186]:
dataset.loc[[234, 529, 650, 936, 973, 977, 1243, 1278], ['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234     BrkFace        0.00
529        None        0.00
650        None        0.00
936        None        0.00
973       Stone      162.00
977        None        0.00
1243      Stone      320.29
1278    BrkFace      179.50

In [187]:
dataset.isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
FireplaceQu       690
LotFrontage       259
GarageYrBlt        81
GarageType         81
GarageFinish       81
GarageQual         81
GarageCond         81
BsmtFinType2       38
BsmtExposure       38
BsmtCond           37
BsmtQual           37
BsmtFinType1       37
Electrical          1
TotRmsAbvGrd        0
Id                  0
KitchenQual         0
Functional          0
BedroomAbvGr        0
HalfBath            0
FullBath            0
BsmtHalfBath        0
BsmtFullBath        0
KitchenAbvGr        0
GarageCars          0
Fireplaces          0
LowQualFinSF        0
GarageArea          0
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
GrLivArea           0
HeatingQC           0
2ndFlrSF            0
1stFlrSF            0
OverallCond         0
OverallQual         0
HouseStyle          0
BldgType            0
Condition2          0
Condition1          0
Neighborhood        0
LandSlope           0
LotConfig           0
Utilities           0
LandContour         0
LotShape            0
Street              0
LotArea             0
MSZoning            0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
BsmtFinSF1          0
CentralAir          0
MSSubClass          0
Heating             0
TotalBsmtSF         0
BsmtUnfSF           0
BsmtFinSF2          0
Foundation          0
RoofMatl            0
ExterCond           0
ExterQual           0
MasVnrArea          0
MasVnrType          0
Exterior2nd         0
Exterior1st         0
SalePrice           0
dtype: int64

In [188]:
dataset[dataset['MasVnrType'].isnull() |
dataset['MasVnrArea'].isnull()][['MasVnrType', 'MasVnrArea']]

Empty DataFrame
Columns: [MasVnrType, MasVnrArea]
Index: []

In [189]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [190]:
dataset[dataset['BsmtQual'].isnull()]['TotalBsmtSF'].value_counts()

TotalBsmtSF
0    37
Name: count, dtype: int64

In [191]:
dataset[dataset['GarageQual'].isnull()]['GarageArea'].value_counts()

GarageArea
0    81
Name: count, dtype: int64

In [192]:
dataset[dataset['FireplaceQu'].isnull()]['Fireplaces'].value_counts()

Fireplaces
0    690
Name: count, dtype: int64

In [193]:
dataset[dataset['MiscFeature'].isnull()]['MiscVal'].value_counts()

MiscVal
0    1406
Name: count, dtype: int64

In [194]:
dataset[dataset['Fence'].isnull()][['Fence', 'LotArea', 'OverallQual']].head(20)

   Fence  LotArea  OverallQual
0    NaN     8450            7
1    NaN     9600            6
2    NaN    11250            7
3    NaN     9550            7
4    NaN    14260            8
6    NaN    10084            8
7    NaN    10382            7
8    NaN     6120            7
9    NaN     7420            5
10   NaN    11200            5
11   NaN    11924            9
12   NaN    12968            5
13   NaN    10652            7
16   NaN    11241            6
17   NaN    10791            4
18   NaN    13695            5
20   NaN    14215            8
22   NaN     9742            8
23   NaN     4224            5
25   NaN    14230            8

In [195]:
dataset.groupby('Neighborhood')['LotFrontage'].agg(['count', 'mean', 'median', 'min', 'max'])

              count       mean  median   min    max
Neighborhood
Blmngtn          14  47.142857    43.0  43.0   53.0
Blueste           2  24.000000    24.0  24.0   24.0
BrDale           16  21.562500    21.0  21.0   24.0
BrkSide          51  57.509804    52.0  50.0  144.0
ClearCr          13  83.461538    80.0  62.0  138.0
CollgCr         126  71.682540    70.0  36.0  122.0
Crawfor          41  71.804878    74.0  40.0  130.0
Edwards          92  68.217391    65.5  24.0  313.0
Gilbert          49  79.877551    65.0  42.0  182.0
IDOTRR           34  62.500000    60.0  40.0  120.0
MeadowV          15  27.800000    21.0  21.0   44.0
Mitchel          36  70.083333    73.0  32.0  129.0
NAmes           186  76.462366    73.0  34.0  313.0
NPkVill           7  32.285714    24.0  24.0   53.0
NWAmes           45  81.288889    80.0  46.0  105.0
NoRidge          33  91.878788    91.0  52.0  174.0
NridgHt          76  81.881579    88.5  34.0  129.0
OldTown         109  62.788991    60.0  30.0  153.0
SWISU            23  58.913043    60.0  50.0  102.0
Sawyer           48  74.437500    71.0  40.0  115.0
SawyerW          50  71.500000    66.5  50.0  116.0
Somerst          78  64.666667    73.5  24.0  116.0
StoneBr          20  62.700000    61.5  39.0  124.0
Timber           30  80.133333    85.0  42.0  150.0
Veenker           7  59.714286    68.0  30.0   90.0

In [196]:
dataset.groupby('Neighborhood')['LotFrontage'].transform('median')

0       70.0
1       68.0
2       70.0
3       74.0
4       91.0
5       73.0
6       73.5
7       80.0
8       60.0
9       52.0
10      71.0
11      88.5
12      71.0
13      70.0
14      73.0
15      52.0
16      73.0
17      71.0
18      66.5
19      73.0
20      88.5
21      60.0
22      70.0
23      21.0
24      71.0
25      88.5
26      73.0
27      88.5
28      73.0
29      52.0
30      60.0
31      71.0
32      70.0
33      73.0
34      88.5
35      88.5
36      70.0
37      73.0
38      73.0
39      65.5
40      73.0
41      85.0
42      66.5
43      70.0
44      73.0
45      88.5
46      73.0
47      73.5
48      60.0
49      71.0
50      65.0
51      52.0
52      60.0
53      68.0
54      73.0
55      73.0
56      73.5
57      70.0
58      61.5
59      70.0
60      66.5
61      60.0
62      88.5
63      60.0
64      70.0
65      88.5
66      73.0
67      70.0
68      60.0
69      80.0
70      73.0
71      73.0
72      65.0
73      73.0
74      60.0
75      21.0
76      73.0
77      52.0
78      71.0
79      60.0
80      73.0
81      73.0
82      73.5
83      73.0
84      65.0
85      91.0
86      65.0
87      73.5
88      60.0
89      70.0
90      73.0
91      73.0
92      74.0
93      60.0
94      70.0
95      65.0
96      70.0
97      65.5
98      65.5
99      73.0
100     80.0
101     66.5
102     66.5
103     70.0
104     60.0
105     73.5
106     60.0
107     60.0
108     60.0
109     80.0
110     65.5
111     65.0
112     70.0
113     74.0
114     74.0
115     73.5
116     71.0
117     65.5
118     66.5
119     70.0
120     80.0
121     60.0
122     73.0
123     66.5
124     80.0
125     60.0
126     24.0
127     60.0
128     73.0
129     73.0
130     73.0
131     65.0
132     73.0
133     85.0
134     71.0
135     80.0
136     73.0
137     73.0
138     70.0
139     70.0
140     73.0
141     70.0
142     73.0
143     70.0
144     71.0
145     65.5
146     52.0
147     65.0
148     66.5
149     52.0
150     70.0
151     88.5
152     80.0
153     80.0
154     60.0
155     65.5
156     73.0
157     85.0
158     73.5
159     65.0
160     68.0
161     88.5
162     88.5
163     60.0
164     60.0
165     65.5
166     80.0
167     88.5
168     65.0
169     85.0
170     60.0
171     73.0
172     61.5
173     73.0
174     85.0
175     65.5
176     80.0
177     71.0
178     61.5
179     60.0
180     73.5
181     74.0
182     65.5
183     60.0
184     52.0
185     60.0
186     73.0
187     60.0
188     66.5
189     61.5
190     74.0
191     73.0
192     70.0
193     65.5
194     70.0
195     24.0
196     73.5
197     73.0
198     60.0
199     88.5
200     65.5
201     73.0
202     60.0
203     70.0
204     60.0
205     65.0
206     71.0
207     73.0
208     66.5
209     73.0
210     65.5
211     65.5
212     73.5
213     70.0
214     70.0
215     73.0
216     70.0
217     60.0
218     74.0
219     43.0
220     70.0
221     65.0
222     80.0
223     73.0
224     88.5
225     21.0
226     91.0
227     21.0
228     71.0
229     43.0
230     73.0
231     91.0
232     21.0
233     70.0
234     65.0
235     21.0
236     70.0
237     66.5
238     88.5
239     65.5
240     73.5
241     60.0
242     60.0
243     66.5
244     66.5
245     80.0
246     60.0
247     73.0
248     70.0
249     80.0
250     52.0
251     74.0
252     66.5
253     73.0
254     73.0
255     65.0
256     73.5
257     70.0
258     70.0
259     60.0
260     73.0
261     70.0
262     71.0
263     60.0
264     60.0
265     80.0
266     65.0
267     60.0
268     60.0
269     65.5
270     73.5
271     80.0
272     91.0
273     73.0
274     73.0
275     52.0
276     73.0
277     65.0
278     88.5
279     80.0
280     66.5
281     73.5
282     88.5
283     73.5
284     66.5
285     73.5
286     73.0
287     73.0
288     71.0
289     52.0
290     70.0
291     60.0
292     65.5
293     80.0
294     73.0
295     73.0
296     60.0
297     73.5
298     80.0
299     74.0
300     74.0
301     70.0
302     70.0
303     70.0
304     60.0
305     70.0
306     66.5
307     60.0
308     65.5
309     88.5
310     65.0
311     73.0
312     60.0
313     85.0
314     60.0
315     65.0
316     80.0
317     73.5
318     91.0
319     80.0
320     88.5
321     88.5
322     66.5
323     60.0
324     73.0
325     60.0
326     68.0
327     73.0
328     52.0
329     60.0
330     73.0
331     73.0
332     88.5
333     88.5
334     65.0
335     85.0
336     61.5
337     70.0
338     80.0
339     73.0
340     85.0
341     66.5
342     73.0
343     88.5
344     21.0
345     52.0
346     73.0
347     73.0
348     88.5
349     88.5
350     88.5
351     80.0
352     65.5
353     60.0
354     60.0
355     70.0
356     65.0
357     21.0
358     80.0
359     91.0
360     73.0
361     52.0
362     65.5
363     21.0
364     80.0
365     60.0
366     73.0
367     73.0
368     73.0
369     73.0
370     65.0
371     80.0
372     66.5
373     73.0
374     70.0
375     65.5
376     70.0
377     73.5
378     61.5
379     65.0
380     60.0
381     73.5
382     70.0
383     66.5
384     80.0
385     43.0
386     65.5
387     65.5
388     70.0
389     88.5
390     65.5
391     73.0
392     73.0
393     52.0
394     60.0
395     65.5
396     70.0
397     73.0
398     60.0
399     73.5
400     68.0
401     70.0
402     71.0
403     91.0
404     65.0
405     71.0
406     60.0
407     74.0
408     88.5
409     73.5
410     65.5
411     65.0
412     73.5
413     60.0
414     66.5
415     65.0
416     71.0
417     74.0
418     65.5
419     73.0
420     73.0
421     80.0
422     73.0
423     91.0
424     73.0
425     60.0
426     66.5
427     73.0
428     70.0
429     85.0
430     21.0
431     60.0
432     21.0
433     65.0
434     21.0
435     70.0
436     60.0
437     52.0
438     74.0
439     65.5
440     88.5
441     65.5
442     52.0
443     43.0
444     70.0
445     65.5
446     73.0
447     65.0
448     60.0
449     60.0
450     60.0
451     80.0
452     85.0
453     73.5
454     73.0
455     80.0
456     60.0
457     80.0
458     60.0
459     52.0
460     73.5
461     60.0
462     71.0
463     74.0
464     70.0
465     43.0
466     73.0
467     73.0
468     88.5
469     66.5
470     61.5
471     80.0
472     65.5
473     88.5
474     61.5
475     71.0
476     70.0
477     88.5
478     70.0
479     60.0
480     88.5
481     88.5
482     60.0
483     73.0
484     71.0
485     73.0
486     73.0
487     80.0
488     60.0
489     21.0
490     21.0
491     73.0
492     65.0
493     73.0
494     60.0
495     60.0
496     91.0
497     52.0
498     71.0
499     73.0
500     21.0
501     73.5
502     65.5
503     74.0
504     24.0
505     60.0
506     66.5
507     73.5
508     60.0
509     73.0
510     73.0
511     88.5
512     73.0
513     73.0
514     74.0
515     88.5
516     80.0
517     91.0
518     70.0
519     74.0
520     60.0
521     73.0
522     52.0
523     65.5
524     91.0
525     73.5
526     73.0
527     88.5
528     65.5
529     74.0
530     85.0
531     52.0
532     73.0
533     52.0
534     65.0
535     65.5
536     70.0
537     73.0
538     71.0
539     70.0
540     85.0
541     91.0
542     80.0
543     73.0
544     65.0
545     80.0
546     52.0
547     73.0
548     60.0
549     73.5
550     24.0
551     60.0
552     88.5
553     65.5
554     88.5
555     52.0
556     73.0
557     60.0
558     65.0
559     43.0
560     71.0
561     73.0
562     65.5
563     65.5
564     91.0
565     60.0
566     61.5
567     88.5
568     66.5
569     73.0
570     73.0
571     73.0
572     85.0
573     65.0
574     73.0
575     73.0
576     60.0
577     71.0
578     73.5
579     60.0
580     73.0
581     88.5
582     65.5
583     60.0
584     52.0
585     85.0
586     52.0
587     71.0
588     80.0
589     52.0
590     70.0
591     88.5
592     73.0
593     70.0
594     70.0
595     61.5
596     60.0
597     43.0
598     74.0
599     24.0
600     88.5
601     60.0
602     66.5
603     73.5
604     70.0
605     73.0
606     70.0
607     65.5
608     74.0
609     71.0
610     70.0
611     80.0
612     70.0
613     73.0
614     21.0
615     73.0
616     65.0
617     73.0
618     88.5
619     85.0
620     65.5
621     80.0
622     71.0
623     73.5
624     80.0
625     73.0
626     73.0
627     73.0
628     73.0
629     73.0
630     60.0
631     88.5
632     80.0
633     73.0
634     60.0
635     60.0
636     52.0
637     60.0
638     65.5
639     43.0
640     88.5
641     73.5
642     73.0
643     80.0
644     73.5
645     73.0
646     73.0
647     65.5
648     73.0
649     21.0
650     73.5
651     65.5
652     70.0
653     60.0
654     91.0
655     21.0
656     73.0
657     74.0
658     73.0
659     65.5
660     80.0
661     91.0
662     73.0
663     65.5
664     73.5
665     65.0
666     73.0
667     66.5
668     71.0
669     74.0
670     70.0
671     65.5
672     68.0
673     74.0
674     73.0
675     24.0
676     60.0
677     60.0
678     61.5
679     71.0
680     66.5
681     60.0
682     80.0
683     70.0
684     91.0
685     61.5
686     73.5
687     73.5
688     61.5
689     88.5
690     70.0
691     91.0
692     85.0
693     60.0
694     52.0
695     85.0
696     52.0
697     65.5
698     71.0
699     73.5
700     85.0
701     80.0
702     61.5
703     60.0
704     70.0
705     60.0
706     80.0
707     88.5
708     65.0
709     71.0
710     52.0
711     60.0
712     61.5
713     52.0
714     71.0
715     80.0
716     60.0
717     80.0
718     91.0
719     70.0
720     61.5
721     70.0
722     73.0
723     65.5
724     65.5
725     73.0
726     74.0
727     70.0
728     73.0
729     60.0
730     61.5
731     85.0
732     70.0
733     71.0
734     71.0
735     60.0
736     73.0
737     65.0
738     65.5
739     70.0
740     60.0
741     71.0
742     66.5
743     71.0
744     61.5
745     80.0
746     65.0
747     60.0
748     91.0
749     65.5
750     60.0
751     65.0
752     70.0
753     88.5
754     73.0
755     73.5
756     70.0
757     71.0
758     73.5
759     91.0
760     73.0
761     52.0
762     73.5
763     91.0
764     68.0
765     73.5
766     80.0
767     73.0
768     70.0
769     61.5
770     71.0
771     65.5
772     65.5
773     73.0
774     88.5
775     73.0
776     70.0
777     71.0
778     66.5
779     73.0
780     65.0
781     66.5
782     70.0
783     73.0
784     60.0
785     80.0
786     60.0
787     66.5
788     60.0
789     80.0
790     43.0
791     73.0
792     91.0
793     73.5
794     65.0
795     66.5
796     71.0
797     73.0
798     88.5
799     60.0
800     80.0
801     60.0
802     70.0
803     88.5
804     73.0
805     73.5
806     73.0
807     52.0
808     73.0
809     60.0
810     80.0
811     70.0
812     60.0
813     73.0
814     65.5
815     70.0
816     73.0
817     73.0
818     80.0
819     88.5
820     70.0
821     60.0
822     65.0
823     60.0
824     73.5
825     88.5
826     52.0
827     66.5
828     80.0
829     73.5
830     73.0
831     73.5
832     70.0
833     73.0
834     73.0
835     71.0
836     60.0
837     21.0
838     70.0
839     65.5
840     60.0
841     60.0
842     73.0
843     73.0
844     60.0
845     71.0
846     66.5
847     70.0
848     80.0
849     68.0
850     70.0
851     43.0
852     74.0
853     73.0
854     71.0
855     71.0
856     70.0
857     65.0
858     80.0
859     80.0
860     74.0
861     71.0
862     66.5
863     73.0
864     73.5
865     73.0
866     85.0
867     71.0
868     65.0
869     66.5
870     73.0
871     70.0
872     73.0
873     73.0
874     60.0
875     73.5
876     73.0
877     88.5
878     71.0
879     70.0
880     65.5
881     85.0
882     65.0
883     60.0
884     73.0
885     73.5
886     73.0
887     65.5
888     73.0
889     73.0
890     73.0
891     71.0
892     71.0
893     71.0
894     66.5
895     73.0
896     60.0
897     66.5
898     88.5
899     71.0
900     73.0
901     73.0
902     65.0
903     65.0
904     71.0
905     73.0
906     73.5
907     74.0
908     73.0
909     65.0
910     73.0
911     70.0
912     52.0
913     74.0
914     73.5
915     21.0
916     60.0
917     65.5
918     66.5
919     73.0
920     66.5
921     65.5
922     65.0
923     66.5
924     80.0
925     80.0
926     88.5
927     80.0
928     70.0
929     65.0
930     85.0
931     73.0
932     73.5
933     70.0
934     73.0
935     52.0
936     66.5
937     73.5
938     70.0
939     80.0
940     73.0
941     65.0
942     65.5
943     73.0
944     85.0
945     60.0
946     73.0
947     85.0
948     70.0
949     80.0
950     73.0
951     66.5
952     70.0
953     73.0
954     65.5
955     74.0
956     24.0
957     71.0
958     70.0
959     73.5
960     52.0
961     80.0
962     24.0
963     70.0
964     85.0
965     65.0
966     74.0
967     73.0
968     60.0
969     73.0
970     73.0
971     88.5
972     66.5
973     73.5
974     52.0
975     73.5
976     52.0
977     73.5
978     65.5
979     71.0
980     73.0
981     91.0
982     43.0
983     70.0
984     73.0
985     65.5
986     60.0
987     88.5
988     80.0
989     73.5
990     91.0
991     60.0
992     73.0
993     70.0
994     88.5
995     52.0
996     73.0
997     80.0
998     60.0
999     70.0
1000    65.5
1001    60.0
1002    73.5
1003    80.0
1004    43.0
1005    70.0
1006    73.0
1007    21.0
1008    73.0
1009    60.0
1010    71.0
1011    65.5
1012    74.0
1013    60.0
1014    73.0
1015    80.0
1016    70.0
1017    61.5
1018    65.0
1019    43.0
1020    65.5
1021    70.0
1022    60.0
1023    43.0
1024    85.0
1025    70.0
1026    73.0
1027    85.0
1028    73.0
1029    21.0
1030    60.0
1031    60.0
1032    91.0
1033    70.0
1034    74.0
1035    65.5
1036    85.0
1037    70.0
1038    21.0
1039    21.0
1040    71.0
1041    80.0
1042    88.5
1043    66.5
1044    80.0
1045    65.5
1046    61.5
1047    70.0
1048    73.0
1049    65.5
1050    65.0
1051    70.0
1052    73.0
1053    65.5
1054    70.0
1055    80.0
1056    88.5
1057    91.0
1058    88.5
1059    74.0
1060    61.5
1061    60.0
1062    60.0
1063    60.0
1064    73.0
1065    80.0
1066    65.0
1067    73.0
1068    21.0
1069    73.0
1070    73.0
1071    80.0
1072    65.5
1073    65.5
1074    70.0
1075    74.0
1076    60.0
1077    73.0
1078    70.0
1079    70.0
1080    80.0
1081    71.0
1082    70.0
1083    73.0
1084    65.0
1085    66.5
1086    21.0
1087    73.5
1088    65.5
1089    73.5
1090    73.0
1091    73.5
1092    60.0
1093    73.0
1094    73.0
1095    70.0
1096    60.0
1097    61.5
1098    52.0
1099    80.0
1100    60.0
1101    73.0
1102    73.0
1103    73.0
1104    21.0
1105    91.0
1106    66.5
1107    65.0
1108    65.0
1109    88.5
1110    65.0
1111    80.0
1112    73.0
1113    73.0
1114    60.0
1115    88.5
1116    65.0
1117    71.0
1118    71.0
1119    73.0
1120    60.0
1121    70.0
1122    65.5
1123    65.5
1124    65.0
1125    73.0
1126    43.0
1127    65.0
1128    65.0
1129    60.0
1130    60.0
1131    73.0
1132    60.0
1133    66.5
1134    65.0
1135    52.0
1136    73.0
1137    71.0
1138    73.0
1139    52.0
1140    73.0
1141    80.0
1142    70.0
1143    71.0
1144    65.5
1145    52.0
1146    66.5
1147    74.0
1148    60.0
1149    60.0
1150    73.0
1151    65.5
1152    74.0
1153    60.0
1154    73.0
1155    68.0
1156    73.0
1157    88.5
1158    73.5
1159    80.0
1160    24.0
1161    74.0
1162    71.0
1163    71.0
1164    68.0
1165    88.5
1166    70.0
1167    65.0
1168    65.5
1169    91.0
1170    73.0
1171    73.0
1172    73.5
1173    80.0
1174    74.0
1175    91.0
1176    73.0
1177    60.0
1178    74.0
1179    65.5
1180    85.0
1181    74.0
1182    91.0
1183    60.0
1184    85.0
1185    65.5
1186    60.0
1187    91.0
1188    70.0
1189    65.0
1190    73.0
1191    73.5
1192    60.0
1193    73.0
1194    71.0
1195    65.0
1196    65.0
1197    60.0
1198    70.0
1199    71.0
1200    73.0
1201    70.0
1202    52.0
1203    70.0
1204    80.0
1205    66.5
1206    66.5
1207    70.0
1208    73.0
1209    73.5
1210    66.5
1211    65.0
1212    65.5
1213    71.0
1214    73.0
1215    71.0
1216    71.0
1217    73.5
1218    52.0
1219    21.0
1220    73.0
1221    71.0
1222    73.0
1223    73.0
1224    65.0
1225    73.0
1226    73.5
1227    73.0
1228    88.5
1229    73.0
1230    71.0
1231    73.0
1232    73.0
1233    73.0
1234    60.0
1235    74.0
1236    88.5
1237    70.0
1238    66.5
1239    85.0
1240    70.0
1241    73.5
1242    80.0
1243    88.5
1244    74.0
1245    80.0
1246    73.5
1247    73.0
1248    60.0
1249    73.0
1250    73.0
1251    88.5
1252    73.0
1253    68.0
1254    65.5
1255    52.0
1256    91.0
1257    65.5
1258    65.0
1259    73.0
1260    65.0
1261    73.0
1262    80.0
1263    52.0
1264    73.0
1265    73.5
1266    60.0
1267    85.0
1268    74.0
1269    73.0
1270    80.0
1271    80.0
1272    71.0
1273    65.5
1274    74.0
1275    73.0
1276    80.0
1277    80.0
1278    70.0
1279    60.0
1280    70.0
1281    85.0
1282    70.0
1283    73.0
1284    60.0
1285    52.0
1286    80.0
1287    80.0
1288    61.5
1289    88.5
1290    73.0
1291    21.0
1292    60.0
1293    80.0
1294    65.5
1295    73.0
1296    73.0
1297    65.5
1298    65.5
1299    73.0
1300    65.0
1301    74.0
1302    91.0
1303    73.5
1304    65.5
1305    88.5
1306    88.5
1307    70.0
1308    60.0
1309    66.5
1310    74.0
1311    70.0
1312    91.0
1313    91.0
1314    65.5
1315    73.0
1316    70.0
1317    73.5
1318    70.0
1319    65.5
1320    73.0
1321    52.0
1322    91.0
1323    52.0
1324    73.5
1325    60.0
1326    65.5
1327    73.0
1328    60.0
1329    65.0
1330    73.5
1331    70.0
1332    65.5
1333    60.0
1334    21.0
1335    80.0
1336    80.0
1337    60.0
1338    70.0
1339    70.0
1340    73.0
1341    66.5
1342    70.0
1343    74.0
1344    70.0
1345    60.0
1346    80.0
1347    85.0
1348    66.5
1349    60.0
1350    73.0
1351    73.0
1352    52.0
1353    91.0
1354    70.0
1355    80.0
1356    73.0
1357    73.0
1358    73.5
1359    88.5
1360    60.0
1361    61.5
1362    73.0
1363    65.0
1364    73.5
1365    73.5
1366    70.0
1367    21.0
1368    70.0
1369    70.0
1370    60.0
1371    73.0
1372    70.0
1373    91.0
1374    73.5
1375    85.0
1376    60.0
1377    65.5
1378    21.0
1379    85.0
1380    65.5
1381    73.0
1382    60.0
1383    71.0
1384    65.5
1385    60.0
1386    80.0
1387    60.0
1388    65.0
1389    52.0
1390    70.0
1391    73.0
1392    73.0
1393    60.0
1394    43.0
1395    85.0
1396    85.0
1397    52.0
1398    73.0
1399    60.0
1400    52.0
1401    65.0
1402    70.0
1403    73.5
1404    60.0
1405    74.0
1406    70.0
1407    73.0
1408    60.0
1409    80.0
1410    70.0
1411    73.0
1412    73.0
1413    66.5
1414    52.0
1415    43.0
1416    60.0
1417    91.0
1418    73.0
1419    74.0
1420    80.0
1421    24.0
1422    70.0
1423    65.5
1424    73.0
1425    73.0
1426    91.0
1427    73.0
1428    60.0
1429    80.0
1430    65.0
1431    24.0
1432    60.0
1433    65.0
1434    73.0
1435    73.0
1436    73.0
1437    88.5
1438    60.0
1439    80.0
1440    74.0
1441    70.0
1442    73.5
1443    52.0
1444    70.0
1445    71.0
1446    73.0
1447    70.0
1448    65.5
1449    21.0
1450    73.0
1451    73.5
1452    65.5
1453    73.0
1454    73.5
1455    65.0
1456    80.0
1457    74.0
1458    73.0
1459    65.5
Name: LotFrontage, dtype: float64

In [197]:
dataset[['Neighborhood', 'LotFrontage']].head(20)

   Neighborhood  LotFrontage
0       CollgCr         65.0
1       Veenker         80.0
2       CollgCr         68.0
3       Crawfor         60.0
4       NoRidge         84.0
5       Mitchel         85.0
6       Somerst         75.0
7        NWAmes          NaN
8       OldTown         51.0
9       BrkSide         50.0
10       Sawyer         70.0
11      NridgHt         85.0
12       Sawyer          NaN
13      CollgCr         91.0
14        NAmes          NaN
15      BrkSide         51.0
16        NAmes          NaN
17       Sawyer         72.0
18      SawyerW         66.0
19        NAmes         70.0

In [198]:
dataset[dataset['LotFrontage'].isnull()][['Neighborhood', 'LotFrontage']].head(20)

    Neighborhood  LotFrontage
7         NWAmes          NaN
12        Sawyer          NaN
14         NAmes          NaN
16         NAmes          NaN
24        Sawyer          NaN
31        Sawyer          NaN
42       SawyerW          NaN
43       CollgCr          NaN
50       Gilbert          NaN
64       CollgCr          NaN
66         NAmes          NaN
76         NAmes          NaN
84       Gilbert          NaN
95       Gilbert          NaN
100       NWAmes          NaN
104       IDOTRR          NaN
111      Gilbert          NaN
113      Crawfor          NaN
116       Sawyer          NaN
120      ClearCr          NaN

In [199]:
dataset['LotFrontage'].isnull().sum()

np.int64(259)

In [200]:
'NeighborhoodMedian' in dataset.columns

False

In [201]:
dataset[dataset['LotFrontage'].isnull()][['Neighborhood', 'LotFrontage']].head(20)

    Neighborhood  LotFrontage
7         NWAmes          NaN
12        Sawyer          NaN
14         NAmes          NaN
16         NAmes          NaN
24        Sawyer          NaN
31        Sawyer          NaN
42       SawyerW          NaN
43       CollgCr          NaN
50       Gilbert          NaN
64       CollgCr          NaN
66         NAmes          NaN
76         NAmes          NaN
84       Gilbert          NaN
95       Gilbert          NaN
100       NWAmes          NaN
104       IDOTRR          NaN
111      Gilbert          NaN
113      Crawfor          NaN
116       Sawyer          NaN
120      ClearCr          NaN

In [202]:
dataset['Electrical'].isnull().sum()

np.int64(1)

In [203]:
missing = dataset.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
Electrical         1
dtype: int64

In [204]:
# Inspecting garage without values
dataset[dataset['GarageType'].isnull()][['GarageArea', 'GarageCars', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']]

,GarageArea,GarageCars,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
39,0,0,NaN,NaN,NaN,NaN,NaN
48,0,0,NaN,NaN,NaN,NaN,NaN
78,0,0,NaN,NaN,NaN,NaN,NaN
88,0,0,NaN,NaN,NaN,NaN,NaN
89,0,0,NaN,NaN,NaN,NaN,NaN
99,0,0,NaN,NaN,NaN,NaN,NaN
108,0,0,NaN,NaN,NaN,NaN,NaN
125,0,0,NaN,NaN,NaN,NaN,NaN
127,0,0,NaN,NaN,NaN,NaN,NaN
140,0,0,NaN,NaN,NaN,NaN,NaN
148,0,0,NaN,NaN,NaN,NaN,NaN
155,0,0,NaN,NaN,NaN,NaN,NaN
163,0,0,NaN,NaN,NaN,NaN,NaN
165,0,0,NaN,NaN,NaN,NaN,NaN
198,0,0,NaN,NaN,NaN,NaN,NaN
210,0,0,NaN,NaN,NaN,NaN,NaN
241,0,0,NaN,NaN,NaN,NaN,NaN
250,0,0,NaN,NaN,NaN,NaN,NaN
287,0,0,NaN,NaN,NaN,NaN,NaN
291,0,0,NaN,NaN,NaN,NaN,NaN
307,0,0,NaN,NaN,NaN,NaN,NaN
375,0,0,NaN,NaN,NaN,NaN,NaN
386,0,0,NaN,NaN,NaN,NaN,NaN
393,0,0,NaN,NaN,NaN,NaN,NaN
431,0,0,NaN,NaN,NaN,NaN,NaN
434,0,0,NaN,NaN,NaN,NaN,NaN
441,0,0,NaN,NaN,NaN,NaN,NaN
464,0,0,NaN,NaN,NaN,NaN,NaN
495,0,0,NaN,NaN,NaN,NaN,NaN
520,0,0,NaN,NaN,NaN,NaN,NaN
528,0,0,NaN,NaN,NaN,NaN,NaN
533,0,0,NaN,NaN,NaN,NaN,NaN
535,0,0,NaN,NaN,NaN,NaN,NaN
562,0,0,NaN,NaN,NaN,NaN,NaN
582,0,0,NaN,NaN,NaN,NaN,NaN
613,0,0,NaN,NaN,NaN,NaN,NaN
614,0,0,NaN,NaN,NaN,NaN,NaN
620,0,0,NaN,NaN,NaN,NaN,NaN
635,0,0,NaN,NaN,NaN,NaN,NaN
636,0,0,NaN,NaN,NaN,NaN,NaN
638,0,0,NaN,NaN,NaN,NaN,NaN
649,0,0,NaN,NaN,NaN,NaN,NaN
705,0,0,NaN,NaN,NaN,NaN,NaN
710,0,0,NaN,NaN,NaN,NaN,NaN
738,0,0,NaN,NaN,NaN,NaN,NaN
750,0,0,NaN,NaN,NaN,NaN,NaN
784,0,0,NaN,NaN,NaN,NaN,NaN
826,0,0,NaN,NaN,NaN,NaN,NaN
843,0,0,NaN,NaN,NaN,NaN,NaN
921,0,0,NaN,NaN,NaN,NaN,NaN
942,0,0,NaN,NaN,NaN,NaN,NaN
954,0,0,NaN,NaN,NaN,NaN,NaN
960,0,0,NaN,NaN,NaN,NaN,NaN
968,0,0,NaN,NaN,NaN,NaN,NaN
970,0,0,NaN,NaN,NaN,NaN,NaN
976,0,0,NaN,NaN,NaN,NaN,NaN
1009,0,0,NaN,NaN,NaN,NaN,NaN
1011,0,0,NaN,NaN,NaN,NaN,NaN
1030,0,0,NaN,NaN,NaN,NaN,NaN
1038,0,0,NaN,NaN,NaN,NaN,NaN
1096,0,0,NaN,NaN,NaN,NaN,NaN
1123,0,0,NaN,NaN,NaN,NaN,NaN
1131,0,0,NaN,NaN,NaN,NaN,NaN
1137,0,0,NaN,NaN,NaN,NaN,NaN
1143,0,0,NaN,NaN,NaN,NaN,NaN
1173,0,0,NaN,NaN,NaN,NaN,NaN
1179,0,0,NaN,NaN,NaN,NaN,NaN
1218,0,0,NaN,NaN,NaN,NaN,NaN
1219,0,0,NaN,NaN,NaN,NaN,NaN
1234,0,0,NaN,NaN,NaN,NaN,NaN
1257,0,0,NaN,NaN,NaN,NaN,NaN
1283,0,0,NaN,NaN,NaN,NaN,NaN
1323,0,0,NaN,NaN,NaN,NaN,NaN
1325,0,0,NaN,NaN,NaN,NaN,NaN
1326,0,0,NaN,NaN,NaN,NaN,NaN
1337,0,0,NaN,NaN,NaN,NaN,NaN
1349,0,0,NaN,NaN,NaN,NaN,NaN
1407,0,0,NaN,NaN,NaN,NaN,NaN
1449,0,0,NaN,NaN,NaN,NaN,NaN
1450,0,0,NaN,NaN,NaN,NaN,NaN
1453,0,0,NaN,NaN,NaN,NaN,NaN

In [205]:
# Inspecting basement without values
dataset[dataset['BsmtQual'].isnull()][['TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtQual', 'BsmtExposure', 'BsmtFinType2', 'BsmtCond', 'BsmtFinType1']]

,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,BsmtQual,BsmtExposure,BsmtFinType2,BsmtCond,BsmtFinType1
17,0,0,0,NaN,NaN,NaN,NaN,NaN
39,0,0,0,NaN,NaN,NaN,NaN,NaN
90,0,0,0,NaN,NaN,NaN,NaN,NaN
102,0,0,0,NaN,NaN,NaN,NaN,NaN
156,0,0,0,NaN,NaN,NaN,NaN,NaN
182,0,0,0,NaN,NaN,NaN,NaN,NaN
259,0,0,0,NaN,NaN,NaN,NaN,NaN
342,0,0,0,NaN,NaN,NaN,NaN,NaN
362,0,0,0,NaN,NaN,NaN,NaN,NaN
371,0,0,0,NaN,NaN,NaN,NaN,NaN
392,0,0,0,NaN,NaN,NaN,NaN,NaN
520,0,0,0,NaN,NaN,NaN,NaN,NaN
532,0,0,0,NaN,NaN,NaN,NaN,NaN
533,0,0,0,NaN,NaN,NaN,NaN,NaN
553,0,0,0,NaN,NaN,NaN,NaN,NaN
646,0,0,0,NaN,NaN,NaN,NaN,NaN
705,0,0,0,NaN,NaN,NaN,NaN,NaN
736,0,0,0,NaN,NaN,NaN,NaN,NaN
749,0,0,0,NaN,NaN,NaN,NaN,NaN
778,0,0,0,NaN,NaN,NaN,NaN,NaN
868,0,0,0,NaN,NaN,NaN,NaN,NaN
894,0,0,0,NaN,NaN,NaN,NaN,NaN
897,0,0,0,NaN,NaN,NaN,NaN,NaN
984,0,0,0,NaN,NaN,NaN,NaN,NaN
1000,0,0,0,NaN,NaN,NaN,NaN,NaN
1011,0,0,0,NaN,NaN,NaN,NaN,NaN
1035,0,0,0,NaN,NaN,NaN,NaN,NaN
1045,0,0,0,NaN,NaN,NaN,NaN,NaN
1048,0,0,0,NaN,NaN,NaN,NaN,NaN
1049,0,0,0,NaN,NaN,NaN,NaN,NaN
1090,0,0,0,NaN,NaN,NaN,NaN,NaN
1179,0,0,0,NaN,NaN,NaN,NaN,NaN
1216,0,0,0,NaN,NaN,NaN,NaN,NaN
1218,0,0,0,NaN,NaN,NaN,NaN,NaN
1232,0,0,0,NaN,NaN,NaN,NaN,NaN
1321,0,0,0,NaN,NaN,NaN,NaN,NaN
1412,0,0,0,NaN,NaN,NaN,NaN,NaN

In [206]:
# Inspecting fireplace without values
dataset[dataset['FireplaceQu'].isnull()][['FireplaceQu', 'Fireplaces']]

     FireplaceQu  Fireplaces
0            NaN           0
5            NaN           0
10           NaN           0
12           NaN           0
15           NaN           0
17           NaN           0
18           NaN           0
19           NaN           0
26           NaN           0
29           NaN           0
30           NaN           0
31           NaN           0
32           NaN           0
36           NaN           0
38           NaN           0
39           NaN           0
42           NaN           0
43           NaN           0
44           NaN           0
47           NaN           0
48           NaN           0
49           NaN           0
50           NaN           0
52           NaN           0
56           NaN           0
57           NaN           0
59           NaN           0
60           NaN           0
61           NaN           0
63           NaN           0
64           NaN           0
67           NaN           0
68           NaN           0
71           NaN           0
73           NaN           0
74           NaN           0
75           NaN           0
76           NaN           0
77           NaN           0
78           NaN           0
79           NaN           0
81           NaN           0
83           NaN           0
87           NaN           0
88           NaN           0
89           NaN           0
90           NaN           0
91           NaN           0
92           NaN           0
94           NaN           0
96           NaN           0
97           NaN           0
98           NaN           0
99           NaN           0
102          NaN           0
103          NaN           0
106          NaN           0
107          NaN           0
108          NaN           0
110          NaN           0
117          NaN           0
121          NaN           0
122          NaN           0
123          NaN           0
125          NaN           0
129          NaN           0
132          NaN           0
133          NaN           0
137          NaN           0
139          NaN           0
141          NaN           0
142          NaN           0
143          NaN           0
144          NaN           0
145          NaN           0
146          NaN           0
148          NaN           0
149          NaN           0
150          NaN           0
154          NaN           0
155          NaN           0
156          NaN           0
160          NaN           0
163          NaN           0
164          NaN           0
165          NaN           0
170          NaN           0
179          NaN           0
183          NaN           0
184          NaN           0
186          NaN           0
187          NaN           0
191          NaN           0
192          NaN           0
193          NaN           0
194          NaN           0
198          NaN           0
200          NaN           0
202          NaN           0
204          NaN           0
205          NaN           0
209          NaN           0
210          NaN           0
211          NaN           0
213          NaN           0
214          NaN           0
216          NaN           0
217          NaN           0
219          NaN           0
220          NaN           0
223          NaN           0
225          NaN           0
227          NaN           0
230          NaN           0
233          NaN           0
235          NaN           0
236          NaN           0
237          NaN           0
238          NaN           0
240          NaN           0
241          NaN           0
242          NaN           0
246          NaN           0
248          NaN           0
250          NaN           0
252          NaN           0
253          NaN           0
254          NaN           0
256          NaN           0
259          NaN           0
263          NaN           0
264          NaN           0
274          NaN           0
275          NaN           0
276          NaN           0
277          NaN           0
281          NaN           0
284          NaN           0
285          NaN           0
287          NaN           0
288          NaN           0
289          NaN           0
291          NaN           0
295          NaN           0
296          NaN           0
303          NaN           0
305          NaN           0
307          NaN           0
308          NaN           0
320          NaN           0
323          NaN           0
325          NaN           0
327          NaN           0
328          NaN           0
329          NaN           0
330          NaN           0
331          NaN           0
337          NaN           0
338          NaN           0
339          NaN           0
340          NaN           0
341          NaN           0
342          NaN           0
344          NaN           0
346          NaN           0
348          NaN           0
352          NaN           0
353          NaN           0
355          NaN           0
356          NaN           0
358          NaN           0
361          NaN           0
363          NaN           0
365          NaN           0
372          NaN           0
373          NaN           0
375          NaN           0
376          NaN           0
382          NaN           0
383          NaN           0
386          NaN           0
388          NaN           0
390          NaN           0
392          NaN           0
394          NaN           0
395          NaN           0
396          NaN           0
398          NaN           0
399          NaN           0
402          NaN           0
406          NaN           0
407          NaN           0
410          NaN           0
411          NaN           0
415          NaN           0
418          NaN           0
420          NaN           0
422          NaN           0
427          NaN           0
428          NaN           0
430          NaN           0
431          NaN           0
432          NaN           0
434          NaN           0
436          NaN           0
437          NaN           0
439          NaN           0
441          NaN           0
449          NaN           0
450          NaN           0
452          NaN           0
453          NaN           0
454          NaN           0
456          NaN           0
460          NaN           0
461          NaN           0
464          NaN           0
469          NaN           0
470          NaN           0
472          NaN           0
474          NaN           0
475          NaN           0
479          NaN           0
483          NaN           0
484          NaN           0
486          NaN           0
489          NaN           0
492          NaN           0
494          NaN           0
495          NaN           0
497          NaN           0
498          NaN           0
499          NaN           0
500          NaN           0
501          NaN           0
502          NaN           0
505          NaN           0
507          NaN           0
509          NaN           0
512          NaN           0
513          NaN           0
514          NaN           0
518          NaN           0
520          NaN           0
526          NaN           0
528          NaN           0
531          NaN           0
533          NaN           0
535          NaN           0
536          NaN           0
537          NaN           0
543          NaN           0
545          NaN           0
547          NaN           0
548          NaN           0
550          NaN           0
551          NaN           0
553          NaN           0
557          NaN           0
565          NaN           0
567          NaN           0
570          NaN           0
571          NaN           0
572          NaN           0
574          NaN           0
575          NaN           0
578          NaN           0
579          NaN           0
582          NaN           0
584          NaN           0
586          NaN           0
587          NaN           0
589          NaN           0
590          NaN           0
592          NaN           0
593          NaN           0
594          NaN           0
596          NaN           0
603          NaN           0
606          NaN           0
607          NaN           0
609          NaN           0
613          NaN           0
614          NaN           0
615          NaN           0
617          NaN           0
620          NaN           0
622          NaN           0
625          NaN           0
629          NaN           0
630          NaN           0
633          NaN           0
634          NaN           0
635          NaN           0
637          NaN           0
638          NaN           0
643          NaN           0
645          NaN           0
646          NaN           0
649          NaN           0
650          NaN           0
653          NaN           0
655          NaN           0
656          NaN           0
659          NaN           0
663          NaN           0
670          NaN           0
671          NaN           0
676          NaN           0
677          NaN           0
679          NaN           0
681          NaN           0
684          NaN           0
686          NaN           0
687          NaN           0
693          NaN           0
694          NaN           0
696          NaN           0
697          NaN           0
699          NaN           0
701          NaN           0
704          NaN           0
705          NaN           0
709          NaN           0
710          NaN           0
711          NaN           0
713          NaN           0
714          NaN           0
716          NaN           0
721          NaN           0
722          NaN           0
723          NaN           0
725          NaN           0
727          NaN           0
728          NaN           0
729          NaN           0
734          NaN           0
736          NaN           0
738          NaN           0
739          NaN           0
740          NaN           0
741          NaN           0
742          NaN           0
749          NaN           0
750          NaN           0
751          NaN           0
752          NaN           0
754          NaN           0
755          NaN           0
756          NaN           0
758          NaN           0
760          NaN           0
761          NaN           0
762          NaN           0
767          NaN           0
770          NaN           0
771          NaN           0
773          NaN           0
775          NaN           0
776          NaN           0
779          NaN           0
781          NaN           0
782          NaN           0
786          NaN           0
787          NaN           0
788          NaN           0
789          NaN           0
793          NaN           0
797          NaN           0
800          NaN           0
801          NaN           0
804          NaN           0
805          NaN           0
806          NaN           0
809          NaN           0
812          NaN           0
813          NaN           0
814          NaN           0
815          NaN           0
818          NaN           0
820          NaN           0
821          NaN           0
826          NaN           0
828          NaN           0
829          NaN           0
831          NaN           0
833          NaN           0
834          NaN           0
835          NaN           0
836          NaN           0
837          NaN           0
838          NaN           0
839          NaN           0
840          NaN           0
842          NaN           0
843          NaN           0
850          NaN           0
855          NaN           0
856          NaN           0
861          NaN           0
862          NaN           0
863          NaN           0
864          NaN           0
865          NaN           0
867          NaN           0
870          NaN           0
871          NaN           0
872          NaN           0
874          NaN           0
876          NaN           0
878          NaN           0
879          NaN           0
880          NaN           0
883          NaN           0
884          NaN           0
886          NaN           0
887          NaN           0
892          NaN           0
894          NaN           0
896          NaN           0
897          NaN           0
900          NaN           0
901          NaN           0
904          NaN           0
905          NaN           0
908          NaN           0
910          NaN           0
911          NaN           0
912          NaN           0
913          NaN           0
914          NaN           0
915          NaN           0
916          NaN           0
917          NaN           0
920          NaN           0
921          NaN           0
925          NaN           0
930          NaN           0
931          NaN           0
933          NaN           0
935          NaN           0
936          NaN           0
938          NaN           0
940          NaN           0
942          NaN           0
943          NaN           0
945          NaN           0
950          NaN           0
951          NaN           0
952          NaN           0
954          NaN           0
955          NaN           0
957          NaN           0
958          NaN           0
959          NaN           0
960          NaN           0
963          NaN           0
967          NaN           0
968          NaN           0
969          NaN           0
970          NaN           0
971          NaN           0
973          NaN           0
974          NaN           0
975          NaN           0
976          NaN           0
977          NaN           0
978          NaN           0
979          NaN           0
980          NaN           0
984          NaN           0
985          NaN           0
986          NaN           0
989          NaN           0
993          NaN           0
995          NaN           0
996          NaN           0
999          NaN           0
1000         NaN           0
1001         NaN           0
1003         NaN           0
1005         NaN           0
1007         NaN           0
1009         NaN           0
1011         NaN           0
1013         NaN           0
1015         NaN           0
1020         NaN           0
1021         NaN           0
1022         NaN           0
1025         NaN           0
1029         NaN           0
1030         NaN           0
1033         NaN           0
1035         NaN           0
1039         NaN           0
1041         NaN           0
1047         NaN           0
1049         NaN           0
1050         NaN           0
1060         NaN           0
1061         NaN           0
1062         NaN           0
1065         NaN           0
1067         NaN           0
1069         NaN           0
1070         NaN           0
1071         NaN           0
1073         NaN           0
1074         NaN           0
1077         NaN           0
1079         NaN           0
1080         NaN           0
1081         NaN           0
1085         NaN           0
1086         NaN           0
1088         NaN           0
1090         NaN           0
1091         NaN           0
1093         NaN           0
1094         NaN           0
1096         NaN           0
1097         NaN           0
1098         NaN           0
1100         NaN           0
1101         NaN           0
1102         NaN           0
1104         NaN           0
1112         NaN           0
1113         NaN           0
1114         NaN           0
1117         NaN           0
1118         NaN           0
1119         NaN           0
1121         NaN           0
1122         NaN           0
1123         NaN           0
1129         NaN           0
1131         NaN           0
1132         NaN           0
1136         NaN           0
1137         NaN           0
1140         NaN           0
1143         NaN           0
1144         NaN           0
1149         NaN           0
1153         NaN           0
1158         NaN           0
1163         NaN           0
1165         NaN           0
1166         NaN           0
1172         NaN           0
1176         NaN           0
1177         NaN           0
1180         NaN           0
1185         NaN           0
1186         NaN           0
1188         NaN           0
1191         NaN           0
1192         NaN           0
1193         NaN           0
1194         NaN           0
1195         NaN           0
1198         NaN           0
1200         NaN           0
1201         NaN           0
1204         NaN           0
1206         NaN           0
1207         NaN           0
1208         NaN           0
1211         NaN           0
1212         NaN           0
1213         NaN           0
1214         NaN           0
1215         NaN           0
1216         NaN           0
1217         NaN           0
1218         NaN           0
1219         NaN           0
1220         NaN           0
1223         NaN           0
1225         NaN           0
1227         NaN           0
1229         NaN           0
1231         NaN           0
1232         NaN           0
1233         NaN           0
1234         NaN           0
1235         NaN           0
1236         NaN           0
1238         NaN           0
1240         NaN           0
1241         NaN           0
1246         NaN           0
1247         NaN           0
1249         NaN           0
1252         NaN           0
1257         NaN           0
1258         NaN           0
1259         NaN           0
1261         NaN           0
1264         NaN           0
1265         NaN           0
1269         NaN           0
1272         NaN           0
1275         NaN           0
1279         NaN           0
1280         NaN           0
1282         NaN           0
1283         NaN           0
1287         NaN           0
1291         NaN           0
1292         NaN           0
1294         NaN           0
1295         NaN           0
1296         NaN           0
1297         NaN           0
1299         NaN           0
1303         NaN           0
1304         NaN           0
1307         NaN           0
1308         NaN           0
1309         NaN           0
1311         NaN           0
1319         NaN           0
1321         NaN           0
1323         NaN           0
1325         NaN           0
1326         NaN           0
1331         NaN           0
1333         NaN           0
1334         NaN           0
1336         NaN           0
1337         NaN           0
1338         NaN           0
1339         NaN           0
1340         NaN           0
1341         NaN           0
1345         NaN           0
1349         NaN           0
1350         NaN           0
1352         NaN           0
1356         NaN           0
1358         NaN           0
1360         NaN           0
1364         NaN           0
1365         NaN           0
1366         NaN           0
1368         NaN           0
1370         NaN           0
1376         NaN           0
1377         NaN           0
1378         NaN           0
1379         NaN           0
1380         NaN           0
1382         NaN           0
1383         NaN           0
1384         NaN           0
1385         NaN           0
1390         NaN           0
1391         NaN           0
1397         NaN           0
1398         NaN           0
1403         NaN           0
1404         NaN           0
1406         NaN           0
1407         NaN           0
1408         NaN           0
1410         NaN           0
1411         NaN           0
1412         NaN           0
1416         NaN           0
1418         NaN           0
1422         NaN           0
1425         NaN           0
1431         NaN           0
1432         NaN           0
1436         NaN           0
1438         NaN           0
1444         NaN           0
1445         NaN           0
1446         NaN           0
1448         NaN           0
1449         NaN           0
1450         NaN           0
1452         NaN           0
1453         NaN           0
1454         NaN           0

In [207]:
# Inspecting pool without values
dataset[dataset['PoolQC'].isnull()][['PoolQC', 'PoolArea']]

     PoolQC  PoolArea
0       NaN         0
1       NaN         0
2       NaN         0
3       NaN         0
4       NaN         0
5       NaN         0
6       NaN         0
7       NaN         0
8       NaN         0
9       NaN         0
10      NaN         0
11      NaN         0
12      NaN         0
13      NaN         0
14      NaN         0
15      NaN         0
16      NaN         0
17      NaN         0
18      NaN         0
19      NaN         0
20      NaN         0
21      NaN         0
22      NaN         0
23      NaN         0
24      NaN         0
25      NaN         0
26      NaN         0
27      NaN         0
28      NaN         0
29      NaN         0
30      NaN         0
31      NaN         0
32      NaN         0
33      NaN         0
34      NaN         0
35      NaN         0
36      NaN         0
37      NaN         0
38      NaN         0
39      NaN         0
40      NaN         0
41      NaN         0
42      NaN         0
43      NaN         0
44      NaN         0
45      NaN         0
46      NaN         0
47      NaN         0
48      NaN         0
49      NaN         0
50      NaN         0
51      NaN         0
52      NaN         0
53      NaN         0
54      NaN         0
55      NaN         0
56      NaN         0
57      NaN         0
58      NaN         0
59      NaN         0
60      NaN         0
61      NaN         0
62      NaN         0
63      NaN         0
64      NaN         0
65      NaN         0
66      NaN         0
67      NaN         0
68      NaN         0
69      NaN         0
70      NaN         0
71      NaN         0
72      NaN         0
73      NaN         0
74      NaN         0
75      NaN         0
76      NaN         0
77      NaN         0
78      NaN         0
79      NaN         0
80      NaN         0
81      NaN         0
82      NaN         0
83      NaN         0
84      NaN         0
85      NaN         0
86      NaN         0
87      NaN         0
88      NaN         0
89      NaN         0
90      NaN         0
91      NaN         0
92      NaN         0
93      NaN         0
94      NaN         0
95      NaN         0
96      NaN         0
97      NaN         0
98      NaN         0
99      NaN         0
100     NaN         0
101     NaN         0
102     NaN         0
103     NaN         0
104     NaN         0
105     NaN         0
106     NaN         0
107     NaN         0
108     NaN         0
109     NaN         0
110     NaN         0
111     NaN         0
112     NaN         0
113     NaN         0
114     NaN         0
115     NaN         0
116     NaN         0
117     NaN         0
118     NaN         0
119     NaN         0
120     NaN         0
121     NaN         0
122     NaN         0
123     NaN         0
124     NaN         0
125     NaN         0
126     NaN         0
127     NaN         0
128     NaN         0
129     NaN         0
130     NaN         0
131     NaN         0
132     NaN         0
133     NaN         0
134     NaN         0
135     NaN         0
136     NaN         0
137     NaN         0
138     NaN         0
139     NaN         0
140     NaN         0
141     NaN         0
142     NaN         0
143     NaN         0
144     NaN         0
145     NaN         0
146     NaN         0
147     NaN         0
148     NaN         0
149     NaN         0
150     NaN         0
151     NaN         0
152     NaN         0
153     NaN         0
154     NaN         0
155     NaN         0
156     NaN         0
157     NaN         0
158     NaN         0
159     NaN         0
160     NaN         0
161     NaN         0
162     NaN         0
163     NaN         0
164     NaN         0
165     NaN         0
166     NaN         0
167     NaN         0
168     NaN         0
169     NaN         0
170     NaN         0
171     NaN         0
172     NaN         0
173     NaN         0
174     NaN         0
175     NaN         0
176     NaN         0
177     NaN         0
178     NaN         0
179     NaN         0
180     NaN         0
181     NaN         0
182     NaN         0
183     NaN         0
184     NaN         0
185     NaN         0
186     NaN         0
187     NaN         0
188     NaN         0
189     NaN         0
190     NaN         0
191     NaN         0
192     NaN         0
193     NaN         0
194     NaN         0
195     NaN         0
196     NaN         0
198     NaN         0
199     NaN         0
200     NaN         0
201     NaN         0
202     NaN         0
203     NaN         0
204     NaN         0
205     NaN         0
206     NaN         0
207     NaN         0
208     NaN         0
209     NaN         0
210     NaN         0
211     NaN         0
212     NaN         0
213     NaN         0
214     NaN         0
215     NaN         0
216     NaN         0
217     NaN         0
218     NaN         0
219     NaN         0
220     NaN         0
221     NaN         0
222     NaN         0
223     NaN         0
224     NaN         0
225     NaN         0
226     NaN         0
227     NaN         0
228     NaN         0
229     NaN         0
230     NaN         0
231     NaN         0
232     NaN         0
233     NaN         0
234     NaN         0
235     NaN         0
236     NaN         0
237     NaN         0
238     NaN         0
239     NaN         0
240     NaN         0
241     NaN         0
242     NaN         0
243     NaN         0
244     NaN         0
245     NaN         0
246     NaN         0
247     NaN         0
248     NaN         0
249     NaN         0
250     NaN         0
251     NaN         0
252     NaN         0
253     NaN         0
254     NaN         0
255     NaN         0
256     NaN         0
257     NaN         0
258     NaN         0
259     NaN         0
260     NaN         0
261     NaN         0
262     NaN         0
263     NaN         0
264     NaN         0
265     NaN         0
266     NaN         0
267     NaN         0
268     NaN         0
269     NaN         0
270     NaN         0
271     NaN         0
272     NaN         0
273     NaN         0
274     NaN         0
275     NaN         0
276     NaN         0
277     NaN         0
278     NaN         0
279     NaN         0
280     NaN         0
281     NaN         0
282     NaN         0
283     NaN         0
284     NaN         0
285     NaN         0
286     NaN         0
287     NaN         0
288     NaN         0
289     NaN         0
290     NaN         0
291     NaN         0
292     NaN         0
293     NaN         0
294     NaN         0
295     NaN         0
296     NaN         0
297     NaN         0
298     NaN         0
299     NaN         0
300     NaN         0
301     NaN         0
302     NaN         0
303     NaN         0
304     NaN         0
305     NaN         0
306     NaN         0
307     NaN         0
308     NaN         0
309     NaN         0
310     NaN         0
311     NaN         0
312     NaN         0
313     NaN         0
314     NaN         0
315     NaN         0
316     NaN         0
317     NaN         0
318     NaN         0
319     NaN         0
320     NaN         0
321     NaN         0
322     NaN         0
323     NaN         0
324     NaN         0
325     NaN         0
326     NaN         0
327     NaN         0
328     NaN         0
329     NaN         0
330     NaN         0
331     NaN         0
332     NaN         0
333     NaN         0
334     NaN         0
335     NaN         0
336     NaN         0
337     NaN         0
338     NaN         0
339     NaN         0
340     NaN         0
341     NaN         0
342     NaN         0
343     NaN         0
344     NaN         0
345     NaN         0
346     NaN         0
347     NaN         0
348     NaN         0
349     NaN         0
350     NaN         0
351     NaN         0
352     NaN         0
353     NaN         0
354     NaN         0
355     NaN         0
356     NaN         0
357     NaN         0
358     NaN         0
359     NaN         0
360     NaN         0
361     NaN         0
362     NaN         0
363     NaN         0
364     NaN         0
365     NaN         0
366     NaN         0
367     NaN         0
368     NaN         0
369     NaN         0
370     NaN         0
371     NaN         0
372     NaN         0
373     NaN         0
374     NaN         0
375     NaN         0
376     NaN         0
377     NaN         0
378     NaN         0
379     NaN         0
380     NaN         0
381     NaN         0
382     NaN         0
383     NaN         0
384     NaN         0
385     NaN         0
386     NaN         0
387     NaN         0
388     NaN         0
389     NaN         0
390     NaN         0
391     NaN         0
392     NaN         0
393     NaN         0
394     NaN         0
395     NaN         0
396     NaN         0
397     NaN         0
398     NaN         0
399     NaN         0
400     NaN         0
401     NaN         0
402     NaN         0
403     NaN         0
404     NaN         0
405     NaN         0
406     NaN         0
407     NaN         0
408     NaN         0
409     NaN         0
410     NaN         0
411     NaN         0
412     NaN         0
413     NaN         0
414     NaN         0
415     NaN         0
416     NaN         0
417     NaN         0
418     NaN         0
419     NaN         0
420     NaN         0
421     NaN         0
422     NaN         0
423     NaN         0
424     NaN         0
425     NaN         0
426     NaN         0
427     NaN         0
428     NaN         0
429     NaN         0
430     NaN         0
431     NaN         0
432     NaN         0
433     NaN         0
434     NaN         0
435     NaN         0
436     NaN         0
437     NaN         0
438     NaN         0
439     NaN         0
440     NaN         0
441     NaN         0
442     NaN         0
443     NaN         0
444     NaN         0
445     NaN         0
446     NaN         0
447     NaN         0
448     NaN         0
449     NaN         0
450     NaN         0
451     NaN         0
452     NaN         0
453     NaN         0
454     NaN         0
455     NaN         0
456     NaN         0
457     NaN         0
458     NaN         0
459     NaN         0
460     NaN         0
461     NaN         0
462     NaN         0
463     NaN         0
464     NaN         0
465     NaN         0
466     NaN         0
467     NaN         0
468     NaN         0
469     NaN         0
470     NaN         0
471     NaN         0
472     NaN         0
473     NaN         0
474     NaN         0
475     NaN         0
476     NaN         0
477     NaN         0
478     NaN         0
479     NaN         0
480     NaN         0
481     NaN         0
482     NaN         0
483     NaN         0
484     NaN         0
485     NaN         0
486     NaN         0
487     NaN         0
488     NaN         0
489     NaN         0
490     NaN         0
491     NaN         0
492     NaN         0
493     NaN         0
494     NaN         0
495     NaN         0
496     NaN         0
497     NaN         0
498     NaN         0
499     NaN         0
500     NaN         0
501     NaN         0
502     NaN         0
503     NaN         0
504     NaN         0
505     NaN         0
506     NaN         0
507     NaN         0
508     NaN         0
509     NaN         0
510     NaN         0
511     NaN         0
512     NaN         0
513     NaN         0
514     NaN         0
515     NaN         0
516     NaN         0
517     NaN         0
518     NaN         0
519     NaN         0
520     NaN         0
521     NaN         0
522     NaN         0
523     NaN         0
524     NaN         0
525     NaN         0
526     NaN         0
527     NaN         0
528     NaN         0
529     NaN         0
530     NaN         0
531     NaN         0
532     NaN         0
533     NaN         0
534     NaN         0
535     NaN         0
536     NaN         0
537     NaN         0
538     NaN         0
539     NaN         0
540     NaN         0
541     NaN         0
542     NaN         0
543     NaN         0
544     NaN         0
545     NaN         0
546     NaN         0
547     NaN         0
548     NaN         0
549     NaN         0
550     NaN         0
551     NaN         0
552     NaN         0
553     NaN         0
554     NaN         0
555     NaN         0
556     NaN         0
557     NaN         0
558     NaN         0
559     NaN         0
560     NaN         0
561     NaN         0
562     NaN         0
563     NaN         0
564     NaN         0
565     NaN         0
566     NaN         0
567     NaN         0
568     NaN         0
569     NaN         0
570     NaN         0
571     NaN         0
572     NaN         0
573     NaN         0
574     NaN         0
575     NaN         0
576     NaN         0
577     NaN         0
578     NaN         0
579     NaN         0
580     NaN         0
581     NaN         0
582     NaN         0
583     NaN         0
584     NaN         0
585     NaN         0
586     NaN         0
587     NaN         0
588     NaN         0
589     NaN         0
590     NaN         0
591     NaN         0
592     NaN         0
593     NaN         0
594     NaN         0
595     NaN         0
596     NaN         0
597     NaN         0
598     NaN         0
599     NaN         0
600     NaN         0
601     NaN         0
602     NaN         0
603     NaN         0
604     NaN         0
605     NaN         0
606     NaN         0
607     NaN         0
608     NaN         0
609     NaN         0
610     NaN         0
611     NaN         0
612     NaN         0
613     NaN         0
614     NaN         0
615     NaN         0
616     NaN         0
617     NaN         0
618     NaN         0
619     NaN         0
620     NaN         0
621     NaN         0
622     NaN         0
623     NaN         0
624     NaN         0
625     NaN         0
626     NaN         0
627     NaN         0
628     NaN         0
629     NaN         0
630     NaN         0
631     NaN         0
632     NaN         0
633     NaN         0
634     NaN         0
635     NaN         0
636     NaN         0
637     NaN         0
638     NaN         0
639     NaN         0
640     NaN         0
641     NaN         0
642     NaN         0
643     NaN         0
644     NaN         0
645     NaN         0
646     NaN         0
647     NaN         0
648     NaN         0
649     NaN         0
650     NaN         0
651     NaN         0
652     NaN         0
653     NaN         0
654     NaN         0
655     NaN         0
656     NaN         0
657     NaN         0
658     NaN         0
659     NaN         0
660     NaN         0
661     NaN         0
662     NaN         0
663     NaN         0
664     NaN         0
665     NaN         0
666     NaN         0
667     NaN         0
668     NaN         0
669     NaN         0
670     NaN         0
671     NaN         0
672     NaN         0
673     NaN         0
674     NaN         0
675     NaN         0
676     NaN         0
677     NaN         0
678     NaN         0
679     NaN         0
680     NaN         0
681     NaN         0
682     NaN         0
683     NaN         0
684     NaN         0
685     NaN         0
686     NaN         0
687     NaN         0
688     NaN         0
689     NaN         0
690     NaN         0
691     NaN         0
692     NaN         0
693     NaN         0
694     NaN         0
695     NaN         0
696     NaN         0
697     NaN         0
698     NaN         0
699     NaN         0
700     NaN         0
701     NaN         0
702     NaN         0
703     NaN         0
704     NaN         0
705     NaN         0
706     NaN         0
707     NaN         0
708     NaN         0
709     NaN         0
710     NaN         0
711     NaN         0
712     NaN         0
713     NaN         0
714     NaN         0
715     NaN         0
716     NaN         0
717     NaN         0
718     NaN         0
719     NaN         0
720     NaN         0
721     NaN         0
722     NaN         0
723     NaN         0
724     NaN         0
725     NaN         0
726     NaN         0
727     NaN         0
728     NaN         0
729     NaN         0
730     NaN         0
731     NaN         0
732     NaN         0
733     NaN         0
734     NaN         0
735     NaN         0
736     NaN         0
737     NaN         0
738     NaN         0
739     NaN         0
740     NaN         0
741     NaN         0
742     NaN         0
743     NaN         0
744     NaN         0
745     NaN         0
746     NaN         0
747     NaN         0
748     NaN         0
749     NaN         0
750     NaN         0
751     NaN         0
752     NaN         0
753     NaN         0
754     NaN         0
755     NaN         0
756     NaN         0
757     NaN         0
758     NaN         0
759     NaN         0
760     NaN         0
761     NaN         0
762     NaN         0
763     NaN         0
764     NaN         0
765     NaN         0
766     NaN         0
767     NaN         0
768     NaN         0
769     NaN         0
770     NaN         0
771     NaN         0
772     NaN         0
773     NaN         0
774     NaN         0
775     NaN         0
776     NaN         0
777     NaN         0
778     NaN         0
779     NaN         0
780     NaN         0
781     NaN         0
782     NaN         0
783     NaN         0
784     NaN         0
785     NaN         0
786     NaN         0
787     NaN         0
788     NaN         0
789     NaN         0
790     NaN         0
791     NaN         0
792     NaN         0
793     NaN         0
794     NaN         0
795     NaN         0
796     NaN         0
797     NaN         0
798     NaN         0
799     NaN         0
800     NaN         0
801     NaN         0
802     NaN         0
803     NaN         0
804     NaN         0
805     NaN         0
806     NaN         0
807     NaN         0
808     NaN         0
809     NaN         0
811     NaN         0
812     NaN         0
813     NaN         0
814     NaN         0
815     NaN         0
816     NaN         0
817     NaN         0
818     NaN         0
819     NaN         0
820     NaN         0
821     NaN         0
822     NaN         0
823     NaN         0
824     NaN         0
825     NaN         0
826     NaN         0
827     NaN         0
828     NaN         0
829     NaN         0
830     NaN         0
831     NaN         0
832     NaN         0
833     NaN         0
834     NaN         0
835     NaN         0
836     NaN         0
837     NaN         0
838     NaN         0
839     NaN         0
840     NaN         0
841     NaN         0
842     NaN         0
843     NaN         0
844     NaN         0
845     NaN         0
846     NaN         0
847     NaN         0
848     NaN         0
849     NaN         0
850     NaN         0
851     NaN         0
852     NaN         0
853     NaN         0
854     NaN         0
855     NaN         0
856     NaN         0
857     NaN         0
858     NaN         0
859     NaN         0
860     NaN         0
861     NaN         0
862     NaN         0
863     NaN         0
864     NaN         0
865     NaN         0
866     NaN         0
867     NaN         0
868     NaN         0
869     NaN         0
870     NaN         0
871     NaN         0
872     NaN         0
873     NaN         0
874     NaN         0
875     NaN         0
876     NaN         0
877     NaN         0
878     NaN         0
879     NaN         0
880     NaN         0
881     NaN         0
882     NaN         0
883     NaN         0
884     NaN         0
885     NaN         0
886     NaN         0
887     NaN         0
888     NaN         0
889     NaN         0
890     NaN         0
891     NaN         0
892     NaN         0
893     NaN         0
894     NaN         0
895     NaN         0
896     NaN         0
897     NaN         0
898     NaN         0
899     NaN         0
900     NaN         0
901     NaN         0
902     NaN         0
903     NaN         0
904     NaN         0
905     NaN         0
906     NaN         0
907     NaN         0
908     NaN         0
909     NaN         0

In [208]:
# Inspecting misc without values
dataset[dataset['MiscFeature'].isnull()][['MiscFeature', 'MiscVal']]

     MiscFeature  MiscVal
0            NaN        0
1            NaN        0
2            NaN        0
3            NaN        0
4            NaN        0
6            NaN        0
8            NaN        0
9            NaN        0
10           NaN        0
11           NaN        0
12           NaN        0
13           NaN        0
14           NaN        0
15           NaN        0
18           NaN        0
19           NaN        0
20           NaN        0
21           NaN        0
22           NaN        0
23           NaN        0
24           NaN        0
25           NaN        0
26           NaN        0
27           NaN        0
28           NaN        0
29           NaN        0
30           NaN        0
31           NaN        0
32           NaN        0
33           NaN        0
34           NaN        0
35           NaN        0
36           NaN        0
37           NaN        0
38           NaN        0
39           NaN        0
40           NaN        0
41           NaN        0
42           NaN        0
43           NaN        0
44           NaN        0
45           NaN        0
46           NaN        0
47           NaN        0
48           NaN        0
49           NaN        0
50           NaN        0
52           NaN        0
53           NaN        0
54           NaN        0
55           NaN        0
56           NaN        0
57           NaN        0
58           NaN        0
59           NaN        0
60           NaN        0
61           NaN        0
62           NaN        0
63           NaN        0
64           NaN        0
65           NaN        0
66           NaN        0
67           NaN        0
68           NaN        0
69           NaN        0
70           NaN        0
71           NaN        0
72           NaN        0
73           NaN        0
74           NaN        0
75           NaN        0
76           NaN        0
77           NaN        0
78           NaN        0
79           NaN        0
80           NaN        0
81           NaN        0
82           NaN        0
83           NaN        0
85           NaN        0
86           NaN        0
87           NaN        0
88           NaN        0
89           NaN        0
90           NaN        0
91           NaN        0
92           NaN        0
93           NaN        0
94           NaN        0
96           NaN        0
97           NaN        0
100          NaN        0
101          NaN        0
102          NaN        0
103          NaN        0
104          NaN        0
105          NaN        0
107          NaN        0
108          NaN        0
109          NaN        0
110          NaN        0
111          NaN        0
112          NaN        0
113          NaN        0
114          NaN        0
115          NaN        0
116          NaN        0
117          NaN        0
118          NaN        0
119          NaN        0
120          NaN        0
121          NaN        0
122          NaN        0
123          NaN        0
124          NaN        0
125          NaN        0
126          NaN        0
127          NaN        0
128          NaN        0
129          NaN        0
130          NaN        0
131          NaN        0
132          NaN        0
133          NaN        0
134          NaN        0
135          NaN        0
136          NaN        0
137          NaN        0
138          NaN        0
139          NaN        0
140          NaN        0
141          NaN        0
142          NaN        0
143          NaN        0
144          NaN        0
145          NaN        0
146          NaN        0
147          NaN        0
148          NaN        0
149          NaN        0
150          NaN        0
151          NaN        0
152          NaN        0
153          NaN        0
154          NaN        0
155          NaN        0
156          NaN        0
157          NaN        0
158          NaN        0
159          NaN        0
160          NaN        0
161          NaN        0
162          NaN        0
163          NaN        0
164          NaN        0
165          NaN        0
166          NaN        0
167          NaN        0
168          NaN        0
169          NaN        0
170          NaN        0
171          NaN        0
172          NaN        0
173          NaN        0
174          NaN        0
175          NaN        0
176          NaN        0
177          NaN        0
178          NaN        0
179          NaN        0
180          NaN        0
181          NaN        0
182          NaN        0
183          NaN        0
184          NaN        0
185          NaN        0
186          NaN        0
187          NaN        0
188          NaN        0
189          NaN        0
190          NaN        0
191          NaN        0
192          NaN        0
193          NaN        0
194          NaN        0
195          NaN        0
196          NaN        0
197          NaN        0
198          NaN        0
199          NaN        0
200          NaN        0
201          NaN        0
202          NaN        0
203          NaN        0
204          NaN        0
205          NaN        0
206          NaN        0
207          NaN        0
208          NaN        0
209          NaN        0
210          NaN        0
211          NaN        0
212          NaN        0
213          NaN        0
215          NaN        0
216          NaN        0
217          NaN        0
218          NaN        0
219          NaN        0
220          NaN        0
221          NaN        0
222          NaN        0
223          NaN        0
224          NaN        0
225          NaN        0
226          NaN        0
227          NaN        0
228          NaN        0
229          NaN        0
230          NaN        0
231          NaN        0
232          NaN        0
233          NaN        0
234          NaN        0
235          NaN        0
236          NaN        0
237          NaN        0
238          NaN        0
239          NaN        0
240          NaN        0
241          NaN        0
242          NaN        0
243          NaN        0
244          NaN        0
245          NaN        0
246          NaN        0
247          NaN        0
248          NaN        0
251          NaN        0
252          NaN        0
253          NaN        0
254          NaN        0
255          NaN        0
256          NaN        0
257          NaN        0
258          NaN        0
259          NaN        0
260          NaN        0
261          NaN        0
262          NaN        0
263          NaN        0
264          NaN        0
265          NaN        0
266          NaN        0
267          NaN        0
268          NaN        0
269          NaN        0
270          NaN        0
271          NaN        0
272          NaN        0
273          NaN        0
274          NaN        0
275          NaN        0
276          NaN        0
277          NaN        0
278          NaN        0
279          NaN        0
280          NaN        0
281          NaN        0
282          NaN        0
283          NaN        0
284          NaN        0
285          NaN        0
286          NaN        0
287          NaN        0
288          NaN        0
289          NaN        0
290          NaN        0
291          NaN        0
292          NaN        0
293          NaN        0
294          NaN        0
295          NaN        0
296          NaN        0
297          NaN        0
298          NaN        0
299          NaN        0
300          NaN        0
301          NaN        0
302          NaN        0
303          NaN        0
304          NaN        0
305          NaN        0
306          NaN        0
307          NaN        0
308          NaN        0
309          NaN        0
310          NaN        0
311          NaN        0
312          NaN        0
313          NaN        0
314          NaN        0
315          NaN        0
316          NaN        0
317          NaN        0
318          NaN        0
319          NaN        0
320          NaN        0
321          NaN        0
322          NaN        0
323          NaN        0
324          NaN        0
325          NaN        0
326          NaN        0
327          NaN        0
328          NaN        0
329          NaN        0
330          NaN        0
331          NaN        0
332          NaN        0
333          NaN        0
334          NaN        0
336          NaN        0
337          NaN        0
339          NaN        0
340          NaN        0
341          NaN        0
342          NaN        0
343          NaN        0
344          NaN        0
345          NaN        0
347          NaN        0
348          NaN        0
349          NaN        0
350          NaN        0
351          NaN        0
352          NaN        0
353          NaN        0
354          NaN        0
355          NaN        0
356          NaN        0
357          NaN        0
358          NaN        0
359          NaN        0
360          NaN        0
361          NaN        0
362          NaN        0
363          NaN        0
364          NaN        0
365          NaN        0
366          NaN        0
367          NaN        0
368          NaN        0
369          NaN        0
370          NaN        0
371          NaN        0
372          NaN        0
373          NaN        0
374          NaN        0
375          NaN        0
376          NaN        0
377          NaN        0
378          NaN        0
379          NaN        0
380          NaN        0
381          NaN        0
382          NaN        0
383          NaN        0
384          NaN        0
385          NaN        0
386          NaN        0
387          NaN        0
388          NaN        0
389          NaN        0
390          NaN        0
391          NaN        0
393          NaN        0
394          NaN        0
395          NaN        0
396          NaN        0
397          NaN        0
398          NaN        0
399          NaN        0
400          NaN        0
401          NaN        0
402          NaN        0
403          NaN        0
404          NaN        0
405          NaN        0
406          NaN        0
407          NaN        0
408          NaN        0
409          NaN        0
410          NaN        0
411          NaN        0
412          NaN        0
413          NaN        0
414          NaN        0
415          NaN        0
416          NaN        0
417          NaN        0
418          NaN        0
419          NaN        0
420          NaN        0
421          NaN        0
422          NaN        0
423          NaN        0
424          NaN        0
425          NaN        0
426          NaN        0
427          NaN        0
428          NaN        0
429          NaN        0
430          NaN        0
431          NaN        0
432          NaN        0
433          NaN        0
434          NaN        0
435          NaN        0
436          NaN        0
437          NaN        0
438          NaN        0
440          NaN        0
441          NaN        0
442          NaN        0
443          NaN        0
444          NaN        0
445          NaN        0
446          NaN        0
447          NaN        0
448          NaN        0
449          NaN        0
450          NaN        0
451          NaN        0
452          NaN        0
453          NaN        0
454          NaN        0
455          NaN        0
456          NaN        0
457          NaN        0
458          NaN        0
459          NaN        0
460          NaN        0
461          NaN        0
462          NaN        0
463          NaN        0
464          NaN        0
465          NaN        0
466          NaN        0
467          NaN        0
468          NaN        0
469          NaN        0
470          NaN        0
471          NaN        0
472          NaN        0
473          NaN        0
474          NaN        0
475          NaN        0
476          NaN        0
477          NaN        0
478          NaN        0
479          NaN        0
480          NaN        0
481          NaN        0
482          NaN        0
483          NaN        0
484          NaN        0
485          NaN        0
486          NaN        0
487          NaN        0
488          NaN        0
489          NaN        0
490          NaN        0
491          NaN        0
492          NaN        0
493          NaN        0
494          NaN        0
495          NaN        0
496          NaN        0
497          NaN        0
498          NaN        0
500          NaN        0
501          NaN        0
503          NaN        0
504          NaN        0
505          NaN        0
506          NaN        0
507          NaN        0
508          NaN        0
509          NaN        0
511          NaN        0
512          NaN        0
513          NaN        0
514          NaN        0
515          NaN        0
516          NaN        0
517          NaN        0
518          NaN        0
519          NaN        0
520          NaN        0
521          NaN        0
522          NaN        0
523          NaN        0
524          NaN        0
525          NaN        0
526          NaN        0
527          NaN        0
528          NaN        0
529          NaN        0
530          NaN        0
531          NaN        0
532          NaN        0
533          NaN        0
534          NaN        0
535          NaN        0
536          NaN        0
537          NaN        0
538          NaN        0
540          NaN        0
541          NaN        0
542          NaN        0
543          NaN        0
544          NaN        0
545          NaN        0
546          NaN        0
547          NaN        0
548          NaN        0
549          NaN        0
550          NaN        0
551          NaN        0
552          NaN        0
553          NaN        0
554          NaN        0
555          NaN        0
556          NaN        0
557          NaN        0
558          NaN        0
559          NaN        0
560          NaN        0
561          NaN        0
562          NaN        0
563          NaN        0
564          NaN        0
565          NaN        0
566          NaN        0
567          NaN        0
568          NaN        0
569          NaN        0
570          NaN        0
571          NaN        0
572          NaN        0
573          NaN        0
574          NaN        0
575          NaN        0
576          NaN        0
577          NaN        0
578          NaN        0
579          NaN        0
580          NaN        0
581          NaN        0
582          NaN        0
583          NaN        0
584          NaN        0
585          NaN        0
586          NaN        0
587          NaN        0
588          NaN        0
590          NaN        0
591          NaN        0
592          NaN        0
593          NaN        0
594          NaN        0
595          NaN        0
596          NaN        0
597          NaN        0
598          NaN        0
599          NaN        0
600          NaN        0
601          NaN        0
602          NaN        0
603          NaN        0
604          NaN        0
605          NaN        0
606          NaN        0
607          NaN        0
608          NaN        0
609          NaN        0
610          NaN        0
612          NaN        0
613          NaN        0
614          NaN        0
615          NaN        0
616          NaN        0
617          NaN        0
618          NaN        0
619          NaN        0
620          NaN        0
621          NaN        0
622          NaN        0
623          NaN        0
624          NaN        0
625          NaN        0
627          NaN        0
628          NaN        0
629          NaN        0
630          NaN        0
631          NaN        0
632          NaN        0
633          NaN        0
635          NaN        0
636          NaN        0
637          NaN        0
638          NaN        0
639          NaN        0
640          NaN        0
641          NaN        0
642          NaN        0
643          NaN        0
644          NaN        0
645          NaN        0
646          NaN        0
647          NaN        0
648          NaN        0
649          NaN        0
650          NaN        0
651          NaN        0
652          NaN        0
653          NaN        0
654          NaN        0
655          NaN        0
656          NaN        0
657          NaN        0
658          NaN        0
659          NaN        0
660          NaN        0
661          NaN        0
662          NaN        0
663          NaN        0
664          NaN        0
665          NaN        0
666          NaN        0
667          NaN        0
668          NaN        0
669          NaN        0
670          NaN        0
671          NaN        0
672          NaN        0
673          NaN        0
674          NaN        0
675          NaN        0
676          NaN        0
677          NaN        0
678          NaN        0
679          NaN        0
680          NaN        0
681          NaN        0
682          NaN        0
683          NaN        0
684          NaN        0
685          NaN        0
686          NaN        0
687          NaN        0
688          NaN        0
689          NaN        0
690          NaN        0
691          NaN        0
692          NaN        0
693          NaN        0
694          NaN        0
695          NaN        0
696          NaN        0
697          NaN        0
698          NaN        0
699          NaN        0
700          NaN        0
701          NaN        0
702          NaN        0
703          NaN        0
704          NaN        0
706          NaN        0
707          NaN        0
708          NaN        0
709          NaN        0
710          NaN        0
711          NaN        0
712          NaN        0
713          NaN        0
714          NaN        0
715          NaN        0
716          NaN        0
717          NaN        0
718          NaN        0
719          NaN        0
720          NaN        0
721          NaN        0
722          NaN        0
723          NaN        0
724          NaN        0
726          NaN        0
727          NaN        0
728          NaN        0
729          NaN        0
730          NaN        0
731          NaN        0
732          NaN        0
734          NaN        0
735          NaN        0
736          NaN        0
737          NaN        0
738          NaN        0
739          NaN        0
740          NaN        0
741          NaN        0
742          NaN        0
743          NaN        0
744          NaN        0
745          NaN        0
746          NaN        0
747          NaN        0
748          NaN        0
749          NaN        0
750          NaN        0
751          NaN        0
752          NaN        0
753          NaN        0
754          NaN        0
755          NaN        0
756          NaN        0
757          NaN        0
758          NaN        0
759          NaN        0
761          NaN        0
762          NaN        0
763          NaN        0
764          NaN        0
765          NaN        0
768          NaN        0
769          NaN        0
770          NaN        0
771          NaN        0
772          NaN        0
773          NaN        0
774          NaN        0
775          NaN        0
776          NaN        0
777          NaN        0
778          NaN        0
779          NaN        0
780          NaN        0
781          NaN        0
782          NaN        0
783          NaN        0
784          NaN        0
785          NaN        0
787          NaN        0
788          NaN        0
789          NaN        0
790          NaN        0
791          NaN        0
792          NaN        0
793          NaN        0
795          NaN        0
796          NaN        0
797          NaN        0
798          NaN        0
799          NaN        0
801          NaN        0
802          NaN        0

In [209]:
# Inspecting Fence without values
dataset['Fence'].value_counts(dropna=False)

Fence
NaN      1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

In [210]:
# Inspecting Fence without values
dataset['Alley'].value_counts(dropna=False)

Alley
NaN     1369
Grvl      50
Pave      41
Name: count, dtype: int64

In [211]:
absent_features = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCond', 'GarageQual', 'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtFinType1', 'BsmtQual']

In [236]:
missing[missing >0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
Electrical         1
dtype: int64

In [213]:
# Investigating Pool
dataset.groupby('PoolQC', dropna=False)['SalePrice'].mean()

PoolQC
Ex     490000.000000
Fa     215500.000000
Gd     201990.000000
NaN    180404.663455
Name: SalePrice, dtype: float64

In [214]:
# Investigating Garage
dataset.groupby('GarageType', dropna=False)['SalePrice'].agg(['count', 'mean'])

            count           mean
GarageType
2Types          6  151283.333333
Attchd        870  202892.656322
Basment        19  160570.684211
BuiltIn        88  254751.738636
CarPort         9  109962.111111
Detchd        387  134091.162791
NaN            81  103317.283951

In [215]:
dataset[dataset['GarageType'].isnull()][['GarageArea', 'GarageCars', 'GarageYrBlt']]

      GarageArea  GarageCars  GarageYrBlt
39             0           0          NaN
48             0           0          NaN
78             0           0          NaN
88             0           0          NaN
89             0           0          NaN
99             0           0          NaN
108            0           0          NaN
125            0           0          NaN
127            0           0          NaN
140            0           0          NaN
148            0           0          NaN
155            0           0          NaN
163            0           0          NaN
165            0           0          NaN
198            0           0          NaN
210            0           0          NaN
241            0           0          NaN
250            0           0          NaN
287            0           0          NaN
291            0           0          NaN
307            0           0          NaN
375            0           0          NaN
386            0           0          NaN
393            0           0          NaN
431            0           0          NaN
434            0           0          NaN
441            0           0          NaN
464            0           0          NaN
495            0           0          NaN
520            0           0          NaN
528            0           0          NaN
533            0           0          NaN
535            0           0          NaN
562            0           0          NaN
582            0           0          NaN
613            0           0          NaN
614            0           0          NaN
620            0           0          NaN
635            0           0          NaN
636            0           0          NaN
638            0           0          NaN
649            0           0          NaN
705            0           0          NaN
710            0           0          NaN
738            0           0          NaN
750            0           0          NaN
784            0           0          NaN
826            0           0          NaN
843            0           0          NaN
921            0           0          NaN
942            0           0          NaN
954            0           0          NaN
960            0           0          NaN
968            0           0          NaN
970            0           0          NaN
976            0           0          NaN
1009           0           0          NaN
1011           0           0          NaN
1030           0           0          NaN
1038           0           0          NaN
1096           0           0          NaN
1123           0           0          NaN
1131           0           0          NaN
1137           0           0          NaN
1143           0           0          NaN
1173           0           0          NaN
1179           0           0          NaN
1218           0           0          NaN
1219           0           0          NaN
1234           0           0          NaN
1257           0           0          NaN
1283           0           0          NaN
1323           0           0          NaN
1325           0           0          NaN
1326           0           0          NaN
1337           0           0          NaN
1349           0           0          NaN
1407           0           0          NaN
1449           0           0          NaN
1450           0           0          NaN
1453           0           0          NaN

In [233]:
absent_features = dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)
absent_features[absent_features > 0]

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageCond        81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtFinType1      37
BsmtQual          37
dtype: int64

In [217]:
dataset[dataset['Electrical'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1379,1380,80,RL,73.0,9735,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500

In [218]:
dataset['Electrical'].value_counts()

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

In [219]:
dataset.loc[1379, ['Electrical', 'OverallQual', 'YearBuilt', 'YearRemodAdd',
                   'Neighborhood', 'HouseStyle', 'CentralAir']]

Electrical         NaN
OverallQual          5
YearBuilt         2006
YearRemodAdd      2007
Neighborhood    Timber
HouseStyle        SLvl
CentralAir           Y
Name: 1379, dtype: object

In [220]:
dataset[dataset['Neighborhood'] == 'Timber']['Electrical'].value_counts()

Electrical
SBrkr    36
FuseA     1
Name: count, dtype: int64

In [221]:
dataset[dataset['YearBuilt'] >= 2000]['Electrical'].value_counts()

Electrical
SBrkr    387
Name: count, dtype: int64

In [222]:
dataset[
    (dataset['Neighborhood'] == 'Timber') & 
    (dataset['YearBuilt'] >= 2000) & 
    (dataset['HouseStyle'] == 'SLvl')]['Electrical'].value_counts(dropna=False)

Electrical
SBrkr    1
NaN      1
Name: count, dtype: int64

In [223]:
dataset[dataset['Neighborhood'] == 'Timber'][['Electrical', 'SalePrice']].sort_values('SalePrice')

     Electrical  SalePrice
944       FuseA     137500
1396      SBrkr     160000
1379        NaN     167500
41        SBrkr     170000
429       SBrkr     175000
530       SBrkr     175000
695       SBrkr     176000
1281      SBrkr     180000
174       SBrkr     184000
1184      SBrkr     186700
881       SBrkr     187500
731       SBrkr     187500
930       SBrkr     201000
340       SBrkr     202900
452       SBrkr     204000
964       SBrkr     214900
133       SBrkr     220000
572       SBrkr     224500
169       SBrkr     228000
335       SBrkr     228950
1375      SBrkr     239000
866       SBrkr     248900
1180      SBrkr     250000
1239      SBrkr     265900
157       SBrkr     269500
947       SBrkr     270000
1395      SBrkr     281213
1347      SBrkr     283463
1024      SBrkr     287000
1027      SBrkr     293077
619       SBrkr     305000
700       SBrkr     312500
540       SBrkr     315000
1036      SBrkr     315500
692       SBrkr     335000
585       SBrkr     369900
313       SBrkr     375000
1267      SBrkr     378500

In [230]:
dataset.loc[1379, ['Electrical']] = 'SBrkr'

In [231]:
dataset.loc[1379, ['Electrical']]

Electrical    SBrkr
Name: 1379, dtype: str

In [240]:
dataset['Electrical'].isnull().sum()

np.int64(0)

In [237]:
absent_features = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCond', 'GarageQual', 'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtFinType1', 'BsmtQual']

In [243]:
missing_values_without_zeros = dataset.isnull().sum()
missing_values_without_zeros[missing_values_without_zeros > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
dtype: int64

In [245]:
dataset[absent_features].dtypes

PoolQC              str
MiscFeature         str
Alley               str
Fence               str
FireplaceQu         str
GarageType          str
GarageYrBlt     float64
GarageFinish        str
GarageCond          str
GarageQual          str
BsmtFinType2        str
BsmtExposure        str
BsmtCond            str
BsmtFinType1        str
BsmtQual            str
dtype: object

In [291]:
dataset['BsmtQual'] = dataset['BsmtQual'].fillna('None')

In [292]:
dataset['BsmtQual'].isnull().value_counts(dropna=False)

BsmtQual
False    1460
Name: count, dtype: int64

In [293]:
dataset['BsmtQual'].value_counts()

BsmtQual
TA      649
Gd      618
Ex      121
None     37
Fa       35
Name: count, dtype: int64

In [294]:
dataset.isnull().sum().sort_values(ascending=False)

LotFrontage      259
Id                 0
BedroomAbvGr       0
GarageYrBlt        0
GarageType         0
FireplaceQu        0
Fireplaces         0
Functional         0
TotRmsAbvGrd       0
KitchenQual        0
KitchenAbvGr       0
HalfBath           0
GarageCars         0
FullBath           0
BsmtHalfBath       0
BsmtFullBath       0
GrLivArea          0
LowQualFinSF       0
2ndFlrSF           0
1stFlrSF           0
GarageFinish       0
GarageArea         0
CentralAir         0
PoolQC             0
SaleCondition      0
SaleType           0
YrSold             0
MoSold             0
MiscVal            0
MiscFeature        0
Fence              0
PoolArea           0
GarageQual         0
ScreenPorch        0
3SsnPorch          0
EnclosedPorch      0
OpenPorchSF        0
WoodDeckSF         0
PavedDrive         0
GarageCond         0
Electrical         0
HeatingQC          0
MSSubClass         0
LandSlope          0
OverallCond        0
OverallQual        0
HouseStyle         0
BldgType           0
Condition2         0
Condition1         0
Neighborhood       0
LotConfig          0
YearRemodAdd       0
Utilities          0
LandContour        0
LotShape           0
Alley              0
Street             0
LotArea            0
MSZoning           0
YearBuilt          0
RoofStyle          0
Heating            0
BsmtCond           0
TotalBsmtSF        0
BsmtUnfSF          0
BsmtFinSF2         0
BsmtFinType2       0
BsmtFinSF1         0
BsmtFinType1       0
BsmtExposure       0
BsmtQual           0
RoofMatl           0
Foundation         0
ExterCond          0
ExterQual          0
MasVnrArea         0
MasVnrType         0
Exterior2nd        0
Exterior1st        0
SalePrice          0
dtype: int64