In [430]:
# Import dependences
import pandas as pd
from sklearn.model_selection import train_test_split
from scipy.stats import f_oneway, chi2_contingency
import math
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
pd.set_option('display.max_rows', None)

In [2]:
# Read the Dataset
dataset = pd.read_csv("train.csv")
dataset

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
5        6          50       RL         85.0    14115   Pave   NaN      IR1
6        7          20       RL         75.0    10084   Pave   NaN      Reg
7        8          60       RL          NaN    10382   Pave   NaN      IR1
8        9          50       RM         51.0     6120   Pave   NaN      Reg
9       10         190       RL         50.0     7420   Pave   NaN      Reg
10      11          20       RL         70.0    11200   Pave   NaN      Reg
11      12          60       RL         85.0    11924   Pave   NaN      IR1
12      13          20       RL          NaN    12968   Pave   NaN      IR2
13      14          20       RL         91.0    10652   Pave   NaN      IR1
14      15          20       RL          NaN    10920   Pave   NaN      IR1
15      16          45       RM         51.0     6120   Pave   NaN      Reg
16      17          20       RL          NaN    11241   Pave   NaN      IR1
17      18          90       RL         72.0    10791   Pave   NaN      Reg
18      19          20       RL         66.0    13695   Pave   NaN      Reg
19      20          20       RL         70.0     7560   Pave   NaN      Reg
20      21          60       RL        101.0    14215   Pave   NaN      IR1
21      22          45       RM         57.0     7449   Pave  Grvl      Reg
22      23          20       RL         75.0     9742   Pave   NaN      Reg
23      24         120       RM         44.0     4224   Pave   NaN      Reg
24      25          20       RL          NaN     8246   Pave   NaN      IR1
25      26          20       RL        110.0    14230   Pave   NaN      Reg
26      27          20       RL         60.0     7200   Pave   NaN      Reg
27      28          20       RL         98.0    11478   Pave   NaN      Reg
28      29          20       RL         47.0    16321   Pave   NaN      IR1
29      30          30       RM         60.0     6324   Pave   NaN      IR1
30      31          70  C (all)         50.0     8500   Pave  Pave      Reg
31      32          20       RL          NaN     8544   Pave   NaN      IR1
32      33          20       RL         85.0    11049   Pave   NaN      Reg
33      34          20       RL         70.0    10552   Pave   NaN      IR1
34      35         120       RL         60.0     7313   Pave   NaN      Reg
35      36          60       RL        108.0    13418   Pave   NaN      Reg
36      37          20       RL        112.0    10859   Pave   NaN      Reg
37      38          20       RL         74.0     8532   Pave   NaN      Reg
38      39          20       RL         68.0     7922   Pave   NaN      Reg
39      40          90       RL         65.0     6040   Pave   NaN      Reg
40      41          20       RL         84.0     8658   Pave   NaN      Reg
41      42          20       RL        115.0    16905   Pave   NaN      Reg
42      43          85       RL          NaN     9180   Pave   NaN      IR1
43      44          20       RL          NaN     9200   Pave   NaN      IR1
44      45          20       RL         70.0     7945   Pave   NaN      Reg
45      46         120       RL         61.0     7658   Pave   NaN      Reg
46      47          50       RL         48.0    12822   Pave   NaN      IR1
47      48          20       FV         84.0    11096   Pave   NaN      Reg
48      49         190       RM         33.0     4456   Pave   NaN      Reg
49      50          20       RL         66.0     7742   Pave   NaN      Reg
50      51          60       RL          NaN    13869   Pave   NaN      IR2
51      52          50       RM         52.0     6240   Pave   NaN      Reg
52      53          90       RM        110.0     8472   Grvl   NaN      IR2
53      54          20       RL         68.0    50271   Pave   NaN      IR1
54      55          80       RL         60.0     7134   Pave   NaN      Reg
55      56          20       RL        100.0    10175   Pave   NaN      IR1
56      57         160       FV         24.0     2645   Pave  Pave      Reg
57      58          60       RL         89.0    11645   Pave   NaN      IR1
58      59          60       RL         66.0    13682   Pave   NaN      IR2
59      60          20       RL         60.0     7200   Pave   NaN      Reg
60      61          20       RL         63.0    13072   Pave   NaN      Reg
61      62          75       RM         60.0     7200   Pave   NaN      Reg
62      63         120       RL         44.0     6442   Pave   NaN      IR1
63      64          70       RM         50.0    10300   Pave   NaN      IR1
64      65          60       RL          NaN     9375   Pave   NaN      Reg
65      66          60       RL         76.0     9591   Pave   NaN      Reg
66      67          20       RL          NaN    19900   Pave   NaN      Reg
67      68          20       RL         72.0    10665   Pave   NaN      IR1
68      69          30       RM         47.0     4608   Pave   NaN      Reg
69      70          50       RL         81.0    15593   Pave   NaN      Reg
70      71          20       RL         95.0    13651   Pave   NaN      IR1
71      72          20       RL         69.0     7599   Pave   NaN      Reg
72      73          60       RL         74.0    10141   Pave   NaN      IR1
73      74          20       RL         85.0    10200   Pave   NaN      Reg
74      75          50       RM         60.0     5790   Pave   NaN      Reg
75      76         180       RM         21.0     1596   Pave   NaN      Reg
76      77          20       RL          NaN     8475   Pave   NaN      IR1
77      78          50       RM         50.0     8635   Pave   NaN      Reg
78      79          90       RL         72.0    10778   Pave   NaN      Reg
79      80          50       RM         60.0    10440   Pave  Grvl      Reg
80      81          60       RL        100.0    13000   Pave   NaN      Reg
81      82         120       RM         32.0     4500   Pave   NaN      Reg
82      83          20       RL         78.0    10206   Pave   NaN      Reg
83      84          20       RL         80.0     8892   Pave   NaN      IR1
84      85          80       RL          NaN     8530   Pave   NaN      IR1
85      86          60       RL        121.0    16059   Pave   NaN      Reg
86      87          60       RL        122.0    11911   Pave   NaN      IR2
87      88         160       FV         40.0     3951   Pave  Pave      Reg
88      89          50  C (all)        105.0     8470   Pave   NaN      IR1
89      90          20       RL         60.0     8070   Pave   NaN      Reg
90      91          20       RL         60.0     7200   Pave   NaN      Reg
91      92          20       RL         85.0     8500   Pave   NaN      Reg
92      93          30       RL         80.0    13360   Pave  Grvl      IR1
93      94         190  C (all)         60.0     7200   Pave   NaN      Reg
94      95          60       RL         69.0     9337   Pave   NaN      IR1
95      96          60       RL          NaN     9765   Pave   NaN      IR2
96      97          20       RL         78.0    10264   Pave   NaN      IR1
97      98          20       RL         73.0    10921   Pave   NaN      Reg
98      99          30       RL         85.0    10625   Pave   NaN      Reg
99     100          20       RL         77.0     9320   Pave   NaN      IR1
100    101          20       RL          NaN    10603   Pave   NaN      IR1
101    102          60       RL         77.0     9206   Pave   NaN      Reg
102    103          90       RL         64.0     7018   Pave   NaN      Reg
103    104          20       RL         94.0    10402   Pave   NaN      IR1
104    105          50       RM          NaN     7758   Pave   NaN      Reg
105    106          60       FV         75.0     9375   Pave   NaN      Reg
106    107          30       RM         60.0    10800   Pave  Grvl      Reg
107    108          20       RM         50.0     6000   Pave   NaN      Reg
108    109          50       RM         85.0     8500   Pave   NaN      Reg
109    110          20       RL        105.0    11751   Pave   NaN      IR1
110    111          50       RL         75.0     9525   Pave   NaN      Reg
111    112          80       RL          NaN     7750   Pave   NaN      IR1
112    113          60       RL         77.0     9965   Pave   NaN      Reg
113    114          20       RL          NaN    21000   Pave   NaN      Reg
114    115          70       RL         61.0     7259   Pave   NaN      IR1
115    116         160       FV         34.0     3230   Pave  Pave      Reg
116    117          20       RL          NaN    11616   Pave   NaN      Reg
117    118          20       RL         74.0     8536   Pave   NaN      Reg
118    119          60       RL         90.0    12376   Pave   NaN      Reg
119    120          60       RL         65.0     8461   Pave   NaN      Reg
120    121          80       RL          NaN    21453   Pave   NaN      IR1
121    122          50       RM         50.0     6060   Pave   NaN      Reg
122    123          20       RL         75.0     9464   Pave   NaN      Reg
123    124         120       RL         55.0     7892   Pave   NaN      Reg
124    125          20       RL         48.0    17043   Pave   NaN      IR1
125    126         190       RM         60.0     6780   Pave   NaN      Reg
126    127         120       RL          NaN     4928   Pave   NaN      IR1
127    128          45       RM         55.0     4388   Pave   NaN      IR1
128    129          60       RL         69.0     7590   Pave   NaN      Reg
129    130          20       RL         69.0     8973   Pave   NaN      Reg
130    131          60       RL         88.0    14200   Pave   NaN      Reg
131    132          60       RL          NaN    12224   Pave   NaN      IR1
132    133          20       RL         75.0     7388   Pave   NaN      Reg
133    134          20       RL          NaN     6853   Pave   NaN      IR1
134    135          20       RL         78.0    10335   Pave   NaN      IR1
135    136          20       RL         80.0    10400   Pave   NaN      Reg
136    137          20       RL          NaN    10355   Pave   NaN      IR1
137    138          90       RL         82.0    11070   Pave   NaN      Reg
138    139          60       RL         73.0     9066   Pave   NaN      IR1
139    140          60       RL         65.0    15426   Pave   NaN      IR1
140    141          20       RL         70.0    10500   Pave   NaN      Reg
141    142          20       RL         78.0    11645   Pave   NaN      Reg
142    143          50       RL         71.0     8520   Pave   NaN      Reg
143    144          20       RL         78.0    10335   Pave   NaN      IR1
144    145          90       RM         70.0     9100   Pave   NaN      Reg
145    146         160       RM         24.0     2522   Pave   NaN      Reg
146    147          30       RM         51.0     6120   Pave   NaN      Reg
147    148          60       RL          NaN     9505   Pave   NaN      IR1
148    149          20       RL         63.0     7500   Pave   NaN      Reg
149    150          50       RM          NaN     6240   Pave   NaN      Reg
150    151          20       RL        120.0    10356   Pave   NaN      Reg
151    152          20       RL        107.0    13891   Pave   NaN      Reg
152    153          60       RL          NaN    14803   Pave   NaN      IR1
153    154          20       RL          NaN    13500   Pave   NaN      Reg
154    155          30       RM         84.0    11340   Pave   NaN      Reg
155    156          50       RL         60.0     9600   Pave   NaN      Reg
156    157          20       RL         60.0     7200   Pave   NaN      Reg
157    158          60       RL         92.0    12003   Pave   NaN      Reg
158    159          60       FV        100.0    12552   Pave   NaN      Reg
159    160          60       RL        134.0    19378   Pave   NaN      IR1
160    161          20       RL          NaN    11120   Pave   NaN      IR1
161    162          60       RL        110.0    13688   Pave   NaN      IR1
162    163          20       RL         95.0    12182   Pave   NaN      Reg
163    164          45       RL         55.0     5500   Pave   NaN      Reg
164    165          40       RM         40.0     5400   Pave  Pave      Reg
165    166         190       RL         62.0    10106   Pave   NaN      Reg
166    167          20       RL          NaN    10708   Pave   NaN      IR1
167    168          60       RL         86.0    10562   Pave   NaN      Reg
168    169          60       RL         62.0     8244   Pave   NaN      IR1
169    170          20       RL          NaN    16669   Pave   NaN      IR1
170    171          50       RM          NaN    12358   Pave   NaN      IR1
171    172          20       RL        141.0    31770   Pave   NaN      IR1
172    173         160       RL         44.0     5306   Pave   NaN      IR1
173    174          20       RL         80.0    10197   Pave   NaN      IR1
174    175          20       RL         47.0    12416   Pave   NaN      IR1
175    176          20       RL         84.0    12615   Pave   NaN      Reg
176    177          60       RL         97.0    10029   Pave   NaN      IR1
177    178          50       RL          NaN    13650   Pave   NaN      Reg
178    179          20       RL         63.0    17423   Pave   NaN      IR1
179    180          30       RM         60.0     8520   Pave   NaN      Reg
180    181         160       FV          NaN     2117   Pave   NaN      Reg
181    182          70       RL         54.0     7588   Pave   NaN      Reg
182    183          20       RL         60.0     9060   Pave   NaN      Reg
183    184          50       RM         63.0    11426   Pave   NaN      Reg
184    185          50       RL         92.0     7438   Pave   NaN      IR1
185    186          75       RM         90.0    22950   Pave   NaN      IR2
186    187          80       RL          NaN     9947   Pave   NaN      IR1
187    188          50       RL         60.0    10410   Pave   NaN      Reg
188    189          90       RL         64.0     7018   Pave   NaN      Reg
189    190         120       RL         41.0     4923   Pave   NaN      Reg
190    191          70       RL         70.0    10570   Pave   NaN      Reg
191    192          60       RL          NaN     7472   Pave   NaN      IR1
192    193          20       RL         68.0     9017   Pave   NaN      IR1
193    194         160       RM         24.0     2522   Pave   NaN      Reg
194    195          20       RL         60.0     7180   Pave   NaN      IR1
195    196         160       RL         24.0     2280   Pave   NaN      Reg
196    197          20       RL         79.0     9416   Pave   NaN      Reg
197    198          75       RL        174.0    25419   Pave   NaN      Reg
198    199          75       RM         92.0     5520   Pave   NaN      Reg
199    200          20       RL         76.0     9591   Pave   NaN      Reg
200    201          20       RM         80.0     8546   Pave   NaN      Reg
201    202          20       RL         75.0    10125   Pave   NaN      Reg
202    203          50       RL         50.0     7000   Pave   NaN      Reg
203    204         120       RM          NaN     4438   Pave   NaN      Reg
204    205          50       RM         50.0     3500   Pave  Grvl      Reg
205    206          20       RL         99.0    11851   Pave   NaN      Reg
206    207          20       RL         40.0    13673   Pave   NaN      IR1
207    208          20       RL          NaN    12493   Pave   NaN      IR1
208    209          60       RL          NaN    14364   Pave   NaN      IR1
209    210          20       RL         75.0     8250   Pave   NaN      Reg
210    211          30       RL         67.0     5604   Pave   NaN      Reg
211    212          20       RL         83.0    10420   Pave   NaN      Reg
212    213          60       FV         72.0     8640   Pave   NaN      Reg
213    214          20       RL         43.0    13568   Pave   NaN      IR2
214    215          60       RL          NaN    10900   Pave   NaN      IR1
215    216          20       RL         72.0    10011   Pave   NaN      IR1
216    217          20       RL         65.0     8450   Pave   NaN      Reg
217    218          70       RM         57.0     9906   Pave  Grvl      Reg
218    219          50       RL          NaN    15660   Pave   NaN      IR1
219    220         120       RL         43.0     3010   Pave   NaN      Reg
220    221          20       RL         73.0     8990   Pave   NaN      IR1
221    222          60       RL          NaN     8068   Pave   NaN      IR1
222    223          60       RL         85.0    11475   Pave   NaN      Reg
223    224          20       RL         70.0    10500   Pave   NaN      Reg
224    225          20       RL        103.0    13472   Pave   NaN      Reg
225    226         160       RM         21.0     1680   Pave   NaN      Reg
226    227          60       RL         82.0     9950   Pave   NaN      IR1
227    228         160       RM         21.0     1869   Pave   NaN      Reg
228    229          20       RL         70.0     8521   Pave   NaN      Reg
229    230         120       RL         43.0     3182   Pave   NaN      Reg
230    231          20       RL         73.0     8760   Pave   NaN      Reg
231    232          60       RL        174.0    15138   Pave   NaN      IR1
232    233         160       RM         21.0     1680   Pave   NaN      Reg
233    234          20       RL         75.0    10650   Pave   NaN      Reg
234    235          60       RL          NaN     7851   Pave   NaN      Reg
235    236         160       RM         21.0     1680   Pave   NaN      Reg
236    237          20       RL         65.0     8773   Pave   NaN      Reg
237    238          60       RL          NaN     9453   Pave   NaN      IR1
238    239          20       RL         93.0    12030   Pave   NaN      Reg
239    240          50       RL         52.0     8741   Pave   NaN      Reg
240    241          20       FV         75.0     9000   Pave   NaN      Reg
241    242          30       RM         40.0     3880   Pave   NaN      Reg
242    243          50       RM         63.0     5000   Pave   NaN      Reg
243    244         160       RL         75.0    10762   Pave   NaN      Reg
244    245          60       RL          NaN     8880   Pave   NaN      IR1
245    246          20       RL         80.0    10400   Pave   NaN      Reg
246    247         190       RM         69.0     9142   Pave  Grvl      Reg
247    248          20       RL         75.0    11310   Pave   NaN      Reg
248    249          60       RL         72.0    11317   Pave   NaN      Reg
249    250          50       RL          NaN   159000   Pave   NaN      IR2
250    251          30       RL         55.0     5350   Pave   NaN      IR1
251    252         120       RM         44.0     4750   Pave   NaN      IR1
252    253          60       RL         65.0     8366   Pave   NaN      IR1
253    254          80       RL         85.0     9350   Pave   NaN      Reg
254    255          20       RL         70.0     8400   Pave   NaN      Reg
255    256          60       RL         66.0     8738   Pave   NaN      IR1
256    257          60       FV         64.0     8791   Pave   NaN      IR1
257    258          20       RL         68.0     8814   Pave   NaN      Reg
258    259          60       RL         80.0    12435   Pave   NaN      Reg
259    260          20       RM         70.0    12702   Pave   NaN      Reg
260    261          80       RL        120.0    19296   Pave   NaN      Reg
261    262          60       RL         69.0     9588   Pave   NaN      IR1

In [3]:
# View dataset statistics
dataset.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,...,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,...,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,...,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,...,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,...,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,...,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [4]:
# Checking missing values
missing_values = dataset.isnull().sum().sum()
print(f"Are any features missing data? Answer:", "No" if missing_values == 0 else "Yes")

Are any features missing data? Answer: Yes

In [5]:
# How to get column names, data types and column counts
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [6]:
# SalePrice statistics
sale_price_count = dataset['SalePrice'].count()
print(f"How many SalePrice values do I have? Answer: {sale_price_count}")

sale_price_mean = dataset['SalePrice'].mean()
print(f"What is the average house price? Answer: {sale_price_mean:.3f}")

sale_price_median = dataset['SalePrice'].median()
print(f"What's the median house price? Answer: {sale_price_median}")

sale_price_std = dataset['SalePrice'].std()
print(f"How spread out are the prices? Answer: {sale_price_std:.3f}")

sale_price_min = dataset['SalePrice'].min()
print(f"What is the cheapest house? Answer: {sale_price_min}")

sale_price_max= dataset['SalePrice'].max()
print(f"What is the most expensive house? Answer: {sale_price_max}")

sale_price_null = dataset['SalePrice'].isnull().sum()
print(f"Is there a null value in the SalePrice column? Answer: ", "No" if sale_price_null == 0 else "Yes")

How many SalePrice values do I have? Answer: 1460
What is the average house price? Answer: 180921.196
What's the median house price? Answer: 163000.0
How spread out are the prices? Answer: 79442.503
What is the cheapest house? Answer: 34900
What is the most expensive house? Answer: 755000
Is there a null value in the SalePrice column? Answer:  No

In [7]:
# View Correlation of SalePrice to other features in descending order
dataset.corr(numeric_only=True)['SalePrice'].sort_values(ascending=False).head(50)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [8]:
# Categorical Features
neighborhood_uniqe_values = dataset["Neighborhood"].nunique()
print(f"How many unique value are in Neighborhood? Answer: {neighborhood_uniqe_values}")

How many unique value are in Neighborhood? Answer: 25

In [9]:
# Grouping neighborhood and there average prices
dataset.groupby(["Neighborhood"])['SalePrice'].mean().sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [10]:
# Getting categorical feature unique values
dataset.select_dtypes('str').nunique().sort_values()

Street            2
Alley             2
CentralAir        2
Utilities         2
MasVnrType        3
LandSlope         3
PoolQC            3
PavedDrive        3
GarageFinish      3
BsmtQual          4
ExterQual         4
KitchenQual       4
BsmtCond          4
BsmtExposure      4
Fence             4
MiscFeature       4
LandContour       4
LotShape          4
FireplaceQu       5
Electrical        5
HeatingQC         5
GarageQual        5
GarageCond        5
MSZoning          5
LotConfig         5
BldgType          5
ExterCond         5
BsmtFinType1      6
RoofStyle         6
GarageType        6
Foundation        6
Heating           6
BsmtFinType2      6
SaleCondition     6
Functional        7
RoofMatl          8
HouseStyle        8
Condition2        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [11]:
dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
FireplaceQu       690
GarageType         81
GarageCond         81
GarageQual         81
GarageFinish       81
BsmtFinType2       38
BsmtExposure       38
BsmtFinType1       37
BsmtQual           37
BsmtCond           37
Electrical          1
KitchenQual         0
CentralAir          0
Functional          0
HeatingQC           0
Heating             0
PavedDrive          0
SaleType            0
MSZoning            0
Street              0
Condition2          0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
BldgType            0
Foundation          0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
SaleCondition       0
dtype: int64

In [12]:
dataset['PoolQC'].value_counts()

PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

In [13]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [14]:
dataset['Alley'].value_counts()

Alley
Grvl    50
Pave    41
Name: count, dtype: int64

In [15]:
dataset[['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageCond', 'GarageQual', 'GarageFinish', 'BsmtFinType2', 'BsmtExposure', 'BsmtFinType1', 'BsmtQual', 'BsmtCond']].head(20)

,PoolQC,MiscFeature,Alley,Fence,FireplaceQu,GarageType,GarageCond,GarageQual,GarageFinish,BsmtFinType2,BsmtExposure,BsmtFinType1,BsmtQual,BsmtCond
0,NaN,NaN,NaN,NaN,NaN,Attchd,TA,TA,RFn,Unf,No,GLQ,Gd,TA
1,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Gd,ALQ,Gd,TA
2,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Mn,GLQ,Gd,TA
3,NaN,NaN,NaN,NaN,Gd,Detchd,TA,TA,Unf,Unf,No,ALQ,TA,Gd
4,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Av,GLQ,Gd,TA
5,NaN,Shed,NaN,MnPrv,NaN,Attchd,TA,TA,Unf,Unf,No,GLQ,Gd,TA
6,NaN,NaN,NaN,NaN,Gd,Attchd,TA,TA,RFn,Unf,Av,GLQ,Ex,TA
7,NaN,Shed,NaN,NaN,TA,Attchd,TA,TA,RFn,BLQ,Mn,ALQ,Gd,TA
8,NaN,NaN,NaN,NaN,TA,Detchd,TA,Fa,Unf,Unf,No,Unf,TA,TA
9,NaN,NaN,NaN,NaN,TA,Attchd,TA,Gd,RFn,Unf,No,GLQ,TA,TA
10,NaN,NaN,NaN,NaN,NaN,Detchd,TA,TA,Unf,Unf,No,Rec,TA,TA
11,NaN,NaN,NaN,NaN,Gd,BuiltIn,TA,TA,Fin,Unf,No,GLQ,Ex,TA
12,NaN,NaN,NaN,NaN,NaN,Detchd,TA,TA,Unf,Unf,No,ALQ,TA,TA
13,NaN,NaN,NaN,NaN,Gd,Attchd,TA,TA,RFn,Unf,Av,Unf,Gd,TA
14,NaN,NaN,NaN,GdWo,Fa,Attchd,TA,TA,RFn,Unf,No,BLQ,TA,TA
15,NaN,NaN,NaN,GdPrv,NaN,Detchd,TA,TA,Unf,Unf,No,Unf,TA,TA
16,NaN,Shed,NaN,NaN,TA,Attchd,TA,TA,Fin,Unf,No,ALQ,TA,TA
17,NaN,Shed,NaN,NaN,NaN,CarPort,TA,TA,Unf,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,Detchd,TA,TA,Unf,Unf,No,GLQ,TA,TA
19,NaN,NaN,NaN,MnPrv,NaN,Attchd,TA,TA,Unf,Unf,No,LwQ,TA,TA

In [16]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [17]:
dataset[dataset['MasVnrType'].isnull()]['MasVnrArea'].value_counts(dropna=False)

MasVnrArea
0.0      859
NaN        8
1.0        2
288.0      1
344.0      1
312.0      1
Name: count, dtype: int64

In [18]:
dataset[dataset['MasVnrType'].isnull() & (dataset['MasVnrArea'] != 0)][['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
624         NaN       288.0
650         NaN         NaN
773         NaN         1.0
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1230        NaN         1.0
1243        NaN         NaN
1278        NaN         NaN
1300        NaN       344.0
1334        NaN       312.0

In [19]:
dataset.loc[
    [624, 773, 1230, 1300, 1334],
    ['MasVnrType', 'MasVnrArea', 'OverallQual',
     'YearBuilt', 'YearRemodAdd', 'Neighborhood', 
     'HouseStyle']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,Neighborhood,HouseStyle
624,NaN,288.0,6,1972,1972,NWAmes,2Story
773,NaN,1.0,5,1958,1958,NAmes,1Story
1230,NaN,1.0,5,1977,1977,Sawyer,1.5Fin
1300,NaN,344.0,7,1999,1999,Gilbert,2Story
1334,NaN,312.0,5,1970,1970,BrDale,2Story

In [20]:
# Investigating cell 624
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['HouseStyle'] == '2Story')
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
7         Stone       240.0            7       1973          1973
152     BrkFace       252.0            6       1971          1971
222         NaN         0.0            6       1975          1975
293     BrkFace        34.0            7       1977          1994
298     BrkFace       365.0            6       1968          1968
316     BrkFace       278.0            7       1980          1980
364     BrkFace       120.0            6       1976          1976
471         NaN         0.0            7       1977          1977
621         NaN         0.0            6       1974          1997
624         NaN       288.0            6       1972          1972
643     BrkFace       263.0            5       1969          1969
660     BrkFace       233.0            7       1976          1976
745     BrkFace       289.0            8       1976          1996
766     BrkFace        42.0            7       1988          1988
859     BrkFace       220.0            6       1968          1984
927     BrkFace       342.0            7       1968          1968
961     BrkFace       424.0            6       1977          1995
988     BrkFace       298.0            6       1976          1976
1015        NaN         0.0            8       2001          2001
1041    BrkFace       252.0            6       1966          2000
1071        NaN         0.0            6       1968          1968
1111    BrkFace       660.0            7       1976          1976
1141    BrkFace        44.0            5       1976          1976
1159    BrkFace       270.0            6       1974          1974
1276        NaN         0.0            6       1972          1972
1293        NaN         0.0            7       1976          1976
1386    BrkFace       184.0            7       1978          1978
1409    BrkFace       123.0            7       1986          1991
1420    BrkFace       420.0            6       1968          1968

In [21]:
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['MasVnrArea'].between(250, 350))
][['MasVnrType', 'MasVnrArea', 'Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea Neighborhood  OverallQual  YearBuilt  YearRemodAdd
135     BrkFace       288.0       NWAmes            7       1970          1970
152     BrkFace       252.0       NWAmes            6       1971          1971
316     BrkFace       278.0       NWAmes            7       1980          1980
455     BrkFace       320.0       NWAmes            7       1973          1973
516     BrkFace       333.0       NWAmes            6       1972          1972
624         NaN       288.0       NWAmes            6       1972          1972
643     BrkFace       263.0       NWAmes            5       1969          1969
745     BrkFace       289.0       NWAmes            8       1976          1996
927     BrkFace       342.0       NWAmes            7       1968          1968
988     BrkFace       298.0       NWAmes            6       1976          1976
1041    BrkFace       252.0       NWAmes            6       1966          2000
1159    BrkFace       270.0       NWAmes            6       1974          1974
1429    BrkFace       310.0       NWAmes            6       1981          1981

In [22]:
dataset.loc[624, ['MasVnrType']] = 'BrkFace'

In [23]:
dataset.loc[624, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      288.0
Name: 624, dtype: object

In [24]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
14      BrkFace       212.0            6       1960          1960
16      BrkFace       180.0            6       1970          1970
37      BrkFace       650.0            5       1954          1990
40      BrkFace       101.0            6       1965          1965
55      BrkFace       272.0            6       1964          1964
66      BrkFace       287.0            7       1970          1989
70      BrkFace      1115.0            7       1973          1973
73      BrkFace       104.0            5       1954          2003
83       BrkCmn        66.0            5       1960          1960
91       BrkCmn       203.0            5       1961          1961
122     BrkFace       135.0            6       1958          1958
129     BrkFace        85.0            5       1958          1991
136     BrkFace       196.0            5       1967          1967
171       Stone       112.0            6       1960          1960
173      BrkCmn       491.0            6       1961          1961
209       Stone       260.0            6       1964          1964
215     BrkFace        64.0            5       1957          1996
230     BrkFace       220.0            6       1959          1959
273      BrkCmn       183.0            6       1958          1988
294       Stone       238.0            6       1953          1953
327     BrkFace       175.0            6       1960          1960
330     BrkFace        84.0            5       1964          1964
339     BrkFace       176.0            6       1958          1998
342     BrkFace       340.0            3       1949          1950
347     BrkFace        30.0            6       1960          1960
366     BrkFace       247.0            6       1963          1963
368     BrkFace       200.0            5       1954          1954
424     BrkFace        74.0            6       1956          1956
486     BrkFace       168.0            5       1965          1965
509     BrkFace       132.0            5       1959          1959
510      BrkCmn        70.0            5       1951          2000
570     BrkFace       108.0            5       1965          1965
571     BrkFace       207.0            6       1959          1959
580     BrkFace        85.0            6       1960          1987
625     BrkFace       261.0            6       1962          1962
656     BrkFace        54.0            5       1959          2006
662     BrkFace       216.0            6       1968          1968
728     BrkFace        95.0            5       1958          1958
773         NaN         1.0            5       1958          1958
813     BrkFace       243.0            6       1958          1958
830     BrkFace       387.0            6       1957          1957
833     BrkFace       180.0            6       1964          1964
834     BrkFace       136.0            5       1961          1961
865     BrkFace        76.0            5       1970          1970
884     BrkFace        60.0            5       1967          1967
886     BrkFace       122.0            5       1959          2005
889     BrkFace        90.0            6       1953          1953
905       Stone       110.0            5       1954          1954
967     BrkFace       151.0            5       1955          1955
1014    BrkFace       206.0            6       1948          1950
1026    BrkFace       324.0            5       1960          1960
1064    BrkFace       200.0            5       1966          1966
1070    BrkFace       120.0            5       1956          1956
1083    BrkFace       425.0            6       1964          1964
1093    BrkFace       166.0            5       1965          1998
1102    BrkFace        45.0            5       1960          2002
1223    BrkFace        44.0            5       1951          1951
1227    BrkFace       300.0            5       1965          2008
1233    BrkFace       180.0            5       1959          1959
1295    BrkFace       168.0            5       1968          1968
1296    BrkFace       148.0            5       1963          1963
1356    BrkFace        65.0            5       1966          1966
1425      Stone       243.0            6       1959          1959
1435    BrkFace       237.0            6       1962          2005

In [25]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['YearBuilt'].between(1955, 1961)) &
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
14      BrkFace       212.0            6       1960          1960     1Story
83       BrkCmn        66.0            5       1960          1960     1Story
91       BrkCmn       203.0            5       1961          1961     1Story
122     BrkFace       135.0            6       1958          1958     1Story
129     BrkFace        85.0            5       1958          1991     1Story
171       Stone       112.0            6       1960          1960     1Story
173      BrkCmn       491.0            6       1961          1961     1Story
215     BrkFace        64.0            5       1957          1996     1Story
230     BrkFace       220.0            6       1959          1959     1Story
273      BrkCmn       183.0            6       1958          1988     1Story
327     BrkFace       175.0            6       1960          1960     1Story
339     BrkFace       176.0            6       1958          1998     1Story
347     BrkFace        30.0            6       1960          1960     1Story
424     BrkFace        74.0            6       1956          1956     1Story
509     BrkFace       132.0            5       1959          1959     1Story
571     BrkFace       207.0            6       1959          1959     1Story
580     BrkFace        85.0            6       1960          1987     1Story
627     BrkFace       164.0            6       1955          1972       SLvl
656     BrkFace        54.0            5       1959          2006     1Story
728     BrkFace        95.0            5       1958          1958     1Story
773         NaN         1.0            5       1958          1958     1Story
813     BrkFace       243.0            6       1958          1958     1Story
830     BrkFace       387.0            6       1957          1957     1Story
834     BrkFace       136.0            5       1961          1961     1Story
886     BrkFace       122.0            5       1959          2005     1Story
910     BrkFace       361.0            5       1960          1960     2Story
946     BrkFace       128.0            5       1959          1959       SLvl
967     BrkFace       151.0            5       1955          1955     1Story
969     BrkFace       105.0            6       1958          1958       SLvl
980       Stone       210.0            7       1961          2007     SFoyer
1026    BrkFace       324.0            5       1960          1960     1Story
1070    BrkFace       120.0            5       1956          1956     1Story
1102    BrkFace        45.0            5       1960          2002     1Story
1225    BrkFace        63.0            6       1958          1958       SLvl
1233    BrkFace       180.0            5       1959          1959     1Story
1269    BrkFace       180.0            5       1958          1958     1.5Fin
1425      Stone       243.0            6       1959          1959     1Story

In [26]:
dataset[(dataset['MasVnrArea'] <= 10) &
(dataset['MasVnrArea'] > 0)][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
773         NaN         1.0            5       1958          1958     1Story
1230        NaN         1.0            5       1977          1977     1.5Fin

In [27]:
# Investigating cell 1230
dataset.loc[1230, ['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

Neighborhood     Sawyer
MasVnrType          NaN
MasVnrArea          1.0
OverallQual           5
YearBuilt          1977
YearRemodAdd       1977
HouseStyle       1.5Fin
Exterior1st     Plywood
Exterior2nd     Plywood
Name: 1230, dtype: object

In [28]:
dataset[
    (dataset['MasVnrType'].isnull()) &
    (dataset['MasVnrArea'] > 0)
    ][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,Exterior1st,Exterior2nd
773,NAmes,NaN,1.0,5,1958,1958,1Story,Wd Sdng,Wd Sdng
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,Plywood,Plywood
1300,Gilbert,NaN,344.0,7,1999,1999,2Story,VinylSd,VinylSd
1334,BrDale,NaN,312.0,5,1970,1970,2Story,HdBoard,HdBoard

In [29]:
# Investigating row 1300
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['YearBuilt'].between(1997, 2001))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
72,BrkFace,40.0,7,1998,1998,2Story,60,RL,Pave,VinylSd,VinylSd
131,BrkFace,40.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
147,BrkFace,180.0,7,2001,2001,2Story,60,RL,Pave,VinylSd,VinylSd
255,BrkFace,302.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
379,BrkFace,16.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
665,BrkFace,40.0,8,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
929,BrkFace,285.0,7,1997,1997,2Story,60,RL,Pave,HdBoard,HdBoard
941,BrkFace,298.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1300,NaN,344.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1433,BrkFace,318.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd

In [30]:
dataset.loc[1300, ['MasVnrType']] = 'BrkFace'

In [31]:
dataset.loc[1300, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      344.0
Name: 1300, dtype: object

In [32]:
# Investigating row 1334
dataset[(dataset['Neighborhood'] == 'BrDale') &
(dataset['YearBuilt'].between(1965, 1975))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
225,BrkFace,142.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
227,BrkFace,127.0,6,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
232,BrkFace,297.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
235,BrkFace,604.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
363,BrkFace,510.0,6,1972,2007,2Story,160,RM,Pave,HdBoard,HdBoard
430,BrkFace,232.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
432,BrkFace,376.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
500,BrkFace,285.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
655,BrkFace,381.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,ImStucc
837,BrkFace,158.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
1029,BrkFace,281.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
1104,BrkFace,304.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1219,BrkFace,236.0,6,1971,1971,2Story,160,RM,Pave,CemntBd,CmentBd
1291,BrkFace,268.0,5,1972,1972,2Story,160,RM,Pave,CemntBd,CmentBd
1334,NaN,312.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1378,BrkFace,408.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard

In [33]:
dataset.loc[1334, ['MasVnrType']] = 'BrkFace'

In [34]:
dataset.loc[1334, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1334, dtype: str

In [35]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['YearBuilt'].between(1956, 1960))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
83,NAmes,BrkCmn,66.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,MetalSd
129,NAmes,BrkFace,85.0,5,1958,1991,1Story,20,RL,Pave,Plywood,Plywood
215,NAmes,BrkFace,64.0,5,1957,1996,1Story,20,RL,Pave,HdBoard,HdBoard
509,NAmes,BrkFace,132.0,5,1959,1959,1Story,20,RL,Pave,MetalSd,MetalSd
656,NAmes,BrkFace,54.0,5,1959,2006,1Story,20,RL,Pave,HdBoard,HdBoard
728,NAmes,BrkFace,95.0,5,1958,1958,1Story,90,RL,Pave,VinylSd,VinylSd
773,NAmes,NaN,1.0,5,1958,1958,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
886,NAmes,BrkFace,122.0,5,1959,2005,1Story,90,RL,Pave,MetalSd,MetalSd
1026,NAmes,BrkFace,324.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,HdBoard
1070,NAmes,BrkFace,120.0,5,1956,1956,1Story,20,RL,Pave,MetalSd,MetalSd
1102,NAmes,BrkFace,45.0,5,1960,2002,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
1233,NAmes,BrkFace,180.0,5,1959,1959,1Story,20,RL,Pave,Plywood,Plywood

In [36]:
dataset.loc[773, ['MasVnrType']] = 'BrkFace'

In [37]:
dataset.loc[773, ['MasVnrType']]

MasVnrType    BrkFace
Name: 773, dtype: str

In [38]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['YearBuilt'].between(1970, 1985))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave,Plywood,Plywood
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave,Plywood,Plywood

In [39]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['Exterior1st'] == 'Plywood') &
(dataset['Exterior2nd'] == 'Plywood') &
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street
538,Sawyer,BrkFace,188.0,5,1968,1968,1Story,20,RL,Pave
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave
796,Sawyer,BrkFace,148.0,6,1977,1977,1Story,20,RL,Pave
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave

In [40]:
dataset.loc[1230, ['MasVnrType']] = 'BrkFace'

In [41]:
dataset.loc[1230, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1230, dtype: str

In [42]:
dataset.loc[[624, 773, 1230, 1300, 1334], ['Neighborhood','MasVnrType']]

     Neighborhood MasVnrType
624        NWAmes    BrkFace
773         NAmes    BrkFace
1230       Sawyer    BrkFace
1300      Gilbert    BrkFace
1334       BrDale    BrkFace

In [43]:
dataset[dataset['MasVnrType'].isnull() &
dataset['MasVnrArea'].isnull()][['Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
234,Gilbert,6,2002,2002,2Story,60,RL,Pave,VinylSd,VinylSd
529,Crawfor,6,1957,1975,1Story,20,RL,Pave,Wd Sdng,Stone
650,Somerst,7,2007,2007,2Story,60,FV,Pave,CemntBd,CmentBd
936,SawyerW,7,2003,2003,1Story,20,RL,Pave,VinylSd,VinylSd
973,Somerst,7,2007,2008,1Story,20,FV,Pave,CemntBd,CmentBd
977,Somerst,7,2006,2007,1Story,120,FV,Pave,VinylSd,VinylSd
1243,NridgHt,10,2006,2006,1Story,20,RL,Pave,VinylSd,VinylSd
1278,CollgCr,8,2002,2002,2Story,60,RL,Pave,VinylSd,VinylSd

In [44]:
dataset.groupby('MasVnrType', dropna=False)['MasVnrArea'].agg(
    ['count', 'min', 'mean', 'max']
)

            count   min        mean     max
MasVnrType
BrkCmn         15  41.0  247.666667   621.0
BrkFace       450   0.0  258.233333  1600.0
Stone         128   0.0  239.304688   860.0
NaN           859   0.0    0.000000     0.0

In [45]:
dataset['MasVnrArea'].isnull().sum()

np.int64(8)

In [46]:
dataset[dataset['MasVnrArea'].isnull()]['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN    8
Name: count, dtype: int64

In [47]:
dataset[['MasVnrType', 'MasVnrArea']].isnull().sum()

MasVnrType    867
MasVnrArea      8
dtype: int64

In [48]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        867
BrkFace    450
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [49]:
dataset[dataset['MasVnrArea'] == 0]['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        859
BrkFace      1
Stone        1
Name: count, dtype: int64

In [50]:
dataset[(dataset['MasVnrArea'] == 0) &
(dataset['MasVnrType'].notnull())][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
688,StoneBr,BrkFace,0.0,8,2007,2007,1Story,20,RL,Pave,MetalSd,MetalSd
1241,Somerst,Stone,0.0,7,2007,2007,1Story,20,RL,Pave,VinylSd,VinylSd

In [51]:
dataset[(dataset['Neighborhood'] == 'StoneBr') &
(dataset['YearBuilt'].between(2000, 2010))][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,Exterior1st,Exterior2nd
58,StoneBr,BrkFace,1031.0,2006,10,2Story,VinylSd,VinylSd
178,StoneBr,Stone,748.0,2008,9,1Story,VinylSd,VinylSd
189,StoneBr,NaN,0.0,2001,8,1Story,CemntBd,CmentBd
336,StoneBr,Stone,200.0,2005,9,1Story,VinylSd,VinylSd
378,StoneBr,Stone,350.0,2010,9,1Story,VinylSd,VinylSd
474,StoneBr,NaN,0.0,2000,8,1Story,CemntBd,CmentBd
566,StoneBr,BrkFace,245.0,2005,9,2Story,VinylSd,VinylSd
595,StoneBr,BrkFace,238.0,2005,8,1Story,VinylSd,Other
678,StoneBr,Stone,464.0,2008,8,1Story,VinylSd,VinylSd
688,StoneBr,BrkFace,0.0,2007,8,1Story,MetalSd,MetalSd
702,StoneBr,BrkFace,466.0,2006,8,2Story,VinylSd,VinylSd
769,StoneBr,BrkFace,603.0,2003,8,2Story,CemntBd,Wd Shng
1046,StoneBr,Stone,208.0,2005,9,2Story,CemntBd,CmentBd
1060,StoneBr,NaN,0.0,2001,8,1Story,CemntBd,CmentBd
1288,StoneBr,NaN,0.0,2000,8,1Story,CemntBd,CmentBd
1361,StoneBr,Stone,16.0,2005,7,1Story,VinylSd,VinylSd

In [52]:
dataset.groupby(['MasVnrType',	'MasVnrArea'], dropna=False).size().sort_values(ascending=False)

MasVnrType  MasVnrArea
NaN         0.0           859
            NaN             8
BrkFace     120.0           7
            180.0           7
            16.0            6
            108.0           6
            80.0            6
            360.0           5
            320.0           5
            170.0           5
            72.0            5
            40.0            4
            196.0           4
            456.0           4
            340.0           4
            168.0           4
            252.0           4
            132.0           3
            130.0           3
Stone       186.0           3
BrkFace     116.0           3
Stone       72.0            3
            200.0           3
BrkFace     106.0           3
            136.0           3
            99.0            3
            90.0            3
            85.0            3
            84.0            3
            104.0           3
            176.0           3
            148.0           3
            169.0           3
Stone       50.0            3
BrkFace     178.0           3
Stone       106.0           3
BrkFace     200.0           3
Stone       100.0           3
BrkFace     210.0           3
            220.0           3
            246.0           3
            288.0           3
            336.0           3
            183.0           3
            312.0           3
            44.0            3
Stone       160.0           2
BrkFace     171.0           2
Stone       208.0           2
BrkFace     18.0            2
Stone       216.0           2
BrkFace     189.0           2
            184.0           2
            335.0           2
            30.0            2
Stone       240.0           2
BrkFace     174.0           2
            172.0           2
            344.0           2
            145.0           2
Stone       256.0           2
            84.0            2
BrkFace     164.0           2
Stone       268.0           2
BrkFace     160.0           2
            158.0           2
            157.0           2
Stone       270.0           2
BrkFace     153.0           2
            42.0            2
            318.0           2
            206.0           2
            212.0           2
            1.0             2
            268.0           2
            266.0           2
Stone       94.0            2
            76.0            2
BrkFace     281.0           2
Stone       108.0           2
            110.0           2
BrkFace     285.0           2
            289.0           2
Stone       132.0           2
BrkFace     245.0           2
            305.0           2
            236.0           2
            298.0           2
            233.0           2
            232.0           2
            226.0           2
            480.0           2
            300.0           2
Stone       166.0           2
BrkFace     304.0           2
            216.0           2
            147.0           2
            350.0           2
            144.0           2
            650.0           2
Stone       420.0           2
BrkFace     54.0            2
            105.0           2
            423.0           2
            101.0           2
            425.0           2
            98.0            2
            95.0            2
            442.0           2
            60.0            2
            82.0            2
            513.0           2
            76.0            2
            75.0            2
            74.0            2
Stone       340.0           2
BrkFace     270.0           2
            45.0            2
Stone       300.0           2
BrkFace     128.0           2
            660.0           2
            362.0           2
            125.0           2
            554.0           1
Stone       16.0            1
BrkFace     564.0           1
            664.0           1
Stone       24.0            1
            36.0            1
            42.0            1
BrkCmn      203.0           1
Stone       68.0            1
BrkFace     562.0           1
            632.0           1
            571.0           1
            530.0           1
Stone       70.0            1
BrkCmn      192.0           1
BrkFace     528.0           1
Stone       74.0            1
BrkFace     673.0           1
            510.0           1
            768.0           1
            766.0           1
Stone       82.0            1
BrkFace     731.0           1
            506.0           1
            541.0           1
            653.0           1
            630.0           1
            816.0           1
            870.0           1
            894.0           1
            616.0           1
            921.0           1
            922.0           1
            604.0           1
            603.0           1
            975.0           1
            600.0           1
            594.0           1
            1031.0          1
            1047.0          1
Stone       0.0             1
BrkFace     584.0           1
            579.0           1
            1115.0          1
            1129.0          1
            705.0           1
            1378.0          1
            1600.0          1
            772.0           1
            576.0           1
            651.0           1
            573.0           1
            1170.0          1
            68.0            1
Stone       92.0            1
            272.0           1
            370.0           1
            366.0           1
            351.0           1
            350.0           1
            338.0           1
            336.0           1
            328.0           1
            306.0           1
            302.0           1
            295.0           1
            294.0           1
            288.0           1
            286.0           1
            284.0           1
            275.0           1
            410.0           1
            424.0           1
            426.0           1
            748.0           1
BrkCmn      67.0            1
Stone       860.0           1
            796.0           1
            788.0           1
            762.0           1
            760.0           1
            640.0           1
            432.0           1
            567.0           1
            481.0           1
            468.0           1
            464.0           1
            450.0           1
            436.0           1
            274.0           1
            260.0           1
BrkCmn      183.0           1
Stone       250.0           1
            163.0           1
            162.0           1
            154.0           1
            149.0           1
            146.0           1
            145.0           1
            143.0           1
            140.0           1
            135.0           1
            128.0           1
            126.0           1
            119.0           1
            117.0           1
            112.0           1
BrkCmn      161.0           1
Stone       174.0           1
            178.0           1
            180.0           1
            224.0           1
            248.0           1
            246.0           1
            243.0           1
            238.0           1
            230.0           1
            226.0           1
            220.0           1
            182.0           1
            215.0           1
            210.0           1
            205.0           1
BrkCmn      70.0            1
Stone       194.0           1
BrkCmn      113.0           1
BrkFace     500.0           1
            376.0           1
            479.0           1
            22.0            1
            188.0           1
            27.0            1
            182.0           1
            28.0            1
            31.0            1
            175.0           1
            32.0            1
            34.0            1
            38.0            1
            167.0           1
            166.0           1
            165.0           1
            162.0           1
            156.0           1
            151.0           1
            192.0           1
            202.0           1
            473.0           1
            203.0           1
            237.0           1
            234.0           1
            228.0           1
            225.0           1
            223.0           1
            11.0            1
            219.0           1
            218.0           1
            215.0           1
            14.0            1
            209.0           1
            208.0           1
            207.0           1
            205.0           1
            204.0           1
            150.0           1
            149.0           1
            143.0           1
            142.0           1
            56.0            1
            102.0           1
            100.0           1
            57.0            1
            97.0            1
            96.0            1
            92.0            1
            89.0            1
            88.0            1
            86.0            1
            63.0            1
            64.0            1
            81.0            1
            65.0            1
            66.0            1
            53.0            1
            109.0           1
            110.0           1
            123.0           1
            140.0           1
            138.0           1
            137.0           1
            135.0           1
            46.0            1
            127.0           1
            122.0           1
            112.0           1
            48.0            1
            117.0           1
            51.0            1
            115.0           1
            114.0           1
            113.0           1
            238.0           1
            240.0           1
            243.0           1
            338.0           1
            388.0           1
            387.0           1
            381.0           1
            380.0           1
            378.0           1
            70.0            1
            375.0           1
            368.0           1
            365.0           1
            361.0           1
BrkCmn      328.0           1
BrkFace     359.0           1
            351.0           1
            348.0           1
            342.0           1
            391.0           1
            396.0           1
            399.0           1
            448.0           1
            472.0           1
            466.0           1
            459.0           1
BrkCmn      272.0           1
BrkFace     452.0           1
            451.0           1
            443.0           1
            408.0           1
            438.0           1
            428.0           1
            424.0           1
            420.0           1
            415.0           1
            412.0           1
BrkCmn      435.0           1
BrkFace     337.0           1
            244.0           1
BrkCmn      472.0           1
BrkFace     280.0           1
            278.0           1
            272.0           1
            263.0           1
            262.0           1
            261.0           1
            260.0           1
            259.0           1
            258.0           1
            256.0           1
            255.0           1
            254.0           1
            0.0             1
            250.0           1
            247.0           1
            284.0           1
            287.0           1
BrkCmn      621.0           1
BrkFace     309.0           1
            333.0           1
            324.0           1
BrkCmn      491.0           1
BrkFace     315.0           1
BrkCmn      66.0            1
BrkFace     310.0           1
            306.0           1
            290.0           1
            302.0           1
            299.0           1
            297.0           1
            296.0           1
            293.0           1
            292.0           1
BrkCmn      41.0            1
dtype: int64

In [53]:
dataset[
    (dataset['MasVnrArea'] == 0) &
    (dataset['MasVnrType'].isnull())].shape[0]

859

In [54]:
dataset.loc[
    (dataset['MasVnrArea'] == 0) &
    (dataset['MasVnrType'].isnull()),
    'MasVnrType'
    ] = 'None'

In [55]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
None       859
BrkFace    450
Stone      128
BrkCmn      15
NaN          8
Name: count, dtype: int64

In [56]:
dataset[dataset['MasVnrArea'].isnull()][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
234,Gilbert,NaN,NaN,2002,6,2Story,60,VinylSd,VinylSd
529,Crawfor,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone
650,Somerst,NaN,NaN,2007,7,2Story,60,CemntBd,CmentBd
936,SawyerW,NaN,NaN,2003,7,1Story,20,VinylSd,VinylSd
973,Somerst,NaN,NaN,2007,7,1Story,20,CemntBd,CmentBd
977,Somerst,NaN,NaN,2006,7,1Story,120,VinylSd,VinylSd
1243,NridgHt,NaN,NaN,2006,10,1Story,20,VinylSd,VinylSd
1278,CollgCr,NaN,NaN,2002,8,2Story,60,VinylSd,VinylSd

In [57]:
# Investigating row 234
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 6) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
221,None,0.0,2002,6,2Story,60,VinylSd,VinylSd
234,NaN,NaN,2002,6,2Story,60,VinylSd,VinylSd
616,None,0.0,2002,6,2Story,60,VinylSd,VinylSd

In [58]:
dataset.loc[234, ['MasVnrType',	'MasVnrArea']] = ['BrkFace', 0]

In [59]:
dataset.loc[234, ['MasVnrType',	'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea        0.0
Name: 234, dtype: object

In [60]:
# Investigating row 529
dataset[(dataset['Neighborhood'] == 'Crawfor') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'Wd Sdng') &
(dataset['Exterior2nd'] == 'Stone')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
529,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone

In [61]:
# Investigating row 529
dataset[(dataset['Neighborhood'] == 'Crawfor') &
(dataset['Exterior2nd'] == 'Stone')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
529,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone
1152,None,0.0,1956,6,1Story,20,Stone,Stone
1343,None,0.0,1928,6,1.5Fin,50,BrkFace,Stone

In [62]:
dataset.loc[529, ['MasVnrType', 'MasVnrArea']] = ['None', 0]

In [63]:
dataset.loc[529, ['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

MasVnrType        None
MasVnrArea         0.0
YearBuilt         1957
OverallQual          6
HouseStyle      1Story
MSSubClass          20
Exterior1st    Wd Sdng
Exterior2nd      Stone
Name: 529, dtype: object

In [64]:
# Investigating row 650
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['Exterior2nd'] == 'CmentBd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
377,None,0.0,2004,8,2Story,60,CemntBd,CmentBd
399,Stone,100.0,2006,7,2Story,60,CemntBd,CmentBd
650,NaN,NaN,2007,7,2Story,60,CemntBd,CmentBd
875,None,0.0,2007,8,2Story,60,CemntBd,CmentBd
1374,None,0.0,2005,7,2Story,60,CemntBd,CmentBd

In [65]:
dataset.loc[650, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [66]:
dataset.loc[650, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 650, dtype: object

In [67]:
# Investigating row 936
dataset[(dataset['Neighborhood'] == 'SawyerW') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
18,None,0.0,2004,5,1Story,20,VinylSd,VinylSd
60,None,0.0,2004,6,1Story,20,VinylSd,VinylSd
148,BrkFace,120.0,2004,7,1Story,20,VinylSd,VinylSd
742,BrkFace,108.0,2000,7,1Story,20,VinylSd,VinylSd
827,None,0.0,2001,7,1Story,20,VinylSd,VinylSd
936,NaN,NaN,2003,7,1Story,20,VinylSd,VinylSd
951,None,0.0,1965,5,1Story,20,VinylSd,VinylSd
1238,None,0.0,2005,6,1Story,20,VinylSd,VinylSd
1341,None,0.0,2003,6,1Story,20,VinylSd,VinylSd
1348,None,0.0,1998,7,1Story,20,VinylSd,VinylSd
1413,Stone,366.0,2005,8,1Story,20,VinylSd,VinylSd

In [68]:
dataset.loc[936, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [69]:
dataset.loc[936, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 936, dtype: object

In [70]:

# Investigating row 973
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['Exterior2nd'] == 'CmentBd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
196,Stone,205.0,2007,7,1Story,20,CemntBd,CmentBd
644,Stone,162.0,2009,9,1Story,20,CemntBd,CmentBd
793,Stone,140.0,2007,8,1Story,20,CemntBd,CmentBd
973,NaN,NaN,2007,7,1Story,20,CemntBd,CmentBd
1217,Stone,72.0,2009,8,1Story,20,CemntBd,CmentBd
1451,Stone,194.0,2008,8,1Story,20,CemntBd,CmentBd

In [71]:

# Investigating row 973
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['MasVnrType'] == 'Stone') &
(dataset['Exterior2nd'] == 'CmentBd')]['MasVnrArea'].agg(['count', 'mean', 'median', 'min', 'max'])

count       5.0
mean      154.6
median    162.0
min        72.0
max       205.0
Name: MasVnrArea, dtype: float64

In [72]:
dataset.loc[973, ['MasVnrArea']] = 162

In [73]:
dataset.loc[973, ['MasVnrType']] = 'Stone'

In [74]:
dataset.loc[973, ['MasVnrType', 'MasVnrArea']]

MasVnrType    Stone
MasVnrArea    162.0
Name: 973, dtype: object

In [75]:
# Investigating row 977
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 120) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
977,NaN,NaN,2006,7,1Story,120,VinylSd,VinylSd
1317,None,0.0,2006,7,1Story,120,VinylSd,VinylSd

In [76]:
dataset.loc[977, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [77]:
dataset.loc[977, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 977, dtype: object

In [78]:
# Investigating row 1243
dataset[(dataset['Neighborhood'] == 'NridgHt') &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2006) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'OverallQual']]

     MasVnrType  MasVnrArea  OverallQual
62        Stone       178.0            8
320       Stone       370.0            9
408     BrkFace       350.0            7
468       Stone       248.0            8
473     BrkFace       304.0            8
477     BrkFace       772.0            9
552       Stone       250.0            8
631       Stone       108.0            8
774     BrkFace       375.0            8
1243        NaN         NaN           10
1289      Stone       788.0            8
1305      Stone       300.0            9

In [79]:
# Investigating row 1243
dataset[(dataset['Neighborhood'] == 'NridgHt') &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2006) &
(dataset['MasVnrType'] == 'Stone') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrArea']].agg(['count', 'mean', 'median', 'min', 'max'])

        MasVnrArea
count     7.000000
mean    320.285714
median  250.000000
min     108.000000
max     788.000000

In [80]:
dataset.loc[1243, ['MasVnrType', 'MasVnrArea']] = ['Stone', 320.29]

In [81]:
dataset.loc[1243, ['MasVnrType', 'MasVnrArea']]

MasVnrType     Stone
MasVnrArea    320.29
Name: 1243, dtype: object

In [82]:
# Investigating row 1278
dataset[(dataset['Neighborhood'] == 'CollgCr') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 8) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
1054,BrkFace,210.0,2002,8,2Story,60,VinylSd,VinylSd
1278,NaN,NaN,2002,8,2Story,60,VinylSd,VinylSd
1342,BrkFace,149.0,2002,8,2Story,60,VinylSd,VinylSd

In [83]:
# Investigating row 1278
dataset[(dataset['Neighborhood'] == 'CollgCr') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 8) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrArea']].agg(['count', 'mean', 'median', 'min', 'max'])

        MasVnrArea
count          2.0
mean         179.5
median       179.5
min          149.0
max          210.0

In [84]:
dataset.loc[1278, ['MasVnrType', 'MasVnrArea']] = ['BrkFace', 179.5]

In [85]:
dataset.loc[1278, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      179.5
Name: 1278, dtype: object

In [86]:
dataset.loc[1278, ['OverallQual', 'GarageArea', 'GrLivArea', 'TotalBsmtSF','1stFlrSF', 'SalePrice']]

OverallQual         8
GarageArea        577
GrLivArea        2031
TotalBsmtSF      1128
1stFlrSF         1128
SalePrice      237000
Name: 1278, dtype: int64

In [87]:
dataset.loc[[234, 529, 650, 936, 973, 977, 1243, 1278], ['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234     BrkFace        0.00
529        None        0.00
650        None        0.00
936        None        0.00
973       Stone      162.00
977        None        0.00
1243      Stone      320.29
1278    BrkFace      179.50

In [88]:
dataset.isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
FireplaceQu       690
LotFrontage       259
GarageYrBlt        81
GarageType         81
GarageFinish       81
GarageQual         81
GarageCond         81
BsmtFinType2       38
BsmtExposure       38
BsmtCond           37
BsmtQual           37
BsmtFinType1       37
Electrical          1
TotRmsAbvGrd        0
Id                  0
KitchenQual         0
Functional          0
BedroomAbvGr        0
HalfBath            0
FullBath            0
BsmtHalfBath        0
BsmtFullBath        0
KitchenAbvGr        0
GarageCars          0
Fireplaces          0
LowQualFinSF        0
GarageArea          0
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
GrLivArea           0
HeatingQC           0
2ndFlrSF            0
1stFlrSF            0
OverallCond         0
OverallQual         0
HouseStyle          0
BldgType            0
Condition2          0
Condition1          0
Neighborhood        0
LandSlope           0
LotConfig           0
Utilities           0
LandContour         0
LotShape            0
Street              0
LotArea             0
MSZoning            0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
BsmtFinSF1          0
CentralAir          0
MSSubClass          0
Heating             0
TotalBsmtSF         0
BsmtUnfSF           0
BsmtFinSF2          0
Foundation          0
RoofMatl            0
ExterCond           0
ExterQual           0
MasVnrArea          0
MasVnrType          0
Exterior2nd         0
Exterior1st         0
SalePrice           0
dtype: int64

In [89]:
dataset[dataset['MasVnrType'].isnull() |
dataset['MasVnrArea'].isnull()][['MasVnrType', 'MasVnrArea']]

Empty DataFrame
Columns: [MasVnrType, MasVnrArea]
Index: []

In [90]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [91]:
dataset[dataset['BsmtQual'].isnull()]['TotalBsmtSF'].value_counts()

TotalBsmtSF
0    37
Name: count, dtype: int64

In [92]:
dataset[dataset['GarageQual'].isnull()]['GarageArea'].value_counts()

GarageArea
0    81
Name: count, dtype: int64

In [93]:
dataset[dataset['FireplaceQu'].isnull()]['Fireplaces'].value_counts()

Fireplaces
0    690
Name: count, dtype: int64

In [94]:
dataset[dataset['MiscFeature'].isnull()]['MiscVal'].value_counts()

MiscVal
0    1406
Name: count, dtype: int64

In [95]:
dataset[dataset['Fence'].isnull()][['Fence', 'LotArea', 'OverallQual']].head(20)

   Fence  LotArea  OverallQual
0    NaN     8450            7
1    NaN     9600            6
2    NaN    11250            7
3    NaN     9550            7
4    NaN    14260            8
6    NaN    10084            8
7    NaN    10382            7
8    NaN     6120            7
9    NaN     7420            5
10   NaN    11200            5
11   NaN    11924            9
12   NaN    12968            5
13   NaN    10652            7
16   NaN    11241            6
17   NaN    10791            4
18   NaN    13695            5
20   NaN    14215            8
22   NaN     9742            8
23   NaN     4224            5
25   NaN    14230            8

In [96]:
dataset['Electrical'].isnull().sum()

np.int64(1)

In [97]:
missing = dataset.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
Electrical         1
dtype: int64

In [98]:
# Inspecting garage without values
dataset[dataset['GarageType'].isnull()][['GarageArea', 'GarageCars', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']].head(20)

,GarageArea,GarageCars,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
39,0,0,NaN,NaN,NaN,NaN,NaN
48,0,0,NaN,NaN,NaN,NaN,NaN
78,0,0,NaN,NaN,NaN,NaN,NaN
88,0,0,NaN,NaN,NaN,NaN,NaN
89,0,0,NaN,NaN,NaN,NaN,NaN
99,0,0,NaN,NaN,NaN,NaN,NaN
108,0,0,NaN,NaN,NaN,NaN,NaN
125,0,0,NaN,NaN,NaN,NaN,NaN
127,0,0,NaN,NaN,NaN,NaN,NaN
140,0,0,NaN,NaN,NaN,NaN,NaN
148,0,0,NaN,NaN,NaN,NaN,NaN
155,0,0,NaN,NaN,NaN,NaN,NaN
163,0,0,NaN,NaN,NaN,NaN,NaN
165,0,0,NaN,NaN,NaN,NaN,NaN
198,0,0,NaN,NaN,NaN,NaN,NaN
210,0,0,NaN,NaN,NaN,NaN,NaN
241,0,0,NaN,NaN,NaN,NaN,NaN
250,0,0,NaN,NaN,NaN,NaN,NaN
287,0,0,NaN,NaN,NaN,NaN,NaN
291,0,0,NaN,NaN,NaN,NaN,NaN

In [99]:
# Inspecting basement without values
dataset[dataset['BsmtQual'].isnull()][['TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtQual', 'BsmtExposure', 'BsmtFinType2', 'BsmtCond', 'BsmtFinType1']].head(20)

,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,BsmtQual,BsmtExposure,BsmtFinType2,BsmtCond,BsmtFinType1
17,0,0,0,NaN,NaN,NaN,NaN,NaN
39,0,0,0,NaN,NaN,NaN,NaN,NaN
90,0,0,0,NaN,NaN,NaN,NaN,NaN
102,0,0,0,NaN,NaN,NaN,NaN,NaN
156,0,0,0,NaN,NaN,NaN,NaN,NaN
182,0,0,0,NaN,NaN,NaN,NaN,NaN
259,0,0,0,NaN,NaN,NaN,NaN,NaN
342,0,0,0,NaN,NaN,NaN,NaN,NaN
362,0,0,0,NaN,NaN,NaN,NaN,NaN
371,0,0,0,NaN,NaN,NaN,NaN,NaN
392,0,0,0,NaN,NaN,NaN,NaN,NaN
520,0,0,0,NaN,NaN,NaN,NaN,NaN
532,0,0,0,NaN,NaN,NaN,NaN,NaN
533,0,0,0,NaN,NaN,NaN,NaN,NaN
553,0,0,0,NaN,NaN,NaN,NaN,NaN
646,0,0,0,NaN,NaN,NaN,NaN,NaN
705,0,0,0,NaN,NaN,NaN,NaN,NaN
736,0,0,0,NaN,NaN,NaN,NaN,NaN
749,0,0,0,NaN,NaN,NaN,NaN,NaN
778,0,0,0,NaN,NaN,NaN,NaN,NaN

In [100]:
# Inspecting fireplace without values
dataset[dataset['FireplaceQu'].isnull()][['FireplaceQu', 'Fireplaces']].head(20)

   FireplaceQu  Fireplaces
0          NaN           0
5          NaN           0
10         NaN           0
12         NaN           0
15         NaN           0
17         NaN           0
18         NaN           0
19         NaN           0
26         NaN           0
29         NaN           0
30         NaN           0
31         NaN           0
32         NaN           0
36         NaN           0
38         NaN           0
39         NaN           0
42         NaN           0
43         NaN           0
44         NaN           0
47         NaN           0

In [101]:
# Inspecting pool without values
dataset[dataset['PoolQC'].isnull()][['PoolQC', 'PoolArea']].head(20)

   PoolQC  PoolArea
0     NaN         0
1     NaN         0
2     NaN         0
3     NaN         0
4     NaN         0
5     NaN         0
6     NaN         0
7     NaN         0
8     NaN         0
9     NaN         0
10    NaN         0
11    NaN         0
12    NaN         0
13    NaN         0
14    NaN         0
15    NaN         0
16    NaN         0
17    NaN         0
18    NaN         0
19    NaN         0

In [102]:
# Inspecting misc without values
dataset[dataset['MiscFeature'].isnull()][['MiscFeature', 'MiscVal']].head(20)

   MiscFeature  MiscVal
0          NaN        0
1          NaN        0
2          NaN        0
3          NaN        0
4          NaN        0
6          NaN        0
8          NaN        0
9          NaN        0
10         NaN        0
11         NaN        0
12         NaN        0
13         NaN        0
14         NaN        0
15         NaN        0
18         NaN        0
19         NaN        0
20         NaN        0
21         NaN        0
22         NaN        0
23         NaN        0

In [103]:
# Inspecting Fence without values
dataset['Fence'].value_counts(dropna=False)

Fence
NaN      1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

In [104]:
# Inspecting Fence without values
dataset['Alley'].value_counts(dropna=False)

Alley
NaN     1369
Grvl      50
Pave      41
Name: count, dtype: int64

In [105]:
absent_features = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCond', 'GarageQual', 'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtFinType1', 'BsmtQual']

In [106]:
missing[missing >0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
Electrical         1
dtype: int64

In [107]:
# Investigating Pool
dataset.groupby('PoolQC', dropna=False)['SalePrice'].mean()

PoolQC
Ex     490000.000000
Fa     215500.000000
Gd     201990.000000
NaN    180404.663455
Name: SalePrice, dtype: float64

In [108]:
# Investigating Garage
dataset.groupby('GarageType', dropna=False)['SalePrice'].agg(['count', 'mean'])

            count           mean
GarageType
2Types          6  151283.333333
Attchd        870  202892.656322
Basment        19  160570.684211
BuiltIn        88  254751.738636
CarPort         9  109962.111111
Detchd        387  134091.162791
NaN            81  103317.283951

In [109]:
dataset[dataset['GarageType'].isnull()][['GarageArea', 'GarageCars', 'GarageYrBlt']].head(20)

     GarageArea  GarageCars  GarageYrBlt
39            0           0          NaN
48            0           0          NaN
78            0           0          NaN
88            0           0          NaN
89            0           0          NaN
99            0           0          NaN
108           0           0          NaN
125           0           0          NaN
127           0           0          NaN
140           0           0          NaN
148           0           0          NaN
155           0           0          NaN
163           0           0          NaN
165           0           0          NaN
198           0           0          NaN
210           0           0          NaN
241           0           0          NaN
250           0           0          NaN
287           0           0          NaN
291           0           0          NaN

In [110]:
absent_features = dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)
absent_features[absent_features > 0]

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageCond        81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtFinType1      37
BsmtQual          37
Electrical         1
dtype: int64

In [111]:
dataset[dataset['Electrical'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1379,1380,80,RL,73.0,9735,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500

In [112]:
dataset['Electrical'].value_counts()

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

In [113]:
dataset.loc[1379, ['Electrical', 'OverallQual', 'YearBuilt', 'YearRemodAdd',
                   'Neighborhood', 'HouseStyle', 'CentralAir']]

Electrical         NaN
OverallQual          5
YearBuilt         2006
YearRemodAdd      2007
Neighborhood    Timber
HouseStyle        SLvl
CentralAir           Y
Name: 1379, dtype: object

In [114]:
dataset[dataset['Neighborhood'] == 'Timber']['Electrical'].value_counts()

Electrical
SBrkr    36
FuseA     1
Name: count, dtype: int64

In [115]:
dataset[dataset['YearBuilt'] >= 2000]['Electrical'].value_counts()

Electrical
SBrkr    387
Name: count, dtype: int64

In [116]:
dataset[
    (dataset['Neighborhood'] == 'Timber') & 
    (dataset['YearBuilt'] >= 2000) & 
    (dataset['HouseStyle'] == 'SLvl')]['Electrical'].value_counts(dropna=False)

Electrical
SBrkr    1
NaN      1
Name: count, dtype: int64

In [117]:
dataset[dataset['Neighborhood'] == 'Timber'][['Electrical', 'SalePrice']].sort_values('SalePrice')

     Electrical  SalePrice
944       FuseA     137500
1396      SBrkr     160000
1379        NaN     167500
41        SBrkr     170000
429       SBrkr     175000
530       SBrkr     175000
695       SBrkr     176000
1281      SBrkr     180000
174       SBrkr     184000
1184      SBrkr     186700
881       SBrkr     187500
731       SBrkr     187500
930       SBrkr     201000
340       SBrkr     202900
452       SBrkr     204000
964       SBrkr     214900
133       SBrkr     220000
572       SBrkr     224500
169       SBrkr     228000
335       SBrkr     228950
1375      SBrkr     239000
866       SBrkr     248900
1180      SBrkr     250000
1239      SBrkr     265900
157       SBrkr     269500
947       SBrkr     270000
1395      SBrkr     281213
1347      SBrkr     283463
1024      SBrkr     287000
1027      SBrkr     293077
619       SBrkr     305000
700       SBrkr     312500
540       SBrkr     315000
1036      SBrkr     315500
692       SBrkr     335000
585       SBrkr     369900
313       SBrkr     375000
1267      SBrkr     378500

In [118]:
dataset.loc[1379, ['Electrical']] = 'SBrkr'

In [119]:
dataset.loc[1379, ['Electrical']]

Electrical    SBrkr
Name: 1379, dtype: str

In [120]:
dataset['Electrical'].isnull().sum()

np.int64(0)

In [121]:
absent_features = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCond', 'GarageQual', 'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtFinType1', 'BsmtQual']

In [122]:
missing_values_without_zeros = dataset.isnull().sum()
missing_values_without_zeros[missing_values_without_zeros > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
dtype: int64

In [123]:
dataset[absent_features].dtypes

PoolQC              str
MiscFeature         str
Alley               str
Fence               str
FireplaceQu         str
GarageType          str
GarageYrBlt     float64
GarageFinish        str
GarageCond          str
GarageQual          str
BsmtFinType2        str
BsmtExposure        str
BsmtCond            str
BsmtFinType1        str
BsmtQual            str
dtype: object

In [124]:
dataset['BsmtQual'] = dataset['BsmtQual'].fillna('None')

In [125]:
dataset['BsmtQual'].isnull().value_counts(dropna=False)

BsmtQual
False    1460
Name: count, dtype: int64

In [126]:
dataset['BsmtQual'].value_counts()

BsmtQual
TA      649
Gd      618
Ex      121
None     37
Fa       35
Name: count, dtype: int64

In [127]:
dataset['BsmtFinType1'] = dataset['BsmtFinType1'].fillna('None')

In [128]:
dataset['BsmtFinType1'].isnull().value_counts(dropna=False)

BsmtFinType1
False    1460
Name: count, dtype: int64

In [129]:
dataset['BsmtFinType1'].value_counts()

BsmtFinType1
Unf     430
GLQ     418
ALQ     220
BLQ     148
Rec     133
LwQ      74
None     37
Name: count, dtype: int64

In [130]:
dataset['BsmtCond'] = dataset['BsmtCond'].fillna('None')

In [131]:
dataset['BsmtCond'].isnull().value_counts(dropna=False)

BsmtCond
False    1460
Name: count, dtype: int64

In [132]:
dataset['BsmtCond'].value_counts()

BsmtCond
TA      1311
Gd        65
Fa        45
None      37
Po         2
Name: count, dtype: int64

In [133]:
dataset['BsmtExposure'] = dataset['BsmtExposure'].fillna('None')

In [134]:
dataset['BsmtExposure'].isnull().value_counts(dropna=False)

BsmtExposure
False    1460
Name: count, dtype: int64

In [135]:
dataset['BsmtExposure'].value_counts()

BsmtExposure
No      953
Av      221
Gd      134
Mn      114
None     38
Name: count, dtype: int64

In [136]:
dataset['BsmtFinType2'] = dataset['BsmtFinType2'].fillna('None')

In [137]:
dataset['BsmtFinType2'].isnull().value_counts(dropna=False)

BsmtFinType2
False    1460
Name: count, dtype: int64

In [138]:
dataset['BsmtFinType2'].value_counts()

BsmtFinType2
Unf     1256
Rec       54
LwQ       46
None      38
BLQ       33
ALQ       19
GLQ       14
Name: count, dtype: int64

In [139]:
dataset['GarageQual'] = dataset['GarageQual'].fillna('None')

In [140]:
dataset['GarageQual'].isnull().value_counts(dropna=False)

GarageQual
False    1460
Name: count, dtype: int64

In [141]:
dataset['GarageQual'].value_counts()

GarageQual
TA      1311
None      81
Fa        48
Gd        14
Ex         3
Po         3
Name: count, dtype: int64

In [142]:
dataset['GarageCond'] = dataset['GarageCond'].fillna('None')

In [143]:
dataset['GarageCond'].isnull().value_counts(dropna=False)

GarageCond
False    1460
Name: count, dtype: int64

In [144]:
dataset['GarageCond'].value_counts()

GarageCond
TA      1326
None      81
Fa        35
Gd         9
Po         7
Ex         2
Name: count, dtype: int64

In [145]:
dataset['GarageFinish'] = dataset['GarageFinish'].fillna('None')

In [146]:
dataset['GarageFinish'].isnull().value_counts(dropna=False)

GarageFinish
False    1460
Name: count, dtype: int64

In [147]:
dataset['GarageFinish'].value_counts()

GarageFinish
Unf     605
RFn     422
Fin     352
None     81
Name: count, dtype: int64

In [148]:
dataset['GarageYrBlt'] = dataset['GarageYrBlt'].fillna(0)

In [149]:
dataset['GarageYrBlt'].isnull().value_counts(dropna=False)

GarageYrBlt
False    1460
Name: count, dtype: int64

In [150]:
dataset['GarageYrBlt'].value_counts()

GarageYrBlt
0.0       81
2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
1977.0    35
1998.0    31
1999.0    30
1976.0    29
2008.0    29
2000.0    27
2002.0    26
1968.0    26
1950.0    24
1993.0    22
1965.0    21
1962.0    21
1958.0    21
1966.0    21
2009.0    21
2001.0    20
1970.0    20
1957.0    20
1996.0    20
1960.0    19
1954.0    19
1997.0    19
1978.0    19
1995.0    18
1964.0    18
1974.0    18
1994.0    18
1959.0    17
1963.0    16
1990.0    16
1956.0    16
1967.0    15
1979.0    15
1969.0    15
1980.0    15
1973.0    14
1920.0    14
1988.0    14
1972.0    14
1940.0    14
1961.0    13
1971.0    13
1955.0    13
1992.0    13
1953.0    12
1987.0    11
1948.0    11
1985.0    10
1981.0    10
1989.0    10
1925.0    10
1941.0    10
1939.0     9
1991.0     9
1975.0     9
1930.0     8
1984.0     8
1949.0     8
1983.0     7
1951.0     6
1926.0     6
1986.0     6
1936.0     5
1916.0     5
1922.0     5
1931.0     4
1935.0     4
1945.0     4
1982.0     4
1928.0     4
1946.0     4
1921.0     3
1923.0     3
1932.0     3
1924.0     3
1910.0     3
2010.0     3
1938.0     3
1952.0     3
1915.0     2
1918.0     2
1947.0     2
1937.0     2
1942.0     2
1934.0     2
1914.0     2
1929.0     2
1900.0     1
1927.0     1
1906.0     1
1908.0     1
1933.0     1
Name: count, dtype: int64

In [151]:
dataset['GarageType'] = dataset['GarageType'].fillna('None')

In [152]:
dataset['GarageType'].isnull().value_counts(dropna=False)

GarageType
False    1460
Name: count, dtype: int64

In [153]:
dataset['GarageType'].value_counts()

GarageType
Attchd     870
Detchd     387
BuiltIn     88
None        81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

In [154]:
dataset['FireplaceQu'] = dataset['FireplaceQu'].fillna('None')

In [155]:
dataset['FireplaceQu'].isnull().value_counts(dropna=False)

FireplaceQu
False    1460
Name: count, dtype: int64

In [156]:
dataset['FireplaceQu'].value_counts()

FireplaceQu
None    690
Gd      380
TA      313
Fa       33
Ex       24
Po       20
Name: count, dtype: int64

In [157]:
dataset['Fence'] = dataset['Fence'].fillna('None')

In [158]:
dataset['Fence'].isnull().value_counts(dropna=False)

Fence
False    1460
Name: count, dtype: int64

In [159]:
dataset['Fence'].value_counts()

Fence
None     1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

In [160]:
dataset['MiscFeature'] = dataset['MiscFeature'].fillna('None')

In [161]:
dataset['MiscFeature'].isnull().value_counts(dropna=False)

MiscFeature
False    1460
Name: count, dtype: int64

In [162]:
dataset['MiscFeature'].value_counts()

MiscFeature
None    1406
Shed      49
Gar2       2
Othr       2
TenC       1
Name: count, dtype: int64

In [163]:
dataset['Alley'] = dataset['Alley'].fillna('None')

In [164]:
dataset['Alley'].isnull().value_counts(dropna=False)

Alley
False    1460
Name: count, dtype: int64

In [165]:
dataset['Alley'].value_counts()

Alley
None    1369
Grvl      50
Pave      41
Name: count, dtype: int64

In [166]:
dataset['PoolQC'] = dataset['PoolQC'].fillna('None')

In [167]:
dataset['PoolQC'].isnull().value_counts(dropna=False)

PoolQC
False    1460
Name: count, dtype: int64

In [168]:
dataset['PoolQC'].value_counts()

PoolQC
None    1453
Gd         3
Ex         2
Fa         2
Name: count, dtype: int64

In [169]:
dataset['BsmtQual'] = dataset['BsmtQual'].fillna('None')

In [170]:
dataset['BsmtQual'].isnull().value_counts(dropna=False)

BsmtQual
False    1460
Name: count, dtype: int64

In [171]:
dataset['BsmtQual'].value_counts()

BsmtQual
TA      649
Gd      618
Ex      121
None     37
Fa       35
Name: count, dtype: int64

In [172]:
dataset.isnull().sum().sort_values(ascending=False)

LotFrontage      259
Id                 0
BedroomAbvGr       0
GarageYrBlt        0
GarageType         0
FireplaceQu        0
Fireplaces         0
Functional         0
TotRmsAbvGrd       0
KitchenQual        0
KitchenAbvGr       0
HalfBath           0
GarageCars         0
FullBath           0
BsmtHalfBath       0
BsmtFullBath       0
GrLivArea          0
LowQualFinSF       0
2ndFlrSF           0
1stFlrSF           0
GarageFinish       0
GarageArea         0
CentralAir         0
PoolQC             0
SaleCondition      0
SaleType           0
YrSold             0
MoSold             0
MiscVal            0
MiscFeature        0
Fence              0
PoolArea           0
GarageQual         0
ScreenPorch        0
3SsnPorch          0
EnclosedPorch      0
OpenPorchSF        0
WoodDeckSF         0
PavedDrive         0
GarageCond         0
Electrical         0
HeatingQC          0
MSSubClass         0
LandSlope          0
OverallCond        0
OverallQual        0
HouseStyle         0
BldgType           0
Condition2         0
Condition1         0
Neighborhood       0
LotConfig          0
YearRemodAdd       0
Utilities          0
LandContour        0
LotShape           0
Alley              0
Street             0
LotArea            0
MSZoning           0
YearBuilt          0
RoofStyle          0
Heating            0
BsmtCond           0
TotalBsmtSF        0
BsmtUnfSF          0
BsmtFinSF2         0
BsmtFinType2       0
BsmtFinSF1         0
BsmtFinType1       0
BsmtExposure       0
BsmtQual           0
RoofMatl           0
Foundation         0
ExterCond          0
ExterQual          0
MasVnrArea         0
MasVnrType         0
Exterior2nd        0
Exterior1st        0
SalePrice          0
dtype: int64

In [173]:
dataset.groupby('Neighborhood')['LotFrontage'].agg(['count', 'mean', 'median', 'min', 'max'])

              count       mean  median   min    max
Neighborhood
Blmngtn          14  47.142857    43.0  43.0   53.0
Blueste           2  24.000000    24.0  24.0   24.0
BrDale           16  21.562500    21.0  21.0   24.0
BrkSide          51  57.509804    52.0  50.0  144.0
ClearCr          13  83.461538    80.0  62.0  138.0
CollgCr         126  71.682540    70.0  36.0  122.0
Crawfor          41  71.804878    74.0  40.0  130.0
Edwards          92  68.217391    65.5  24.0  313.0
Gilbert          49  79.877551    65.0  42.0  182.0
IDOTRR           34  62.500000    60.0  40.0  120.0
MeadowV          15  27.800000    21.0  21.0   44.0
Mitchel          36  70.083333    73.0  32.0  129.0
NAmes           186  76.462366    73.0  34.0  313.0
NPkVill           7  32.285714    24.0  24.0   53.0
NWAmes           45  81.288889    80.0  46.0  105.0
NoRidge          33  91.878788    91.0  52.0  174.0
NridgHt          76  81.881579    88.5  34.0  129.0
OldTown         109  62.788991    60.0  30.0  153.0
SWISU            23  58.913043    60.0  50.0  102.0
Sawyer           48  74.437500    71.0  40.0  115.0
SawyerW          50  71.500000    66.5  50.0  116.0
Somerst          78  64.666667    73.5  24.0  116.0
StoneBr          20  62.700000    61.5  39.0  124.0
Timber           30  80.133333    85.0  42.0  150.0
Veenker           7  59.714286    68.0  30.0   90.0

In [174]:
dataset['NeighborhoodMedian'] = dataset.groupby('Neighborhood')['LotFrontage'].transform('median')

In [175]:
dataset[['Neighborhood', 'LotFrontage', 'NeighborhoodMedian']].head(20)

   Neighborhood  LotFrontage  NeighborhoodMedian
0       CollgCr         65.0                70.0
1       Veenker         80.0                68.0
2       CollgCr         68.0                70.0
3       Crawfor         60.0                74.0
4       NoRidge         84.0                91.0
5       Mitchel         85.0                73.0
6       Somerst         75.0                73.5
7        NWAmes          NaN                80.0
8       OldTown         51.0                60.0
9       BrkSide         50.0                52.0
10       Sawyer         70.0                71.0
11      NridgHt         85.0                88.5
12       Sawyer          NaN                71.0
13      CollgCr         91.0                70.0
14        NAmes          NaN                73.0
15      BrkSide         51.0                52.0
16        NAmes          NaN                73.0
17       Sawyer         72.0                71.0
18      SawyerW         66.0                66.5
19        NAmes         70.0                73.0

In [176]:
dataset[dataset['LotFrontage'].isnull()][['Neighborhood', 'LotFrontage', 'NeighborhoodMedian']].head(20)

    Neighborhood  LotFrontage  NeighborhoodMedian
7         NWAmes          NaN                80.0
12        Sawyer          NaN                71.0
14         NAmes          NaN                73.0
16         NAmes          NaN                73.0
24        Sawyer          NaN                71.0
31        Sawyer          NaN                71.0
42       SawyerW          NaN                66.5
43       CollgCr          NaN                70.0
50       Gilbert          NaN                65.0
64       CollgCr          NaN                70.0
66         NAmes          NaN                73.0
76         NAmes          NaN                73.0
84       Gilbert          NaN                65.0
95       Gilbert          NaN                65.0
100       NWAmes          NaN                80.0
104       IDOTRR          NaN                60.0
111      Gilbert          NaN                65.0
113      Crawfor          NaN                74.0
116       Sawyer          NaN                71.0
120      ClearCr          NaN                80.0

In [177]:
dataset['LotFrontage'] = dataset['LotFrontage'].fillna(dataset['NeighborhoodMedian'])

In [178]:
dataset['LotFrontage'].isnull().sum()

np.int64(0)

In [179]:
dataset = dataset.drop('NeighborhoodMedian', axis=1)

In [180]:
'NeighborhoodMedian' in dataset.columns

False

In [181]:
dataset.loc[[7, 12, 14], ['Neighborhood',	'LotFrontage']]

   Neighborhood  LotFrontage
7        NWAmes         80.0
12       Sawyer         71.0
14        NAmes         73.0

In [182]:
dataset.isnull().sum().sort_values(ascending=False)

Id               0
CentralAir       0
GarageYrBlt      0
GarageType       0
FireplaceQu      0
Fireplaces       0
Functional       0
TotRmsAbvGrd     0
KitchenQual      0
KitchenAbvGr     0
BedroomAbvGr     0
HalfBath         0
FullBath         0
BsmtHalfBath     0
BsmtFullBath     0
GrLivArea        0
LowQualFinSF     0
2ndFlrSF         0
1stFlrSF         0
GarageFinish     0
GarageCars       0
GarageArea       0
PoolQC           0
SaleCondition    0
SaleType         0
YrSold           0
MoSold           0
MiscVal          0
MiscFeature      0
Fence            0
PoolArea         0
GarageQual       0
ScreenPorch      0
3SsnPorch        0
EnclosedPorch    0
OpenPorchSF      0
WoodDeckSF       0
PavedDrive       0
GarageCond       0
Electrical       0
HeatingQC        0
MSSubClass       0
Heating          0
OverallCond      0
OverallQual      0
HouseStyle       0
BldgType         0
Condition2       0
Condition1       0
Neighborhood     0
LandSlope        0
LotConfig        0
Utilities        0
LandContour      0
LotShape         0
Alley            0
Street           0
LotArea          0
LotFrontage      0
MSZoning         0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
BsmtCond         0
TotalBsmtSF      0
BsmtUnfSF        0
BsmtFinSF2       0
BsmtFinType2     0
BsmtFinSF1       0
BsmtFinType1     0
BsmtExposure     0
BsmtQual         0
RoofMatl         0
Foundation       0
ExterCond        0
ExterQual        0
MasVnrArea       0
MasVnrType       0
Exterior2nd      0
Exterior1st      0
SalePrice        0
dtype: int64

In [183]:
missing_values = dataset.isnull().sum()
missing_values[missing_values > 0].sum()

np.int64(0)

In [184]:
dataset[['Id', 'SalePrice']].head(20)

    Id  SalePrice
0    1     208500
1    2     181500
2    3     223500
3    4     140000
4    5     250000
5    6     143000
6    7     307000
7    8     200000
8    9     129900
9   10     118000
10  11     129500
11  12     345000
12  13     144000
13  14     279500
14  15     157000
15  16     132000
16  17     149000
17  18      90000
18  19     159000
19  20     139000

In [185]:
dataset['Id'].nunique()

1460

In [186]:
dataset[['Id', 'SalePrice']].corr()

                 Id  SalePrice
Id         1.000000  -0.021917
SalePrice -0.021917   1.000000

In [187]:
dataset = dataset.drop('Id', axis=1)

In [188]:
dataset

      MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0             60       RL         65.0     8450   Pave  None      Reg
1             20       RL         80.0     9600   Pave  None      Reg
2             60       RL         68.0    11250   Pave  None      IR1
3             70       RL         60.0     9550   Pave  None      IR1
4             60       RL         84.0    14260   Pave  None      IR1
5             50       RL         85.0    14115   Pave  None      IR1
6             20       RL         75.0    10084   Pave  None      Reg
7             60       RL         80.0    10382   Pave  None      IR1
8             50       RM         51.0     6120   Pave  None      Reg
9            190       RL         50.0     7420   Pave  None      Reg
10            20       RL         70.0    11200   Pave  None      Reg
11            60       RL         85.0    11924   Pave  None      IR1
12            20       RL         71.0    12968   Pave  None      IR2
13            20       RL         91.0    10652   Pave  None      IR1
14            20       RL         73.0    10920   Pave  None      IR1
15            45       RM         51.0     6120   Pave  None      Reg
16            20       RL         73.0    11241   Pave  None      IR1
17            90       RL         72.0    10791   Pave  None      Reg
18            20       RL         66.0    13695   Pave  None      Reg
19            20       RL         70.0     7560   Pave  None      Reg
20            60       RL        101.0    14215   Pave  None      IR1
21            45       RM         57.0     7449   Pave  Grvl      Reg
22            20       RL         75.0     9742   Pave  None      Reg
23           120       RM         44.0     4224   Pave  None      Reg
24            20       RL         71.0     8246   Pave  None      IR1
25            20       RL        110.0    14230   Pave  None      Reg
26            20       RL         60.0     7200   Pave  None      Reg
27            20       RL         98.0    11478   Pave  None      Reg
28            20       RL         47.0    16321   Pave  None      IR1
29            30       RM         60.0     6324   Pave  None      IR1
30            70  C (all)         50.0     8500   Pave  Pave      Reg
31            20       RL         71.0     8544   Pave  None      IR1
32            20       RL         85.0    11049   Pave  None      Reg
33            20       RL         70.0    10552   Pave  None      IR1
34           120       RL         60.0     7313   Pave  None      Reg
35            60       RL        108.0    13418   Pave  None      Reg
36            20       RL        112.0    10859   Pave  None      Reg
37            20       RL         74.0     8532   Pave  None      Reg
38            20       RL         68.0     7922   Pave  None      Reg
39            90       RL         65.0     6040   Pave  None      Reg
40            20       RL         84.0     8658   Pave  None      Reg
41            20       RL        115.0    16905   Pave  None      Reg
42            85       RL         66.5     9180   Pave  None      IR1
43            20       RL         70.0     9200   Pave  None      IR1
44            20       RL         70.0     7945   Pave  None      Reg
45           120       RL         61.0     7658   Pave  None      Reg
46            50       RL         48.0    12822   Pave  None      IR1
47            20       FV         84.0    11096   Pave  None      Reg
48           190       RM         33.0     4456   Pave  None      Reg
49            20       RL         66.0     7742   Pave  None      Reg
50            60       RL         65.0    13869   Pave  None      IR2
51            50       RM         52.0     6240   Pave  None      Reg
52            90       RM        110.0     8472   Grvl  None      IR2
53            20       RL         68.0    50271   Pave  None      IR1
54            80       RL         60.0     7134   Pave  None      Reg
55            20       RL        100.0    10175   Pave  None      IR1
56           160       FV         24.0     2645   Pave  Pave      Reg
57            60       RL         89.0    11645   Pave  None      IR1
58            60       RL         66.0    13682   Pave  None      IR2
59            20       RL         60.0     7200   Pave  None      Reg
60            20       RL         63.0    13072   Pave  None      Reg
61            75       RM         60.0     7200   Pave  None      Reg
62           120       RL         44.0     6442   Pave  None      IR1
63            70       RM         50.0    10300   Pave  None      IR1
64            60       RL         70.0     9375   Pave  None      Reg
65            60       RL         76.0     9591   Pave  None      Reg
66            20       RL         73.0    19900   Pave  None      Reg
67            20       RL         72.0    10665   Pave  None      IR1
68            30       RM         47.0     4608   Pave  None      Reg
69            50       RL         81.0    15593   Pave  None      Reg
70            20       RL         95.0    13651   Pave  None      IR1
71            20       RL         69.0     7599   Pave  None      Reg
72            60       RL         74.0    10141   Pave  None      IR1
73            20       RL         85.0    10200   Pave  None      Reg
74            50       RM         60.0     5790   Pave  None      Reg
75           180       RM         21.0     1596   Pave  None      Reg
76            20       RL         73.0     8475   Pave  None      IR1
77            50       RM         50.0     8635   Pave  None      Reg
78            90       RL         72.0    10778   Pave  None      Reg
79            50       RM         60.0    10440   Pave  Grvl      Reg
80            60       RL        100.0    13000   Pave  None      Reg
81           120       RM         32.0     4500   Pave  None      Reg
82            20       RL         78.0    10206   Pave  None      Reg
83            20       RL         80.0     8892   Pave  None      IR1
84            80       RL         65.0     8530   Pave  None      IR1
85            60       RL        121.0    16059   Pave  None      Reg
86            60       RL        122.0    11911   Pave  None      IR2
87           160       FV         40.0     3951   Pave  Pave      Reg
88            50  C (all)        105.0     8470   Pave  None      IR1
89            20       RL         60.0     8070   Pave  None      Reg
90            20       RL         60.0     7200   Pave  None      Reg
91            20       RL         85.0     8500   Pave  None      Reg
92            30       RL         80.0    13360   Pave  Grvl      IR1
93           190  C (all)         60.0     7200   Pave  None      Reg
94            60       RL         69.0     9337   Pave  None      IR1
95            60       RL         65.0     9765   Pave  None      IR2
96            20       RL         78.0    10264   Pave  None      IR1
97            20       RL         73.0    10921   Pave  None      Reg
98            30       RL         85.0    10625   Pave  None      Reg
99            20       RL         77.0     9320   Pave  None      IR1
100           20       RL         80.0    10603   Pave  None      IR1
101           60       RL         77.0     9206   Pave  None      Reg
102           90       RL         64.0     7018   Pave  None      Reg
103           20       RL         94.0    10402   Pave  None      IR1
104           50       RM         60.0     7758   Pave  None      Reg
105           60       FV         75.0     9375   Pave  None      Reg
106           30       RM         60.0    10800   Pave  Grvl      Reg
107           20       RM         50.0     6000   Pave  None      Reg
108           50       RM         85.0     8500   Pave  None      Reg
109           20       RL        105.0    11751   Pave  None      IR1
110           50       RL         75.0     9525   Pave  None      Reg
111           80       RL         65.0     7750   Pave  None      IR1
112           60       RL         77.0     9965   Pave  None      Reg
113           20       RL         74.0    21000   Pave  None      Reg
114           70       RL         61.0     7259   Pave  None      IR1
115          160       FV         34.0     3230   Pave  Pave      Reg
116           20       RL         71.0    11616   Pave  None      Reg
117           20       RL         74.0     8536   Pave  None      Reg
118           60       RL         90.0    12376   Pave  None      Reg
119           60       RL         65.0     8461   Pave  None      Reg
120           80       RL         80.0    21453   Pave  None      IR1
121           50       RM         50.0     6060   Pave  None      Reg
122           20       RL         75.0     9464   Pave  None      Reg
123          120       RL         55.0     7892   Pave  None      Reg
124           20       RL         48.0    17043   Pave  None      IR1
125          190       RM         60.0     6780   Pave  None      Reg
126          120       RL         24.0     4928   Pave  None      IR1
127           45       RM         55.0     4388   Pave  None      IR1
128           60       RL         69.0     7590   Pave  None      Reg
129           20       RL         69.0     8973   Pave  None      Reg
130           60       RL         88.0    14200   Pave  None      Reg
131           60       RL         65.0    12224   Pave  None      IR1
132           20       RL         75.0     7388   Pave  None      Reg
133           20       RL         85.0     6853   Pave  None      IR1
134           20       RL         78.0    10335   Pave  None      IR1
135           20       RL         80.0    10400   Pave  None      Reg
136           20       RL         73.0    10355   Pave  None      IR1
137           90       RL         82.0    11070   Pave  None      Reg
138           60       RL         73.0     9066   Pave  None      IR1
139           60       RL         65.0    15426   Pave  None      IR1
140           20       RL         70.0    10500   Pave  None      Reg
141           20       RL         78.0    11645   Pave  None      Reg
142           50       RL         71.0     8520   Pave  None      Reg
143           20       RL         78.0    10335   Pave  None      IR1
144           90       RM         70.0     9100   Pave  None      Reg
145          160       RM         24.0     2522   Pave  None      Reg
146           30       RM         51.0     6120   Pave  None      Reg
147           60       RL         65.0     9505   Pave  None      IR1
148           20       RL         63.0     7500   Pave  None      Reg
149           50       RM         52.0     6240   Pave  None      Reg
150           20       RL        120.0    10356   Pave  None      Reg
151           20       RL        107.0    13891   Pave  None      Reg
152           60       RL         80.0    14803   Pave  None      IR1
153           20       RL         80.0    13500   Pave  None      Reg
154           30       RM         84.0    11340   Pave  None      Reg
155           50       RL         60.0     9600   Pave  None      Reg
156           20       RL         60.0     7200   Pave  None      Reg
157           60       RL         92.0    12003   Pave  None      Reg
158           60       FV        100.0    12552   Pave  None      Reg
159           60       RL        134.0    19378   Pave  None      IR1
160           20       RL         68.0    11120   Pave  None      IR1
161           60       RL        110.0    13688   Pave  None      IR1
162           20       RL         95.0    12182   Pave  None      Reg
163           45       RL         55.0     5500   Pave  None      Reg
164           40       RM         40.0     5400   Pave  Pave      Reg
165          190       RL         62.0    10106   Pave  None      Reg
166           20       RL         80.0    10708   Pave  None      IR1
167           60       RL         86.0    10562   Pave  None      Reg
168           60       RL         62.0     8244   Pave  None      IR1
169           20       RL         85.0    16669   Pave  None      IR1
170           50       RM         60.0    12358   Pave  None      IR1
171           20       RL        141.0    31770   Pave  None      IR1
172          160       RL         44.0     5306   Pave  None      IR1
173           20       RL         80.0    10197   Pave  None      IR1
174           20       RL         47.0    12416   Pave  None      IR1
175           20       RL         84.0    12615   Pave  None      Reg
176           60       RL         97.0    10029   Pave  None      IR1
177           50       RL         71.0    13650   Pave  None      Reg
178           20       RL         63.0    17423   Pave  None      IR1
179           30       RM         60.0     8520   Pave  None      Reg
180          160       FV         73.5     2117   Pave  None      Reg
181           70       RL         54.0     7588   Pave  None      Reg
182           20       RL         60.0     9060   Pave  None      Reg
183           50       RM         63.0    11426   Pave  None      Reg
184           50       RL         92.0     7438   Pave  None      IR1
185           75       RM         90.0    22950   Pave  None      IR2
186           80       RL         73.0     9947   Pave  None      IR1
187           50       RL         60.0    10410   Pave  None      Reg
188           90       RL         64.0     7018   Pave  None      Reg
189          120       RL         41.0     4923   Pave  None      Reg
190           70       RL         70.0    10570   Pave  None      Reg
191           60       RL         73.0     7472   Pave  None      IR1
192           20       RL         68.0     9017   Pave  None      IR1
193          160       RM         24.0     2522   Pave  None      Reg
194           20       RL         60.0     7180   Pave  None      IR1
195          160       RL         24.0     2280   Pave  None      Reg
196           20       RL         79.0     9416   Pave  None      Reg
197           75       RL        174.0    25419   Pave  None      Reg
198           75       RM         92.0     5520   Pave  None      Reg
199           20       RL         76.0     9591   Pave  None      Reg
200           20       RM         80.0     8546   Pave  None      Reg
201           20       RL         75.0    10125   Pave  None      Reg
202           50       RL         50.0     7000   Pave  None      Reg
203          120       RM         70.0     4438   Pave  None      Reg
204           50       RM         50.0     3500   Pave  Grvl      Reg
205           20       RL         99.0    11851   Pave  None      Reg
206           20       RL         40.0    13673   Pave  None      IR1
207           20       RL         73.0    12493   Pave  None      IR1
208           60       RL         66.5    14364   Pave  None      IR1
209           20       RL         75.0     8250   Pave  None      Reg
210           30       RL         67.0     5604   Pave  None      Reg
211           20       RL         83.0    10420   Pave  None      Reg
212           60       FV         72.0     8640   Pave  None      Reg
213           20       RL         43.0    13568   Pave  None      IR2
214           60       RL         70.0    10900   Pave  None      IR1
215           20       RL         72.0    10011   Pave  None      IR1
216           20       RL         65.0     8450   Pave  None      Reg
217           70       RM         57.0     9906   Pave  Grvl      Reg
218           50       RL         74.0    15660   Pave  None      IR1
219          120       RL         43.0     3010   Pave  None      Reg
220           20       RL         73.0     8990   Pave  None      IR1
221           60       RL         65.0     8068   Pave  None      IR1
222           60       RL         85.0    11475   Pave  None      Reg
223           20       RL         70.0    10500   Pave  None      Reg
224           20       RL        103.0    13472   Pave  None      Reg
225          160       RM         21.0     1680   Pave  None      Reg
226           60       RL         82.0     9950   Pave  None      IR1
227          160       RM         21.0     1869   Pave  None      Reg
228           20       RL         70.0     8521   Pave  None      Reg
229          120       RL         43.0     3182   Pave  None      Reg
230           20       RL         73.0     8760   Pave  None      Reg
231           60       RL        174.0    15138   Pave  None      IR1
232          160       RM         21.0     1680   Pave  None      Reg
233           20       RL         75.0    10650   Pave  None      Reg
234           60       RL         65.0     7851   Pave  None      Reg
235          160       RM         21.0     1680   Pave  None      Reg
236           20       RL         65.0     8773   Pave  None      Reg
237           60       RL         66.5     9453   Pave  None      IR1
238           20       RL         93.0    12030   Pave  None      Reg
239           50       RL         52.0     8741   Pave  None      Reg
240           20       FV         75.0     9000   Pave  None      Reg
241           30       RM         40.0     3880   Pave  None      Reg
242           50       RM         63.0     5000   Pave  None      Reg
243          160       RL         75.0    10762   Pave  None      Reg
244           60       RL         66.5     8880   Pave  None      IR1
245           20       RL         80.0    10400   Pave  None      Reg
246          190       RM         69.0     9142   Pave  Grvl      Reg
247           20       RL         75.0    11310   Pave  None      Reg
248           60       RL         72.0    11317   Pave  None      Reg
249           50       RL         80.0   159000   Pave  None      IR2
250           30       RL         55.0     5350   Pave  None      IR1
251          120       RM         44.0     4750   Pave  None      IR1
252           60       RL         65.0     8366   Pave  None      IR1
253           80       RL         85.0     9350   Pave  None      Reg
254           20       RL         70.0     8400   Pave  None      Reg
255           60       RL         66.0     8738   Pave  None      IR1
256           60       FV         64.0     8791   Pave  None      IR1
257           20       RL         68.0     8814   Pave  None      Reg
258           60       RL         80.0    12435   Pave  None      Reg
259           20       RM         70.0    12702   Pave  None      Reg
260           80       RL        120.0    19296   Pave  None      Reg
261           60       RL         69.0     9588   Pave  None      IR1
262           80       RL         88.0     8471   Pave  None      IR1
263           50       RM         50.0     5500   Pave  None      Reg
264           30       RM         30.0     5232   Pave  Grvl      IR3
265           20       RL         78.0    12090   Pave  None      IR1
266           60       RL         70.0    11207   Pave  None      IR1
267           75       RL         60.0     8400   Pave  None      Reg
268           30       RM         71.0     6900   Pave  None      Reg
269           20       RL         65.5     7917   Pave  None      IR1
270           60       FV         84.0    10728   Pave  None      Reg
271           20       RL         73.0    39104   Pave  None      IR1
272           60       RL         92.0    11764   Pave  None      IR1
273           20       RL         80.0     9600   Pave  None      Reg
274           20       RL         76.0     8314   Pave  None      Reg
275           50       RL         55.0     7264   Pave  None      Reg
276           20       RL        129.0     9196   Pave  None      IR1
277           20       RL        140.0    19138   Pave  None      Reg
278           20       RL        107.0    14450   Pave  None      Reg
279           60       RL         83.0    10005   Pave  None      Reg
280           60       RL         82.0    11287   Pave  None      Reg
281           20       FV         60.0     7200   Pave  Pave      Reg
282          120       RL         34.0     5063   Pave  None      Reg
283           20       RL         74.0     9612   Pave  None      Reg

In [189]:
categorical_features = dataset.select_dtypes(include='str').columns

In [190]:
categorical_features

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='str')

In [191]:
numerical_features = dataset.select_dtypes('number').columns

In [192]:
numerical_features

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SalePrice'],
      dtype='str')

In [193]:
dataset.groupby('HouseStyle')['SalePrice'].agg(['count', 'mean', 'median', 'max', 'min']).sort_values('mean', ascending=False)

            count           mean    median     max     min
HouseStyle
2.5Fin          8  220000.000000  194000.0  475000  104000
2Story        445  210051.764045  190000.0  755000   40000
1Story        726  175985.477961  154750.0  611657   34900
SLvl           65  166703.384615  164500.0  345000   91000
2.5Unf         11  157354.545455  133900.0  325000  101000
1.5Fin        154  143116.740260  132000.0  410000   37900
SFoyer         37  135074.486486  135960.0  206300   75500
1.5Unf         14  110150.000000  111250.0  139400   76000

In [194]:
house_style_mean = dataset.groupby('HouseStyle')['SalePrice'].mean()

In [195]:
house_style_mean.max() - house_style_mean.min()

np.float64(109850.0)

In [196]:
neighborhood_mean = dataset.groupby('Neighborhood')['SalePrice'].mean()

In [197]:
neighborhood_mean.max() - neighborhood_mean.min()

np.float64(236718.84648493544)

In [198]:
neighborhood_mean.sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [199]:
features_mean = {}
for feature in categorical_features:
    group_mean = (dataset.groupby(feature)['SalePrice'].mean())
    difference = group_mean.max() - group_mean.min()
    features_mean[feature] = difference

In [200]:
features_mean

{'MSZoning': np.float64(139486.06153846154),
 'Street': np.float64(50940.03851444292),
 'Alley': np.float64(61233.05148283417),
 'LotShape': np.float64(75078.54747528015),
 'LandContour': np.float64(88429.86063492062),
 'Utilities': np.float64(43450.95681973954),
 'LotConfig': np.float64(46916.569492759474),
 'LandSlope': np.float64(24422.431203384185),
 'Neighborhood': np.float64(236718.84648493544),
 'Condition1': np.float64(90783.33333333334),
 'Condition2': np.float64(228250.0),
 'BldgType': np.float64(57331.54931253304),
 'HouseStyle': np.float64(109850.0),
 'RoofStyle': np.float64(76090.90909090909),
 'RoofMatl': np.float64(253250.0),
 'Exterior1st': np.float64(191000.0),
 'Exterior2nd': np.float64(214000.0),
 'MasVnrType': np.float64(120156.5794871795),
 'ExterQual': np.float64(279375.7472527473),
 'ExterCond': np.float64(124833.33333333334),
 'Foundation': np.float64(117864.81704018547),
 'BsmtQual': np.float64(221388.14943042217),
 'BsmtCond': np.float64(149599.9076923077),
 'BsmtExposure': np.float64(149751.4638648861),
 'BsmtFinType1': np.float64(129760.82820380188),
 'BsmtFinType2': np.float64(99595.86842105263),
 'Heating': np.float64(109521.19537815126),
 'HeatingQC': np.float64(127914.42914979756),
 'CentralAir': np.float64(80922.63620589937),
 'Electrical': np.float64(119810.63745318353),
 'KitchenQual': np.float64(222989.46487179486),
 'Functional': np.float64(97629.14705882352),
 'FireplaceQu': np.float64(207948.35),
 'GarageType': np.float64(151434.45468574634),
 'GarageFinish': np.float64(136735.4063902918),
 'GarageQual': np.float64(140833.3333333333),
 'GarageCond': np.float64(84568.45134350036),
 'PavedDrive': np.float64(71394.85165837478),
 'PoolQC': np.float64(309595.33654507913),
 'Fence': np.float64(53310.474361939996),
 'MiscFeature': np.float64(156000.0),
 'SaleType': np.float64(155095.41803278687),
 'SaleCondition': np.float64(168166.75199999998)}

In [201]:
type(features_mean)

dict

In [202]:
pd.Series(features_mean).sort_values(ascending=False)

PoolQC           309595.336545
ExterQual        279375.747253
RoofMatl         253250.000000
Neighborhood     236718.846485
Condition2       228250.000000
KitchenQual      222989.464872
BsmtQual         221388.149430
Exterior2nd      214000.000000
FireplaceQu      207948.350000
Exterior1st      191000.000000
SaleCondition    168166.752000
MiscFeature      156000.000000
SaleType         155095.418033
GarageType       151434.454686
BsmtExposure     149751.463865
BsmtCond         149599.907692
GarageQual       140833.333333
MSZoning         139486.061538
GarageFinish     136735.406390
BsmtFinType1     129760.828204
HeatingQC        127914.429150
ExterCond        124833.333333
MasVnrType       120156.579487
Electrical       119810.637453
Foundation       117864.817040
HouseStyle       109850.000000
Heating          109521.195378
BsmtFinType2      99595.868421
Functional        97629.147059
Condition1        90783.333333
LandContour       88429.860635
GarageCond        84568.451344
CentralAir        80922.636206
RoofStyle         76090.909091
LotShape          75078.547475
PavedDrive        71394.851658
Alley             61233.051483
BldgType          57331.549313
Fence             53310.474362
Street            50940.038514
LotConfig         46916.569493
Utilities         43450.956820
LandSlope         24422.431203
dtype: float64

In [203]:
dataset.groupby('PoolQC')['SalePrice'].agg(['count', 'mean'])

        count           mean
PoolQC
Ex          2  490000.000000
Fa          2  215500.000000
Gd          3  201990.000000
None     1453  180404.663455

In [204]:
dataset.groupby('ExterQual')['SalePrice'].agg(['count', 'mean'])

           count           mean
ExterQual
Ex            52  367360.961538
Fa            14   87985.214286
Gd           488  231633.510246
TA           906  144341.313466

In [205]:
groups_lowest_counts = {}
for feature in categorical_features:
    lowest_count = dataset.groupby(feature).size().min()
    groups_lowest_counts[feature] = lowest_count

In [206]:
groups_lowest_counts

{'MSZoning': np.int64(10),
 'Street': np.int64(6),
 'Alley': np.int64(41),
 'LotShape': np.int64(10),
 'LandContour': np.int64(36),
 'Utilities': np.int64(1),
 'LotConfig': np.int64(4),
 'LandSlope': np.int64(13),
 'Neighborhood': np.int64(2),
 'Condition1': np.int64(2),
 'Condition2': np.int64(1),
 'BldgType': np.int64(31),
 'HouseStyle': np.int64(8),
 'RoofStyle': np.int64(2),
 'RoofMatl': np.int64(1),
 'Exterior1st': np.int64(1),
 'Exterior2nd': np.int64(1),
 'MasVnrType': np.int64(15),
 'ExterQual': np.int64(14),
 'ExterCond': np.int64(1),
 'Foundation': np.int64(3),
 'BsmtQual': np.int64(35),
 'BsmtCond': np.int64(2),
 'BsmtExposure': np.int64(38),
 'BsmtFinType1': np.int64(37),
 'BsmtFinType2': np.int64(14),
 'Heating': np.int64(1),
 'HeatingQC': np.int64(1),
 'CentralAir': np.int64(95),
 'Electrical': np.int64(1),
 'KitchenQual': np.int64(39),
 'Functional': np.int64(1),
 'FireplaceQu': np.int64(20),
 'GarageType': np.int64(6),
 'GarageFinish': np.int64(81),
 'GarageQual': np.int64(3),
 'GarageCond': np.int64(2),
 'PavedDrive': np.int64(30),
 'PoolQC': np.int64(2),
 'Fence': np.int64(11),
 'MiscFeature': np.int64(1),
 'SaleType': np.int64(2),
 'SaleCondition': np.int64(4)}

In [207]:
pd.Series(groups_lowest_counts).sort_values(ascending=False)

CentralAir       95
GarageFinish     81
Alley            41
KitchenQual      39
BsmtExposure     38
BsmtFinType1     37
LandContour      36
BsmtQual         35
BldgType         31
PavedDrive       30
FireplaceQu      20
MasVnrType       15
BsmtFinType2     14
ExterQual        14
LandSlope        13
Fence            11
MSZoning         10
LotShape         10
HouseStyle        8
Street            6
GarageType        6
SaleCondition     4
LotConfig         4
Foundation        3
GarageQual        3
Neighborhood      2
SaleType          2
PoolQC            2
GarageCond        2
Condition1        2
RoofStyle         2
BsmtCond          2
Exterior1st       1
Functional        1
Electrical        1
Condition2        1
HeatingQC         1
Heating           1
Utilities         1
RoofMatl          1
MiscFeature       1
ExterCond         1
Exterior2nd       1
dtype: int64

In [208]:
dataset.groupby('RoofMatl')['SalePrice'].agg(['count', 'mean']).sort_values('count')

          count           mean
RoofMatl
ClyTile       1  160000.000000
Membran       1  241500.000000
Metal         1  180000.000000
Roll          1  137000.000000
WdShake       5  241400.000000
WdShngl       6  390250.000000
Tar&Grv      11  185406.363636
CompShg    1434  179803.679219

In [209]:
dataset[dataset['ExterQual'] == 'Fa']['SalePrice'].sort_values()

533      39300
705      55000
812      55993
636      60000
375      61000
1061     81000
341      82000
1323     82500
88       85000
821      93000
1370    105000
52      110000
1266    122000
635     200000
Name: SalePrice, dtype: int64

In [210]:
groups = dataset.groupby('HouseStyle')['SalePrice']

In [211]:
group_sale_price = []
for group_name, sales_prices in groups:
    group_sale_price.append(sales_prices)

In [212]:
len(group_sale_price)

8

In [213]:
group_sale_price

[5       143000
 8       129900
 46      239686
 51      114500
 69      225000
 77      127000
 88       85000
 104     169500
 108     115000
 110     136900
 121     100000
 125      84500
 142     166000
 149     115000
 155      79000
 165     127500
 170     128500
 177     172500
 183     200000
 184     127000
 187     135000
 202     112000
 204     110000
 218     311500
 239     113000
 242      79000
 249     277000
 263     130000
 275     205000
 286     159000
 292     131000
 296     152000
 307      89500
 312     119900
 335     228950
 345     140200
 352      95000
 354     140000
 361     145000
 371     134432
 380     127000
 386      81000
 390     119000
 394     109000
 406     115000
 418     126000
 431      79900
 436     116000
 439     110000
 442     162900
 448     119500
 449     120000
 459     110000
 488     160000
 491     133000
 497     184000
 522     159000
 545     229000
 546     210000
 557     108000
 563     185000
 568     316600
 575     118500
 576     145000
 579     131500
 584     133000
 601     141000
 637      93000
 653     135000
 658      97500
 681     159434
 694     141500
 711     102776
 723     135000
 729     103000
 749      98000
 750      96500
 767     160000
 786     139000
 799     175000
 814     116000
 823     139500
 839     130500
 844     153900
 848     240000
 860     189950
 874      66500
 881     187500
 887     135500
 890     122900
 907     250000
 921     145900
 945     124900
 966     160000
 968      37900
 970     135000
 984     126000
 986     117000
 995     121600
 1009    102000
 1010    135000
 1022     87000
 1028    105000
 1059    220000
 1072     91500
 1076    170000
 1092    136500
 1098    128000
 1130    135000
 1136    119000
 1137     94000
 1144     80000
 1145    149000
 1148    116900
 1173    200500
 1175    285000
 1177    115000
 1178    154900
 1185    104900
 1192    125000
 1202    117000
 1211    164000
 1216    112000
 1218     80500
 1222    143000
 1230    190000
 1255    127500
 1262    161500
 1268    381000
 1269    144000
 1274    139000
 1279     68400
 1284    169000
 1285    132500
 1328    256000
 1333    125500
 1343    177000
 1352    134900
 1353    410000
 1362    104900
 1370    105000
 1377    117000
 1384    105000
 1385    125500
 1387    136000
 1389    131000
 1393    163000
 1398    138000
 1399    137450
 1400    120000
 1404    105000
 1411    140000
 1414    207000
 1427    140000
 Name: SalePrice, dtype: int64,
 9       118000
 15      132000
 21      139400
 127      87000
 163     103200
 325      87000
 383      76000
 437     119000
 514      96500
 555     113000
 617     105500
 826     109500
 1069    135000
 1443    121000
 Name: SalePrice, dtype: int64,
 1       181500
 6       307000
 10      129500
 12      144000
 13      279500
 14      157000
 16      149000
 17       90000
 18      159000
 19      139000
 22      230000
 23      129900
 24      154000
 25      256300
 26      134800
 27      306000
 28      207500
 29       68500
 31      149350
 32      179900
 33      165500
 34      277500
 36      145000
 37      153000
 38      109000
 39       82000
 40      160000
 41      170000
 43      130250
 44      141000
 45      319900
 47      249700
 49      127000
 52      110000
 53      385000
 55      180500
 59      124900
 60      158000
 62      202500
 66      180000
 67      226000
 68       80000
 70      244000
 71      129500
 73      144900
 76      135750
 78      136500
 81      153500
 82      245000
 83      126500
 89      123600
 90      109900
 91       98600
 92      163500
 96      214000
 97       94750
 98       83000
 99      128950
 100     205000
 102     118964
 103     198900
 106     100000
 107     115000
 109     190000
 113     217000
 116     139000
 117     155000
 122     136000
 123     153900
 124     181000
 126     128000
 129     150000
 132     150750
 133     220000
 134     180000
 135     174000
 136     143000
 137     171000
 140     115000
 141     260000
 143     204000
 144     125000
 146     105000
 148     141000
 150     122000
 151     372402
 153     235000
 154     125000
 156     109500
 160     162500
 162     220000
 164     152000
 166     190000
 169     228000
 171     215000
 173     163000
 174     184000
 175     243000
 178     501837
 179     100000
 182     120000
 189     286000
 192     192000
 194     127000
 196     311872
 199     274900
 200     140000
 201     171500
 203     149000
 205     180500
 206     143900
 207     141000
 209     145000
 210      98000
 211     186000
 213     156000
 215     134450
 216     210000
 219     167240
 220     204900
 223      97000
 224     386250
 228     125000
 229     192500
 230     148000
 233     128200
 236     185500
 238     318000
 240     262500
 241     110500
 245     241500
 247     140000
 250      76500
 251     235000
 254     145000
 257     220000
 259      97000
 264      73000
 265     175500
 268     120500
 269     148000
 271     241500
 273     139000
 274     124500
 276     201000
 277     141000
 278     415298
 281     185000
 282     207500
 283     244600
 284     179200
 287      88000
 288     122000
 294     167000
 299     158500
 300     157000
 302     205000
 303     149900
 305     305900
 308      82500
 309     360000
 311     132000
 313     375000
 323     126175
 326     324000
 327     145250
 330     119000
 331     139000
 332     284000
 333     207000
 336     377426
 337     214000
 338     202500
 339     155000
 341      82000
 342      87500
 343     266000
 346     151500
 347     157500
 350     318061
 351     190000
 353     105900
 355     177500
 356     173000
 357     134000
 366     159000
 368     132000
 369     162000
 372     125000
 373     123000
 375      61000
 378     394432
 381     187750
 385     192000
 388     191000
 392     106500
 393     100000
 395     129000
 396     123000
 398      67000
 400     245500
 401     164990
 402     108000
 405     150000
 410      60000
 411     145000
 412     222000
 413     115000
 415     181134
 419     142000
 421     215000
 422     113000
 424     139000
 427     109008
 428     195400
 429     175000
 438      90350
 440     555000
 441     118000
 443     172500
 445     127500
 446     190000
 450     110000
 451     280000
 454     188000
 455     175500
 457     256000
 462      62383
 464     124000
 465     178740
 466     167000
 468     250000
 470     212000
 473     440000
 474     251000
 475     132500
 476     208900
 478     297000
 479      89471
 480     326000
 481     374000
 483     164000
 484     132500
 485     147000
 486     156000
 487     175000
 493     155000
 494      91300
 495      34900
 496     430000
 498     130000
 499     120000
 502     140000
 503     289000
 507     208300
 509     124500
 510     164900
 511     202665
 512     129900
 513     134000
 515     402861
 521     150000
 525     176000
 526     132000
 528      86000
 529     200624
 532     107500
 533      39300
 537     111250
 538     158000
 539     272000
 540     315000
 542     213250
 548     125000
 550     140000
 551     112500
 552     255500
 553     108000
 556     141000
 559     234000
 560     121500
 561     170000
 562     108000
 567     214000
 570     142600
 571     120000
 580     181900
 581     253293
 585     369900
 586     130000
 588     143000
 589      79500
 592     138000
 593     140000
 594     110000
 595     319000
 597     194201
 598     217500
 604     221000
 606     152000
 609     118500
 613     147000
 618     314813
 620      67000
 622     135000
 625     160000
 626     139900
 631     209500
 632      82500
 633     139400
 636      60000
 638      85000
 639     264561
 640     274000
 644     370878
 645     143250
 646      98300
 647     155000
 654     350000
 656     145500
 659     167000
 662     110000
 664     423000
 667     193500
 668     168000
 669     137500
 672     165000
 673     257500
 674     140000
 677     109500
 678     372500
 679     128500
 680     143000
 682     173000
 683     285000
 688     392000
 689     194700
 690     141000
 693     108480
 695     176000
 696      89000
 697     123500
 698     138500
 699     196000
 700     312500
 701     140000
 704     213000
 706     302000
 707     254000
 709     109900
 710      52000
 712     189000
 713     129000
 715     165000
 717     157000
 719     128500
 720     275000
 721     143000
 722     124500
 724     320000
 725     120500
 726     222000
 727     194500
 728     110000
 730     236500
 733     131400
 734     108000
 736      93500
 738     179000
 741     142000
 742     179000
 744     180000
 748     260400
 752     217000
 754     156000
 760     127500
 761     100000
 764     270000
 765     264132
 768     216837
 771     102000
 773     114500
 774     395000
 775     162000
 776     221500
 777     142500
 778     144000
 780     176000
 782     187100
 785     161500
 788     107900
 790     160200
 793     225000
 796     143500
 797     110000
 801     109900
 804     118000
 805     227680
 810     181000
 811     144500
 812      55993
 813     157900
 815     224900
 816     137000
 817     271000
 819     224000
 821      93000
 824     232600
 825     385000
 827     189000
 830     166000
 833     167000
 834     139950
 835     128000
 836     153500
 838     144000
 843     141000
 847     133500
 850     131500
 851     215000
 854     170000
 855     127000
 858     152000
 861     131500
 862     152000
 863     132500
 864     250580
 865     148500
 866     248900
 867     129000
 870     109500
 872     116000
 873     133000
 876     132250
 879     136500
 880     157000
 884     100000
 885     328900
 886     145000
 888     268000
 889     149500
 892     154500
 893     165000
 894     118858
 896     106500
 898     611657
 899     135000
 900     110000
 901     153000
 903     240000
 904     125500
 905     128000
 906     255000
 908     131000
 911     143500
 912      88000
 916      35311
 917     135000
 919     176500
 922     169990
 923     193000
 924     207500
 925     175000
 928     236500
 930     201000
 931     117500
 932     320000
 933     190000
 934     242000
 935      79900
 936     184900
 940     150900
 942     150000
 943     143000
 947     270000
 949     197500
 950     129000
 951     119900
 957     132000
 958     185000
 960     116500
 963     239000
 967     135000
 972      99500
 973     182000
 976      85500
 977     199900
 978     110000
 979     139000
 982     159895
 985     125000
 987     395192
 994     337500
 996     136500
 997     185000
 998      91000
 999     206000
 1000     82000
 1001     86000
 1002    232000
 1003    136905
 1004    181000
 1006    163500
 1008    240000
 1011    100000
 1013     85000
 1014    119200
 1016    203000
 1017    187500
 1019    213490
 1020    176000
 1021    194000
 1023    191000
 1024    287000
 1025    112500
 1026    167500
 1027    293077
 1033    230000
 1034    119750
 1035     84000
 1036    315500
 1040    155000
 1042    196000
 1044    278000
 1045    139600
 1047    145000
 1048    115000
 1049     84900
 1050    176485
 1051    200141
 1053    144500
 1055    180000
 1056    185850
 1060    213500
 1061     81000
 1063    110500
 1064    154000
 1070    135000
 1074    194000
 1077    138800
 1078    155900
 1079    126000
 1080    145000
 1081    133000
 1082    192000
 1083    160000
 1089    197000
 1090     92900
 1093    146000
 1094    129000
 1095    176432
 1097    170000
 1099    157000
 1100     60000
 1101    119500
 1102    135000
 1103    159500
 1106    179900
 1109    280000
 1112    129900
 1113    134500
 1114    117000
 1115    318000
 1117    130000
 1119    133700
 1120    118400
 1121    212900
 1122    112000
 1123    118000
 1125    115000
 1126    174000
 1127    259000
 1131     93500
 1135    102000
 1138    196000
 1139    144000
 1140    139000
 1143     80000
 1146    180000
 1150    124000
 1151    149900
 1152    230000
 1153    120500
 1155    218000
 1157    230000
 1158    235128
 1161    224000
 1162    129000
 1165    233170
 1166    245350
 1171    163000
 1176    119500
 1179     93000
 1181    392500
 1183    120000
 1184    186700
 1187    262000
 1190    168000
 1193    165000
 1198    178000
 1199    148000
 1200    116050
 1203    213000
 1204    153500
 1205    271900
 1206    107000
 1207    200000
 1208    140000
 1209    290000
 1212    113000
 1215    125000
 1217    229456
 1220    115000
 1221    134000
 1223    137900
 1227    147000
 1228    367294
 1232    101800
 1233    142000
 1238    142500
 1239    265900
 1241    248328
 1243    465000
 1249    119000
 1250    244000
 1251    171750
 1252    130000
 1256    301500
 1257     99900
 1259    151000
 1261    128900
 1264    181000
 1267    378500
 1270    260000
 1271    185750
 1272    137000
 1280    227000
 1281    180000
 1282    150500
 1286    143000
 1287    190000
 1288    278000
 1294    115000
 1295    138500
 1296    155000
 1299    154000
 1303    232000
 1305    325000
 1306    202500
 1307    138000
 1308    147000
 1309    179200
 1310    335000
 1311    203000
 1314    119000
 1316    295493
 1317    208900
 1318    275000
 1319    111000
 1320    156500
 1321     72500
 1323     82500
 1324    147000
 1325     55000
 1326     79000
 1327    130500
 1330    227000
 1332    100000
 1335    167900
 1336    135000
 1337     52500
 1339    128500
 1340    123000
 1341    155000
 1345    108500
 1346    262500
 1347    283463
 1348    215000
 1356    110000
 1357    149900
 1359    315000
 1361    260000
 1368    144000
 1369    232000
 1373    466500
 1375    239000
 1376     91000
 1380     58500
 1381    237500
 1383    112000
 1388    377500
 1390    235000
 1391    124000
 1394    246578
 1396    160000
 1402    193879
 1403    282922
 1405    275000
 1407    112000
 1412     90000
 1413    257000
 1415    175900
 1418    124000
 1419    223000
 1421    127500
 1422    136500
 1424    144000
 1425    142000
 1428    119000
 1429    182900
 1431    143750
 1432     64500
 1434    160000
 1435    174000
 1436    120500
 1437    394617
 1438    149700
 1441    149300
 1444    179600
 1446    157900
 1451    287090
 1453     84500
 1454    185000
 1456    210000
 1458    142125
 1459    147500
 Name: SalePrice, dtype: int64,
 185     475000
 198     104000
 267     179500
 304     295000
 635     200000
 883     118500
 1031    197000
 1440    191000
 Name: SalePrice, dtype: int64,
 61      101000
 93      133900
 328     214500
 583     325000
 735     163000
 784     128000
 809     106000
 852     164000
 1197    144000
 1248    129500
 1266    122000
 Name: SalePrice, dtype: int64,
 0       208500
 2       223500
 3       140000
 4       250000
 7       200000
 11      345000
 20      325300
 30       40000
 35      309000
 48      113000
 50      177000
 56      172500
 57      196500
 58      438780
 63      140000
 64      219500
 65      317000
 72      185000
 74      107400
 79      110000
 80      193500
 85      260000
 86      174000
 87      164500
 94      204750
 95      185000
 101     178000
 105     250000
 112     383970
 114     259500
 115     176000
 118     320000
 119     163990
 128     155000
 130     226000
 131     244000
 138     230000
 139     231500
 145     130000
 147     222500
 152     190000
 157     269500
 158     254900
 159     320000
 161     412500
 167     325624
 168     183500
 172     239000
 176     211000
 180     177000
 181     200100
 190     315000
 191     184000
 193     130000
 195     148500
 197     235000
 208     277000
 212     252678
 214     161750
 217     107000
 221     200000
 222     179900
 225     112000
 226     290000
 227     106000
 231     403000
 232      94500
 234     216500
 235      89500
 237     194500
 243     120000
 244     205000
 246     137000
 248     180000
 252     173000
 255     230000
 256     207500
 258     231500
 261     276000
 266     185000
 270     266000
 272     290000
 279     192000
 280     228500
 285     164700
 289     153575
 290     233230
 291     135900
 293     235000
 297     239000
 298     175000
 301     267000
 306     225000
 310     165600
 314     178000
 315     188500
 316     260000
 317     270000
 318     260000
 320     342643
 321     354000
 322     301000
 329      78000
 334     192000
 340     202900
 344      85000
 348     154000
 349     437154
 359     280000
 363     118000
 364     190000
 365     147000
 370     172400
 374     219500
 377     340000
 379     179000
 382     213500
 384     240000
 389     426000
 391     215000
 397     169500
 399     241000
 403     258000
 404     168000
 407     177000
 408     280000
 409     339750
 414     228000
 416     149500
 417     239000
 423     315000
 425     135000
 430      85400
 432     122500
 433     181000
 435     212000
 444     210000
 447     199900
 452     204000
 453     210000
 456      98000
 458     161000
 460     263435
 461     155000
 463     188700
 467     146500
 469     187000
 471     190000
 477     380000
 482     155000
 490     115000
 492     172785
 500     113000
 501     226700
 504     147000
 505     124500
 506     215000
 508     161000
 517     265000
 518     211000
 519     234000
 520     106250
 523     184750
 524     315750
 527     446261
 531     128000
 534     178000
 535     107500
 536     188000
 541     248000
 544     179665
 549     263000
 554     284000
 558     175000
 564     268000
 565     128000
 566     325000
 572     224500
 578     146000
 590     185900
 591     451950
 596     114504
 599     151000
 600     275000
 602     220000
 603     151000
 605     205000
 607     225000
 608     359100
 610     313000
 612     261500
 616     183200
 619     305000
 621     240000
 623     168500
 624     165150
 628     135000
 630     124000
 641     226000
 643     152000
 648     155000
 650     205950
 651     108000
 652     191000
 655      88000
 657     149000
 660     197900
 661     402000
 665     230500
 666     129000
 670     173500
 671     103600
 675     148500
 676      87000
 684     221000
 685     207500
 686     227875
 687     148800
 691     755000
 692     335000
 702     361919
 703     140000
 705      55000
 708     179540
 714     130500
 716     159500
 718     341000
 732     222500
 737     239900
 739     190000
 740     132000
 745     299800
 746     236000
 747     265979
 751     162000
 753     275500
 755     172500
 756     212000
 757     158900
 758     179400
 759     290000
 762     215200
 763     337000
 766     196500
 769     538000
 781     175900
 787     233000
 789     187500
 792     269790
 794     194500
 795     171000
 798     485000
 800     200000
 802     189000
 803     582933
 807     223500
 820     183000
 822     225000
 828     185000
 829     147400
 831     151000
 832     237000
 837     100000
 840     140000
 841     157500
 846     213000
 857     174000
 859     250000
 868     169000
 869     236000
 871     200500
 875     303477
 877     350000
 882     178000
 891     172500
 895     140000
 897     142953
 902     180000
 909     174000
 910     154300
 913     145000
 914     173733
 915      75000
 918     238000
 920     201000
 926     285000
 927     176000
 929     222000
 937     253000
 938     239799
 939     244400
 941     214000
 948     192500
 953     172000
 955     145000
 956     124000
 959     155000
 961     272000
 962     155000
 964     214900
 965     178900
 971     173000
 974     167500
 975     165000
 981     336000
 983     255900
 988     195000
 989     197000
 990     348000
 991     168000
 992     187000
 993     173900
 1007     88000
 1012    165000
 1015    227000
 1029    118000
 1030    160000
 1032    310000
 1037    287000
 1038     97000
 1041    173000
 1043    262280
 1046    556581
 1052    165000
 1054    255000
 1057    248000
 1058    335000

In [214]:
anova_results = f_oneway(*group_sale_price)

In [215]:
anova_results

F_onewayResult(statistic=np.float64(19.59500099598122), pvalue=np.float64(3.376776535118099e-25))

In [216]:
anova_f_scores = {} 
for feature in categorical_features:
    groups = dataset.groupby(feature)['SalePrice']
    
    group_sale_price = []
    for group_name, sale_prices in groups:
        group_sale_price.append(sale_prices)
    
    anova_results = f_oneway(*group_sale_price)
    anova_f_scores[feature] = anova_results.statistic

In [217]:
pd.Series(anova_f_scores).sort_values(ascending=False)

ExterQual        443.334831
KitchenQual      407.806352
BsmtQual         316.148635
GarageFinish     213.867028
FireplaceQu      121.075121
MasVnrType       112.882739
Foundation       100.253851
CentralAir        98.305344
HeatingQC         88.394462
GarageType        80.379992
Neighborhood      71.784865
BsmtFinType1      64.688200
BsmtExposure      63.939761
SaleCondition     45.578428
MSZoning          43.840282
PavedDrive        42.024179
LotShape          40.132852
SaleType          28.863054
GarageQual        25.776093
GarageCond        25.750153
Electrical        23.074438
BsmtCond          19.708139
HouseStyle        19.595001
Exterior1st       18.611743
RoofStyle         17.805497
Exterior2nd       17.500840
Alley             15.176614
Fence             13.433276
BldgType          13.011077
LandContour       12.850188
PoolQC            10.509853
ExterCond          8.798714
LotConfig          7.809954
BsmtFinType2       7.565378
RoofMatl           6.727305
Condition1         6.118017
Heating            4.259819
Functional         4.057875
MiscFeature        2.593622
Street             2.459290
Condition2         2.073899
LandSlope          1.958817
Utilities          0.298804
dtype: float64

In [218]:
dataset.groupby('ExterQual')['SalePrice'].count()

ExterQual
Ex     52
Fa     14
Gd    488
TA    906
Name: SalePrice, dtype: int64

In [219]:
dataset.groupby('KitchenQual')['SalePrice'].count()

KitchenQual
Ex    100
Fa     39
Gd    586
TA    735
Name: SalePrice, dtype: int64

In [220]:
dataset.groupby('ExterQual')['SalePrice'].mean()

ExterQual
Ex    367360.961538
Fa     87985.214286
Gd    231633.510246
TA    144341.313466
Name: SalePrice, dtype: float64

In [221]:
dataset.groupby('KitchenQual')['SalePrice'].mean()

KitchenQual
Ex    328554.670000
Fa    105565.205128
Gd    212116.023891
TA    139962.511565
Name: SalePrice, dtype: float64

In [222]:
pd.crosstab(dataset['KitchenQual'], dataset['ExterQual'])

ExterQual    Ex  Fa   Gd   TA
KitchenQual
Ex           42   0   47   11
Fa            0   8    0   31
Gd            8   0  408  170
TA            2   6   33  694

In [223]:
pd.crosstab(dataset['KitchenQual'], dataset['ExterQual'], normalize='index')

ExterQual          Ex        Fa        Gd        TA
KitchenQual
Ex           0.420000  0.000000  0.470000  0.110000
Fa           0.000000  0.205128  0.000000  0.794872
Gd           0.013652  0.000000  0.696246  0.290102
TA           0.002721  0.008163  0.044898  0.944218

In [224]:
table = pd.crosstab(dataset['KitchenQual'], dataset['ExterQual'])

In [225]:
table

ExterQual    Ex  Fa   Gd   TA
KitchenQual
Ex           42   0   47   11
Fa            0   8    0   31
Gd            8   0  408  170
TA            2   6   33  694

In [226]:
# chi_square
chi2, p, dof, expected = chi2_contingency(table)
print(f"chi_square: {chi2}")
print(f"p-value: {p}")
print("degress of freedom:", dof)

chi_square: 1312.2513151093713
p-value: 6.988389926465085e-277
degress of freedom: 9

In [227]:
table.shape

(4, 4)

In [228]:
# Calculating Cramér's V
math.sqrt(chi2 / (1460 * min(4-1, 4-1)))

0.5473579787253363

In [229]:
expected

array([[3.56164384e+00, 9.58904110e-01, 3.34246575e+01, 6.20547945e+01],
       [1.38904110e+00, 3.73972603e-01, 1.30356164e+01, 2.42013699e+01],
       [2.08712329e+01, 5.61917808e+00, 1.95868493e+02, 3.63641096e+02],
       [2.61780822e+01, 7.04794521e+00, 2.45671233e+02, 4.56102740e+02]])

In [230]:
dataset.groupby(['KitchenQual', 'ExterQual'])['SalePrice'].mean()

KitchenQual  ExterQual
Ex           Ex           384854.214286
             Gd           317257.234043
             TA           161863.636364
Fa           Fa            79849.125000
             TA           112201.612903
Gd           Ex           322174.125000
             Gd           226499.237745
             TA           172417.105882
TA           Ex           180750.000000
             Fa            98833.333333
             Gd           173162.848485
             TA           138621.861671
Name: SalePrice, dtype: float64

In [231]:
len(group_sale_price)

6

In [232]:
feature = 'ExterQual'
group = dataset.groupby(feature)['SalePrice']

In [233]:
group

In [234]:
results = []
for feature in categorical_features:
    results.append(dataset.groupby([feature])['SalePrice'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False))
results

[          count           mean    median
 MSZoning
 FV           65  214014.061538  205950.0
 RL         1151  191004.994787  174000.0
 RH           16  131558.375000  136500.0
 RM          218  126316.830275  120500.0
 C (all)      10   74528.000000   74700.0,
         count           mean    median
 Street
 Pave     1454  181130.538514  163000.0
 Grvl        6  130190.500000  114250.0,
        count           mean    median
 Alley
 None    1369  183452.131483  165000.0
 Pave      41  168000.585366  172500.0
 Grvl      50  122219.080000  119500.0,
           count           mean    median
 LotShape
 IR2          41  239833.365854  221000.0
 IR3          10  216036.500000  203570.0
 IR1         484  206101.665289  189000.0
 Reg         925  164754.818378  146000.0,
              count           mean    median
 LandContour
 HLS             50  231533.940000  222250.0
 Low             36  203661.111111  190000.0
 Lvl           1311  180183.746758  162900.0
 Bnk             63  143104.079365  139400.0,
            count          mean    median
 Utilities
 AllPub      1459  180950.95682  163000.0
 NoSeWa         1  137500.00000  137500.0,
            count           mean    median
 LotConfig
 CulDSac       94  223854.617021  199262.0
 FR3            4  208475.000000  195450.0
 Corner       263  181623.425856  160000.0
 FR2           47  177934.574468  165000.0
 Inside      1052  176938.047529  159697.5,
            count           mean    median
 LandSlope
 Sev           13  204379.230769  185000.0
 Mod           65  196734.138462  186700.0
 Gtl         1382  179956.799566  161875.0,
               count           mean    median
 Neighborhood
 NoRidge          41  335295.317073  301500.0
 NridgHt          77  316270.623377  315000.0
 StoneBr          25  310499.000000  278000.0
 Timber           38  242247.447368  228475.0
 Veenker          11  238772.727273  218000.0
 Somerst          86  225379.837209  225500.0
 ClearCr          28  212565.428571  200250.0
 Crawfor          51  210624.725490  200624.0
 CollgCr         150  197965.773333  197200.0
 Blmngtn          17  194870.882353  191000.0
 Gilbert          79  192854.506329  181000.0
 NWAmes           73  189050.068493  182900.0
 SawyerW          59  186555.796610  179900.0
 Mitchel          49  156270.122449  153500.0
 NAmes           225  145847.080000  140000.0
 NPkVill           9  142694.444444  146000.0
 SWISU            25  142591.360000  139500.0
 Blueste           2  137500.000000  137500.0
 Sawyer           74  136793.135135  135000.0
 OldTown         113  128225.300885  119000.0
 Edwards         100  128219.700000  121750.0
 BrkSide          58  124834.051724  124300.0
 BrDale           16  104493.750000  106000.0
 IDOTRR           37  100123.783784  103000.0
 MeadowV          17   98576.470588   88000.0,
             count           mean    median
 Condition1
 PosA            8  225875.000000  212500.0
 PosN           19  215184.210526  200000.0
 RRNn            5  212400.000000  214000.0
 RRNe            2  190750.000000  190750.0
 Norm         1260  184495.492063  166500.0
 RRAn           26  184396.615385  171495.0
 Feedr          81  142475.481481  140000.0
 RRAe           11  138400.000000  142500.0
 Artery         48  135091.666667  119550.0,
             count           mean    median
 Condition2
 PosA            1  325000.000000  325000.0
 PosN            2  284875.000000  284875.0
 RRAe            1  190000.000000  190000.0
 Norm         1445  181169.405536  163500.0
 RRAn            1  136905.000000  136905.0
 Feedr           6  121166.666667  127500.0
 Artery          2  106500.000000  106500.0
 RRNn            2   96750.000000   96750.0,
           count           mean    median
 BldgType
 1Fam       1220  185763.807377  167900.0
 TwnhsE      114  181959.342105  172200.0
 Twnhs        43  135911.627907  137500.0
 Duplex       52  133541.076923  135980.0
 2fmCon       31  128432.258065  127500.0,
             count           mean    median
 HouseStyle
 2.5Fin          8  220000.000000  194000.0
 2Story        445  210051.764045  190000.0
 1Story        726  175985.477961  154750.0
 SLvl           65  166703.384615  164500.0
 2.5Unf         11  157354.545455  133900.0
 1.5Fin        154  143116.740260  132000.0
 SFoyer         37  135074.486486  135960.0
 1.5Unf         14  110150.000000  111250.0,
            count           mean    median
 RoofStyle
 Shed           2  225000.000000  225000.0
 Hip          286  218876.933566  176500.0
 Flat          13  194690.000000  185000.0
 Mansard        7  180568.428571  175000.0
 Gable       1141  171483.956179  160000.0
 Gambrel       11  148909.090909  139000.0,
           count           mean    median
 RoofMatl
 WdShngl       6  390250.000000  332500.0
 Membran       1  241500.000000  241500.0
 WdShake       5  241400.000000  242000.0
 Tar&Grv      11  185406.363636  167000.0
 Metal         1  180000.000000  180000.0
 CompShg    1434  179803.679219  162000.0
 ClyTile       1  160000.000000  160000.0
 Roll          1  137000.000000  137000.0,
              count           mean    median
 Exterior1st
 ImStucc          1  262000.000000  262000.0
 Stone            2  258500.000000  258500.0
 CemntBd         61  231690.655738  236500.0
 VinylSd        515  213732.900971  200000.0
 BrkFace         50  194573.000000  165750.0
 Plywood        108  175942.379630  167450.0
 HdBoard        222  163077.450450  149900.0
 Stucco          25  162990.000000  144000.0
 WdShing         26  150655.076923  128700.0
 Wd Sdng        206  149841.645631  138943.5
 MetalSd        220  149422.177273  139000.0
 AsbShng         20  107385.550000  108000.0
 CBlock           1  105000.000000  105000.0
 AsphShn          1  100000.000000  100000.0
 BrkComm          2   71000.000000   71000.0,
              count           mean    median
 Exterior2nd
 Other            1  319000.000000  319000.0
 ImStucc         10  252070.000000  187600.0
 CmentBd         60  230093.833333  238750.0
 VinylSd        504  214432.460317  200070.5
 BrkFace         25  195818.000000  160000.0
 Plywood        142  168112.387324  160750.0
 HdBoard        207  167661.565217  155000.0
 Wd Shng         38  161328.947368  138225.0
 Stone            5  158224.800000  177000.0
 Stucco          26  155905.153846  142000.0
 MetalSd        214  149803.172897  138750.0
 Wd Sdng        197  148386.065990  138000.0
 AsphShn          3  138000.000000  139000.0
 Brk Cmn          7  126714.285714  147000.0
 AsbShng         20  114060.550000  111000.0
 CBlock           1  105000.000000  105000.0,
             count           mean    median
 MasVnrType
 Stone         130  266474.646154  246839.0
 BrkFace       452  204338.568584  181450.0
 None          863  156370.148320  143000.0
 BrkCmn         15  146318.066667  139000.0,
            count           mean    median
 ExterQual
 Ex            52  367360.961538  364606.5
 Gd           488  231633.510246  220000.0
 TA           906  144341.313466  139450.0
 Fa            14   87985.214286   82250.0,
            count           mean    median
 ExterCond
 Ex             3  201333.333333  161000.0
 TA          1282  184034.896256  167370.0
 Gd           146  168897.568493  151250.0
 Fa            28  102595.142857   95750.0
 Po             1   76500.000000   76500.0,
             count           mean    median
 Foundation
 PConc         647  225230.442040  205000.0
 Wood            3  185666.666667  164000.0
 Stone           6  165959.166667  126500.0
 CBlock        634  149805.714511  141500.0
 BrkTil        146  132291.075342  125250.0
 Slab           24  107365.625000  104150.0,
           count           mean    median
 BsmtQual
 Ex          121  327041.041322  318000.0
 Gd          618  202688.478964  192070.0
 TA          649  140759.818182  135500.0
 Fa           35  115692.028571  112000.0
 None         37  105652.891892  101800.0,
           count           mean    median
 BsmtCond
 Gd           65  213599.907692  193879.0
 TA         1311  183632.620900  165000.0
 Fa           45  121809.533333  118500.0
 None         37  105652.891892  101800.0
 Po            2   64000.000000   64000.0,
               count           mean    median
 BsmtExposure
 Gd              134  257689.805970  226975.0
 Av              221  206643.420814  185850.0
 Mn              114  192789.657895  182450.0
 No              953  165652.295908  154000.0
 None             38  107938.342105  104025.0,
               count           mean    median
 BsmtFinType1
 GLQ             418  235413.720096  213750.0
 Unf             430  170670.576744  161750.0
 ALQ             220  161573.068182  149250.0
 LwQ              74  151852.702703  139000.0
 BLQ             148  149493.655405  139100.0
 Rec             133  146889.248120  142000.0
 None             37  105652.891892  101800.0,
               count           mean    median
 BsmtFinType2
 ALQ              19  209942.105263  174900.0
 Unf            1256  184694.690287  167000.0
 GLQ              14  180982.142857  203125.0
 Rec              54  164917.129630  148750.0
 LwQ              46  164364.130435  154000.0
 BLQ              33  151101.000000  143000.0
 None             38  110346.236842  104025.0,
          count           mean    median
 Heating
 GasA      1428  182021.195378  164500.0
 GasW        18  166632.166667  134950.0
 OthW         2  125750.000000  125750.0
 Wall         4   92100.000000   91450.0
 Grav         7   75271.428571   79000.0
 Floor        1   72500.000000   72500.0,
            count           mean    median
 HeatingQC
 Ex           741  214914.429150  194700.0
 Gd           241  156858.871369  152000.0
 TA           428  142362.876168  135000.0
 Fa            49  123919.489796  123500.0
 Po             1   87000.000000   87000.0,
             count           mean    median
 CentralAir
 Y            1365  186186.709890  168000.0
 N              95  105264.073684   98000.0,
             count           mean    median
 Electrical
 SBrkr        1335  186810.637453  170000.0
 FuseA          94  122196.893617  121250.0
 FuseF          27  107675.444444  115000.0
 FuseP           3   97333.333333   82000.0
 Mix             1   67000.000000   67000.0,
              count           mean    median
 KitchenQual
 Ex             100  328554.670000  316750.0
 Gd             586  212116.023891  201400.0
 TA             735  139962.511565  137000.0
 Fa              39  105565.205128  115000.0,
             count           mean    median
 Functional
 Typ          1360  183429.147059  165500.0
 Mod            15  168393.333333  137900.0
 Maj1           14  153948.142857  140750.0
 Min1           31  146385.483871  139000.0
 Min2           34  144240.647059  140000.0
 Sev             1  129000.000000  129000.0
 Maj2            5   85800.000000   85000.0,
              count           mean    median
 FireplaceQu
 Ex              24  337712.500000  314250.0
 Gd             380  226351.415789  206950.0
 TA             313  205723.488818  187500.0
 Fa              33  167298.484848  158000.0
 None           690  141331.482609  135000.0
 Po              20  129764.150000  131500.0,
             count           mean    median
 GarageType
 BuiltIn        88  254751.738636  227500.0
 Attchd        870  202892.656322  185000.0
 Basment        19  160570.684211  148000.0
 2Types          6  151283.333333  159000.0
 Detchd        387  134091.162791  129500.0
 CarPort         9  109962.111111  108000.0
 None           81  103317.283951  100000.0,
               count           mean    median
 GarageFinish
 Fin             352  240052.690341  215000.0
 RFn             422  202068.869668  190000.0
 Unf             605  142156.423140  135000.0
 None             81  103317.283951  100000.0,
             count           mean    median
 GarageQual
 Ex              3  241000.000000  127500.0
 Gd             14  215860.714286  209115.0
 TA           1311  187489.836003  170000.0
 Fa             48  123573.354167  115000.0
 None           81  103317.283951  100000.0
 Po              3  100166.666667   96500.0,
             count           mean    median
 GarageCond
 TA           1326  187885.735294  170000.0
 Gd              9  179930.000000  148000.0
 Ex              2  124000.000000  124000.0
 Fa             35  114654.028571  114504.0
 Po              7  108500.000000  108000.0
 None           81  103317.283951  100000.0,
             count           mean    median
 PavedDrive
 Y            1340  186433.973881  168500.0
 P              30  132330.000000  132250.0
 N              90  115039.122222  111000.0,
         count           mean    median
 PoolQC
 Ex          2  490000.000000  490000.0
 Fa          2  215500.000000  215500.0
 Gd          3  201990.000000  171000.0
 None     1453  180404.663455  162900.0,
        count           mean    median
 Fence
 None    1179  187596.837998  173000.0
 GdPrv     59  178927.457627  167500.0
 MnPrv    157  148751.089172  137450.0
 GdWo      54  140379.314815  138750.0
 MnWw      11  134286.363636  130000.0,
              count           mean    median
 MiscFeature
 TenC             1  250000.000000  250000.0
 None          1406  182046.410384  164250.0
 Gar2             2  170750.000000  170750.0
 Shed            49  151187.612245  144000.0
 Othr             2   94000.000000   94000.0,
           count           mean    median
 SaleType
 New         122  274945.418033  247453.0
 Con           2  269600.000000  269600.0
 CWD           4  210600.000000  188750.0
 ConLI         5  200390.000000  125000.0
 WD         1267  173401.836622  158000.0
 COD          43  143973.255814  139000.0
 ConLw         5  143700.000000  144000.0
 ConLD         9  138780.888889  140000.0
 Oth           3  119850.000000  116050.0,
                count           mean    median
 SaleCondition
 Partial          125  272291.752000  244600.0
 Normal          1198  175202.219533  160000.0
 Alloca            12  167377.416667  148145.0
 Family            20  149600.000000  140500.0
 Abnorml          101  146526.623762  130000.0
 AdjLand            4  104125.000000  104000.0]

In [235]:
dataset[categorical_features].nunique()

MSZoning          5
Street            2
Alley             3
LotShape          4
LandContour       4
Utilities         2
LotConfig         5
LandSlope         3
Neighborhood     25
Condition1        9
Condition2        8
BldgType          5
HouseStyle        8
RoofStyle         6
RoofMatl          8
Exterior1st      15
Exterior2nd      16
MasVnrType        4
ExterQual         4
ExterCond         5
Foundation        6
BsmtQual          5
BsmtCond          5
BsmtExposure      5
BsmtFinType1      7
BsmtFinType2      7
Heating           6
HeatingQC         5
CentralAir        2
Electrical        5
KitchenQual       4
Functional        7
FireplaceQu       6
GarageType        7
GarageFinish      4
GarageQual        6
GarageCond        6
PavedDrive        3
PoolQC            4
Fence             5
MiscFeature       5
SaleType          9
SaleCondition     6
dtype: int64

In [236]:
X = dataset[['ExterQual']]
y = dataset['SalePrice']

In [237]:
X.shape

(1460, 1)

In [238]:
y.shape

(1460,)

In [239]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [240]:
X_train.shape

(1168, 1)

In [241]:
X_test.shape

(292, 1)

In [242]:
y_train.shape

(1168,)

In [243]:
y_test.shape

(292,)

In [244]:
encoder = OneHotEncoder()

In [245]:
X_train_encoded = encoder.fit_transform(X_train)

In [246]:
encoder

OneHotEncoder()

In [247]:
X_test_encoded = encoder.transform(X_test)

In [248]:
modelA = LinearRegression()

In [249]:
modelA.fit(X_train_encoded, y_train)

LinearRegression()

In [250]:
modelA_pred = modelA.predict(X_test_encoded)

In [251]:
modelA_mae = mean_absolute_error(y_test, modelA_pred)

In [252]:
modelA_mae

40003.945943276565

In [253]:
X_2 = dataset[['ExterQual', 'KitchenQual']]
y_2 = dataset['SalePrice']

In [254]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, test_size=0.20, random_state=42)

In [255]:
encoder_2 = OneHotEncoder()

In [256]:
X_train_encoded_2 = encoder_2.fit_transform(X_train_2)

In [257]:
X_test_encoded_2 = encoder_2.transform(X_test_2)

In [258]:
modelB = LinearRegression()

In [259]:
modelB.fit(X_train_encoded_2, y_train_2)

LinearRegression()

In [260]:
modelB_pred = modelB.predict(X_test_encoded_2)

In [261]:
modelB_mae = mean_absolute_error(y_test_2, modelB_pred)

In [262]:
modelB_mae

38156.54920283288

In [263]:
kf = KFold(n_splits=5, random_state=42, shuffle=True)

In [264]:
for train_index, val_index in kf.split(X_train_2):
    print(f"Training length", len(train_index))
    print(f"Validation length", len(val_index))

Training length 934
Validation length 234
Training length 934
Validation length 234
Training length 934
Validation length 234
Training length 935
Validation length 233
Training length 935
Validation length 233

In [265]:
mae_values = []
for train_index, val_index in kf.split(X_train_2):
    X_train_fold = X_train_2.iloc[train_index]
    X_val_fold = X_train_2.iloc[val_index]

    y_train_fold = y_train_2.iloc[train_index]
    y_val_fold = y_train_2.iloc[val_index]
    
    encoder = OneHotEncoder()
    
    X_train_fold_encoded = encoder.fit_transform(X_train_fold)
    X_val_fold_encoded = encoder.transform(X_val_fold)
    
    modelC = LinearRegression()
    
    modelC.fit(X_train_fold_encoded, y_train_fold)
    
    modelC_pred = modelC.predict(X_val_fold_encoded)
    
    modelC_mae = mean_absolute_error(y_val_fold, modelC_pred)
    mae_values.append(modelC_mae)

In [266]:
mae_values

[37946.85647942454,
 37915.8090966761,
 39136.80430901418,
 36632.84629453827,
 35818.98974087559]

In [267]:
data = pd.Series(mae_values)

In [268]:
data.mean()

np.float64(37490.26118410573)

In [269]:
# Experiment 1(with 2 features)
# Pipeline
pipeline = Pipeline([
    ('encoder', OneHotEncoder()),
    ('modelD', LinearRegression())
])

In [270]:
# Cross Validation Scores
scores = cross_val_score(
    pipeline,
    X_train_2,
    y_train_2,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [271]:
scores

array([-37946.85647942, -37915.80909668, -39136.80430901, -36632.84629454,
       -35818.98974088])

In [272]:
mae_scores = -scores

In [273]:
data_experiment_1 = pd.Series(mae_scores)

In [274]:
data_experiment_1.mean()

np.float64(37490.26118410573)

In [275]:
# Experiment 2(with 3 features)
X_3 = dataset[['ExterQual', 'KitchenQual', 'BsmtQual']]
y_3 = dataset['SalePrice']

In [276]:
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X_3, y_3, test_size=0.20, random_state=42)

In [277]:
# Pipeline
pipeline_2 = Pipeline([
    ('encoder', OneHotEncoder()),
    ('modelE', LinearRegression())
    
])

In [278]:
scores_experiment_2 = cross_val_score(
    pipeline_2,
    X_train_3,
    y_train_3,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [279]:
scores_experiment_2

array([-35577.59619007, -34545.63930744, -36917.83155896, -32475.07255385,
       -32865.84989946])

In [280]:
mae_scores_experiment_2 = -scores_experiment_2

In [281]:
data_experiment_2 = pd.Series(mae_scores_experiment_2)

In [282]:
data_experiment_2.mean()

np.float64(34476.39790195465)

In [283]:
# Experiment 3(with 4 features)
X_4 = dataset[['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish']]
y_4 = dataset['SalePrice']

In [284]:
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(X_4, y_4, test_size=0.20, random_state=42)

In [285]:
pipeline_3 = Pipeline([
    ('encoder', OneHotEncoder()),
    ('modelF', LinearRegression())
])

In [286]:
scores_experiment_3 = cross_val_score(
    pipeline_3,
    X_train_4,
    y_train_4,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [287]:
scores_experiment_3

array([-33907.20012378, -32629.42937229, -34630.18236278, -30579.16399933,
       -31600.7475634 ])

In [288]:
mae_scores_experiment_3 = -scores_experiment_3

In [289]:
mae_scores_experiment_3

array([33907.20012378, 32629.42937229, 34630.18236278, 30579.16399933,
       31600.7475634 ])

In [290]:
data_experiment_3 = pd.Series(mae_scores_experiment_3)

In [291]:
data_experiment_3

0    33907.200124
1    32629.429372
2    34630.182363
3    30579.163999
4    31600.747563
dtype: float64

In [292]:
data_experiment_3.mean()

np.float64(32669.344684314845)

In [293]:
print(f"std for mae with 2 features", data_experiment_1.std())
print(f"std for mae with 3 features", data_experiment_2.std())
print(f"std for mae with 4 features", data_experiment_3.std())

std for mae with 2 features 1287.3405805761035
std for mae with 3 features 1855.8824289855997
std for mae with 4 features 1649.9635469564191

In [294]:
# Experiment 5(with 5 features)
X_5 = dataset[['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType']]
y_5 = dataset['SalePrice']

In [295]:
X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(X_5, y_5, test_size=0.20, random_state=42)

In [296]:
pipeline_4 = Pipeline([
    ('encoder', OneHotEncoder()),
    ('modelE', LinearRegression())
])

In [297]:
scores_experiment_4 = cross_val_score(
    pipeline_4,
    X_train_5,
    y_train_5,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [298]:
scores_experiment_4

array([-32923.72775626, -31846.84837264, -34141.74070235, -31065.51787152,
       -30645.33210437])

In [299]:
mae_scores_experiment_4 = -scores_experiment_4

In [300]:
mae_scores_experiment_4

array([32923.72775626, 31846.84837264, 34141.74070235, 31065.51787152,
       30645.33210437])

In [301]:
data_experiment_4 = pd.Series(mae_scores_experiment_4)

In [302]:
data_experiment_4.mean()

np.float64(32124.633361426124)

In [303]:
data_experiment_4.std()

np.float64(1422.541405965847)

In [304]:
# Experiment 6(with 6 features)
X_6 = dataset[['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu']]
y_6 = dataset['SalePrice']

In [305]:
X_train_6, X_test_6, y_train_6, y_test_6 = train_test_split(X_6, y_6, test_size=0.20, random_state=42)

In [306]:
pipeline_experiment_6 = Pipeline([
    ('encoder', OneHotEncoder()),
    ('modelF', LinearRegression())
])

In [307]:
scores_experiment_6 = cross_val_score(
    pipeline_experiment_6,
    X_train_6,
    y_train_6,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [308]:
scores_experiment_6

array([-31455.61240437, -29077.07957352, -32908.01903086, -29379.82761864,
       -28029.83558   ])

In [309]:
mae_scores_experiment_6 = -scores_experiment_6

In [310]:
mae_scores_experiment_6

array([31455.61240437, 29077.07957352, 32908.01903086, 29379.82761864,
       28029.83558   ])

In [311]:
data_experiment_6 = pd.Series(mae_scores_experiment_6)

In [312]:
data_experiment_6.mean()

np.float64(30170.074841477104)

In [313]:
data_experiment_6.std()

np.float64(1971.591909798857)

In [314]:
# Experiment 7(with 7 features)
X_7 = dataset[['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']]
y_7 = dataset['SalePrice']

In [315]:
X_train_7, X_test_7, y_train_7, y_test_7 = train_test_split(X_7, y_7, test_size=0.20, random_state=42)

In [316]:
pipeline_experiment_7 = Pipeline([
    ('encoder', OneHotEncoder()),
    ('model', LinearRegression())
])

In [317]:
scores_experiment_7 = cross_val_score(
    pipeline_experiment_7,
    X_train_7,
    y_train_7,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [318]:
scores_experiment_7

array([-31478.07565903, -29008.12948744, -32467.66665127, -29520.24934174,
       -27884.64647271])

In [319]:
mae_scores_experiment_7 = -scores_experiment_7

In [320]:
mae_scores_experiment_7

array([31478.07565903, 29008.12948744, 32467.66665127, 29520.24934174,
       27884.64647271])

In [321]:
data_experiment_7 = pd.Series(mae_scores_experiment_7)

In [322]:
data_experiment_7

0    31478.075659
1    29008.129487
2    32467.666651
3    29520.249342
4    27884.646473
dtype: float64

In [323]:
data_experiment_7.mean()

np.float64(30071.753522434847)

In [324]:
data_experiment_7.std()

np.float64(1866.6167167421852)

In [325]:
# Experiment 1 with numerical feature(1 feature)
X_num_1 = dataset[['OverallQual']]
y_num_1 = dataset['SalePrice']

In [326]:
X_train_num_1, X_test_num_1, y_train_num_1, y_test_num_1 = train_test_split(X_num_1, y_num_1, test_size=0.20, random_state=42)

In [327]:
pipeline_num_1 = Pipeline([
    ('model', LinearRegression())
])

In [328]:
scores_num_1 = cross_val_score(
    pipeline_num_1,
    X_train_num_1,
    y_train_num_1,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [329]:
scores_num_1

array([-32927.24129335, -33788.98026162, -35121.65566421, -35218.41347433,
       -31301.42503828])

In [330]:
scores_num_positive = -scores_num_1

In [331]:
data_num_1 = pd.Series(scores_num_positive)

In [332]:
data_num_1

0    32927.241293
1    33788.980262
2    35121.655664
3    35218.413474
4    31301.425038
dtype: float64

In [333]:
mae_num_1 = data_num_1.mean()

In [334]:
mae_num_1

np.float64(33671.54314635731)

In [335]:
data_num_1.std()

np.float64(1634.0800696933215)

In [336]:
# Experiment 2 with numerical feature(2 feature)
X_num_2 = dataset[['OverallQual', 'GrLivArea']]
y_num_2 = dataset['SalePrice']

In [337]:
X_train_num_2, X_test_num_2, y_train_num_2, y_test_num_2 = train_test_split(X_num_2, y_num_2, test_size=0.20, random_state=42)

In [338]:
pipeline_num_2 = Pipeline([
    ('model', LinearRegression())
])

In [339]:
scores_num_2 = cross_val_score(
    pipeline_num_2,
    X_train_num_2,
    y_train_num_2,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [340]:
scores_num_2

array([-27283.77237853, -29905.64508322, -29622.93645248, -29378.5944704 ,
       -27161.35020875])

In [341]:
scores_num_2_positive = -scores_num_2

In [342]:
scores_num_2_positive

array([27283.77237853, 29905.64508322, 29622.93645248, 29378.5944704 ,
       27161.35020875])

In [343]:
data_num_2 = pd.Series(scores_num_2_positive)

In [344]:
data_num_2.mean()

np.float64(28670.45971867768)

In [345]:
data_num_2.std()

np.float64(1335.5394913739012)

In [346]:
# Experiment 3 with numerical feature(3 feature)
X_num_3 = dataset[['OverallQual', 'GrLivArea', 'GarageCars']]
y_num_3 = dataset['SalePrice']

In [347]:
X_train_num_3, X_test_num_3, y_train_num_3, y_test_num_3 = train_test_split(X_num_3, y_num_3, test_size=0.20, random_state=42)

In [348]:
pipeline_num_3 = Pipeline([
    ('model', LinearRegression())
])

In [349]:
scores_num_3 = cross_val_score(
    pipeline_num_3,
    X_train_num_3,
    y_train_num_3,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [350]:
scores_num_3_positive = -scores_num_3

In [351]:
scores_num_3_positive

array([26556.38937345, 28905.84492607, 28460.8548299 , 26669.22455086,
       25793.34496968])

In [352]:
data_num_3 = pd.Series(scores_num_3_positive)

In [353]:
data_num_3.mean()

np.float64(27277.13172999234)

In [354]:
data_num_3.std()

np.float64(1336.464635274692)

In [355]:
# Experiment 4 with numerical feature(4 feature)
X_num_4 = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea']]
y_num_4 = dataset['SalePrice']

In [356]:
X_train_num_4, X_test_num_4, y_train_num_4, y_test_num_4 = train_test_split(X_num_4, y_num_4, test_size=0.20, random_state=42)

In [357]:
pipeline_num_4 = Pipeline([
    ('model', LinearRegression())
])

In [358]:
scores_num_4 = cross_val_score(
    pipeline_num_4,
    X_train_num_4,
    y_train_num_4,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [359]:
scores_num_4_positive = -scores_num_4

In [360]:
scores_num_4_positive

array([26357.29179571, 28432.1490222 , 28055.40865113, 26275.87398555,
       25429.88739042])

In [361]:
scores_num_4_positive.mean()

np.float64(26910.122169003072)

In [362]:
scores_num_4_positive.std()

np.float64(1142.5615123519458)

In [363]:
# Experiment 5 with numerical feature(5 feature)
X_num_5 = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF']]
y_num_5 = dataset['SalePrice']

In [364]:
X_train_num_5, X_test_num_5, y_train_num_5, y_test_num_5 = train_test_split(X_num_5, y_num_5, test_size=0.20, random_state=42)

In [365]:
pipeline_num_5 = Pipeline([
    ('model', LinearRegression())
])

In [366]:
scores_num_5 = cross_val_score(
    pipeline_num_5,
    X_train_num_5,
    y_train_num_5,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [367]:
scores_num_5_positive = -scores_num_5

In [368]:
scores_num_5_positive

array([24453.53876723, 27114.34710962, 26608.94217702, 24475.07551807,
       23523.94405348])

In [369]:
scores_num_5_positive.mean()

np.float64(25235.169525083376)

In [370]:
scores_num_5_positive.std()

np.float64(1380.9809447798016)

In [371]:
# Experiment 6 with numerical feature(6 feature)
X_num_6 = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', 'Fireplaces']]
y_num_6 = dataset['SalePrice']

In [372]:
X_train_num_6, X_test_num_6, y_train_num_6, y_test_num_6 = train_test_split(X_num_6, y_num_6, test_size=0.20, random_state=42)

In [373]:
pipeline_num_6 = Pipeline([
    ('model', LinearRegression())
])

In [374]:
scores_num_6 = cross_val_score(
    pipeline_num_6,
    X_train_num_6,
    y_train_num_6,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [375]:
scores_num_6_positive = -scores_num_6

In [376]:
scores_num_6_positive

array([24255.26138556, 26804.32765829, 26333.29579001, 24981.81957371,
       23093.59491315])

In [377]:
scores_num_6_positive.mean()

np.float64(25093.6598641435)

In [378]:
scores_num_6_positive.std()

np.float64(1354.8993762072917)

In [379]:
# Experiment 7 with numerical feature(7 feature)
X_num_7 = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', 'Fireplaces', 'YearBuilt']]
y_num_7 = dataset['SalePrice']

In [380]:
X_train_num_7, X_test_num_7, y_train_num_7, y_test_num_7 = train_test_split(X_num_7, y_num_7, test_size=0.20, random_state=42)

In [381]:
pipeline_num_7 = Pipeline([
    ('model', LinearRegression())
])

In [382]:
scores_num_7 = cross_val_score(
    pipeline_num_7,
    X_train_num_7,
    y_train_num_7,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [383]:
scores_num_7_positive = -scores_num_7

In [384]:
scores_num_7_positive

array([23867.73166943, 25990.24301532, 25051.16998777, 24101.89511806,
       22631.58319117])

In [385]:
scores_num_7_positive.mean()

np.float64(24328.524596349074)

In [386]:
scores_num_7_positive.std()

np.float64(1133.739444513933)

In [387]:
# Categorical baseline:
# Mean CV MAE ≈ $30,071.75

# Numerical baseline:
# Mean CV MAE ≈ $24,328.52

In [388]:
X_mixed = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', 'YearBuilt', 'Fireplaces', 'ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']]
y_mixed = dataset['SalePrice']

In [389]:
X_mixed.shape

(1460, 14)

In [390]:
X_mixed.dtypes

OverallQual     int64
GrLivArea       int64
GarageCars      int64
GarageArea      int64
TotalBsmtSF     int64
YearBuilt       int64
Fireplaces      int64
ExterQual         str
KitchenQual       str
BsmtQual          str
GarageFinish      str
GarageType        str
FireplaceQu       str
MasVnrType        str
dtype: object

In [391]:
X_mixed_train, X_mixed_test, y_mixed_train, y_mixed_test = train_test_split(X_mixed, y_mixed, test_size=0.20, random_state=42)

In [392]:
numerical_features = ['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', 'YearBuilt', 'Fireplaces']
categorical_features = ['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']

In [393]:
preprocessor = ColumnTransformer([
    ('num', 'passthrough', numerical_features),
    ('cat', OneHotEncoder(), categorical_features)
])

In [394]:
pipeline_mixed = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

In [395]:
# X_mixed_transformed = preprocessor.fit_transform(X_mixed_train)

In [396]:
# X_mixed_transformed.shape

In [397]:
scores_mixed = cross_val_score(
    pipeline_mixed,
    X_mixed_train,
    y_mixed_train,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [398]:
scores_mixed

array([-20812.47774173, -23090.59207415, -22234.1485784 , -22020.92649641,
       -19538.72482869])

In [399]:
positive_scores_mixed = -scores_mixed

In [400]:
positive_scores_mixed

array([20812.47774173, 23090.59207415, 22234.1485784 , 22020.92649641,
       19538.72482869])

In [401]:
positive_scores_mixed.mean()

np.float64(21539.373943875515)

In [402]:
positive_scores_mixed.std()

np.float64(1237.0818333558414)

In [403]:
# Linear Regression
# Mixed baseline
# 24 features
# Mean CV MAE ≈ $19000.17
# Std ≈ $1232.63

In [404]:
X_mixed_2 = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF',  'YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'MasVnrArea', 'Fireplaces', 'BsmtFinSF1', 'WoodDeckSF', 'LotArea', 'OverallCond', 'MSSubClass', 'EnclosedPorch', 'KitchenAbvGr', 'ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']]
y_mixed_2 = dataset['SalePrice']

In [405]:
X_mixed_train_2, X_mixed_test_2, y_mixed_train_2, y_mixed_test_2 = train_test_split(X_mixed_2, y_mixed_2, test_size=0.20, random_state=42)

In [406]:
numerical_features_2 = ['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF',  'YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'MasVnrArea', 'Fireplaces', 'BsmtFinSF1', 'WoodDeckSF', 'LotArea', 'OverallCond', 'MSSubClass', 'EnclosedPorch', 'KitchenAbvGr']
categorical_features_2 = ['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']

In [407]:
preprocessor_2 = ColumnTransformer([
    ('num', 'passthrough', numerical_features_2),
    ('cat', OneHotEncoder(), categorical_features_2)
])

In [408]:
pipeline_mixed_2 = Pipeline([
    ('preprocessor_2', preprocessor_2),
    ('model', LinearRegression())
])

In [409]:
scores_mixed_2 = cross_val_score(
    pipeline_mixed_2,
    X_mixed_train_2,
    y_mixed_train_2,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [410]:
scores_mixed_2

array([-18361.13430324, -19554.58089335, -20702.38317117, -19347.9554425 ,
       -17034.80065002])

In [411]:
positive_scores_mixed_2 = -scores_mixed_2

In [412]:
positive_scores_mixed_2

array([18361.13430324, 19554.58089335, 20702.38317117, 19347.9554425 ,
       17034.80065002])

In [413]:
positive_scores_mixed_2.mean()

np.float64(19000.170892057755)

In [414]:
positive_scores_mixed_2.std()

np.float64(1232.631261680859)

In [ ]:
# Decision Tree Regressor
# Mixed baseline
# 24 features
# Mean CV MAE ≈ $26826.21
# Std ≈ $1491.49

In [418]:
# Experiment with DecisionTreeRegressor
X_mixed_3 = dataset[['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF',  'YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'MasVnrArea', 'Fireplaces', 'BsmtFinSF1', 'WoodDeckSF', 'LotArea', 'OverallCond', 'MSSubClass', 'EnclosedPorch', 'KitchenAbvGr', 'ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']]
y_mixed_3 = dataset['SalePrice']

In [419]:
X_mixed_train_3, X_mixed_test_3, y_mixed_train_3, y_mixed_test_3 = train_test_split(X_mixed_3, y_mixed_3, test_size=0.20, random_state=42)

In [420]:
numerical_features_3 = ['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF',  'YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'MasVnrArea', 'Fireplaces', 'BsmtFinSF1', 'WoodDeckSF', 'LotArea', 'OverallCond', 'MSSubClass', 'EnclosedPorch', 'KitchenAbvGr']
categorical_features_3 = ['ExterQual', 'KitchenQual', 'BsmtQual', 'GarageFinish', 'GarageType', 'FireplaceQu', 'MasVnrType']

In [421]:
preprocessor_3 = ColumnTransformer([
    ('num', 'passthrough', numerical_features_3),
    ('cat', OneHotEncoder(), categorical_features_3)
])

In [438]:
pipeline_mixed_3 = Pipeline([
    ('preprocessor_3', preprocessor_3),
    ('model', DecisionTreeRegressor())
])

In [439]:
scores_mixed_3 = cross_val_score(
    pipeline_mixed_3,
    X_mixed_train_3,
    y_mixed_train_3,
    cv=kf,
    scoring='neg_mean_absolute_error'
)

In [440]:
scores_mixed_3

array([-25180.86324786, -25490.25641026, -28564.05128205, -28821.81545064,
       -23666.68240343])

In [441]:
positive_scores_mixed_3 = -scores_mixed_3

In [442]:
positive_scores_mixed_3

array([25180.86324786, 25490.25641026, 28564.05128205, 28821.81545064,
       23666.68240343])

In [443]:
positive_scores_mixed_3.mean()

np.float64(26344.733758849638)

In [444]:
positive_scores_mixed_3.std()

np.float64(2015.836756508849)