In [1]:
# Import dependences
import pandas as pd

In [2]:
# Read the Dataset
dataset = pd.read_csv("train.csv")
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
# View dataset statistics
dataset.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,...,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,...,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,...,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,...,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,...,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,...,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [4]:
# Checking missing values
missing_values = dataset.isnull().sum().sum()
print(f"Are any features missing data? Answer:", "No" if missing_values == 0 else "Yes")

Are any features missing data? Answer: Yes

In [5]:
# How to get column names, data types and column counts
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [6]:
# SalePrice statistics
sale_price_count = dataset['SalePrice'].count()
print(f"How many SalePrice values do I have? Answer: {sale_price_count}")

sale_price_mean = dataset['SalePrice'].mean()
print(f"What is the average house price? Answer: {sale_price_mean:.3f}")

sale_price_median = dataset['SalePrice'].median()
print(f"What's the median house price? Answer: {sale_price_median}")

sale_price_std = dataset['SalePrice'].std()
print(f"How spread out are the prices? Answer: {sale_price_std:.3f}")

sale_price_min = dataset['SalePrice'].min()
print(f"What is the cheapest house? Answer: {sale_price_min}")

sale_price_max= dataset['SalePrice'].max()
print(f"What is the most expensive house? Answer: {sale_price_max}")

sale_price_null = dataset['SalePrice'].isnull().sum()
print(f"Is there a null value in the SalePrice column? Answer: ", "No" if sale_price_null == 0 else "Yes")

How many SalePrice values do I have? Answer: 1460
What is the average house price? Answer: 180921.196
What's the median house price? Answer: 163000.0
How spread out are the prices? Answer: 79442.503
What is the cheapest house? Answer: 34900
What is the most expensive house? Answer: 755000
Is there a null value in the SalePrice column? Answer:  No

In [7]:
# View Correlation of SalePrice to other features in descending order
dataset.corr(numeric_only=True)['SalePrice'].sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [8]:
# Categorical Features
neighborhood_uniqe_values = dataset["Neighborhood"].nunique()
print(f"How many unique value are in Neighborhood? Answer: {neighborhood_uniqe_values}")

How many unique value are in Neighborhood? Answer: 25

In [9]:
# Grouping neighborhood and there average prices
dataset.groupby(["Neighborhood"])['SalePrice'].mean().sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [10]:
# Getting categorical feature unique values
dataset.select_dtypes('str').nunique().sort_values()

Street            2
Alley             2
CentralAir        2
Utilities         2
MasVnrType        3
LandSlope         3
PoolQC            3
PavedDrive        3
GarageFinish      3
BsmtQual          4
ExterQual         4
KitchenQual       4
BsmtCond          4
BsmtExposure      4
Fence             4
MiscFeature       4
LandContour       4
LotShape          4
FireplaceQu       5
Electrical        5
HeatingQC         5
GarageQual        5
GarageCond        5
MSZoning          5
LotConfig         5
BldgType          5
ExterCond         5
BsmtFinType1      6
RoofStyle         6
GarageType        6
Foundation        6
Heating           6
BsmtFinType2      6
SaleCondition     6
Functional        7
RoofMatl          8
HouseStyle        8
Condition2        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [11]:
dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
FireplaceQu       690
GarageType         81
GarageCond         81
GarageQual         81
GarageFinish       81
BsmtFinType2       38
BsmtExposure       38
BsmtFinType1       37
BsmtQual           37
BsmtCond           37
Electrical          1
KitchenQual         0
CentralAir          0
Functional          0
HeatingQC           0
Heating             0
PavedDrive          0
SaleType            0
MSZoning            0
Street              0
Condition2          0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
BldgType            0
Foundation          0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
SaleCondition       0
dtype: int64

In [12]:
dataset['PoolQC'].value_counts()

PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

In [13]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [14]:
dataset['Alley'].value_counts()

Alley
Grvl    50
Pave    41
Name: count, dtype: int64

In [15]:
dataset[['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageCond', 'GarageQual', 'GarageFinish', 'BsmtFinType2', 'BsmtExposure', 'BsmtFinType1', 'BsmtQual', 'BsmtCond']]

,PoolQC,MiscFeature,Alley,Fence,FireplaceQu,GarageType,GarageCond,GarageQual,GarageFinish,BsmtFinType2,BsmtExposure,BsmtFinType1,BsmtQual,BsmtCond
0,NaN,NaN,NaN,NaN,NaN,Attchd,TA,TA,RFn,Unf,No,GLQ,Gd,TA
1,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Gd,ALQ,Gd,TA
2,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Mn,GLQ,Gd,TA
3,NaN,NaN,NaN,NaN,Gd,Detchd,TA,TA,Unf,Unf,No,ALQ,TA,Gd
4,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Av,GLQ,Gd,TA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,No,Unf,Gd,TA
1456,NaN,NaN,NaN,MnPrv,TA,Attchd,TA,TA,Unf,Rec,No,ALQ,Gd,TA
1457,NaN,Shed,NaN,GdPrv,Gd,Attchd,TA,TA,RFn,Unf,No,GLQ,TA,Gd
1458,NaN,NaN,NaN,NaN,NaN,Attchd,TA,TA,Unf,Rec,Mn,GLQ,TA,TA
1459,NaN,NaN,NaN,NaN,NaN,Attchd,TA,TA,Fin,LwQ,No,BLQ,TA,TA

In [16]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [17]:
dataset[dataset['MasVnrType'].isnull()]['MasVnrArea'].value_counts(dropna=False)

MasVnrArea
0.0      859
NaN        8
1.0        2
288.0      1
344.0      1
312.0      1
Name: count, dtype: int64

In [18]:
dataset[dataset['MasVnrType'].isnull() & (dataset['MasVnrArea'] != 0)][['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
624         NaN       288.0
650         NaN         NaN
773         NaN         1.0
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1230        NaN         1.0
1243        NaN         NaN
1278        NaN         NaN
1300        NaN       344.0
1334        NaN       312.0

In [19]:
dataset.loc[
    [624, 773, 1230, 1300, 1334],
    ['MasVnrType', 'MasVnrArea', 'OverallQual',
     'YearBuilt', 'YearRemodAdd', 'Neighborhood', 
     'HouseStyle']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,Neighborhood,HouseStyle
624,NaN,288.0,6,1972,1972,NWAmes,2Story
773,NaN,1.0,5,1958,1958,NAmes,1Story
1230,NaN,1.0,5,1977,1977,Sawyer,1.5Fin
1300,NaN,344.0,7,1999,1999,Gilbert,2Story
1334,NaN,312.0,5,1970,1970,BrDale,2Story

In [20]:
# Investigating cell 624
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['HouseStyle'] == '2Story')
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
7         Stone       240.0            7       1973          1973
152     BrkFace       252.0            6       1971          1971
222         NaN         0.0            6       1975          1975
293     BrkFace        34.0            7       1977          1994
298     BrkFace       365.0            6       1968          1968
316     BrkFace       278.0            7       1980          1980
364     BrkFace       120.0            6       1976          1976
471         NaN         0.0            7       1977          1977
621         NaN         0.0            6       1974          1997
624         NaN       288.0            6       1972          1972
643     BrkFace       263.0            5       1969          1969
660     BrkFace       233.0            7       1976          1976
745     BrkFace       289.0            8       1976          1996
766     BrkFace        42.0            7       1988          1988
859     BrkFace       220.0            6       1968          1984
927     BrkFace       342.0            7       1968          1968
961     BrkFace       424.0            6       1977          1995
988     BrkFace       298.0            6       1976          1976
1015        NaN         0.0            8       2001          2001
1041    BrkFace       252.0            6       1966          2000
1071        NaN         0.0            6       1968          1968
1111    BrkFace       660.0            7       1976          1976
1141    BrkFace        44.0            5       1976          1976
1159    BrkFace       270.0            6       1974          1974
1276        NaN         0.0            6       1972          1972
1293        NaN         0.0            7       1976          1976
1386    BrkFace       184.0            7       1978          1978
1409    BrkFace       123.0            7       1986          1991
1420    BrkFace       420.0            6       1968          1968

In [21]:
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['MasVnrArea'].between(250, 350))
][['MasVnrType', 'MasVnrArea', 'Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea Neighborhood  OverallQual  YearBuilt  YearRemodAdd
135     BrkFace       288.0       NWAmes            7       1970          1970
152     BrkFace       252.0       NWAmes            6       1971          1971
316     BrkFace       278.0       NWAmes            7       1980          1980
455     BrkFace       320.0       NWAmes            7       1973          1973
516     BrkFace       333.0       NWAmes            6       1972          1972
624         NaN       288.0       NWAmes            6       1972          1972
643     BrkFace       263.0       NWAmes            5       1969          1969
745     BrkFace       289.0       NWAmes            8       1976          1996
927     BrkFace       342.0       NWAmes            7       1968          1968
988     BrkFace       298.0       NWAmes            6       1976          1976
1041    BrkFace       252.0       NWAmes            6       1966          2000
1159    BrkFace       270.0       NWAmes            6       1974          1974
1429    BrkFace       310.0       NWAmes            6       1981          1981

In [22]:
dataset.loc[624, ['MasVnrType']] = 'BrkFace'

In [23]:
dataset.loc[624, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      288.0
Name: 624, dtype: object

In [24]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
14      BrkFace       212.0            6       1960          1960
16      BrkFace       180.0            6       1970          1970
37      BrkFace       650.0            5       1954          1990
40      BrkFace       101.0            6       1965          1965
55      BrkFace       272.0            6       1964          1964
...         ...         ...          ...        ...           ...
1295    BrkFace       168.0            5       1968          1968
1296    BrkFace       148.0            5       1963          1963
1356    BrkFace        65.0            5       1966          1966
1425      Stone       243.0            6       1959          1959
1435    BrkFace       237.0            6       1962          2005

[64 rows x 5 columns]

In [25]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['YearBuilt'].between(1955, 1961)) &
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
14      BrkFace       212.0            6       1960          1960     1Story
83       BrkCmn        66.0            5       1960          1960     1Story
91       BrkCmn       203.0            5       1961          1961     1Story
122     BrkFace       135.0            6       1958          1958     1Story
129     BrkFace        85.0            5       1958          1991     1Story
171       Stone       112.0            6       1960          1960     1Story
173      BrkCmn       491.0            6       1961          1961     1Story
215     BrkFace        64.0            5       1957          1996     1Story
230     BrkFace       220.0            6       1959          1959     1Story
273      BrkCmn       183.0            6       1958          1988     1Story
327     BrkFace       175.0            6       1960          1960     1Story
339     BrkFace       176.0            6       1958          1998     1Story
347     BrkFace        30.0            6       1960          1960     1Story
424     BrkFace        74.0            6       1956          1956     1Story
509     BrkFace       132.0            5       1959          1959     1Story
571     BrkFace       207.0            6       1959          1959     1Story
580     BrkFace        85.0            6       1960          1987     1Story
627     BrkFace       164.0            6       1955          1972       SLvl
656     BrkFace        54.0            5       1959          2006     1Story
728     BrkFace        95.0            5       1958          1958     1Story
773         NaN         1.0            5       1958          1958     1Story
813     BrkFace       243.0            6       1958          1958     1Story
830     BrkFace       387.0            6       1957          1957     1Story
834     BrkFace       136.0            5       1961          1961     1Story
886     BrkFace       122.0            5       1959          2005     1Story
910     BrkFace       361.0            5       1960          1960     2Story
946     BrkFace       128.0            5       1959          1959       SLvl
967     BrkFace       151.0            5       1955          1955     1Story
969     BrkFace       105.0            6       1958          1958       SLvl
980       Stone       210.0            7       1961          2007     SFoyer
1026    BrkFace       324.0            5       1960          1960     1Story
1070    BrkFace       120.0            5       1956          1956     1Story
1102    BrkFace        45.0            5       1960          2002     1Story
1225    BrkFace        63.0            6       1958          1958       SLvl
1233    BrkFace       180.0            5       1959          1959     1Story
1269    BrkFace       180.0            5       1958          1958     1.5Fin
1425      Stone       243.0            6       1959          1959     1Story

In [26]:
dataset[(dataset['MasVnrArea'] <= 10) &
(dataset['MasVnrArea'] > 0)][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
773         NaN         1.0            5       1958          1958     1Story
1230        NaN         1.0            5       1977          1977     1.5Fin

In [ ]:
# Investigating cell 1230
dataset.loc[1230, ['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

Neighborhood     Sawyer
MasVnrType          NaN
MasVnrArea          1.0
OverallQual           5
YearBuilt          1977
YearRemodAdd       1977
HouseStyle       1.5Fin
MSSubClass           90
MSZoning             RL
Street             Pave
Exterior1st     Plywood
Exterior2nd     Plywood
Name: 1230, dtype: object

In [46]:
dataset[
    (dataset['MasVnrType'].isnull()) &
    (dataset['MasVnrArea'] > 0)
    ][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,Exterior1st,Exterior2nd
773,NAmes,NaN,1.0,5,1958,1958,1Story,Wd Sdng,Wd Sdng
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,Plywood,Plywood
1300,Gilbert,NaN,344.0,7,1999,1999,2Story,VinylSd,VinylSd
1334,BrDale,NaN,312.0,5,1970,1970,2Story,HdBoard,HdBoard

In [51]:
# Investigating row 1300
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['YearBuilt'].between(1997, 2001))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
72,BrkFace,40.0,7,1998,1998,2Story,60,RL,Pave,VinylSd,VinylSd
131,BrkFace,40.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
147,BrkFace,180.0,7,2001,2001,2Story,60,RL,Pave,VinylSd,VinylSd
255,BrkFace,302.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
379,BrkFace,16.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
665,BrkFace,40.0,8,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
929,BrkFace,285.0,7,1997,1997,2Story,60,RL,Pave,HdBoard,HdBoard
941,BrkFace,298.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1300,BrkFace,344.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1433,BrkFace,318.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd

In [48]:
dataset.loc[1300, ['MasVnrType']] = 'BrkFace'

In [50]:
dataset.loc[1300, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      344.0
Name: 1300, dtype: object

In [52]:
# Investigating row 1334
dataset[(dataset['Neighborhood'] == 'BrDale') &
(dataset['YearBuilt'].between(1965, 1975))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
225,BrkFace,142.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
227,BrkFace,127.0,6,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
232,BrkFace,297.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
235,BrkFace,604.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
363,BrkFace,510.0,6,1972,2007,2Story,160,RM,Pave,HdBoard,HdBoard
430,BrkFace,232.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
432,BrkFace,376.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
500,BrkFace,285.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
655,BrkFace,381.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,ImStucc
837,BrkFace,158.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
1029,BrkFace,281.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
1104,BrkFace,304.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1219,BrkFace,236.0,6,1971,1971,2Story,160,RM,Pave,CemntBd,CmentBd
1291,BrkFace,268.0,5,1972,1972,2Story,160,RM,Pave,CemntBd,CmentBd
1334,NaN,312.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1378,BrkFace,408.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard

In [53]:
dataset.loc[1334, ['MasVnrType']] = 'BrkFace'

In [54]:
dataset.loc[1334, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1334, dtype: str

In [55]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['YearBuilt'].between(1956, 1960))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
83,NAmes,BrkCmn,66.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,MetalSd
129,NAmes,BrkFace,85.0,5,1958,1991,1Story,20,RL,Pave,Plywood,Plywood
215,NAmes,BrkFace,64.0,5,1957,1996,1Story,20,RL,Pave,HdBoard,HdBoard
509,NAmes,BrkFace,132.0,5,1959,1959,1Story,20,RL,Pave,MetalSd,MetalSd
656,NAmes,BrkFace,54.0,5,1959,2006,1Story,20,RL,Pave,HdBoard,HdBoard
728,NAmes,BrkFace,95.0,5,1958,1958,1Story,90,RL,Pave,VinylSd,VinylSd
773,NAmes,NaN,1.0,5,1958,1958,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
886,NAmes,BrkFace,122.0,5,1959,2005,1Story,90,RL,Pave,MetalSd,MetalSd
1026,NAmes,BrkFace,324.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,HdBoard
1070,NAmes,BrkFace,120.0,5,1956,1956,1Story,20,RL,Pave,MetalSd,MetalSd
1102,NAmes,BrkFace,45.0,5,1960,2002,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
1233,NAmes,BrkFace,180.0,5,1959,1959,1Story,20,RL,Pave,Plywood,Plywood

In [56]:
dataset.loc[773, ['MasVnrType']] = 'BrkFace'

In [57]:
dataset.loc[773, ['MasVnrType']]

MasVnrType    BrkFace
Name: 773, dtype: str

In [64]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['YearBuilt'].between(1970, 1985))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave,Plywood,Plywood
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave,Plywood,Plywood

In [65]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['Exterior1st'] == 'Plywood') &
(dataset['Exterior2nd'] == 'Plywood') &
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street
538,Sawyer,BrkFace,188.0,5,1968,1968,1Story,20,RL,Pave
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave
796,Sawyer,BrkFace,148.0,6,1977,1977,1Story,20,RL,Pave
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave

In [66]:
dataset.loc[1230, ['MasVnrType']] = 'BrkFace'

In [67]:
dataset.loc[1230, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1230, dtype: str

In [76]:
dataset.loc[[624, 773, 1230, 1300, 1334], ['Neighborhood','MasVnrType']]

     Neighborhood MasVnrType
624        NWAmes    BrkFace
773         NAmes    BrkFace
1230       Sawyer    BrkFace
1300      Gilbert    BrkFace
1334       BrDale    BrkFace

In [78]:
dataset[dataset['MasVnrType'].isnull() &
dataset['MasVnrArea'].isnull()][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street
234,Gilbert,NaN,NaN,6,2002,2002,2Story,60,RL,Pave
529,Crawfor,NaN,NaN,6,1957,1975,1Story,20,RL,Pave
650,Somerst,NaN,NaN,7,2007,2007,2Story,60,FV,Pave
936,SawyerW,NaN,NaN,7,2003,2003,1Story,20,RL,Pave
973,Somerst,NaN,NaN,7,2007,2008,1Story,20,FV,Pave
977,Somerst,NaN,NaN,7,2006,2007,1Story,120,FV,Pave
1243,NridgHt,NaN,NaN,10,2006,2006,1Story,20,RL,Pave
1278,CollgCr,NaN,NaN,8,2002,2002,2Story,60,RL,Pave

In [79]:
dataset.groupby('MasVnrType', dropna=False)['MasVnrArea'].agg(
    ['count', 'min', 'mean', 'max']
)

            count   min        mean     max
MasVnrType
BrkCmn         15  41.0  247.666667   621.0
BrkFace       450   0.0  258.233333  1600.0
Stone         128   0.0  239.304688   860.0
NaN           859   0.0    0.000000     0.0

In [27]:
absent_features = dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)
absent_features[absent_features > 0]

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       871
FireplaceQu      690
GarageType        81
GarageCond        81
GarageQual        81
GarageFinish      81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtQual          37
BsmtCond          37
Electrical         1
dtype: int64

In [28]:
dataset[dataset['Electrical'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1379,1380,80,RL,73.0,9735,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500

In [29]:
dataset['Electrical'].value_counts()

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

In [30]:
dataset.loc[1379, ['Electrical', 'OverallQual', 'YearBuilt', 'YearRemodAdd',
                   'Neighborhood', 'HouseStyle', 'CentralAir']]

Electrical         NaN
OverallQual          5
YearBuilt         2006
YearRemodAdd      2007
Neighborhood    Timber
HouseStyle        SLvl
CentralAir           Y
Name: 1379, dtype: object

In [31]:
dataset[dataset['Neighborhood'] == 'Timber']['Electrical'].value_counts()

Electrical
SBrkr    36
FuseA     1
Name: count, dtype: int64

In [32]:
dataset[dataset['YearBuilt'] >= 2000]['Electrical'].value_counts()

Electrical
SBrkr    387
Name: count, dtype: int64

In [33]:
dataset[
    (dataset['Neighborhood'] == 'Timber') & 
    (dataset['YearBuilt'] >= 2000) & 
    (dataset['HouseStyle'] == 'SLvl')]['Electrical'].value_counts(dropna=False)

Electrical
SBrkr    1
NaN      1
Name: count, dtype: int64

In [34]:
dataset[dataset['Neighborhood'] == 'Timber'][['Electrical', 'SalePrice']].sort_values('SalePrice')

     Electrical  SalePrice
944       FuseA     137500
1396      SBrkr     160000
1379        NaN     167500
41        SBrkr     170000
429       SBrkr     175000
530       SBrkr     175000
695       SBrkr     176000
1281      SBrkr     180000
174       SBrkr     184000
1184      SBrkr     186700
881       SBrkr     187500
731       SBrkr     187500
930       SBrkr     201000
340       SBrkr     202900
452       SBrkr     204000
964       SBrkr     214900
133       SBrkr     220000
572       SBrkr     224500
169       SBrkr     228000
335       SBrkr     228950
1375      SBrkr     239000
866       SBrkr     248900
1180      SBrkr     250000
1239      SBrkr     265900
157       SBrkr     269500
947       SBrkr     270000
1395      SBrkr     281213
1347      SBrkr     283463
1024      SBrkr     287000
1027      SBrkr     293077
619       SBrkr     305000
700       SBrkr     312500
540       SBrkr     315000
1036      SBrkr     315500
692       SBrkr     335000
585       SBrkr     369900
313       SBrkr     375000
1267      SBrkr     378500

In [35]:
dataset.loc[1379, ['Electrical']] = 'SBrkr'

In [36]:
dataset.loc[1379, ['Electrical']]

Electrical    SBrkr
Name: 1379, dtype: str

In [37]:
dataset['Electrical'].isnull().sum()

np.int64(0)

In [38]:
dataset[dataset['MasVnrType'].isnull()]['MasVnrArea'].sort_values(ascending=False)

1300    344.0
1334    312.0
1230      1.0
773       1.0
989       0.0
        ...
936       NaN
973       NaN
977       NaN
1243      NaN
1278      NaN
Name: MasVnrArea, Length: 871, dtype: float64

In [39]:

# training_df = dataset.loc[('SalePrice', 'Neighborhood', 'Utilities', 'HouseStyle', 'YearBuilt', 'YearRemodAdd', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'Bedroom', 'Kitchen', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageArea', 'PoolArea', 'Fence', 'MiscFeature', 'MiscVal', 'SaleType', 'SaleCondition')]
# training_df.head(50)