In [264]:
# Import dependences
import pandas as pd
from sklearn.model_selection import train_test_split
from scipy.stats import f_oneway
# pd.set_option('display.max_rows', None)

In [2]:
# Read the Dataset
dataset = pd.read_csv("train.csv")
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
# View dataset statistics
dataset.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,...,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,...,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,...,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,...,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,...,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,...,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [4]:
# Checking missing values
missing_values = dataset.isnull().sum().sum()
print(f"Are any features missing data? Answer:", "No" if missing_values == 0 else "Yes")

Are any features missing data? Answer: Yes

In [5]:
# How to get column names, data types and column counts
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [6]:
# SalePrice statistics
sale_price_count = dataset['SalePrice'].count()
print(f"How many SalePrice values do I have? Answer: {sale_price_count}")

sale_price_mean = dataset['SalePrice'].mean()
print(f"What is the average house price? Answer: {sale_price_mean:.3f}")

sale_price_median = dataset['SalePrice'].median()
print(f"What's the median house price? Answer: {sale_price_median}")

sale_price_std = dataset['SalePrice'].std()
print(f"How spread out are the prices? Answer: {sale_price_std:.3f}")

sale_price_min = dataset['SalePrice'].min()
print(f"What is the cheapest house? Answer: {sale_price_min}")

sale_price_max= dataset['SalePrice'].max()
print(f"What is the most expensive house? Answer: {sale_price_max}")

sale_price_null = dataset['SalePrice'].isnull().sum()
print(f"Is there a null value in the SalePrice column? Answer: ", "No" if sale_price_null == 0 else "Yes")

How many SalePrice values do I have? Answer: 1460
What is the average house price? Answer: 180921.196
What's the median house price? Answer: 163000.0
How spread out are the prices? Answer: 79442.503
What is the cheapest house? Answer: 34900
What is the most expensive house? Answer: 755000
Is there a null value in the SalePrice column? Answer:  No

In [7]:
# View Correlation of SalePrice to other features in descending order
dataset.corr(numeric_only=True)['SalePrice'].sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [8]:
# Categorical Features
neighborhood_uniqe_values = dataset["Neighborhood"].nunique()
print(f"How many unique value are in Neighborhood? Answer: {neighborhood_uniqe_values}")

How many unique value are in Neighborhood? Answer: 25

In [9]:
# Grouping neighborhood and there average prices
dataset.groupby(["Neighborhood"])['SalePrice'].mean().sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [10]:
# Getting categorical feature unique values
dataset.select_dtypes('str').nunique().sort_values()

Street            2
Alley             2
CentralAir        2
Utilities         2
MasVnrType        3
LandSlope         3
PoolQC            3
PavedDrive        3
GarageFinish      3
BsmtQual          4
ExterQual         4
KitchenQual       4
BsmtCond          4
BsmtExposure      4
Fence             4
MiscFeature       4
LandContour       4
LotShape          4
FireplaceQu       5
Electrical        5
HeatingQC         5
GarageQual        5
GarageCond        5
MSZoning          5
LotConfig         5
BldgType          5
ExterCond         5
BsmtFinType1      6
RoofStyle         6
GarageType        6
Foundation        6
Heating           6
BsmtFinType2      6
SaleCondition     6
Functional        7
RoofMatl          8
HouseStyle        8
Condition2        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [11]:
dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
FireplaceQu       690
GarageType         81
GarageCond         81
GarageQual         81
GarageFinish       81
BsmtFinType2       38
BsmtExposure       38
BsmtFinType1       37
BsmtQual           37
BsmtCond           37
Electrical          1
KitchenQual         0
CentralAir          0
Functional          0
HeatingQC           0
Heating             0
PavedDrive          0
SaleType            0
MSZoning            0
Street              0
Condition2          0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
BldgType            0
Foundation          0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
SaleCondition       0
dtype: int64

In [12]:
dataset['PoolQC'].value_counts()

PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

In [13]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [14]:
dataset['Alley'].value_counts()

Alley
Grvl    50
Pave    41
Name: count, dtype: int64

In [15]:
dataset[['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageCond', 'GarageQual', 'GarageFinish', 'BsmtFinType2', 'BsmtExposure', 'BsmtFinType1', 'BsmtQual', 'BsmtCond']].head(20)

,PoolQC,MiscFeature,Alley,Fence,FireplaceQu,GarageType,GarageCond,GarageQual,GarageFinish,BsmtFinType2,BsmtExposure,BsmtFinType1,BsmtQual,BsmtCond
0,NaN,NaN,NaN,NaN,NaN,Attchd,TA,TA,RFn,Unf,No,GLQ,Gd,TA
1,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Gd,ALQ,Gd,TA
2,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Mn,GLQ,Gd,TA
3,NaN,NaN,NaN,NaN,Gd,Detchd,TA,TA,Unf,Unf,No,ALQ,TA,Gd
4,NaN,NaN,NaN,NaN,TA,Attchd,TA,TA,RFn,Unf,Av,GLQ,Gd,TA
5,NaN,Shed,NaN,MnPrv,NaN,Attchd,TA,TA,Unf,Unf,No,GLQ,Gd,TA
6,NaN,NaN,NaN,NaN,Gd,Attchd,TA,TA,RFn,Unf,Av,GLQ,Ex,TA
7,NaN,Shed,NaN,NaN,TA,Attchd,TA,TA,RFn,BLQ,Mn,ALQ,Gd,TA
8,NaN,NaN,NaN,NaN,TA,Detchd,TA,Fa,Unf,Unf,No,Unf,TA,TA
9,NaN,NaN,NaN,NaN,TA,Attchd,TA,Gd,RFn,Unf,No,GLQ,TA,TA
10,NaN,NaN,NaN,NaN,NaN,Detchd,TA,TA,Unf,Unf,No,Rec,TA,TA
11,NaN,NaN,NaN,NaN,Gd,BuiltIn,TA,TA,Fin,Unf,No,GLQ,Ex,TA
12,NaN,NaN,NaN,NaN,NaN,Detchd,TA,TA,Unf,Unf,No,ALQ,TA,TA
13,NaN,NaN,NaN,NaN,Gd,Attchd,TA,TA,RFn,Unf,Av,Unf,Gd,TA
14,NaN,NaN,NaN,GdWo,Fa,Attchd,TA,TA,RFn,Unf,No,BLQ,TA,TA
15,NaN,NaN,NaN,GdPrv,NaN,Detchd,TA,TA,Unf,Unf,No,Unf,TA,TA
16,NaN,Shed,NaN,NaN,TA,Attchd,TA,TA,Fin,Unf,No,ALQ,TA,TA
17,NaN,Shed,NaN,NaN,NaN,CarPort,TA,TA,Unf,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,Detchd,TA,TA,Unf,Unf,No,GLQ,TA,TA
19,NaN,NaN,NaN,MnPrv,NaN,Attchd,TA,TA,Unf,Unf,No,LwQ,TA,TA

In [16]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [17]:
dataset[dataset['MasVnrType'].isnull()]['MasVnrArea'].value_counts(dropna=False)

MasVnrArea
0.0      859
NaN        8
1.0        2
288.0      1
344.0      1
312.0      1
Name: count, dtype: int64

In [18]:
dataset[dataset['MasVnrType'].isnull() & (dataset['MasVnrArea'] != 0)][['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
624         NaN       288.0
650         NaN         NaN
773         NaN         1.0
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1230        NaN         1.0
1243        NaN         NaN
1278        NaN         NaN
1300        NaN       344.0
1334        NaN       312.0

In [19]:
dataset.loc[
    [624, 773, 1230, 1300, 1334],
    ['MasVnrType', 'MasVnrArea', 'OverallQual',
     'YearBuilt', 'YearRemodAdd', 'Neighborhood', 
     'HouseStyle']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,Neighborhood,HouseStyle
624,NaN,288.0,6,1972,1972,NWAmes,2Story
773,NaN,1.0,5,1958,1958,NAmes,1Story
1230,NaN,1.0,5,1977,1977,Sawyer,1.5Fin
1300,NaN,344.0,7,1999,1999,Gilbert,2Story
1334,NaN,312.0,5,1970,1970,BrDale,2Story

In [20]:
# Investigating cell 624
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['HouseStyle'] == '2Story')
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
7         Stone       240.0            7       1973          1973
152     BrkFace       252.0            6       1971          1971
222         NaN         0.0            6       1975          1975
293     BrkFace        34.0            7       1977          1994
298     BrkFace       365.0            6       1968          1968
316     BrkFace       278.0            7       1980          1980
364     BrkFace       120.0            6       1976          1976
471         NaN         0.0            7       1977          1977
621         NaN         0.0            6       1974          1997
624         NaN       288.0            6       1972          1972
643     BrkFace       263.0            5       1969          1969
660     BrkFace       233.0            7       1976          1976
745     BrkFace       289.0            8       1976          1996
766     BrkFace        42.0            7       1988          1988
859     BrkFace       220.0            6       1968          1984
927     BrkFace       342.0            7       1968          1968
961     BrkFace       424.0            6       1977          1995
988     BrkFace       298.0            6       1976          1976
1015        NaN         0.0            8       2001          2001
1041    BrkFace       252.0            6       1966          2000
1071        NaN         0.0            6       1968          1968
1111    BrkFace       660.0            7       1976          1976
1141    BrkFace        44.0            5       1976          1976
1159    BrkFace       270.0            6       1974          1974
1276        NaN         0.0            6       1972          1972
1293        NaN         0.0            7       1976          1976
1386    BrkFace       184.0            7       1978          1978
1409    BrkFace       123.0            7       1986          1991
1420    BrkFace       420.0            6       1968          1968

In [21]:
dataset[(dataset['Neighborhood'] == 'NWAmes') &
(dataset['MasVnrArea'].between(250, 350))
][['MasVnrType', 'MasVnrArea', 'Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea Neighborhood  OverallQual  YearBuilt  YearRemodAdd
135     BrkFace       288.0       NWAmes            7       1970          1970
152     BrkFace       252.0       NWAmes            6       1971          1971
316     BrkFace       278.0       NWAmes            7       1980          1980
455     BrkFace       320.0       NWAmes            7       1973          1973
516     BrkFace       333.0       NWAmes            6       1972          1972
624         NaN       288.0       NWAmes            6       1972          1972
643     BrkFace       263.0       NWAmes            5       1969          1969
745     BrkFace       289.0       NWAmes            8       1976          1996
927     BrkFace       342.0       NWAmes            7       1968          1968
988     BrkFace       298.0       NWAmes            6       1976          1976
1041    BrkFace       252.0       NWAmes            6       1966          2000
1159    BrkFace       270.0       NWAmes            6       1974          1974
1429    BrkFace       310.0       NWAmes            6       1981          1981

In [22]:
dataset.loc[624, ['MasVnrType']] = 'BrkFace'

In [23]:
dataset.loc[624, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      288.0
Name: 624, dtype: object

In [24]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd
14      BrkFace       212.0            6       1960          1960
16      BrkFace       180.0            6       1970          1970
37      BrkFace       650.0            5       1954          1990
40      BrkFace       101.0            6       1965          1965
55      BrkFace       272.0            6       1964          1964
...         ...         ...          ...        ...           ...
1295    BrkFace       168.0            5       1968          1968
1296    BrkFace       148.0            5       1963          1963
1356    BrkFace        65.0            5       1966          1966
1425      Stone       243.0            6       1959          1959
1435    BrkFace       237.0            6       1962          2005

[64 rows x 5 columns]

In [25]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['YearBuilt'].between(1955, 1961)) &
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
14      BrkFace       212.0            6       1960          1960     1Story
83       BrkCmn        66.0            5       1960          1960     1Story
91       BrkCmn       203.0            5       1961          1961     1Story
122     BrkFace       135.0            6       1958          1958     1Story
129     BrkFace        85.0            5       1958          1991     1Story
171       Stone       112.0            6       1960          1960     1Story
173      BrkCmn       491.0            6       1961          1961     1Story
215     BrkFace        64.0            5       1957          1996     1Story
230     BrkFace       220.0            6       1959          1959     1Story
273      BrkCmn       183.0            6       1958          1988     1Story
327     BrkFace       175.0            6       1960          1960     1Story
339     BrkFace       176.0            6       1958          1998     1Story
347     BrkFace        30.0            6       1960          1960     1Story
424     BrkFace        74.0            6       1956          1956     1Story
509     BrkFace       132.0            5       1959          1959     1Story
571     BrkFace       207.0            6       1959          1959     1Story
580     BrkFace        85.0            6       1960          1987     1Story
627     BrkFace       164.0            6       1955          1972       SLvl
656     BrkFace        54.0            5       1959          2006     1Story
728     BrkFace        95.0            5       1958          1958     1Story
773         NaN         1.0            5       1958          1958     1Story
813     BrkFace       243.0            6       1958          1958     1Story
830     BrkFace       387.0            6       1957          1957     1Story
834     BrkFace       136.0            5       1961          1961     1Story
886     BrkFace       122.0            5       1959          2005     1Story
910     BrkFace       361.0            5       1960          1960     2Story
946     BrkFace       128.0            5       1959          1959       SLvl
967     BrkFace       151.0            5       1955          1955     1Story
969     BrkFace       105.0            6       1958          1958       SLvl
980       Stone       210.0            7       1961          2007     SFoyer
1026    BrkFace       324.0            5       1960          1960     1Story
1070    BrkFace       120.0            5       1956          1956     1Story
1102    BrkFace        45.0            5       1960          2002     1Story
1225    BrkFace        63.0            6       1958          1958       SLvl
1233    BrkFace       180.0            5       1959          1959     1Story
1269    BrkFace       180.0            5       1958          1958     1.5Fin
1425      Stone       243.0            6       1959          1959     1Story

In [26]:
dataset[(dataset['MasVnrArea'] <= 10) &
(dataset['MasVnrArea'] > 0)][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle']]

     MasVnrType  MasVnrArea  OverallQual  YearBuilt  YearRemodAdd HouseStyle
773         NaN         1.0            5       1958          1958     1Story
1230        NaN         1.0            5       1977          1977     1.5Fin

In [27]:
# Investigating cell 1230
dataset.loc[1230, ['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

Neighborhood     Sawyer
MasVnrType          NaN
MasVnrArea          1.0
OverallQual           5
YearBuilt          1977
YearRemodAdd       1977
HouseStyle       1.5Fin
Exterior1st     Plywood
Exterior2nd     Plywood
Name: 1230, dtype: object

In [28]:
dataset[
    (dataset['MasVnrType'].isnull()) &
    (dataset['MasVnrArea'] > 0)
    ][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,Exterior1st,Exterior2nd
773,NAmes,NaN,1.0,5,1958,1958,1Story,Wd Sdng,Wd Sdng
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,Plywood,Plywood
1300,Gilbert,NaN,344.0,7,1999,1999,2Story,VinylSd,VinylSd
1334,BrDale,NaN,312.0,5,1970,1970,2Story,HdBoard,HdBoard

In [29]:
# Investigating row 1300
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['YearBuilt'].between(1997, 2001))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
72,BrkFace,40.0,7,1998,1998,2Story,60,RL,Pave,VinylSd,VinylSd
131,BrkFace,40.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
147,BrkFace,180.0,7,2001,2001,2Story,60,RL,Pave,VinylSd,VinylSd
255,BrkFace,302.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
379,BrkFace,16.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
665,BrkFace,40.0,8,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd
929,BrkFace,285.0,7,1997,1997,2Story,60,RL,Pave,HdBoard,HdBoard
941,BrkFace,298.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1300,NaN,344.0,7,1999,1999,2Story,60,RL,Pave,VinylSd,VinylSd
1433,BrkFace,318.0,6,2000,2000,2Story,60,RL,Pave,VinylSd,VinylSd

In [30]:
dataset.loc[1300, ['MasVnrType']] = 'BrkFace'

In [31]:
dataset.loc[1300, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      344.0
Name: 1300, dtype: object

In [32]:
# Investigating row 1334
dataset[(dataset['Neighborhood'] == 'BrDale') &
(dataset['YearBuilt'].between(1965, 1975))&
(dataset['MasVnrArea'] > 0)
][['MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
225,BrkFace,142.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
227,BrkFace,127.0,6,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
232,BrkFace,297.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
235,BrkFace,604.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
363,BrkFace,510.0,6,1972,2007,2Story,160,RM,Pave,HdBoard,HdBoard
430,BrkFace,232.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
432,BrkFace,376.0,5,1971,1971,2Story,160,RM,Pave,HdBoard,HdBoard
500,BrkFace,285.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
655,BrkFace,381.0,6,1971,1971,2Story,160,RM,Pave,HdBoard,ImStucc
837,BrkFace,158.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard
1029,BrkFace,281.0,6,1972,1972,2Story,160,RM,Pave,HdBoard,HdBoard
1104,BrkFace,304.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1219,BrkFace,236.0,6,1971,1971,2Story,160,RM,Pave,CemntBd,CmentBd
1291,BrkFace,268.0,5,1972,1972,2Story,160,RM,Pave,CemntBd,CmentBd
1334,NaN,312.0,5,1970,1970,2Story,160,RM,Pave,HdBoard,HdBoard
1378,BrkFace,408.0,6,1973,1973,2Story,160,RM,Pave,HdBoard,HdBoard

In [33]:
dataset.loc[1334, ['MasVnrType']] = 'BrkFace'

In [34]:
dataset.loc[1334, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1334, dtype: str

In [35]:
# Investigating cell 773
dataset[(dataset['Neighborhood'] == 'NAmes') &
(dataset['HouseStyle'] == '1Story')&
(dataset['YearBuilt'].between(1956, 1960))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
83,NAmes,BrkCmn,66.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,MetalSd
129,NAmes,BrkFace,85.0,5,1958,1991,1Story,20,RL,Pave,Plywood,Plywood
215,NAmes,BrkFace,64.0,5,1957,1996,1Story,20,RL,Pave,HdBoard,HdBoard
509,NAmes,BrkFace,132.0,5,1959,1959,1Story,20,RL,Pave,MetalSd,MetalSd
656,NAmes,BrkFace,54.0,5,1959,2006,1Story,20,RL,Pave,HdBoard,HdBoard
728,NAmes,BrkFace,95.0,5,1958,1958,1Story,90,RL,Pave,VinylSd,VinylSd
773,NAmes,NaN,1.0,5,1958,1958,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
886,NAmes,BrkFace,122.0,5,1959,2005,1Story,90,RL,Pave,MetalSd,MetalSd
1026,NAmes,BrkFace,324.0,5,1960,1960,1Story,20,RL,Pave,MetalSd,HdBoard
1070,NAmes,BrkFace,120.0,5,1956,1956,1Story,20,RL,Pave,MetalSd,MetalSd
1102,NAmes,BrkFace,45.0,5,1960,2002,1Story,20,RL,Pave,Wd Sdng,Wd Sdng
1233,NAmes,BrkFace,180.0,5,1959,1959,1Story,20,RL,Pave,Plywood,Plywood

In [36]:
dataset.loc[773, ['MasVnrType']] = 'BrkFace'

In [37]:
dataset.loc[773, ['MasVnrType']]

MasVnrType    BrkFace
Name: 773, dtype: str

In [38]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['YearBuilt'].between(1970, 1985))&
(dataset['OverallQual'] == 5)&
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave,Plywood,Plywood
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave,Plywood,Plywood

In [39]:
# Investigating cell 1230
dataset[(dataset['Neighborhood'] == 'Sawyer') &
(dataset['Exterior1st'] == 'Plywood') &
(dataset['Exterior2nd'] == 'Plywood') &
(dataset['MasVnrArea'] > 0)
][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street
538,Sawyer,BrkFace,188.0,5,1968,1968,1Story,20,RL,Pave
622,Sawyer,BrkFace,153.0,5,1977,1977,1Story,20,RL,Pave
796,Sawyer,BrkFace,148.0,6,1977,1977,1Story,20,RL,Pave
1230,Sawyer,NaN,1.0,5,1977,1977,1.5Fin,90,RL,Pave

In [40]:
dataset.loc[1230, ['MasVnrType']] = 'BrkFace'

In [41]:
dataset.loc[1230, ['MasVnrType']]

MasVnrType    BrkFace
Name: 1230, dtype: str

In [42]:
dataset.loc[[624, 773, 1230, 1300, 1334], ['Neighborhood','MasVnrType']]

     Neighborhood MasVnrType
624        NWAmes    BrkFace
773         NAmes    BrkFace
1230       Sawyer    BrkFace
1300      Gilbert    BrkFace
1334       BrDale    BrkFace

In [43]:
dataset[dataset['MasVnrType'].isnull() &
dataset['MasVnrArea'].isnull()][['Neighborhood', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
234,Gilbert,6,2002,2002,2Story,60,RL,Pave,VinylSd,VinylSd
529,Crawfor,6,1957,1975,1Story,20,RL,Pave,Wd Sdng,Stone
650,Somerst,7,2007,2007,2Story,60,FV,Pave,CemntBd,CmentBd
936,SawyerW,7,2003,2003,1Story,20,RL,Pave,VinylSd,VinylSd
973,Somerst,7,2007,2008,1Story,20,FV,Pave,CemntBd,CmentBd
977,Somerst,7,2006,2007,1Story,120,FV,Pave,VinylSd,VinylSd
1243,NridgHt,10,2006,2006,1Story,20,RL,Pave,VinylSd,VinylSd
1278,CollgCr,8,2002,2002,2Story,60,RL,Pave,VinylSd,VinylSd

In [44]:
dataset.groupby('MasVnrType', dropna=False)['MasVnrArea'].agg(
    ['count', 'min', 'mean', 'max']
)

            count   min        mean     max
MasVnrType
BrkCmn         15  41.0  247.666667   621.0
BrkFace       450   0.0  258.233333  1600.0
Stone         128   0.0  239.304688   860.0
NaN           859   0.0    0.000000     0.0

In [45]:
dataset['MasVnrArea'].isnull().sum()

np.int64(8)

In [46]:
dataset[dataset['MasVnrArea'].isnull()]['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN    8
Name: count, dtype: int64

In [47]:
dataset[['MasVnrType', 'MasVnrArea']].isnull().sum()

MasVnrType    867
MasVnrArea      8
dtype: int64

In [48]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        867
BrkFace    450
Stone      128
BrkCmn      15
Name: count, dtype: int64

In [49]:
dataset[dataset['MasVnrArea'] == 0]['MasVnrType'].value_counts(dropna=False)

MasVnrType
NaN        859
BrkFace      1
Stone        1
Name: count, dtype: int64

In [50]:
dataset[(dataset['MasVnrArea'] == 0) &
(dataset['MasVnrType'].notnull())][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'HouseStyle', 'MSSubClass', 'MSZoning', 'Street', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,OverallQual,YearBuilt,YearRemodAdd,HouseStyle,MSSubClass,MSZoning,Street,Exterior1st,Exterior2nd
688,StoneBr,BrkFace,0.0,8,2007,2007,1Story,20,RL,Pave,MetalSd,MetalSd
1241,Somerst,Stone,0.0,7,2007,2007,1Story,20,RL,Pave,VinylSd,VinylSd

In [51]:
dataset[(dataset['Neighborhood'] == 'StoneBr') &
(dataset['YearBuilt'].between(2000, 2010))][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,Exterior1st,Exterior2nd
58,StoneBr,BrkFace,1031.0,2006,10,2Story,VinylSd,VinylSd
178,StoneBr,Stone,748.0,2008,9,1Story,VinylSd,VinylSd
189,StoneBr,NaN,0.0,2001,8,1Story,CemntBd,CmentBd
336,StoneBr,Stone,200.0,2005,9,1Story,VinylSd,VinylSd
378,StoneBr,Stone,350.0,2010,9,1Story,VinylSd,VinylSd
474,StoneBr,NaN,0.0,2000,8,1Story,CemntBd,CmentBd
566,StoneBr,BrkFace,245.0,2005,9,2Story,VinylSd,VinylSd
595,StoneBr,BrkFace,238.0,2005,8,1Story,VinylSd,Other
678,StoneBr,Stone,464.0,2008,8,1Story,VinylSd,VinylSd
688,StoneBr,BrkFace,0.0,2007,8,1Story,MetalSd,MetalSd
702,StoneBr,BrkFace,466.0,2006,8,2Story,VinylSd,VinylSd
769,StoneBr,BrkFace,603.0,2003,8,2Story,CemntBd,Wd Shng
1046,StoneBr,Stone,208.0,2005,9,2Story,CemntBd,CmentBd
1060,StoneBr,NaN,0.0,2001,8,1Story,CemntBd,CmentBd
1288,StoneBr,NaN,0.0,2000,8,1Story,CemntBd,CmentBd
1361,StoneBr,Stone,16.0,2005,7,1Story,VinylSd,VinylSd

In [52]:
dataset.groupby(['MasVnrType',	'MasVnrArea'], dropna=False).size().sort_values(ascending=False)

MasVnrType  MasVnrArea
NaN         0.0           859
            NaN             8
BrkFace     120.0           7
            180.0           7
            16.0            6
                         ...
            297.0           1
            296.0           1
            293.0           1
            292.0           1
BrkCmn      41.0            1
Length: 399, dtype: int64

In [53]:
dataset[
    (dataset['MasVnrArea'] == 0) &
    (dataset['MasVnrType'].isnull())].shape[0]

859

In [54]:
dataset.loc[
    (dataset['MasVnrArea'] == 0) &
    (dataset['MasVnrType'].isnull()),
    'MasVnrType'
    ] = 'None'

In [55]:
dataset['MasVnrType'].value_counts(dropna=False)

MasVnrType
None       859
BrkFace    450
Stone      128
BrkCmn      15
NaN          8
Name: count, dtype: int64

In [56]:
dataset[dataset['MasVnrArea'].isnull()][['Neighborhood', 'MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass', 'Exterior1st', 'Exterior2nd']]

,Neighborhood,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
234,Gilbert,NaN,NaN,2002,6,2Story,60,VinylSd,VinylSd
529,Crawfor,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone
650,Somerst,NaN,NaN,2007,7,2Story,60,CemntBd,CmentBd
936,SawyerW,NaN,NaN,2003,7,1Story,20,VinylSd,VinylSd
973,Somerst,NaN,NaN,2007,7,1Story,20,CemntBd,CmentBd
977,Somerst,NaN,NaN,2006,7,1Story,120,VinylSd,VinylSd
1243,NridgHt,NaN,NaN,2006,10,1Story,20,VinylSd,VinylSd
1278,CollgCr,NaN,NaN,2002,8,2Story,60,VinylSd,VinylSd

In [57]:
# Investigating row 234
dataset[(dataset['Neighborhood'] == 'Gilbert') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 6) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
221,None,0.0,2002,6,2Story,60,VinylSd,VinylSd
234,NaN,NaN,2002,6,2Story,60,VinylSd,VinylSd
616,None,0.0,2002,6,2Story,60,VinylSd,VinylSd

In [58]:
dataset.loc[234, ['MasVnrType',	'MasVnrArea']] = ['BrkFace', 0]

In [59]:
dataset.loc[234, ['MasVnrType',	'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea        0.0
Name: 234, dtype: object

In [60]:
# Investigating row 529
dataset[(dataset['Neighborhood'] == 'Crawfor') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'Wd Sdng') &
(dataset['Exterior2nd'] == 'Stone')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
529,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone

In [61]:
# Investigating row 529
dataset[(dataset['Neighborhood'] == 'Crawfor') &
(dataset['Exterior2nd'] == 'Stone')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
529,NaN,NaN,1957,6,1Story,20,Wd Sdng,Stone
1152,None,0.0,1956,6,1Story,20,Stone,Stone
1343,None,0.0,1928,6,1.5Fin,50,BrkFace,Stone

In [62]:
dataset.loc[529, ['MasVnrType', 'MasVnrArea']] = ['None', 0]

In [63]:
dataset.loc[529, ['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

MasVnrType        None
MasVnrArea         0.0
YearBuilt         1957
OverallQual          6
HouseStyle      1Story
MSSubClass          20
Exterior1st    Wd Sdng
Exterior2nd      Stone
Name: 529, dtype: object

In [64]:
# Investigating row 650
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['Exterior2nd'] == 'CmentBd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
377,None,0.0,2004,8,2Story,60,CemntBd,CmentBd
399,Stone,100.0,2006,7,2Story,60,CemntBd,CmentBd
650,NaN,NaN,2007,7,2Story,60,CemntBd,CmentBd
875,None,0.0,2007,8,2Story,60,CemntBd,CmentBd
1374,None,0.0,2005,7,2Story,60,CemntBd,CmentBd

In [65]:
dataset.loc[650, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [66]:
dataset.loc[650, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 650, dtype: object

In [67]:
# Investigating row 936
dataset[(dataset['Neighborhood'] == 'SawyerW') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
18,None,0.0,2004,5,1Story,20,VinylSd,VinylSd
60,None,0.0,2004,6,1Story,20,VinylSd,VinylSd
148,BrkFace,120.0,2004,7,1Story,20,VinylSd,VinylSd
742,BrkFace,108.0,2000,7,1Story,20,VinylSd,VinylSd
827,None,0.0,2001,7,1Story,20,VinylSd,VinylSd
936,NaN,NaN,2003,7,1Story,20,VinylSd,VinylSd
951,None,0.0,1965,5,1Story,20,VinylSd,VinylSd
1238,None,0.0,2005,6,1Story,20,VinylSd,VinylSd
1341,None,0.0,2003,6,1Story,20,VinylSd,VinylSd
1348,None,0.0,1998,7,1Story,20,VinylSd,VinylSd
1413,Stone,366.0,2005,8,1Story,20,VinylSd,VinylSd

In [68]:
dataset.loc[936, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [69]:
dataset.loc[936, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 936, dtype: object

In [70]:

# Investigating row 973
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['Exterior2nd'] == 'CmentBd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
196,Stone,205.0,2007,7,1Story,20,CemntBd,CmentBd
644,Stone,162.0,2009,9,1Story,20,CemntBd,CmentBd
793,Stone,140.0,2007,8,1Story,20,CemntBd,CmentBd
973,NaN,NaN,2007,7,1Story,20,CemntBd,CmentBd
1217,Stone,72.0,2009,8,1Story,20,CemntBd,CmentBd
1451,Stone,194.0,2008,8,1Story,20,CemntBd,CmentBd

In [71]:

# Investigating row 973
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 20) &
(dataset['Exterior1st'] == 'CemntBd') &
(dataset['MasVnrType'] == 'Stone') &
(dataset['Exterior2nd'] == 'CmentBd')]['MasVnrArea'].agg(['count', 'mean', 'median', 'min', 'max'])

count       5.0
mean      154.6
median    162.0
min        72.0
max       205.0
Name: MasVnrArea, dtype: float64

In [72]:
dataset.loc[973, ['MasVnrArea']] = 162

In [73]:
dataset.loc[973, ['MasVnrType']] = 'Stone'

In [74]:
dataset.loc[973, ['MasVnrType', 'MasVnrArea']]

MasVnrType    Stone
MasVnrArea    162.0
Name: 973, dtype: object

In [75]:
# Investigating row 977
dataset[(dataset['Neighborhood'] == 'Somerst') &
(dataset['HouseStyle'] == '1Story') &
(dataset['MSSubClass'] == 120) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
977,NaN,NaN,2006,7,1Story,120,VinylSd,VinylSd
1317,None,0.0,2006,7,1Story,120,VinylSd,VinylSd

In [76]:
dataset.loc[977, ['MasVnrType',	'MasVnrArea']] = ['None', 0]

In [77]:
dataset.loc[977, ['MasVnrType',	'MasVnrArea']]

MasVnrType    None
MasVnrArea     0.0
Name: 977, dtype: object

In [78]:
# Investigating row 1243
dataset[(dataset['Neighborhood'] == 'NridgHt') &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2006) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'OverallQual']]

     MasVnrType  MasVnrArea  OverallQual
62        Stone       178.0            8
320       Stone       370.0            9
408     BrkFace       350.0            7
468       Stone       248.0            8
473     BrkFace       304.0            8
477     BrkFace       772.0            9
552       Stone       250.0            8
631       Stone       108.0            8
774     BrkFace       375.0            8
1243        NaN         NaN           10
1289      Stone       788.0            8
1305      Stone       300.0            9

In [79]:
# Investigating row 1243
dataset[(dataset['Neighborhood'] == 'NridgHt') &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2006) &
(dataset['MasVnrType'] == 'Stone') &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrArea']].agg(['count', 'mean', 'median', 'min', 'max'])

        MasVnrArea
count     7.000000
mean    320.285714
median  250.000000
min     108.000000
max     788.000000

In [80]:
dataset.loc[1243, ['MasVnrType', 'MasVnrArea']] = ['Stone', 320.29]

In [81]:
dataset.loc[1243, ['MasVnrType', 'MasVnrArea']]

MasVnrType     Stone
MasVnrArea    320.29
Name: 1243, dtype: object

In [82]:
# Investigating row 1278
dataset[(dataset['Neighborhood'] == 'CollgCr') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 8) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrType', 'MasVnrArea', 'YearBuilt', 'OverallQual', 'HouseStyle', 'MSSubClass','Exterior1st', 'Exterior2nd']]

,MasVnrType,MasVnrArea,YearBuilt,OverallQual,HouseStyle,MSSubClass,Exterior1st,Exterior2nd
1054,BrkFace,210.0,2002,8,2Story,60,VinylSd,VinylSd
1278,NaN,NaN,2002,8,2Story,60,VinylSd,VinylSd
1342,BrkFace,149.0,2002,8,2Story,60,VinylSd,VinylSd

In [83]:
# Investigating row 1278
dataset[(dataset['Neighborhood'] == 'CollgCr') &
(dataset['HouseStyle'] == '2Story') &
(dataset['MSSubClass'] == 60) &
(dataset['Exterior1st'] == 'VinylSd') &
(dataset['YearBuilt'] == 2002) &
(dataset['OverallQual'] == 8) &
(dataset['Exterior2nd'] == 'VinylSd')][['MasVnrArea']].agg(['count', 'mean', 'median', 'min', 'max'])

        MasVnrArea
count          2.0
mean         179.5
median       179.5
min          149.0
max          210.0

In [84]:
dataset.loc[1278, ['MasVnrType', 'MasVnrArea']] = ['BrkFace', 179.5]

In [85]:
dataset.loc[1278, ['MasVnrType', 'MasVnrArea']]

MasVnrType    BrkFace
MasVnrArea      179.5
Name: 1278, dtype: object

In [86]:
dataset.loc[1278, ['OverallQual', 'GarageArea', 'GrLivArea', 'TotalBsmtSF','1stFlrSF', 'SalePrice']]

OverallQual         8
GarageArea        577
GrLivArea        2031
TotalBsmtSF      1128
1stFlrSF         1128
SalePrice      237000
Name: 1278, dtype: int64

In [87]:
dataset.loc[[234, 529, 650, 936, 973, 977, 1243, 1278], ['MasVnrType', 'MasVnrArea']]

     MasVnrType  MasVnrArea
234     BrkFace        0.00
529        None        0.00
650        None        0.00
936        None        0.00
973       Stone      162.00
977        None        0.00
1243      Stone      320.29
1278    BrkFace      179.50

In [88]:
dataset.isnull().sum().sort_values(ascending=False)

PoolQC         1453
MiscFeature    1406
Alley          1369
Fence          1179
FireplaceQu     690
               ...
MasVnrArea        0
MasVnrType        0
Exterior2nd       0
Exterior1st       0
SalePrice         0
Length: 81, dtype: int64

In [89]:
dataset[dataset['MasVnrType'].isnull() |
dataset['MasVnrArea'].isnull()][['MasVnrType', 'MasVnrArea']]

Empty DataFrame
Columns: [MasVnrType, MasVnrArea]
Index: []

In [90]:
dataset[dataset['PoolQC'].isnull()]['PoolArea'].value_counts()

PoolArea
0    1453
Name: count, dtype: int64

In [91]:
dataset[dataset['BsmtQual'].isnull()]['TotalBsmtSF'].value_counts()

TotalBsmtSF
0    37
Name: count, dtype: int64

In [92]:
dataset[dataset['GarageQual'].isnull()]['GarageArea'].value_counts()

GarageArea
0    81
Name: count, dtype: int64

In [93]:
dataset[dataset['FireplaceQu'].isnull()]['Fireplaces'].value_counts()

Fireplaces
0    690
Name: count, dtype: int64

In [94]:
dataset[dataset['MiscFeature'].isnull()]['MiscVal'].value_counts()

MiscVal
0    1406
Name: count, dtype: int64

In [95]:
dataset[dataset['Fence'].isnull()][['Fence', 'LotArea', 'OverallQual']].head(20)

   Fence  LotArea  OverallQual
0    NaN     8450            7
1    NaN     9600            6
2    NaN    11250            7
3    NaN     9550            7
4    NaN    14260            8
6    NaN    10084            8
7    NaN    10382            7
8    NaN     6120            7
9    NaN     7420            5
10   NaN    11200            5
11   NaN    11924            9
12   NaN    12968            5
13   NaN    10652            7
16   NaN    11241            6
17   NaN    10791            4
18   NaN    13695            5
20   NaN    14215            8
22   NaN     9742            8
23   NaN     4224            5
25   NaN    14230            8

In [96]:
dataset['Electrical'].isnull().sum()

np.int64(1)

In [97]:
missing = dataset.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
Electrical         1
dtype: int64

In [98]:
# Inspecting garage without values
dataset[dataset['GarageType'].isnull()][['GarageArea', 'GarageCars', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']].head(20)

,GarageArea,GarageCars,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
39,0,0,NaN,NaN,NaN,NaN,NaN
48,0,0,NaN,NaN,NaN,NaN,NaN
78,0,0,NaN,NaN,NaN,NaN,NaN
88,0,0,NaN,NaN,NaN,NaN,NaN
89,0,0,NaN,NaN,NaN,NaN,NaN
99,0,0,NaN,NaN,NaN,NaN,NaN
108,0,0,NaN,NaN,NaN,NaN,NaN
125,0,0,NaN,NaN,NaN,NaN,NaN
127,0,0,NaN,NaN,NaN,NaN,NaN
140,0,0,NaN,NaN,NaN,NaN,NaN
148,0,0,NaN,NaN,NaN,NaN,NaN
155,0,0,NaN,NaN,NaN,NaN,NaN
163,0,0,NaN,NaN,NaN,NaN,NaN
165,0,0,NaN,NaN,NaN,NaN,NaN
198,0,0,NaN,NaN,NaN,NaN,NaN
210,0,0,NaN,NaN,NaN,NaN,NaN
241,0,0,NaN,NaN,NaN,NaN,NaN
250,0,0,NaN,NaN,NaN,NaN,NaN
287,0,0,NaN,NaN,NaN,NaN,NaN
291,0,0,NaN,NaN,NaN,NaN,NaN

In [99]:
# Inspecting basement without values
dataset[dataset['BsmtQual'].isnull()][['TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtQual', 'BsmtExposure', 'BsmtFinType2', 'BsmtCond', 'BsmtFinType1']].head(20)

,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,BsmtQual,BsmtExposure,BsmtFinType2,BsmtCond,BsmtFinType1
17,0,0,0,NaN,NaN,NaN,NaN,NaN
39,0,0,0,NaN,NaN,NaN,NaN,NaN
90,0,0,0,NaN,NaN,NaN,NaN,NaN
102,0,0,0,NaN,NaN,NaN,NaN,NaN
156,0,0,0,NaN,NaN,NaN,NaN,NaN
182,0,0,0,NaN,NaN,NaN,NaN,NaN
259,0,0,0,NaN,NaN,NaN,NaN,NaN
342,0,0,0,NaN,NaN,NaN,NaN,NaN
362,0,0,0,NaN,NaN,NaN,NaN,NaN
371,0,0,0,NaN,NaN,NaN,NaN,NaN
392,0,0,0,NaN,NaN,NaN,NaN,NaN
520,0,0,0,NaN,NaN,NaN,NaN,NaN
532,0,0,0,NaN,NaN,NaN,NaN,NaN
533,0,0,0,NaN,NaN,NaN,NaN,NaN
553,0,0,0,NaN,NaN,NaN,NaN,NaN
646,0,0,0,NaN,NaN,NaN,NaN,NaN
705,0,0,0,NaN,NaN,NaN,NaN,NaN
736,0,0,0,NaN,NaN,NaN,NaN,NaN
749,0,0,0,NaN,NaN,NaN,NaN,NaN
778,0,0,0,NaN,NaN,NaN,NaN,NaN

In [100]:
# Inspecting fireplace without values
dataset[dataset['FireplaceQu'].isnull()][['FireplaceQu', 'Fireplaces']].head(20)

   FireplaceQu  Fireplaces
0          NaN           0
5          NaN           0
10         NaN           0
12         NaN           0
15         NaN           0
17         NaN           0
18         NaN           0
19         NaN           0
26         NaN           0
29         NaN           0
30         NaN           0
31         NaN           0
32         NaN           0
36         NaN           0
38         NaN           0
39         NaN           0
42         NaN           0
43         NaN           0
44         NaN           0
47         NaN           0

In [101]:
# Inspecting pool without values
dataset[dataset['PoolQC'].isnull()][['PoolQC', 'PoolArea']].head(20)

   PoolQC  PoolArea
0     NaN         0
1     NaN         0
2     NaN         0
3     NaN         0
4     NaN         0
5     NaN         0
6     NaN         0
7     NaN         0
8     NaN         0
9     NaN         0
10    NaN         0
11    NaN         0
12    NaN         0
13    NaN         0
14    NaN         0
15    NaN         0
16    NaN         0
17    NaN         0
18    NaN         0
19    NaN         0

In [102]:
# Inspecting misc without values
dataset[dataset['MiscFeature'].isnull()][['MiscFeature', 'MiscVal']].head(20)

   MiscFeature  MiscVal
0          NaN        0
1          NaN        0
2          NaN        0
3          NaN        0
4          NaN        0
6          NaN        0
8          NaN        0
9          NaN        0
10         NaN        0
11         NaN        0
12         NaN        0
13         NaN        0
14         NaN        0
15         NaN        0
18         NaN        0
19         NaN        0
20         NaN        0
21         NaN        0
22         NaN        0
23         NaN        0

In [103]:
# Inspecting Fence without values
dataset['Fence'].value_counts(dropna=False)

Fence
NaN      1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

In [104]:
# Inspecting Fence without values
dataset['Alley'].value_counts(dropna=False)

Alley
NaN     1369
Grvl      50
Pave      41
Name: count, dtype: int64

In [105]:
absent_features = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCond', 'GarageQual', 'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtFinType1', 'BsmtQual']

In [106]:
missing[missing >0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
Electrical         1
dtype: int64

In [107]:
# Investigating Pool
dataset.groupby('PoolQC', dropna=False)['SalePrice'].mean()

PoolQC
Ex     490000.000000
Fa     215500.000000
Gd     201990.000000
NaN    180404.663455
Name: SalePrice, dtype: float64

In [108]:
# Investigating Garage
dataset.groupby('GarageType', dropna=False)['SalePrice'].agg(['count', 'mean'])

            count           mean
GarageType
2Types          6  151283.333333
Attchd        870  202892.656322
Basment        19  160570.684211
BuiltIn        88  254751.738636
CarPort         9  109962.111111
Detchd        387  134091.162791
NaN            81  103317.283951

In [109]:
dataset[dataset['GarageType'].isnull()][['GarageArea', 'GarageCars', 'GarageYrBlt']].head(20)

     GarageArea  GarageCars  GarageYrBlt
39            0           0          NaN
48            0           0          NaN
78            0           0          NaN
88            0           0          NaN
89            0           0          NaN
99            0           0          NaN
108           0           0          NaN
125           0           0          NaN
127           0           0          NaN
140           0           0          NaN
148           0           0          NaN
155           0           0          NaN
163           0           0          NaN
165           0           0          NaN
198           0           0          NaN
210           0           0          NaN
241           0           0          NaN
250           0           0          NaN
287           0           0          NaN
291           0           0          NaN

In [110]:
absent_features = dataset.select_dtypes('str').isnull().sum().sort_values(ascending=False)
absent_features[absent_features > 0]

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageCond        81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtFinType1      37
BsmtQual          37
Electrical         1
dtype: int64

In [111]:
dataset[dataset['Electrical'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1379,1380,80,RL,73.0,9735,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500

In [112]:
dataset['Electrical'].value_counts()

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

In [113]:
dataset.loc[1379, ['Electrical', 'OverallQual', 'YearBuilt', 'YearRemodAdd',
                   'Neighborhood', 'HouseStyle', 'CentralAir']]

Electrical         NaN
OverallQual          5
YearBuilt         2006
YearRemodAdd      2007
Neighborhood    Timber
HouseStyle        SLvl
CentralAir           Y
Name: 1379, dtype: object

In [114]:
dataset[dataset['Neighborhood'] == 'Timber']['Electrical'].value_counts()

Electrical
SBrkr    36
FuseA     1
Name: count, dtype: int64

In [115]:
dataset[dataset['YearBuilt'] >= 2000]['Electrical'].value_counts()

Electrical
SBrkr    387
Name: count, dtype: int64

In [116]:
dataset[
    (dataset['Neighborhood'] == 'Timber') & 
    (dataset['YearBuilt'] >= 2000) & 
    (dataset['HouseStyle'] == 'SLvl')]['Electrical'].value_counts(dropna=False)

Electrical
SBrkr    1
NaN      1
Name: count, dtype: int64

In [117]:
dataset[dataset['Neighborhood'] == 'Timber'][['Electrical', 'SalePrice']].sort_values('SalePrice')

     Electrical  SalePrice
944       FuseA     137500
1396      SBrkr     160000
1379        NaN     167500
41        SBrkr     170000
429       SBrkr     175000
530       SBrkr     175000
695       SBrkr     176000
1281      SBrkr     180000
174       SBrkr     184000
1184      SBrkr     186700
881       SBrkr     187500
731       SBrkr     187500
930       SBrkr     201000
340       SBrkr     202900
452       SBrkr     204000
964       SBrkr     214900
133       SBrkr     220000
572       SBrkr     224500
169       SBrkr     228000
335       SBrkr     228950
1375      SBrkr     239000
866       SBrkr     248900
1180      SBrkr     250000
1239      SBrkr     265900
157       SBrkr     269500
947       SBrkr     270000
1395      SBrkr     281213
1347      SBrkr     283463
1024      SBrkr     287000
1027      SBrkr     293077
619       SBrkr     305000
700       SBrkr     312500
540       SBrkr     315000
1036      SBrkr     315500
692       SBrkr     335000
585       SBrkr     369900
313       SBrkr     375000
1267      SBrkr     378500

In [118]:
dataset.loc[1379, ['Electrical']] = 'SBrkr'

In [119]:
dataset.loc[1379, ['Electrical']]

Electrical    SBrkr
Name: 1379, dtype: str

In [120]:
dataset['Electrical'].isnull().sum()

np.int64(0)

In [121]:
absent_features = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCond', 'GarageQual', 'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtFinType1', 'BsmtQual']

In [122]:
missing_values_without_zeros = dataset.isnull().sum()
missing_values_without_zeros[missing_values_without_zeros > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
dtype: int64

In [123]:
dataset[absent_features].dtypes

PoolQC              str
MiscFeature         str
Alley               str
Fence               str
FireplaceQu         str
GarageType          str
GarageYrBlt     float64
GarageFinish        str
GarageCond          str
GarageQual          str
BsmtFinType2        str
BsmtExposure        str
BsmtCond            str
BsmtFinType1        str
BsmtQual            str
dtype: object

In [124]:
dataset['BsmtQual'] = dataset['BsmtQual'].fillna('None')

In [125]:
dataset['BsmtQual'].isnull().value_counts(dropna=False)

BsmtQual
False    1460
Name: count, dtype: int64

In [126]:
dataset['BsmtQual'].value_counts()

BsmtQual
TA      649
Gd      618
Ex      121
None     37
Fa       35
Name: count, dtype: int64

In [127]:
dataset['BsmtFinType1'] = dataset['BsmtFinType1'].fillna('None')

In [128]:
dataset['BsmtFinType1'].isnull().value_counts(dropna=False)

BsmtFinType1
False    1460
Name: count, dtype: int64

In [129]:
dataset['BsmtFinType1'].value_counts()

BsmtFinType1
Unf     430
GLQ     418
ALQ     220
BLQ     148
Rec     133
LwQ      74
None     37
Name: count, dtype: int64

In [130]:
dataset['BsmtCond'] = dataset['BsmtCond'].fillna('None')

In [131]:
dataset['BsmtCond'].isnull().value_counts(dropna=False)

BsmtCond
False    1460
Name: count, dtype: int64

In [132]:
dataset['BsmtCond'].value_counts()

BsmtCond
TA      1311
Gd        65
Fa        45
None      37
Po         2
Name: count, dtype: int64

In [133]:
dataset['BsmtExposure'] = dataset['BsmtExposure'].fillna('None')

In [134]:
dataset['BsmtExposure'].isnull().value_counts(dropna=False)

BsmtExposure
False    1460
Name: count, dtype: int64

In [135]:
dataset['BsmtExposure'].value_counts()

BsmtExposure
No      953
Av      221
Gd      134
Mn      114
None     38
Name: count, dtype: int64

In [136]:
dataset['BsmtFinType2'] = dataset['BsmtFinType2'].fillna('None')

In [137]:
dataset['BsmtFinType2'].isnull().value_counts(dropna=False)

BsmtFinType2
False    1460
Name: count, dtype: int64

In [138]:
dataset['BsmtFinType2'].value_counts()

BsmtFinType2
Unf     1256
Rec       54
LwQ       46
None      38
BLQ       33
ALQ       19
GLQ       14
Name: count, dtype: int64

In [139]:
dataset['GarageQual'] = dataset['GarageQual'].fillna('None')

In [140]:
dataset['GarageQual'].isnull().value_counts(dropna=False)

GarageQual
False    1460
Name: count, dtype: int64

In [141]:
dataset['GarageQual'].value_counts()

GarageQual
TA      1311
None      81
Fa        48
Gd        14
Ex         3
Po         3
Name: count, dtype: int64

In [142]:
dataset['GarageCond'] = dataset['GarageCond'].fillna('None')

In [143]:
dataset['GarageCond'].isnull().value_counts(dropna=False)

GarageCond
False    1460
Name: count, dtype: int64

In [144]:
dataset['GarageCond'].value_counts()

GarageCond
TA      1326
None      81
Fa        35
Gd         9
Po         7
Ex         2
Name: count, dtype: int64

In [145]:
dataset['GarageFinish'] = dataset['GarageFinish'].fillna('None')

In [146]:
dataset['GarageFinish'].isnull().value_counts(dropna=False)

GarageFinish
False    1460
Name: count, dtype: int64

In [147]:
dataset['GarageFinish'].value_counts()

GarageFinish
Unf     605
RFn     422
Fin     352
None     81
Name: count, dtype: int64

In [148]:
dataset['GarageYrBlt'] = dataset['GarageYrBlt'].fillna(0)

In [149]:
dataset['GarageYrBlt'].isnull().value_counts(dropna=False)

GarageYrBlt
False    1460
Name: count, dtype: int64

In [150]:
dataset['GarageYrBlt'].value_counts()

GarageYrBlt
0.0       81
2005.0    65
2006.0    59
2004.0    53
2003.0    50
          ..
1900.0     1
1927.0     1
1906.0     1
1908.0     1
1933.0     1
Name: count, Length: 98, dtype: int64

In [151]:
dataset['GarageType'] = dataset['GarageType'].fillna('None')

In [152]:
dataset['GarageType'].isnull().value_counts(dropna=False)

GarageType
False    1460
Name: count, dtype: int64

In [153]:
dataset['GarageType'].value_counts()

GarageType
Attchd     870
Detchd     387
BuiltIn     88
None        81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

In [154]:
dataset['FireplaceQu'] = dataset['FireplaceQu'].fillna('None')

In [155]:
dataset['FireplaceQu'].isnull().value_counts(dropna=False)

FireplaceQu
False    1460
Name: count, dtype: int64

In [156]:
dataset['FireplaceQu'].value_counts()

FireplaceQu
None    690
Gd      380
TA      313
Fa       33
Ex       24
Po       20
Name: count, dtype: int64

In [157]:
dataset['Fence'] = dataset['Fence'].fillna('None')

In [158]:
dataset['Fence'].isnull().value_counts(dropna=False)

Fence
False    1460
Name: count, dtype: int64

In [159]:
dataset['Fence'].value_counts()

Fence
None     1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

In [160]:
dataset['MiscFeature'] = dataset['MiscFeature'].fillna('None')

In [161]:
dataset['MiscFeature'].isnull().value_counts(dropna=False)

MiscFeature
False    1460
Name: count, dtype: int64

In [162]:
dataset['MiscFeature'].value_counts()

MiscFeature
None    1406
Shed      49
Gar2       2
Othr       2
TenC       1
Name: count, dtype: int64

In [163]:
dataset['Alley'] = dataset['Alley'].fillna('None')

In [164]:
dataset['Alley'].isnull().value_counts(dropna=False)

Alley
False    1460
Name: count, dtype: int64

In [165]:
dataset['Alley'].value_counts()

Alley
None    1369
Grvl      50
Pave      41
Name: count, dtype: int64

In [166]:
dataset['PoolQC'] = dataset['PoolQC'].fillna('None')

In [167]:
dataset['PoolQC'].isnull().value_counts(dropna=False)

PoolQC
False    1460
Name: count, dtype: int64

In [168]:
dataset['PoolQC'].value_counts()

PoolQC
None    1453
Gd         3
Ex         2
Fa         2
Name: count, dtype: int64

In [169]:
dataset['BsmtQual'] = dataset['BsmtQual'].fillna('None')

In [170]:
dataset['BsmtQual'].isnull().value_counts(dropna=False)

BsmtQual
False    1460
Name: count, dtype: int64

In [171]:
dataset['BsmtQual'].value_counts()

BsmtQual
TA      649
Gd      618
Ex      121
None     37
Fa       35
Name: count, dtype: int64

In [172]:
dataset.isnull().sum().sort_values(ascending=False)

LotFrontage     259
Id                0
BedroomAbvGr      0
GarageYrBlt       0
GarageType        0
               ...
MasVnrArea        0
MasVnrType        0
Exterior2nd       0
Exterior1st       0
SalePrice         0
Length: 81, dtype: int64

In [173]:
dataset.groupby('Neighborhood')['LotFrontage'].agg(['count', 'mean', 'median', 'min', 'max'])

              count       mean  median   min    max
Neighborhood
Blmngtn          14  47.142857    43.0  43.0   53.0
Blueste           2  24.000000    24.0  24.0   24.0
BrDale           16  21.562500    21.0  21.0   24.0
BrkSide          51  57.509804    52.0  50.0  144.0
ClearCr          13  83.461538    80.0  62.0  138.0
CollgCr         126  71.682540    70.0  36.0  122.0
Crawfor          41  71.804878    74.0  40.0  130.0
Edwards          92  68.217391    65.5  24.0  313.0
Gilbert          49  79.877551    65.0  42.0  182.0
IDOTRR           34  62.500000    60.0  40.0  120.0
MeadowV          15  27.800000    21.0  21.0   44.0
Mitchel          36  70.083333    73.0  32.0  129.0
NAmes           186  76.462366    73.0  34.0  313.0
NPkVill           7  32.285714    24.0  24.0   53.0
NWAmes           45  81.288889    80.0  46.0  105.0
NoRidge          33  91.878788    91.0  52.0  174.0
NridgHt          76  81.881579    88.5  34.0  129.0
OldTown         109  62.788991    60.0  30.0  153.0
SWISU            23  58.913043    60.0  50.0  102.0
Sawyer           48  74.437500    71.0  40.0  115.0
SawyerW          50  71.500000    66.5  50.0  116.0
Somerst          78  64.666667    73.5  24.0  116.0
StoneBr          20  62.700000    61.5  39.0  124.0
Timber           30  80.133333    85.0  42.0  150.0
Veenker           7  59.714286    68.0  30.0   90.0

In [174]:
dataset['NeighborhoodMedian'] = dataset.groupby('Neighborhood')['LotFrontage'].transform('median')

In [175]:
dataset[['Neighborhood', 'LotFrontage', 'NeighborhoodMedian']].head(20)

   Neighborhood  LotFrontage  NeighborhoodMedian
0       CollgCr         65.0                70.0
1       Veenker         80.0                68.0
2       CollgCr         68.0                70.0
3       Crawfor         60.0                74.0
4       NoRidge         84.0                91.0
5       Mitchel         85.0                73.0
6       Somerst         75.0                73.5
7        NWAmes          NaN                80.0
8       OldTown         51.0                60.0
9       BrkSide         50.0                52.0
10       Sawyer         70.0                71.0
11      NridgHt         85.0                88.5
12       Sawyer          NaN                71.0
13      CollgCr         91.0                70.0
14        NAmes          NaN                73.0
15      BrkSide         51.0                52.0
16        NAmes          NaN                73.0
17       Sawyer         72.0                71.0
18      SawyerW         66.0                66.5
19        NAmes         70.0                73.0

In [176]:
dataset[dataset['LotFrontage'].isnull()][['Neighborhood', 'LotFrontage', 'NeighborhoodMedian']].head(20)

    Neighborhood  LotFrontage  NeighborhoodMedian
7         NWAmes          NaN                80.0
12        Sawyer          NaN                71.0
14         NAmes          NaN                73.0
16         NAmes          NaN                73.0
24        Sawyer          NaN                71.0
31        Sawyer          NaN                71.0
42       SawyerW          NaN                66.5
43       CollgCr          NaN                70.0
50       Gilbert          NaN                65.0
64       CollgCr          NaN                70.0
66         NAmes          NaN                73.0
76         NAmes          NaN                73.0
84       Gilbert          NaN                65.0
95       Gilbert          NaN                65.0
100       NWAmes          NaN                80.0
104       IDOTRR          NaN                60.0
111      Gilbert          NaN                65.0
113      Crawfor          NaN                74.0
116       Sawyer          NaN                71.0
120      ClearCr          NaN                80.0

In [177]:
dataset['LotFrontage'] = dataset['LotFrontage'].fillna(dataset['NeighborhoodMedian'])

In [178]:
dataset['LotFrontage'].isnull().sum()

np.int64(0)

In [179]:
dataset = dataset.drop('NeighborhoodMedian', axis=1)

In [180]:
'NeighborhoodMedian' in dataset.columns

False

In [181]:
dataset.loc[[7, 12, 14], ['Neighborhood',	'LotFrontage']]

   Neighborhood  LotFrontage
7        NWAmes         80.0
12       Sawyer         71.0
14        NAmes         73.0

In [182]:
dataset.isnull().sum().sort_values(ascending=False)

Id             0
CentralAir     0
GarageYrBlt    0
GarageType     0
FireplaceQu    0
              ..
MasVnrArea     0
MasVnrType     0
Exterior2nd    0
Exterior1st    0
SalePrice      0
Length: 81, dtype: int64

In [183]:
missing_values = dataset.isnull().sum()
missing_values[missing_values > 0].sum()

np.int64(0)

In [184]:
dataset[['Id', 'SalePrice']].head(20)

    Id  SalePrice
0    1     208500
1    2     181500
2    3     223500
3    4     140000
4    5     250000
5    6     143000
6    7     307000
7    8     200000
8    9     129900
9   10     118000
10  11     129500
11  12     345000
12  13     144000
13  14     279500
14  15     157000
15  16     132000
16  17     149000
17  18      90000
18  19     159000
19  20     139000

In [185]:
dataset['Id'].nunique()

1460

In [186]:
dataset[['Id', 'SalePrice']].corr()

                 Id  SalePrice
Id         1.000000  -0.021917
SalePrice -0.021917   1.000000

In [187]:
dataset = dataset.drop('Id', axis=1)

In [188]:
dataset

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,None,Reg,Lvl,AllPub,FR2,...,0,None,None,None,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,None,None,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,None,IR1,Lvl,AllPub,Corner,...,0,None,None,None,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,None,IR1,Lvl,AllPub,FR2,...,0,None,None,None,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,6,2008,WD,Normal,147500

In [189]:
categorical_features = dataset.select_dtypes(include='str').columns

In [190]:
categorical_features

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='str')

In [191]:
numerical_features = dataset.select_dtypes('number').columns

In [192]:
numerical_features

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SalePrice'],
      dtype='str')

In [193]:
dataset.groupby('HouseStyle')['SalePrice'].agg(['count', 'mean', 'median', 'max', 'min']).sort_values('mean', ascending=False)

            count           mean    median     max     min
HouseStyle
2.5Fin          8  220000.000000  194000.0  475000  104000
2Story        445  210051.764045  190000.0  755000   40000
1Story        726  175985.477961  154750.0  611657   34900
SLvl           65  166703.384615  164500.0  345000   91000
2.5Unf         11  157354.545455  133900.0  325000  101000
1.5Fin        154  143116.740260  132000.0  410000   37900
SFoyer         37  135074.486486  135960.0  206300   75500
1.5Unf         14  110150.000000  111250.0  139400   76000

In [194]:
house_style_mean = dataset.groupby('HouseStyle')['SalePrice'].mean()

In [195]:
house_style_mean.max() - house_style_mean.min()

np.float64(109850.0)

In [196]:
neighborhood_mean = dataset.groupby('Neighborhood')['SalePrice'].mean()

In [197]:
neighborhood_mean.max() - neighborhood_mean.min()

np.float64(236718.84648493544)

In [198]:
neighborhood_mean.sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [199]:
features_mean = {}
for feature in categorical_features:
    group_mean = (dataset.groupby(feature)['SalePrice'].mean())
    difference = group_mean.max() - group_mean.min()
    features_mean[feature] = difference

In [200]:
features_mean

{'MSZoning': np.float64(139486.06153846154),
 'Street': np.float64(50940.03851444292),
 'Alley': np.float64(61233.05148283417),
 'LotShape': np.float64(75078.54747528015),
 'LandContour': np.float64(88429.86063492062),
 'Utilities': np.float64(43450.95681973954),
 'LotConfig': np.float64(46916.569492759474),
 'LandSlope': np.float64(24422.431203384185),
 'Neighborhood': np.float64(236718.84648493544),
 'Condition1': np.float64(90783.33333333334),
 'Condition2': np.float64(228250.0),
 'BldgType': np.float64(57331.54931253304),
 'HouseStyle': np.float64(109850.0),
 'RoofStyle': np.float64(76090.90909090909),
 'RoofMatl': np.float64(253250.0),
 'Exterior1st': np.float64(191000.0),
 'Exterior2nd': np.float64(214000.0),
 'MasVnrType': np.float64(120156.5794871795),
 'ExterQual': np.float64(279375.7472527473),
 'ExterCond': np.float64(124833.33333333334),
 'Foundation': np.float64(117864.81704018547),
 'BsmtQual': np.float64(221388.14943042217),
 'BsmtCond': np.float64(149599.9076923077),
 'BsmtExposure': np.float64(149751.4638648861),
 'BsmtFinType1': np.float64(129760.82820380188),
 'BsmtFinType2': np.float64(99595.86842105263),
 'Heating': np.float64(109521.19537815126),
 'HeatingQC': np.float64(127914.42914979756),
 'CentralAir': np.float64(80922.63620589937),
 'Electrical': np.float64(119810.63745318353),
 'KitchenQual': np.float64(222989.46487179486),
 'Functional': np.float64(97629.14705882352),
 'FireplaceQu': np.float64(207948.35),
 'GarageType': np.float64(151434.45468574634),
 'GarageFinish': np.float64(136735.4063902918),
 'GarageQual': np.float64(140833.3333333333),
 'GarageCond': np.float64(84568.45134350036),
 'PavedDrive': np.float64(71394.85165837478),
 'PoolQC': np.float64(309595.33654507913),
 'Fence': np.float64(53310.474361939996),
 'MiscFeature': np.float64(156000.0),
 'SaleType': np.float64(155095.41803278687),
 'SaleCondition': np.float64(168166.75199999998)}

In [201]:
type(features_mean)

dict

In [202]:
pd.Series(features_mean).sort_values(ascending=False)

PoolQC           309595.336545
ExterQual        279375.747253
RoofMatl         253250.000000
Neighborhood     236718.846485
Condition2       228250.000000
KitchenQual      222989.464872
BsmtQual         221388.149430
Exterior2nd      214000.000000
FireplaceQu      207948.350000
Exterior1st      191000.000000
SaleCondition    168166.752000
MiscFeature      156000.000000
SaleType         155095.418033
GarageType       151434.454686
BsmtExposure     149751.463865
BsmtCond         149599.907692
GarageQual       140833.333333
MSZoning         139486.061538
GarageFinish     136735.406390
BsmtFinType1     129760.828204
HeatingQC        127914.429150
ExterCond        124833.333333
MasVnrType       120156.579487
Electrical       119810.637453
Foundation       117864.817040
HouseStyle       109850.000000
Heating          109521.195378
BsmtFinType2      99595.868421
Functional        97629.147059
Condition1        90783.333333
LandContour       88429.860635
GarageCond        84568.451344
CentralAir        80922.636206
RoofStyle         76090.909091
LotShape          75078.547475
PavedDrive        71394.851658
Alley             61233.051483
BldgType          57331.549313
Fence             53310.474362
Street            50940.038514
LotConfig         46916.569493
Utilities         43450.956820
LandSlope         24422.431203
dtype: float64

In [203]:
dataset.groupby('PoolQC')['SalePrice'].agg(['count', 'mean'])

        count           mean
PoolQC
Ex          2  490000.000000
Fa          2  215500.000000
Gd          3  201990.000000
None     1453  180404.663455

In [204]:
dataset.groupby('ExterQual')['SalePrice'].agg(['count', 'mean'])

           count           mean
ExterQual
Ex            52  367360.961538
Fa            14   87985.214286
Gd           488  231633.510246
TA           906  144341.313466

In [205]:
groups_lowest_counts = {}
for feature in categorical_features:
    lowest_count = dataset.groupby(feature).size().min()
    groups_lowest_counts[feature] = lowest_count

In [206]:
groups_lowest_counts

{'MSZoning': np.int64(10),
 'Street': np.int64(6),
 'Alley': np.int64(41),
 'LotShape': np.int64(10),
 'LandContour': np.int64(36),
 'Utilities': np.int64(1),
 'LotConfig': np.int64(4),
 'LandSlope': np.int64(13),
 'Neighborhood': np.int64(2),
 'Condition1': np.int64(2),
 'Condition2': np.int64(1),
 'BldgType': np.int64(31),
 'HouseStyle': np.int64(8),
 'RoofStyle': np.int64(2),
 'RoofMatl': np.int64(1),
 'Exterior1st': np.int64(1),
 'Exterior2nd': np.int64(1),
 'MasVnrType': np.int64(15),
 'ExterQual': np.int64(14),
 'ExterCond': np.int64(1),
 'Foundation': np.int64(3),
 'BsmtQual': np.int64(35),
 'BsmtCond': np.int64(2),
 'BsmtExposure': np.int64(38),
 'BsmtFinType1': np.int64(37),
 'BsmtFinType2': np.int64(14),
 'Heating': np.int64(1),
 'HeatingQC': np.int64(1),
 'CentralAir': np.int64(95),
 'Electrical': np.int64(1),
 'KitchenQual': np.int64(39),
 'Functional': np.int64(1),
 'FireplaceQu': np.int64(20),
 'GarageType': np.int64(6),
 'GarageFinish': np.int64(81),
 'GarageQual': np.int64(3),
 'GarageCond': np.int64(2),
 'PavedDrive': np.int64(30),
 'PoolQC': np.int64(2),
 'Fence': np.int64(11),
 'MiscFeature': np.int64(1),
 'SaleType': np.int64(2),
 'SaleCondition': np.int64(4)}

In [207]:
pd.Series(groups_lowest_counts).sort_values(ascending=False)

CentralAir       95
GarageFinish     81
Alley            41
KitchenQual      39
BsmtExposure     38
BsmtFinType1     37
LandContour      36
BsmtQual         35
BldgType         31
PavedDrive       30
FireplaceQu      20
MasVnrType       15
BsmtFinType2     14
ExterQual        14
LandSlope        13
Fence            11
MSZoning         10
LotShape         10
HouseStyle        8
Street            6
GarageType        6
SaleCondition     4
LotConfig         4
Foundation        3
GarageQual        3
Neighborhood      2
SaleType          2
PoolQC            2
GarageCond        2
Condition1        2
RoofStyle         2
BsmtCond          2
Exterior1st       1
Functional        1
Electrical        1
Condition2        1
HeatingQC         1
Heating           1
Utilities         1
RoofMatl          1
MiscFeature       1
ExterCond         1
Exterior2nd       1
dtype: int64

In [208]:
dataset.groupby('RoofMatl')['SalePrice'].agg(['count', 'mean']).sort_values('count')

          count           mean
RoofMatl
ClyTile       1  160000.000000
Membran       1  241500.000000
Metal         1  180000.000000
Roll          1  137000.000000
WdShake       5  241400.000000
WdShngl       6  390250.000000
Tar&Grv      11  185406.363636
CompShg    1434  179803.679219

In [246]:
dataset[dataset['ExterQual'] == 'Fa']['SalePrice'].sort_values()

533      39300
705      55000
812      55993
636      60000
375      61000
1061     81000
341      82000
1323     82500
88       85000
821      93000
1370    105000
52      110000
1266    122000
635     200000
Name: SalePrice, dtype: int64

In [277]:
groups = dataset.groupby('HouseStyle')['SalePrice']

In [278]:
group_sale_price = []
for group_name, sales_prices in groups:
    group_sale_price.append(sales_prices)

In [279]:
len(group_sale_price)

8

In [280]:
group_sale_price

[5       143000
 8       129900
 46      239686
 51      114500
 69      225000
          ...
 1400    120000
 1404    105000
 1411    140000
 1414    207000
 1427    140000
 Name: SalePrice, Length: 154, dtype: int64,
 9       118000
 15      132000
 21      139400
 127      87000
 163     103200
 325      87000
 383      76000
 437     119000
 514      96500
 555     113000
 617     105500
 826     109500
 1069    135000
 1443    121000
 Name: SalePrice, dtype: int64,
 1       181500
 6       307000
 10      129500
 12      144000
 13      279500
          ...
 1453     84500
 1454    185000
 1456    210000
 1458    142125
 1459    147500
 Name: SalePrice, Length: 726, dtype: int64,
 185     475000
 198     104000
 267     179500
 304     295000
 635     200000
 883     118500
 1031    197000
 1440    191000
 Name: SalePrice, dtype: int64,
 61      101000
 93      133900
 328     214500
 583     325000
 735     163000
 784     128000
 809     106000
 852     164000
 1197    144000
 1248    129500
 1266    122000
 Name: SalePrice, dtype: int64,
 0       208500
 2       223500
 3       140000
 4       250000
 7       200000
          ...
 1447    240000
 1448    112000
 1450    136000
 1455    175000
 1457    266500
 Name: SalePrice, Length: 445, dtype: int64,
 42      144000
 188     153337
 360     156000
 362     198500
 376     148000
 420     206300
 434      81000
 489      86000
 543     133000
 547     129500
 569     135960
 582     118500
 587     137000
 614      75500
 615     137500
 634     144000
 649      84500
 663     137500
 770     134900
 779     135000
 783     165500
 845     171000
 878     148000
 952     133900
 954     127500
 980     178400
 1039     80000
 1085    147000
 1129    140000
 1163    108959
 1214    134500
 1242    170000
 1297    140000
 1392    123000
 1406    133000
 1445    129000
 1449     92000
 Name: SalePrice, dtype: int64,
 54      130000
 75       91000
 84      168500
 111     180000
 120     180000
          ...
 1371    165500
 1379    167500
 1423    274970
 1439    197000
 1452    145000
 Name: SalePrice, Length: 65, dtype: int64]

In [281]:
anova_results = f_oneway(*group_sale_price)

In [283]:
anova_results

F_onewayResult(statistic=np.float64(19.59500099598122), pvalue=np.float64(3.376776535118099e-25))

In [248]:
Fa_group = groups.get_group('Fa')

In [249]:
Fa_group

52      110000
88       85000
341      82000
375      61000
533      39300
635     200000
636      60000
705      55000
812      55993
821      93000
1061     81000
1266    122000
1323     82500
1370    105000
Name: SalePrice, dtype: int64

In [274]:
feature = 'ExterQual'
group = dataset.groupby(feature)['SalePrice']

In [275]:
group

In [209]:
results = []
for feature in categorical_features:
    results.append(dataset.groupby([feature])['SalePrice'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False))
results

[          count           mean    median
 MSZoning
 FV           65  214014.061538  205950.0
 RL         1151  191004.994787  174000.0
 RH           16  131558.375000  136500.0
 RM          218  126316.830275  120500.0
 C (all)      10   74528.000000   74700.0,
         count           mean    median
 Street
 Pave     1454  181130.538514  163000.0
 Grvl        6  130190.500000  114250.0,
        count           mean    median
 Alley
 None    1369  183452.131483  165000.0
 Pave      41  168000.585366  172500.0
 Grvl      50  122219.080000  119500.0,
           count           mean    median
 LotShape
 IR2          41  239833.365854  221000.0
 IR3          10  216036.500000  203570.0
 IR1         484  206101.665289  189000.0
 Reg         925  164754.818378  146000.0,
              count           mean    median
 LandContour
 HLS             50  231533.940000  222250.0
 Low             36  203661.111111  190000.0
 Lvl           1311  180183.746758  162900.0
 Bnk             63  143104.079365  139400.0,
            count          mean    median
 Utilities
 AllPub      1459  180950.95682  163000.0
 NoSeWa         1  137500.00000  137500.0,
            count           mean    median
 LotConfig
 CulDSac       94  223854.617021  199262.0
 FR3            4  208475.000000  195450.0
 Corner       263  181623.425856  160000.0
 FR2           47  177934.574468  165000.0
 Inside      1052  176938.047529  159697.5,
            count           mean    median
 LandSlope
 Sev           13  204379.230769  185000.0
 Mod           65  196734.138462  186700.0
 Gtl         1382  179956.799566  161875.0,
               count           mean    median
 Neighborhood
 NoRidge          41  335295.317073  301500.0
 NridgHt          77  316270.623377  315000.0
 StoneBr          25  310499.000000  278000.0
 Timber           38  242247.447368  228475.0
 Veenker          11  238772.727273  218000.0
 Somerst          86  225379.837209  225500.0
 ClearCr          28  212565.428571  200250.0
 Crawfor          51  210624.725490  200624.0
 CollgCr         150  197965.773333  197200.0
 Blmngtn          17  194870.882353  191000.0
 Gilbert          79  192854.506329  181000.0
 NWAmes           73  189050.068493  182900.0
 SawyerW          59  186555.796610  179900.0
 Mitchel          49  156270.122449  153500.0
 NAmes           225  145847.080000  140000.0
 NPkVill           9  142694.444444  146000.0
 SWISU            25  142591.360000  139500.0
 Blueste           2  137500.000000  137500.0
 Sawyer           74  136793.135135  135000.0
 OldTown         113  128225.300885  119000.0
 Edwards         100  128219.700000  121750.0
 BrkSide          58  124834.051724  124300.0
 BrDale           16  104493.750000  106000.0
 IDOTRR           37  100123.783784  103000.0
 MeadowV          17   98576.470588   88000.0,
             count           mean    median
 Condition1
 PosA            8  225875.000000  212500.0
 PosN           19  215184.210526  200000.0
 RRNn            5  212400.000000  214000.0
 RRNe            2  190750.000000  190750.0
 Norm         1260  184495.492063  166500.0
 RRAn           26  184396.615385  171495.0
 Feedr          81  142475.481481  140000.0
 RRAe           11  138400.000000  142500.0
 Artery         48  135091.666667  119550.0,
             count           mean    median
 Condition2
 PosA            1  325000.000000  325000.0
 PosN            2  284875.000000  284875.0
 RRAe            1  190000.000000  190000.0
 Norm         1445  181169.405536  163500.0
 RRAn            1  136905.000000  136905.0
 Feedr           6  121166.666667  127500.0
 Artery          2  106500.000000  106500.0
 RRNn            2   96750.000000   96750.0,
           count           mean    median
 BldgType
 1Fam       1220  185763.807377  167900.0
 TwnhsE      114  181959.342105  172200.0
 Twnhs        43  135911.627907  137500.0
 Duplex       52  133541.076923  135980.0
 2fmCon       31  128432.258065  127500.0,
             count           mean    median
 HouseStyle
 2.5Fin          8  220000.000000  194000.0
 2Story        445  210051.764045  190000.0
 1Story        726  175985.477961  154750.0
 SLvl           65  166703.384615  164500.0
 2.5Unf         11  157354.545455  133900.0
 1.5Fin        154  143116.740260  132000.0
 SFoyer         37  135074.486486  135960.0
 1.5Unf         14  110150.000000  111250.0,
            count           mean    median
 RoofStyle
 Shed           2  225000.000000  225000.0
 Hip          286  218876.933566  176500.0
 Flat          13  194690.000000  185000.0
 Mansard        7  180568.428571  175000.0
 Gable       1141  171483.956179  160000.0
 Gambrel       11  148909.090909  139000.0,
           count           mean    median
 RoofMatl
 WdShngl       6  390250.000000  332500.0
 Membran       1  241500.000000  241500.0
 WdShake       5  241400.000000  242000.0
 Tar&Grv      11  185406.363636  167000.0
 Metal         1  180000.000000  180000.0
 CompShg    1434  179803.679219  162000.0
 ClyTile       1  160000.000000  160000.0
 Roll          1  137000.000000  137000.0,
              count           mean    median
 Exterior1st
 ImStucc          1  262000.000000  262000.0
 Stone            2  258500.000000  258500.0
 CemntBd         61  231690.655738  236500.0
 VinylSd        515  213732.900971  200000.0
 BrkFace         50  194573.000000  165750.0
 Plywood        108  175942.379630  167450.0
 HdBoard        222  163077.450450  149900.0
 Stucco          25  162990.000000  144000.0
 WdShing         26  150655.076923  128700.0
 Wd Sdng        206  149841.645631  138943.5
 MetalSd        220  149422.177273  139000.0
 AsbShng         20  107385.550000  108000.0
 CBlock           1  105000.000000  105000.0
 AsphShn          1  100000.000000  100000.0
 BrkComm          2   71000.000000   71000.0,
              count           mean    median
 Exterior2nd
 Other            1  319000.000000  319000.0
 ImStucc         10  252070.000000  187600.0
 CmentBd         60  230093.833333  238750.0
 VinylSd        504  214432.460317  200070.5
 BrkFace         25  195818.000000  160000.0
 Plywood        142  168112.387324  160750.0
 HdBoard        207  167661.565217  155000.0
 Wd Shng         38  161328.947368  138225.0
 Stone            5  158224.800000  177000.0
 Stucco          26  155905.153846  142000.0
 MetalSd        214  149803.172897  138750.0
 Wd Sdng        197  148386.065990  138000.0
 AsphShn          3  138000.000000  139000.0
 Brk Cmn          7  126714.285714  147000.0
 AsbShng         20  114060.550000  111000.0
 CBlock           1  105000.000000  105000.0,
             count           mean    median
 MasVnrType
 Stone         130  266474.646154  246839.0
 BrkFace       452  204338.568584  181450.0
 None          863  156370.148320  143000.0
 BrkCmn         15  146318.066667  139000.0,
            count           mean    median
 ExterQual
 Ex            52  367360.961538  364606.5
 Gd           488  231633.510246  220000.0
 TA           906  144341.313466  139450.0
 Fa            14   87985.214286   82250.0,
            count           mean    median
 ExterCond
 Ex             3  201333.333333  161000.0
 TA          1282  184034.896256  167370.0
 Gd           146  168897.568493  151250.0
 Fa            28  102595.142857   95750.0
 Po             1   76500.000000   76500.0,
             count           mean    median
 Foundation
 PConc         647  225230.442040  205000.0
 Wood            3  185666.666667  164000.0
 Stone           6  165959.166667  126500.0
 CBlock        634  149805.714511  141500.0
 BrkTil        146  132291.075342  125250.0
 Slab           24  107365.625000  104150.0,
           count           mean    median
 BsmtQual
 Ex          121  327041.041322  318000.0
 Gd          618  202688.478964  192070.0
 TA          649  140759.818182  135500.0
 Fa           35  115692.028571  112000.0
 None         37  105652.891892  101800.0,
           count           mean    median
 BsmtCond
 Gd           65  213599.907692  193879.0
 TA         1311  183632.620900  165000.0
 Fa           45  121809.533333  118500.0
 None         37  105652.891892  101800.0
 Po            2   64000.000000   64000.0,
               count           mean    median
 BsmtExposure
 Gd              134  257689.805970  226975.0
 Av              221  206643.420814  185850.0
 Mn              114  192789.657895  182450.0
 No              953  165652.295908  154000.0
 None             38  107938.342105  104025.0,
               count           mean    median
 BsmtFinType1
 GLQ             418  235413.720096  213750.0
 Unf             430  170670.576744  161750.0
 ALQ             220  161573.068182  149250.0
 LwQ              74  151852.702703  139000.0
 BLQ             148  149493.655405  139100.0
 Rec             133  146889.248120  142000.0
 None             37  105652.891892  101800.0,
               count           mean    median
 BsmtFinType2
 ALQ              19  209942.105263  174900.0
 Unf            1256  184694.690287  167000.0
 GLQ              14  180982.142857  203125.0
 Rec              54  164917.129630  148750.0
 LwQ              46  164364.130435  154000.0
 BLQ              33  151101.000000  143000.0
 None             38  110346.236842  104025.0,
          count           mean    median
 Heating
 GasA      1428  182021.195378  164500.0
 GasW        18  166632.166667  134950.0
 OthW         2  125750.000000  125750.0
 Wall         4   92100.000000   91450.0
 Grav         7   75271.428571   79000.0
 Floor        1   72500.000000   72500.0,
            count           mean    median
 HeatingQC
 Ex           741  214914.429150  194700.0
 Gd           241  156858.871369  152000.0
 TA           428  142362.876168  135000.0
 Fa            49  123919.489796  123500.0
 Po             1   87000.000000   87000.0,
             count           mean    median
 CentralAir
 Y            1365  186186.709890  168000.0
 N              95  105264.073684   98000.0,
             count           mean    median
 Electrical
 SBrkr        1335  186810.637453  170000.0
 FuseA          94  122196.893617  121250.0
 FuseF          27  107675.444444  115000.0
 FuseP           3   97333.333333   82000.0
 Mix             1   67000.000000   67000.0,
              count           mean    median
 KitchenQual
 Ex             100  328554.670000  316750.0
 Gd             586  212116.023891  201400.0
 TA             735  139962.511565  137000.0
 Fa              39  105565.205128  115000.0,
             count           mean    median
 Functional
 Typ          1360  183429.147059  165500.0
 Mod            15  168393.333333  137900.0
 Maj1           14  153948.142857  140750.0
 Min1           31  146385.483871  139000.0
 Min2           34  144240.647059  140000.0
 Sev             1  129000.000000  129000.0
 Maj2            5   85800.000000   85000.0,
              count           mean    median
 FireplaceQu
 Ex              24  337712.500000  314250.0
 Gd             380  226351.415789  206950.0
 TA             313  205723.488818  187500.0
 Fa              33  167298.484848  158000.0
 None           690  141331.482609  135000.0
 Po              20  129764.150000  131500.0,
             count           mean    median
 GarageType
 BuiltIn        88  254751.738636  227500.0
 Attchd        870  202892.656322  185000.0
 Basment        19  160570.684211  148000.0
 2Types          6  151283.333333  159000.0
 Detchd        387  134091.162791  129500.0
 CarPort         9  109962.111111  108000.0
 None           81  103317.283951  100000.0,
               count           mean    median
 GarageFinish
 Fin             352  240052.690341  215000.0
 RFn             422  202068.869668  190000.0
 Unf             605  142156.423140  135000.0
 None             81  103317.283951  100000.0,
             count           mean    median
 GarageQual
 Ex              3  241000.000000  127500.0
 Gd             14  215860.714286  209115.0
 TA           1311  187489.836003  170000.0
 Fa             48  123573.354167  115000.0
 None           81  103317.283951  100000.0
 Po              3  100166.666667   96500.0,
             count           mean    median
 GarageCond
 TA           1326  187885.735294  170000.0
 Gd              9  179930.000000  148000.0
 Ex              2  124000.000000  124000.0
 Fa             35  114654.028571  114504.0
 Po              7  108500.000000  108000.0
 None           81  103317.283951  100000.0,
             count           mean    median
 PavedDrive
 Y            1340  186433.973881  168500.0
 P              30  132330.000000  132250.0
 N              90  115039.122222  111000.0,
         count           mean    median
 PoolQC
 Ex          2  490000.000000  490000.0
 Fa          2  215500.000000  215500.0
 Gd          3  201990.000000  171000.0
 None     1453  180404.663455  162900.0,
        count           mean    median
 Fence
 None    1179  187596.837998  173000.0
 GdPrv     59  178927.457627  167500.0
 MnPrv    157  148751.089172  137450.0
 GdWo      54  140379.314815  138750.0
 MnWw      11  134286.363636  130000.0,
              count           mean    median
 MiscFeature
 TenC             1  250000.000000  250000.0
 None          1406  182046.410384  164250.0
 Gar2             2  170750.000000  170750.0
 Shed            49  151187.612245  144000.0
 Othr             2   94000.000000   94000.0,
           count           mean    median
 SaleType
 New         122  274945.418033  247453.0
 Con           2  269600.000000  269600.0
 CWD           4  210600.000000  188750.0
 ConLI         5  200390.000000  125000.0
 WD         1267  173401.836622  158000.0
 COD          43  143973.255814  139000.0
 ConLw         5  143700.000000  144000.0
 ConLD         9  138780.888889  140000.0
 Oth           3  119850.000000  116050.0,
                count           mean    median
 SaleCondition
 Partial          125  272291.752000  244600.0
 Normal          1198  175202.219533  160000.0
 Alloca            12  167377.416667  148145.0
 Family            20  149600.000000  140500.0
 Abnorml          101  146526.623762  130000.0
 AdjLand            4  104125.000000  104000.0]

In [210]:
dataset[categorical_features].nunique()

MSZoning          5
Street            2
Alley             3
LotShape          4
LandContour       4
Utilities         2
LotConfig         5
LandSlope         3
Neighborhood     25
Condition1        9
Condition2        8
BldgType          5
HouseStyle        8
RoofStyle         6
RoofMatl          8
Exterior1st      15
Exterior2nd      16
MasVnrType        4
ExterQual         4
ExterCond         5
Foundation        6
BsmtQual          5
BsmtCond          5
BsmtExposure      5
BsmtFinType1      7
BsmtFinType2      7
Heating           6
HeatingQC         5
CentralAir        2
Electrical        5
KitchenQual       4
Functional        7
FireplaceQu       6
GarageType        7
GarageFinish      4
GarageQual        6
GarageCond        6
PavedDrive        3
PoolQC            4
Fence             5
MiscFeature       5
SaleType          9
SaleCondition     6
dtype: int64

In [211]:
X = dataset[['GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', '1stFlrSF']]
y = dataset['SalePrice']

In [212]:
X.shape

(1460, 5)

In [213]:
y.shape

(1460,)

In [214]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [215]:
X_train.shape

(1168, 5)

In [216]:
X_test.shape

(292, 5)

In [217]:
y_train.shape

(1168,)

In [218]:
y_test.shape

(292,)